# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Select No Dashii as a trusted perceived mask.
data modify storage botc_patch:buffet action.mask set value {actual:122,perceived:122,alignment:2,perceived_alignment:2,category:4,archetype:"demon_corruption_and_misinformation",archetype_id:19,hidden:0b,hidden_mode:0,hermit_forced_ability:0,name:"No Dashii",color:"#ff5555",glyph:""}
scoreboard players set draft_mask_picked botc_patch 1
