Set-StrictMode -Version Latest

function Write-BotcFilteredPlayerDialog {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] [string] $OutputRoot,
        [Parameter(Mandatory)] [string] $FunctionPath,
        [Parameter(Mandatory)] [string] $GeneratorName,
        [Parameter(Mandatory)] [string] $StorageKey,
        [Parameter(Mandatory)] [string] $Title,
        [Parameter(Mandatory)] [string] $BodyText,
        [Parameter(Mandatory)] [string] $EligibilitySelectorTemplate,
        [Parameter(Mandatory)] [string] $ActionCommand,
        [Parameter(Mandatory)] [string] $PhaseCondition,
        [Parameter(Mandatory)] [string] $InvalidPhaseMessage,
        [Parameter(Mandatory)] [string] $NoPlayersMessage
    )

    if ($StorageKey -notmatch '^[a-z][a-z0-9_]*$') {
        throw "Invalid filtered-player dialog storage key '$StorageKey'."
    }
    if ($FunctionPath -notmatch '^[a-z0-9_/]+$') {
        throw "Invalid filtered-player dialog function path '$FunctionPath'."
    }
    if ($EligibilitySelectorTemplate -notmatch '<seat>') {
        throw "Eligibility selector template must contain <seat>."
    }

    $utf8NoBom = [System.Text.UTF8Encoding]::new($false)
    $dialogRoot = Join-Path $OutputRoot "dialog"
    New-Item -ItemType Directory -Path $dialogRoot -Force | Out-Null

    $newHeader = {
        param([string] $Responsibility)

        $lines = [System.Collections.Generic.List[string]]::new()
        $lines.Add("# Generated by $GeneratorName.")
        $lines.Add("# Do not hand-edit this file; update the generator and regenerate.")
        $lines.Add("# $Responsibility")
        return ,$lines
    }

    $writeLines = {
        param(
            [string] $Path,
            [System.Collections.Generic.List[string]] $Lines
        )

        [System.IO.File]::WriteAllText(
            $Path,
            (($Lines -join "`n") + "`n"),
            $utf8NoBom
        )
    }

    $builder = & $newHeader "Compacts only currently eligible seated players into a bounded Player (Role) dialog."
    $builder.Add("dialog clear @s")
    $builder.Add("execute unless entity @s[tag=storyteller] run return 0")
    $builder.Add(('execute unless {0} run return run tellraw @s [{{text:"{1}",color:"red"}}]' -f $PhaseCondition, $InvalidPhaseMessage))
    $builder.Add("function botc_patch:grim/editor/refresh_live_roles")
    $builder.Add("function botc_patch:grim/editor/player_labels/prepare")
    $builder.Add("data remove storage botc_patch:dialogs $StorageKey")
    $builder.Add("scoreboard players set @s botc_st_menu_slot 0")

    for ($seat = 1; $seat -le 15; $seat++) {
        $selector = $EligibilitySelectorTemplate.Replace("<seat>", [string] $seat)
        $builder.Add("execute if entity $selector run scoreboard players add @s botc_st_menu_slot 1")
        $builder.Add(('execute if entity {0} run data modify storage botc_patch:dialogs lookup set value {{source:{1},target:0}}' -f $selector, $seat))
        $builder.Add("execute if entity $selector store result storage botc_patch:dialogs lookup.target int 1 run scoreboard players get @s botc_st_menu_slot")
        $builder.Add("execute if entity $selector run function botc_patch:$FunctionPath/dialog/append with storage botc_patch:dialogs lookup")
    }

    $builder.Add(('execute if score @s botc_st_menu_slot matches 0 run tellraw @s [{{text:"{0}",color:"yellow"}}]' -f $NoPlayersMessage))
    for ($count = 1; $count -le 15; $count++) {
        $builder.Add("execute if score @s botc_st_menu_slot matches $count run function botc_patch:$FunctionPath/dialog/count_$count with storage botc_patch:dialogs $StorageKey")
    }
    $builder.Add("scoreboard players reset @s botc_st_menu_slot")
    & $writeLines (Join-Path $OutputRoot "dialog.mcfunction") $builder

    $append = & $newHeader "Copies one eligible seat into the next compact dialog entry."
    $append.Add(('$data modify storage botc_patch:dialogs {0}.e$(target)_name set from storage botc_patch:grim editor.player_labels.p$(source)_name' -f $StorageKey))
    $append.Add(('$data modify storage botc_patch:dialogs {0}.e$(target)_role set from storage botc_patch:grim editor.player_labels.p$(source)_role' -f $StorageKey))
    $append.Add(('$data modify storage botc_patch:dialogs {0}.e$(target)_glyph set from storage botc_patch:grim editor.player_labels.p$(source)_glyph' -f $StorageKey))
    $append.Add(('$data modify storage botc_patch:dialogs {0}.e$(target)_color set from storage botc_patch:grim editor.player_labels.p$(source)_color' -f $StorageKey))
    $append.Add(('$data modify storage botc_patch:dialogs {0}.e$(target)_seat set value $(source)' -f $StorageKey))
    & $writeLines (Join-Path $dialogRoot "append.mcfunction") $append

    Remove-Item -LiteralPath (Join-Path $dialogRoot "count_0.mcfunction") -Force -ErrorAction SilentlyContinue
    for ($count = 1; $count -le 15; $count++) {
        $actions = [System.Collections.Generic.List[string]]::new()
        for ($index = 1; $index -le $count; $index++) {
            $actions.Add('{label:{text:"$(e' + $index + '_glyph)",font:"botc_patch:role_icons",color:"white",extra:[{text:" $(e' + $index + '_name)",font:"minecraft:default",color:"white"},{text:" ($(e' + $index + '_role))",font:"minecraft:default",color:"$(e' + $index + '_color)"}]},tooltip:{text:"Seat $(e' + $index + '_seat)",color:"gray"},action:{type:"run_command",command:"/botc ' + $ActionCommand + ' $(e' + $index + '_seat)"}}')
        }

        $line = '$dialog show @s {type:"multi_action",title:"' + $Title + '",body:{type:"plain_message",contents:{text:"' + $BodyText + '",color:"gray"},width:360},columns:3,actions:[' + ($actions -join ',') + '],exit_action:{label:"Back",action:{type:"run_command",command:"/botc dialog_cancel"}}}'
        $variant = & $newHeader "Filtered player dialog with $count eligible seat(s)."
        $variant.Add($line)
        & $writeLines (Join-Path $dialogRoot "count_$count.mcfunction") $variant
    }
}
