# Generated by tools/generate-grim-dialog.ps1.
# Do not hand-edit this file; update the generator and regenerate.
# Reveal dialog for 0 captured seats.
dialog show @s {type:"multi_action",title:"Grimoire Reveal",columns:2,actions:[{label:{text:"Good Wins",color:"#0000aa",bold:true},action:{type:"run_command",command:"/botc winner good"}},{label:{text:"Evil Wins",color:"#aa0000",bold:true},action:{type:"run_command",command:"/botc winner evil"}}]}
