# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Apply the fixed part of a variable setup modifier without advancing.
$scoreboard players set draft_delta_town botc_patch $(town)
$scoreboard players set draft_delta_outsider botc_patch $(outsider)
$scoreboard players set draft_delta_minion botc_patch $(minion)
$scoreboard players set draft_delta_demon botc_patch $(demon)
scoreboard players operation draft_target_town botc_patch += draft_delta_town botc_patch
scoreboard players operation draft_target_outsider botc_patch += draft_delta_outsider botc_patch
scoreboard players operation draft_target_minion botc_patch += draft_delta_minion botc_patch
scoreboard players operation draft_target_demon botc_patch += draft_delta_demon botc_patch
$data modify storage botc_patch:buffet draft.seats.s$(seat).delta_town set value $(town)
$data modify storage botc_patch:buffet draft.seats.s$(seat).delta_outsider set value $(outsider)
$data modify storage botc_patch:buffet draft.seats.s$(seat).delta_minion set value $(minion)
$data modify storage botc_patch:buffet draft.seats.s$(seat).delta_demon set value $(demon)
$data modify storage botc_patch:buffet draft.seats.s$(seat).modifier_owner set value 1b
function botc_patch:buffet/draft/recount_needs
