# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Replace every Minion slot with Riot and reserve the required duplicate Riot choices.
scoreboard players operation draft_riot_old_minion botc_patch = draft_target_minion botc_patch
scoreboard players operation draft_target_demon botc_patch += draft_riot_old_minion botc_patch
scoreboard players set draft_target_minion botc_patch 0
scoreboard players operation draft_riot_total botc_patch = draft_riot_old_minion botc_patch
scoreboard players add draft_riot_total botc_patch 1
scoreboard players operation draft_required_riot botc_patch = draft_riot_old_minion botc_patch
scoreboard players set draft_riot_active botc_patch 1
execute store result storage botc_patch:buffet modifier.seat int 1 run scoreboard players get @s id
$execute store result storage botc_patch:buffet draft.seats.s$(seat).delta_minion int -1 run scoreboard players get draft_riot_old_minion botc_patch
$execute store result storage botc_patch:buffet draft.seats.s$(seat).delta_demon int 1 run scoreboard players get draft_riot_old_minion botc_patch
$data modify storage botc_patch:buffet draft.seats.s$(seat).modifier_owner set value 1b
function botc_patch:buffet/draft/recount_needs
function botc_patch:buffet/draft/next_turn
