# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Show or reopen the private Alchemist-Summoner decision for every Storyteller.
execute unless score draft_modifier_pending botc_patch matches 1 run return 0
execute unless data storage botc_patch:buffet modifier{kind:"alchemist_summoner"} run return 0
dialog show @a[tag=storyteller] {type:"multi_action",title:{text:"Alchemist: Summoner Ability",color:"gold",bold:true},body:[{type:"plain_message",contents:{text:"Give this Alchemist the Summoner\u0027s ability? The game starts with one extra Townsfolk and no Demon. The Minion count stays the same.",color:"gray"},width:430}],columns:2,actions:[{label:{text:"Give Summoner Ability",color:"green",bold:true},action:{type:"run_command",command:"/trigger botc_buffet_action set 7450"}},{label:{text:"Keep Normal Ability",color:"red",bold:true},action:{type:"run_command",command:"/trigger botc_buffet_action set 7451"}}],exit_action:{label:"Decide Later"}}
