# Generated by tools/generate-storyteller-nomination-menu.ps1.
# Do not hand-edit this file; update the generator and regenerate.
# Back rescinds an unfinished current nomination before restoring the normal nomination hotbar.
tag @s add botc_st_tool_used
execute if entity @a[tag=botc_st_nom_selected,tag=nominee,limit=1] run function botc_patch:storyteller_tools/nomination_menu/rescind
function botc_patch:storyteller_tools/nomination_menu/close
