# Generated by tools/generate-buffet-gamemodes.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Stage one direct Hermit assignment without changing the confirmed seat.
$data modify storage botc_patch:buffet greedy.hermit_pending set value {active:1b,seat:$(seat),role:90,perceived:90,alignment:1,perceived_alignment:1,forced_ability:0,abilities:{}}
function botc_patch:buffet/greedy/review/hermit/open_abilities
