# Generated by tools/generate-buffet-gamemodes.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Open a new or existing direct Hermit assignment for the selected seat.
execute if score buffet_selected_seat botc_patch matches 1 if data storage botc_patch:buffet greedy.seats.s1{role:90} run function botc_patch:buffet/greedy/review/hermit/begin_existing {seat:1}
execute if score buffet_selected_seat botc_patch matches 1 unless data storage botc_patch:buffet greedy.seats.s1{role:90} run function botc_patch:buffet/greedy/review/hermit/begin_direct {seat:1}
execute if score buffet_selected_seat botc_patch matches 2 if data storage botc_patch:buffet greedy.seats.s2{role:90} run function botc_patch:buffet/greedy/review/hermit/begin_existing {seat:2}
execute if score buffet_selected_seat botc_patch matches 2 unless data storage botc_patch:buffet greedy.seats.s2{role:90} run function botc_patch:buffet/greedy/review/hermit/begin_direct {seat:2}
execute if score buffet_selected_seat botc_patch matches 3 if data storage botc_patch:buffet greedy.seats.s3{role:90} run function botc_patch:buffet/greedy/review/hermit/begin_existing {seat:3}
execute if score buffet_selected_seat botc_patch matches 3 unless data storage botc_patch:buffet greedy.seats.s3{role:90} run function botc_patch:buffet/greedy/review/hermit/begin_direct {seat:3}
execute if score buffet_selected_seat botc_patch matches 4 if data storage botc_patch:buffet greedy.seats.s4{role:90} run function botc_patch:buffet/greedy/review/hermit/begin_existing {seat:4}
execute if score buffet_selected_seat botc_patch matches 4 unless data storage botc_patch:buffet greedy.seats.s4{role:90} run function botc_patch:buffet/greedy/review/hermit/begin_direct {seat:4}
execute if score buffet_selected_seat botc_patch matches 5 if data storage botc_patch:buffet greedy.seats.s5{role:90} run function botc_patch:buffet/greedy/review/hermit/begin_existing {seat:5}
execute if score buffet_selected_seat botc_patch matches 5 unless data storage botc_patch:buffet greedy.seats.s5{role:90} run function botc_patch:buffet/greedy/review/hermit/begin_direct {seat:5}
execute if score buffet_selected_seat botc_patch matches 6 if data storage botc_patch:buffet greedy.seats.s6{role:90} run function botc_patch:buffet/greedy/review/hermit/begin_existing {seat:6}
execute if score buffet_selected_seat botc_patch matches 6 unless data storage botc_patch:buffet greedy.seats.s6{role:90} run function botc_patch:buffet/greedy/review/hermit/begin_direct {seat:6}
execute if score buffet_selected_seat botc_patch matches 7 if data storage botc_patch:buffet greedy.seats.s7{role:90} run function botc_patch:buffet/greedy/review/hermit/begin_existing {seat:7}
execute if score buffet_selected_seat botc_patch matches 7 unless data storage botc_patch:buffet greedy.seats.s7{role:90} run function botc_patch:buffet/greedy/review/hermit/begin_direct {seat:7}
execute if score buffet_selected_seat botc_patch matches 8 if data storage botc_patch:buffet greedy.seats.s8{role:90} run function botc_patch:buffet/greedy/review/hermit/begin_existing {seat:8}
execute if score buffet_selected_seat botc_patch matches 8 unless data storage botc_patch:buffet greedy.seats.s8{role:90} run function botc_patch:buffet/greedy/review/hermit/begin_direct {seat:8}
execute if score buffet_selected_seat botc_patch matches 9 if data storage botc_patch:buffet greedy.seats.s9{role:90} run function botc_patch:buffet/greedy/review/hermit/begin_existing {seat:9}
execute if score buffet_selected_seat botc_patch matches 9 unless data storage botc_patch:buffet greedy.seats.s9{role:90} run function botc_patch:buffet/greedy/review/hermit/begin_direct {seat:9}
execute if score buffet_selected_seat botc_patch matches 10 if data storage botc_patch:buffet greedy.seats.s10{role:90} run function botc_patch:buffet/greedy/review/hermit/begin_existing {seat:10}
execute if score buffet_selected_seat botc_patch matches 10 unless data storage botc_patch:buffet greedy.seats.s10{role:90} run function botc_patch:buffet/greedy/review/hermit/begin_direct {seat:10}
execute if score buffet_selected_seat botc_patch matches 11 if data storage botc_patch:buffet greedy.seats.s11{role:90} run function botc_patch:buffet/greedy/review/hermit/begin_existing {seat:11}
execute if score buffet_selected_seat botc_patch matches 11 unless data storage botc_patch:buffet greedy.seats.s11{role:90} run function botc_patch:buffet/greedy/review/hermit/begin_direct {seat:11}
execute if score buffet_selected_seat botc_patch matches 12 if data storage botc_patch:buffet greedy.seats.s12{role:90} run function botc_patch:buffet/greedy/review/hermit/begin_existing {seat:12}
execute if score buffet_selected_seat botc_patch matches 12 unless data storage botc_patch:buffet greedy.seats.s12{role:90} run function botc_patch:buffet/greedy/review/hermit/begin_direct {seat:12}
execute if score buffet_selected_seat botc_patch matches 13 if data storage botc_patch:buffet greedy.seats.s13{role:90} run function botc_patch:buffet/greedy/review/hermit/begin_existing {seat:13}
execute if score buffet_selected_seat botc_patch matches 13 unless data storage botc_patch:buffet greedy.seats.s13{role:90} run function botc_patch:buffet/greedy/review/hermit/begin_direct {seat:13}
execute if score buffet_selected_seat botc_patch matches 14 if data storage botc_patch:buffet greedy.seats.s14{role:90} run function botc_patch:buffet/greedy/review/hermit/begin_existing {seat:14}
execute if score buffet_selected_seat botc_patch matches 14 unless data storage botc_patch:buffet greedy.seats.s14{role:90} run function botc_patch:buffet/greedy/review/hermit/begin_direct {seat:14}
execute if score buffet_selected_seat botc_patch matches 15 if data storage botc_patch:buffet greedy.seats.s15{role:90} run function botc_patch:buffet/greedy/review/hermit/begin_existing {seat:15}
execute if score buffet_selected_seat botc_patch matches 15 unless data storage botc_patch:buffet greedy.seats.s15{role:90} run function botc_patch:buffet/greedy/review/hermit/begin_direct {seat:15}
