# Generated by tools/generate-buffet-gamemodes.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Toggle one trusted Greedy Hermit Outsider ability.
scoreboard players set buffet_hermit_removed botc_patch 0
$execute if data storage botc_patch:buffet greedy.hermit_pending.abilities{r$(role):1b} run scoreboard players set buffet_hermit_removed botc_patch 1
$execute if data storage botc_patch:buffet greedy.hermit_pending.abilities{r$(role):1b} run data remove storage botc_patch:buffet greedy.hermit_pending.abilities.r$(role)
$execute unless data storage botc_patch:buffet greedy.hermit_pending.abilities{r$(role):1b} if score buffet_hermit_removed botc_patch matches 0 if score buffet_hermit_ability_count botc_patch matches 3.. run return run function botc_patch:buffet/greedy/review/hermit/full
$execute unless data storage botc_patch:buffet greedy.hermit_pending.abilities{r$(role):1b} if score buffet_hermit_removed botc_patch matches 0 run data modify storage botc_patch:buffet greedy.hermit_pending.abilities.r$(role) set value 1b
function botc_patch:buffet/greedy/review/hermit/open_abilities
