# Generated by tools/generate-buffet-gamemodes.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Name one submitted Greedy assignment that is absent from the current picks.
$tellraw @s [{"text":"! ","color":"red","bold":true},{"text":"Seat $(seat)","color":"yellow","bold":true},{"text":" (","color":"gray","bold":false},{"nbt":"greedy.seats.s$(seat).name","storage":"botc_patch:buffet","color":"white","bold":true},{"text":") has ","color":"gray","bold":false},{"nbt":"catalog.s$(role).name","storage":"botc_patch:buffet","color":"yellow","bold":true},{"text":" assigned, but it is not in the current picks and no override is active.","color":"gray","bold":false}]
