# Generated by tools/generate-buffet-gamemodes.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Validate Greedy assignments and flag non-standard but Storyteller-approved setups.
scoreboard players set buffet_hard_valid botc_patch 1
scoreboard players set buffet_soft_warning botc_patch 0
scoreboard players set buffet_count_town botc_patch 0
scoreboard players set buffet_count_outsider botc_patch 0
scoreboard players set buffet_count_minion botc_patch 0
scoreboard players set buffet_count_demon botc_patch 0
execute if score buffet_roster_count botc_patch matches 1.. unless data storage botc_patch:buffet greedy.seats.s1{active:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 1.. unless entity @a[tag=botc_buffet_roster,scores={botc_buffet_seat=1},limit=1] run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 1.. unless data storage botc_patch:buffet greedy.seats.s1{submitted:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 1.. unless data storage botc_patch:buffet greedy.seats.s1{status:2} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 1.. if data storage botc_patch:buffet greedy.seats.s1{role:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 1.. if data storage botc_patch:buffet greedy.seats.s1{perceived:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 1.. if data storage botc_patch:buffet greedy.seats.s1{hermit_forced_ability:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 1.. if data storage botc_patch:buffet greedy.seats.s1.hermit_abilities{r113:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 2.. unless data storage botc_patch:buffet greedy.seats.s2{active:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 2.. unless entity @a[tag=botc_buffet_roster,scores={botc_buffet_seat=2},limit=1] run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 2.. unless data storage botc_patch:buffet greedy.seats.s2{submitted:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 2.. unless data storage botc_patch:buffet greedy.seats.s2{status:2} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 2.. if data storage botc_patch:buffet greedy.seats.s2{role:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 2.. if data storage botc_patch:buffet greedy.seats.s2{perceived:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 2.. if data storage botc_patch:buffet greedy.seats.s2{hermit_forced_ability:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 2.. if data storage botc_patch:buffet greedy.seats.s2.hermit_abilities{r113:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 3.. unless data storage botc_patch:buffet greedy.seats.s3{active:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 3.. unless entity @a[tag=botc_buffet_roster,scores={botc_buffet_seat=3},limit=1] run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 3.. unless data storage botc_patch:buffet greedy.seats.s3{submitted:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 3.. unless data storage botc_patch:buffet greedy.seats.s3{status:2} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 3.. if data storage botc_patch:buffet greedy.seats.s3{role:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 3.. if data storage botc_patch:buffet greedy.seats.s3{perceived:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 3.. if data storage botc_patch:buffet greedy.seats.s3{hermit_forced_ability:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 3.. if data storage botc_patch:buffet greedy.seats.s3.hermit_abilities{r113:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 4.. unless data storage botc_patch:buffet greedy.seats.s4{active:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 4.. unless entity @a[tag=botc_buffet_roster,scores={botc_buffet_seat=4},limit=1] run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 4.. unless data storage botc_patch:buffet greedy.seats.s4{submitted:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 4.. unless data storage botc_patch:buffet greedy.seats.s4{status:2} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 4.. if data storage botc_patch:buffet greedy.seats.s4{role:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 4.. if data storage botc_patch:buffet greedy.seats.s4{perceived:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 4.. if data storage botc_patch:buffet greedy.seats.s4{hermit_forced_ability:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 4.. if data storage botc_patch:buffet greedy.seats.s4.hermit_abilities{r113:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 5.. unless data storage botc_patch:buffet greedy.seats.s5{active:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 5.. unless entity @a[tag=botc_buffet_roster,scores={botc_buffet_seat=5},limit=1] run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 5.. unless data storage botc_patch:buffet greedy.seats.s5{submitted:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 5.. unless data storage botc_patch:buffet greedy.seats.s5{status:2} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 5.. if data storage botc_patch:buffet greedy.seats.s5{role:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 5.. if data storage botc_patch:buffet greedy.seats.s5{perceived:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 5.. if data storage botc_patch:buffet greedy.seats.s5{hermit_forced_ability:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 5.. if data storage botc_patch:buffet greedy.seats.s5.hermit_abilities{r113:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 6.. unless data storage botc_patch:buffet greedy.seats.s6{active:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 6.. unless entity @a[tag=botc_buffet_roster,scores={botc_buffet_seat=6},limit=1] run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 6.. unless data storage botc_patch:buffet greedy.seats.s6{submitted:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 6.. unless data storage botc_patch:buffet greedy.seats.s6{status:2} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 6.. if data storage botc_patch:buffet greedy.seats.s6{role:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 6.. if data storage botc_patch:buffet greedy.seats.s6{perceived:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 6.. if data storage botc_patch:buffet greedy.seats.s6{hermit_forced_ability:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 6.. if data storage botc_patch:buffet greedy.seats.s6.hermit_abilities{r113:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 7.. unless data storage botc_patch:buffet greedy.seats.s7{active:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 7.. unless entity @a[tag=botc_buffet_roster,scores={botc_buffet_seat=7},limit=1] run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 7.. unless data storage botc_patch:buffet greedy.seats.s7{submitted:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 7.. unless data storage botc_patch:buffet greedy.seats.s7{status:2} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 7.. if data storage botc_patch:buffet greedy.seats.s7{role:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 7.. if data storage botc_patch:buffet greedy.seats.s7{perceived:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 7.. if data storage botc_patch:buffet greedy.seats.s7{hermit_forced_ability:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 7.. if data storage botc_patch:buffet greedy.seats.s7.hermit_abilities{r113:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 8.. unless data storage botc_patch:buffet greedy.seats.s8{active:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 8.. unless entity @a[tag=botc_buffet_roster,scores={botc_buffet_seat=8},limit=1] run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 8.. unless data storage botc_patch:buffet greedy.seats.s8{submitted:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 8.. unless data storage botc_patch:buffet greedy.seats.s8{status:2} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 8.. if data storage botc_patch:buffet greedy.seats.s8{role:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 8.. if data storage botc_patch:buffet greedy.seats.s8{perceived:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 8.. if data storage botc_patch:buffet greedy.seats.s8{hermit_forced_ability:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 8.. if data storage botc_patch:buffet greedy.seats.s8.hermit_abilities{r113:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 9.. unless data storage botc_patch:buffet greedy.seats.s9{active:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 9.. unless entity @a[tag=botc_buffet_roster,scores={botc_buffet_seat=9},limit=1] run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 9.. unless data storage botc_patch:buffet greedy.seats.s9{submitted:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 9.. unless data storage botc_patch:buffet greedy.seats.s9{status:2} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 9.. if data storage botc_patch:buffet greedy.seats.s9{role:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 9.. if data storage botc_patch:buffet greedy.seats.s9{perceived:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 9.. if data storage botc_patch:buffet greedy.seats.s9{hermit_forced_ability:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 9.. if data storage botc_patch:buffet greedy.seats.s9.hermit_abilities{r113:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 10.. unless data storage botc_patch:buffet greedy.seats.s10{active:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 10.. unless entity @a[tag=botc_buffet_roster,scores={botc_buffet_seat=10},limit=1] run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 10.. unless data storage botc_patch:buffet greedy.seats.s10{submitted:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 10.. unless data storage botc_patch:buffet greedy.seats.s10{status:2} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 10.. if data storage botc_patch:buffet greedy.seats.s10{role:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 10.. if data storage botc_patch:buffet greedy.seats.s10{perceived:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 10.. if data storage botc_patch:buffet greedy.seats.s10{hermit_forced_ability:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 10.. if data storage botc_patch:buffet greedy.seats.s10.hermit_abilities{r113:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 11.. unless data storage botc_patch:buffet greedy.seats.s11{active:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 11.. unless entity @a[tag=botc_buffet_roster,scores={botc_buffet_seat=11},limit=1] run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 11.. unless data storage botc_patch:buffet greedy.seats.s11{submitted:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 11.. unless data storage botc_patch:buffet greedy.seats.s11{status:2} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 11.. if data storage botc_patch:buffet greedy.seats.s11{role:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 11.. if data storage botc_patch:buffet greedy.seats.s11{perceived:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 11.. if data storage botc_patch:buffet greedy.seats.s11{hermit_forced_ability:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 11.. if data storage botc_patch:buffet greedy.seats.s11.hermit_abilities{r113:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 12.. unless data storage botc_patch:buffet greedy.seats.s12{active:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 12.. unless entity @a[tag=botc_buffet_roster,scores={botc_buffet_seat=12},limit=1] run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 12.. unless data storage botc_patch:buffet greedy.seats.s12{submitted:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 12.. unless data storage botc_patch:buffet greedy.seats.s12{status:2} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 12.. if data storage botc_patch:buffet greedy.seats.s12{role:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 12.. if data storage botc_patch:buffet greedy.seats.s12{perceived:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 12.. if data storage botc_patch:buffet greedy.seats.s12{hermit_forced_ability:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 12.. if data storage botc_patch:buffet greedy.seats.s12.hermit_abilities{r113:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 13.. unless data storage botc_patch:buffet greedy.seats.s13{active:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 13.. unless entity @a[tag=botc_buffet_roster,scores={botc_buffet_seat=13},limit=1] run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 13.. unless data storage botc_patch:buffet greedy.seats.s13{submitted:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 13.. unless data storage botc_patch:buffet greedy.seats.s13{status:2} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 13.. if data storage botc_patch:buffet greedy.seats.s13{role:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 13.. if data storage botc_patch:buffet greedy.seats.s13{perceived:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 13.. if data storage botc_patch:buffet greedy.seats.s13{hermit_forced_ability:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 13.. if data storage botc_patch:buffet greedy.seats.s13.hermit_abilities{r113:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 14.. unless data storage botc_patch:buffet greedy.seats.s14{active:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 14.. unless entity @a[tag=botc_buffet_roster,scores={botc_buffet_seat=14},limit=1] run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 14.. unless data storage botc_patch:buffet greedy.seats.s14{submitted:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 14.. unless data storage botc_patch:buffet greedy.seats.s14{status:2} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 14.. if data storage botc_patch:buffet greedy.seats.s14{role:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 14.. if data storage botc_patch:buffet greedy.seats.s14{perceived:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 14.. if data storage botc_patch:buffet greedy.seats.s14{hermit_forced_ability:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 14.. if data storage botc_patch:buffet greedy.seats.s14.hermit_abilities{r113:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 15.. unless data storage botc_patch:buffet greedy.seats.s15{active:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 15.. unless entity @a[tag=botc_buffet_roster,scores={botc_buffet_seat=15},limit=1] run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 15.. unless data storage botc_patch:buffet greedy.seats.s15{submitted:1b} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 15.. unless data storage botc_patch:buffet greedy.seats.s15{status:2} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 15.. if data storage botc_patch:buffet greedy.seats.s15{role:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 15.. if data storage botc_patch:buffet greedy.seats.s15{perceived:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 15.. if data storage botc_patch:buffet greedy.seats.s15{hermit_forced_ability:113} run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 15.. if data storage botc_patch:buffet greedy.seats.s15.hermit_abilities{r113:1b} run scoreboard players set buffet_hard_valid botc_patch 0
function botc_patch:buffet/greedy/start/count_town
function botc_patch:buffet/greedy/start/count_outsider
function botc_patch:buffet/greedy/start/count_minion
function botc_patch:buffet/greedy/start/count_demon
execute if score buffet_roster_count botc_patch matches 1.. if data storage botc_patch:buffet greedy.seats.s1{active:1b,role:90} run function botc_patch:buffet/greedy/start/validate_hermit_1
execute if score buffet_roster_count botc_patch matches 2.. if data storage botc_patch:buffet greedy.seats.s2{active:1b,role:90} run function botc_patch:buffet/greedy/start/validate_hermit_2
execute if score buffet_roster_count botc_patch matches 3.. if data storage botc_patch:buffet greedy.seats.s3{active:1b,role:90} run function botc_patch:buffet/greedy/start/validate_hermit_3
execute if score buffet_roster_count botc_patch matches 4.. if data storage botc_patch:buffet greedy.seats.s4{active:1b,role:90} run function botc_patch:buffet/greedy/start/validate_hermit_4
execute if score buffet_roster_count botc_patch matches 5.. if data storage botc_patch:buffet greedy.seats.s5{active:1b,role:90} run function botc_patch:buffet/greedy/start/validate_hermit_5
execute if score buffet_roster_count botc_patch matches 6.. if data storage botc_patch:buffet greedy.seats.s6{active:1b,role:90} run function botc_patch:buffet/greedy/start/validate_hermit_6
execute if score buffet_roster_count botc_patch matches 7.. if data storage botc_patch:buffet greedy.seats.s7{active:1b,role:90} run function botc_patch:buffet/greedy/start/validate_hermit_7
execute if score buffet_roster_count botc_patch matches 8.. if data storage botc_patch:buffet greedy.seats.s8{active:1b,role:90} run function botc_patch:buffet/greedy/start/validate_hermit_8
execute if score buffet_roster_count botc_patch matches 9.. if data storage botc_patch:buffet greedy.seats.s9{active:1b,role:90} run function botc_patch:buffet/greedy/start/validate_hermit_9
execute if score buffet_roster_count botc_patch matches 10.. if data storage botc_patch:buffet greedy.seats.s10{active:1b,role:90} run function botc_patch:buffet/greedy/start/validate_hermit_10
execute if score buffet_roster_count botc_patch matches 11.. if data storage botc_patch:buffet greedy.seats.s11{active:1b,role:90} run function botc_patch:buffet/greedy/start/validate_hermit_11
execute if score buffet_roster_count botc_patch matches 12.. if data storage botc_patch:buffet greedy.seats.s12{active:1b,role:90} run function botc_patch:buffet/greedy/start/validate_hermit_12
execute if score buffet_roster_count botc_patch matches 13.. if data storage botc_patch:buffet greedy.seats.s13{active:1b,role:90} run function botc_patch:buffet/greedy/start/validate_hermit_13
execute if score buffet_roster_count botc_patch matches 14.. if data storage botc_patch:buffet greedy.seats.s14{active:1b,role:90} run function botc_patch:buffet/greedy/start/validate_hermit_14
execute if score buffet_roster_count botc_patch matches 15.. if data storage botc_patch:buffet greedy.seats.s15{active:1b,role:90} run function botc_patch:buffet/greedy/start/validate_hermit_15
function botc_patch:buffet/greedy/start/validate_jinxes
execute unless score buffet_count_demon botc_patch matches 1.. run scoreboard players set buffet_hard_valid botc_patch 0
scoreboard players set buffet_has_choirboy botc_patch 0
scoreboard players set buffet_has_king botc_patch 0
scoreboard players set buffet_has_huntsman botc_patch 0
scoreboard players set buffet_has_damsel botc_patch 0
execute if data storage botc_patch:buffet greedy.seats.s1{active:1b,role:58} run scoreboard players set buffet_has_choirboy botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s1{active:1b,role:66} run scoreboard players set buffet_has_king botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s1{active:1b,role:65} run scoreboard players set buffet_has_huntsman botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s1{active:1b,role:87} run scoreboard players set buffet_has_damsel botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s2{active:1b,role:58} run scoreboard players set buffet_has_choirboy botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s2{active:1b,role:66} run scoreboard players set buffet_has_king botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s2{active:1b,role:65} run scoreboard players set buffet_has_huntsman botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s2{active:1b,role:87} run scoreboard players set buffet_has_damsel botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s3{active:1b,role:58} run scoreboard players set buffet_has_choirboy botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s3{active:1b,role:66} run scoreboard players set buffet_has_king botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s3{active:1b,role:65} run scoreboard players set buffet_has_huntsman botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s3{active:1b,role:87} run scoreboard players set buffet_has_damsel botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s4{active:1b,role:58} run scoreboard players set buffet_has_choirboy botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s4{active:1b,role:66} run scoreboard players set buffet_has_king botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s4{active:1b,role:65} run scoreboard players set buffet_has_huntsman botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s4{active:1b,role:87} run scoreboard players set buffet_has_damsel botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s5{active:1b,role:58} run scoreboard players set buffet_has_choirboy botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s5{active:1b,role:66} run scoreboard players set buffet_has_king botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s5{active:1b,role:65} run scoreboard players set buffet_has_huntsman botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s5{active:1b,role:87} run scoreboard players set buffet_has_damsel botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s6{active:1b,role:58} run scoreboard players set buffet_has_choirboy botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s6{active:1b,role:66} run scoreboard players set buffet_has_king botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s6{active:1b,role:65} run scoreboard players set buffet_has_huntsman botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s6{active:1b,role:87} run scoreboard players set buffet_has_damsel botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s7{active:1b,role:58} run scoreboard players set buffet_has_choirboy botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s7{active:1b,role:66} run scoreboard players set buffet_has_king botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s7{active:1b,role:65} run scoreboard players set buffet_has_huntsman botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s7{active:1b,role:87} run scoreboard players set buffet_has_damsel botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s8{active:1b,role:58} run scoreboard players set buffet_has_choirboy botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s8{active:1b,role:66} run scoreboard players set buffet_has_king botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s8{active:1b,role:65} run scoreboard players set buffet_has_huntsman botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s8{active:1b,role:87} run scoreboard players set buffet_has_damsel botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s9{active:1b,role:58} run scoreboard players set buffet_has_choirboy botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s9{active:1b,role:66} run scoreboard players set buffet_has_king botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s9{active:1b,role:65} run scoreboard players set buffet_has_huntsman botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s9{active:1b,role:87} run scoreboard players set buffet_has_damsel botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s10{active:1b,role:58} run scoreboard players set buffet_has_choirboy botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s10{active:1b,role:66} run scoreboard players set buffet_has_king botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s10{active:1b,role:65} run scoreboard players set buffet_has_huntsman botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s10{active:1b,role:87} run scoreboard players set buffet_has_damsel botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s11{active:1b,role:58} run scoreboard players set buffet_has_choirboy botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s11{active:1b,role:66} run scoreboard players set buffet_has_king botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s11{active:1b,role:65} run scoreboard players set buffet_has_huntsman botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s11{active:1b,role:87} run scoreboard players set buffet_has_damsel botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s12{active:1b,role:58} run scoreboard players set buffet_has_choirboy botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s12{active:1b,role:66} run scoreboard players set buffet_has_king botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s12{active:1b,role:65} run scoreboard players set buffet_has_huntsman botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s12{active:1b,role:87} run scoreboard players set buffet_has_damsel botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s13{active:1b,role:58} run scoreboard players set buffet_has_choirboy botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s13{active:1b,role:66} run scoreboard players set buffet_has_king botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s13{active:1b,role:65} run scoreboard players set buffet_has_huntsman botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s13{active:1b,role:87} run scoreboard players set buffet_has_damsel botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s14{active:1b,role:58} run scoreboard players set buffet_has_choirboy botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s14{active:1b,role:66} run scoreboard players set buffet_has_king botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s14{active:1b,role:65} run scoreboard players set buffet_has_huntsman botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s14{active:1b,role:87} run scoreboard players set buffet_has_damsel botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s15{active:1b,role:58} run scoreboard players set buffet_has_choirboy botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s15{active:1b,role:66} run scoreboard players set buffet_has_king botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s15{active:1b,role:65} run scoreboard players set buffet_has_huntsman botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s15{active:1b,role:87} run scoreboard players set buffet_has_damsel botc_patch 1
execute if score buffet_has_choirboy botc_patch matches 1 unless score buffet_has_king botc_patch matches 1 run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_has_huntsman botc_patch matches 1 unless score buffet_has_damsel botc_patch matches 1 run scoreboard players set buffet_hard_valid botc_patch 0
execute if score buffet_roster_count botc_patch matches 5 unless score buffet_count_town botc_patch matches 3 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 5 unless score buffet_count_outsider botc_patch matches 0 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 5 unless score buffet_count_minion botc_patch matches 1 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 5 unless score buffet_count_demon botc_patch matches 1 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 6 unless score buffet_count_town botc_patch matches 3 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 6 unless score buffet_count_outsider botc_patch matches 1 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 6 unless score buffet_count_minion botc_patch matches 1 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 6 unless score buffet_count_demon botc_patch matches 1 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 7 unless score buffet_count_town botc_patch matches 5 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 7 unless score buffet_count_outsider botc_patch matches 0 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 7 unless score buffet_count_minion botc_patch matches 1 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 7 unless score buffet_count_demon botc_patch matches 1 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 8 unless score buffet_count_town botc_patch matches 5 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 8 unless score buffet_count_outsider botc_patch matches 1 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 8 unless score buffet_count_minion botc_patch matches 1 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 8 unless score buffet_count_demon botc_patch matches 1 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 9 unless score buffet_count_town botc_patch matches 5 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 9 unless score buffet_count_outsider botc_patch matches 2 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 9 unless score buffet_count_minion botc_patch matches 1 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 9 unless score buffet_count_demon botc_patch matches 1 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 10 unless score buffet_count_town botc_patch matches 7 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 10 unless score buffet_count_outsider botc_patch matches 0 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 10 unless score buffet_count_minion botc_patch matches 2 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 10 unless score buffet_count_demon botc_patch matches 1 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 11 unless score buffet_count_town botc_patch matches 7 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 11 unless score buffet_count_outsider botc_patch matches 1 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 11 unless score buffet_count_minion botc_patch matches 2 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 11 unless score buffet_count_demon botc_patch matches 1 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 12 unless score buffet_count_town botc_patch matches 7 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 12 unless score buffet_count_outsider botc_patch matches 2 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 12 unless score buffet_count_minion botc_patch matches 2 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 12 unless score buffet_count_demon botc_patch matches 1 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 13 unless score buffet_count_town botc_patch matches 9 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 13 unless score buffet_count_outsider botc_patch matches 0 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 13 unless score buffet_count_minion botc_patch matches 3 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 13 unless score buffet_count_demon botc_patch matches 1 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 14 unless score buffet_count_town botc_patch matches 9 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 14 unless score buffet_count_outsider botc_patch matches 1 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 14 unless score buffet_count_minion botc_patch matches 3 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 14 unless score buffet_count_demon botc_patch matches 1 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 15 unless score buffet_count_town botc_patch matches 9 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 15 unless score buffet_count_outsider botc_patch matches 2 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 15 unless score buffet_count_minion botc_patch matches 3 run scoreboard players set buffet_soft_warning botc_patch 1
execute if score buffet_roster_count botc_patch matches 15 unless score buffet_count_demon botc_patch matches 1 run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s1{active:1b,role:53} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s2{active:1b,role:53} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s3{active:1b,role:53} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s4{active:1b,role:53} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s5{active:1b,role:53} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s6{active:1b,role:53} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s7{active:1b,role:53} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s8{active:1b,role:53} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s9{active:1b,role:53} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s10{active:1b,role:53} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s11{active:1b,role:53} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s12{active:1b,role:53} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s13{active:1b,role:53} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s14{active:1b,role:53} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s15{active:1b,role:53} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s1{active:1b,role:54} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s2{active:1b,role:54} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s3{active:1b,role:54} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s4{active:1b,role:54} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s5{active:1b,role:54} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s6{active:1b,role:54} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s7{active:1b,role:54} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s8{active:1b,role:54} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s9{active:1b,role:54} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s10{active:1b,role:54} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s11{active:1b,role:54} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s12{active:1b,role:54} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s13{active:1b,role:54} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s14{active:1b,role:54} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s15{active:1b,role:54} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s1{active:1b,role:20} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s2{active:1b,role:20} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s3{active:1b,role:20} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s4{active:1b,role:20} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s5{active:1b,role:20} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s6{active:1b,role:20} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s7{active:1b,role:20} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s8{active:1b,role:20} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s9{active:1b,role:20} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s10{active:1b,role:20} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s11{active:1b,role:20} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s12{active:1b,role:20} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s13{active:1b,role:20} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s14{active:1b,role:20} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s15{active:1b,role:20} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s1{active:1b,role:56} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s2{active:1b,role:56} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s3{active:1b,role:56} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s4{active:1b,role:56} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s5{active:1b,role:56} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s6{active:1b,role:56} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s7{active:1b,role:56} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s8{active:1b,role:56} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s9{active:1b,role:56} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s10{active:1b,role:56} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s11{active:1b,role:56} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s12{active:1b,role:56} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s13{active:1b,role:56} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s14{active:1b,role:56} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s15{active:1b,role:56} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s1{active:1b,role:120} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s2{active:1b,role:120} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s3{active:1b,role:120} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s4{active:1b,role:120} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s5{active:1b,role:120} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s6{active:1b,role:120} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s7{active:1b,role:120} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s8{active:1b,role:120} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s9{active:1b,role:120} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s10{active:1b,role:120} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s11{active:1b,role:120} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s12{active:1b,role:120} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s13{active:1b,role:120} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s14{active:1b,role:120} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s15{active:1b,role:120} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s1{active:1b,role:102} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s2{active:1b,role:102} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s3{active:1b,role:102} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s4{active:1b,role:102} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s5{active:1b,role:102} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s6{active:1b,role:102} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s7{active:1b,role:102} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s8{active:1b,role:102} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s9{active:1b,role:102} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s10{active:1b,role:102} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s11{active:1b,role:102} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s12{active:1b,role:102} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s13{active:1b,role:102} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s14{active:1b,role:102} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s15{active:1b,role:102} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s1{active:1b,role:90} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s2{active:1b,role:90} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s3{active:1b,role:90} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s4{active:1b,role:90} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s5{active:1b,role:90} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s6{active:1b,role:90} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s7{active:1b,role:90} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s8{active:1b,role:90} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s9{active:1b,role:90} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s10{active:1b,role:90} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s11{active:1b,role:90} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s12{active:1b,role:90} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s13{active:1b,role:90} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s14{active:1b,role:90} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s15{active:1b,role:90} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s1{active:1b,role:129} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s2{active:1b,role:129} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s3{active:1b,role:129} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s4{active:1b,role:129} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s5{active:1b,role:129} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s6{active:1b,role:129} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s7{active:1b,role:129} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s8{active:1b,role:129} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s9{active:1b,role:129} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s10{active:1b,role:129} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s11{active:1b,role:129} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s12{active:1b,role:129} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s13{active:1b,role:129} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s14{active:1b,role:129} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s15{active:1b,role:129} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s1{active:1b,role:130} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s2{active:1b,role:130} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s3{active:1b,role:130} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s4{active:1b,role:130} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s5{active:1b,role:130} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s6{active:1b,role:130} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s7{active:1b,role:130} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s8{active:1b,role:130} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s9{active:1b,role:130} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s10{active:1b,role:130} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s11{active:1b,role:130} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s12{active:1b,role:130} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s13{active:1b,role:130} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s14{active:1b,role:130} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s15{active:1b,role:130} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s1{active:1b,role:132} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s2{active:1b,role:132} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s3{active:1b,role:132} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s4{active:1b,role:132} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s5{active:1b,role:132} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s6{active:1b,role:132} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s7{active:1b,role:132} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s8{active:1b,role:132} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s9{active:1b,role:132} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s10{active:1b,role:132} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s11{active:1b,role:132} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s12{active:1b,role:132} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s13{active:1b,role:132} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s14{active:1b,role:132} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s15{active:1b,role:132} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s1{active:1b,role:134} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s2{active:1b,role:134} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s3{active:1b,role:134} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s4{active:1b,role:134} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s5{active:1b,role:134} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s6{active:1b,role:134} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s7{active:1b,role:134} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s8{active:1b,role:134} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s9{active:1b,role:134} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s10{active:1b,role:134} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s11{active:1b,role:134} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s12{active:1b,role:134} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s13{active:1b,role:134} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s14{active:1b,role:134} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s15{active:1b,role:134} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s1{active:1b,role:111} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s2{active:1b,role:111} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s3{active:1b,role:111} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s4{active:1b,role:111} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s5{active:1b,role:111} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s6{active:1b,role:111} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s7{active:1b,role:111} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s8{active:1b,role:111} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s9{active:1b,role:111} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s10{active:1b,role:111} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s11{active:1b,role:111} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s12{active:1b,role:111} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s13{active:1b,role:111} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s14{active:1b,role:111} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s15{active:1b,role:111} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s1{active:1b,role:136} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s2{active:1b,role:136} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s3{active:1b,role:136} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s4{active:1b,role:136} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s5{active:1b,role:136} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s6{active:1b,role:136} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s7{active:1b,role:136} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s8{active:1b,role:136} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s9{active:1b,role:136} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s10{active:1b,role:136} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s11{active:1b,role:136} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s12{active:1b,role:136} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s13{active:1b,role:136} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s14{active:1b,role:136} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s15{active:1b,role:136} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s1{active:1b,role:115} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s2{active:1b,role:115} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s3{active:1b,role:115} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s4{active:1b,role:115} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s5{active:1b,role:115} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s6{active:1b,role:115} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s7{active:1b,role:115} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s8{active:1b,role:115} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s9{active:1b,role:115} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s10{active:1b,role:115} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s11{active:1b,role:115} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s12{active:1b,role:115} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s13{active:1b,role:115} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s14{active:1b,role:115} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s15{active:1b,role:115} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s1{active:1b,role:121} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s2{active:1b,role:121} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s3{active:1b,role:121} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s4{active:1b,role:121} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s5{active:1b,role:121} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s6{active:1b,role:121} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s7{active:1b,role:121} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s8{active:1b,role:121} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s9{active:1b,role:121} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s10{active:1b,role:121} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s11{active:1b,role:121} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s12{active:1b,role:121} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s13{active:1b,role:121} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s14{active:1b,role:121} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s15{active:1b,role:121} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s1{active:1b,role:119} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s2{active:1b,role:119} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s3{active:1b,role:119} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s4{active:1b,role:119} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s5{active:1b,role:119} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s6{active:1b,role:119} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s7{active:1b,role:119} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s8{active:1b,role:119} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s9{active:1b,role:119} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s10{active:1b,role:119} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s11{active:1b,role:119} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s12{active:1b,role:119} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s13{active:1b,role:119} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s14{active:1b,role:119} run scoreboard players set buffet_soft_warning botc_patch 1
execute if data storage botc_patch:buffet greedy.seats.s15{active:1b,role:119} run scoreboard players set buffet_soft_warning botc_patch 1
