# Generated by tools/generate-storyteller-boomdandy.ps1.
# Do not hand-edit this file; update the generator and regenerate.
# Rebuilds seat 10 from the locked 14-player layout.
setblock 120 72 69 minecraft:spruce_door[facing=west,half=lower,hinge=left,open=false,powered=false]
setblock 120 73 69 minecraft:spruce_door[facing=west,half=upper,hinge=left,open=false,powered=false]
setblock 121 72 69 minecraft:spruce_slab[type=bottom,waterlogged=false]
setblock 121 72 68 minecraft:spruce_trapdoor[facing=north,half=bottom,open=true,powered=false,waterlogged=false]
setblock 121 72 70 minecraft:spruce_trapdoor[facing=south,half=bottom,open=true,powered=false,waterlogged=false]
setblock 122 72 69 minecraft:spruce_wall_sign[facing=east,waterlogged=false]
data modify block 122 72 69 front_text.messages[1] set value {"selector":"@a[team=10_purple]","color":"#911eb4"}
setblock 121 73 69 minecraft:white_wall_banner[facing=east]
data modify block 121 73 69 patterns set value [{pattern:"ct:purple",color:"white"}]
