services:
  mc:
    image: itzg/minecraft-server:latest
    container_name: botc-minecraft
    tty: true
    stdin_open: true

    ports:
      - "25565:25565/tcp"
      - "24454:24454/udp"

    environment:
      EULA: "TRUE"

      MODPACK_PLATFORM: "MODRINTH"
      MODRINTH_MODPACK: "https://modrinth.com/modpack/blood-on-the-clocktower/version/1.5.4"
      VERSION: "1.21.10"

      MEMORY: "6144M"
      MAX_PLAYERS: "25"
      ENABLE_COMMAND_BLOCK: "true"
      USE_AIKAR_FLAGS: "true"

      MODRINTH_FORCE_INCLUDE_FILES: |
        spiffyhud
        fancymenu
        konkrete
        melody

      MODRINTH_PROJECTS: |
        fabric:fancymenu:3.8.2-1.21.10-fabric
        fabric:advanced-chat:1.8.2-1.21.9

      MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
      MODRINTH_FORCE_SYNCHRONIZE: "false"
      MODRINTH_OVERRIDES_EXCLUSIONS: |
        config/voicechat/voicechat-server.properties
        server/config/voicechat/voicechat-server.properties

      ENABLE_RCON: "true"
      RCON_CMDS_STARTUP: |-
        reload
        function ct:admin/init/yawp_reset
        function ct:admin/init/yawp_regions

    volumes:
      - ./data:/data
