# Generated by tools/generate-storyteller-boomdandy.ps1.
# Do not hand-edit this file; update the generator and regenerate.
# Commits Sybillian's normal execution and death flow without starting Final Three.
dialog clear @s
execute unless entity @s[tag=storyteller,tag=botc_boomdandy_execution_pending] run return 0
execute unless score phase game_data matches 3 run tag @s remove botc_boomdandy_execution_pending
execute unless score phase game_data matches 3 run tag @a remove botc_st_last_executed
execute unless score phase game_data matches 3 run return run tellraw @s [{text:"! ",color:"red",bold:true},{text:"Boomdandy can only be executed during nominations.",color:"gray",bold:false}]
execute unless entity @a[tag=botc_st_last_executed,tag=marked_for_execution,tag=!dead,scores={id=1..15,role=107},limit=1] run tag @s remove botc_boomdandy_execution_pending
execute unless entity @a[tag=botc_st_last_executed,tag=marked_for_execution,tag=!dead,scores={id=1..15,role=107},limit=1] run tag @a remove botc_st_last_executed
execute unless entity @a[tag=botc_st_last_executed,tag=marked_for_execution,tag=!dead,scores={id=1..15,role=107},limit=1] run return run tellraw @s [{text:"! ",color:"red",bold:true},{text:"The marked execution target is no longer a living Boomdandy.",color:"gray",bold:false}]
tag @s remove botc_boomdandy_execution_pending
execute as @a[tag=botc_st_last_executed,tag=marked_for_execution,tag=!dead,scores={id=1..15,role=107},limit=1] run function ct:kill/execute/execute
execute as @a[tag=botc_st_last_executed,tag=!dead,scores={id=1..15,role=107},limit=1] run function ct:kill/die
tag @s add botc_st_post_kill_resolved
scoreboard players set grim_notice_boomdandy_done botc_patch 1
tag @a remove botc_st_last_executed
function botc_patch:storyteller_tools/post_execution/replace_items
