# Generated by tools/generate-storyteller-boomdandy.ps1.
# Do not hand-edit this file; update the generator and regenerate.
# Copies the nearest selected seat ID onto the current finalist voter.
scoreboard players operation @a[tag=botc_boomdandy_current_voter,limit=1] pointing_at = @s id
