# Generated by tools/generate-grim-character-editor.ps1.
# Do not hand-edit this file; update the generator and regenerate.
# Shows the occupied-seat player picker using Sybillian's game-start name snapshot.
dialog clear @s
execute unless score phase game_data matches 1.. run return run tellraw @s {"text":"You can only change characters during an active game.","color":"red"}
execute if score grim_editor_reveal_started botc_patch matches 1 run return run function botc_patch:grim/editor/locked
execute unless score grim_editor_game_captured botc_patch matches 1 run function botc_patch:grim/editor/capture_game
execute unless score grim_editor_game_captured botc_patch matches 1 run return run tellraw @s {"text":"The player list from the start of the game isn't available yet.","color":"red"}
function botc_patch:grim/editor/refresh_live_roles
function botc_patch:grim/editor/player_labels/prepare
execute if score grim_editor_dialog_size botc_patch matches 0 run function botc_patch:grim/editor/player_dialog/count_0 with storage botc_patch:grim editor.player_labels
execute if score grim_editor_dialog_size botc_patch matches 1 run function botc_patch:grim/editor/player_dialog/count_1 with storage botc_patch:grim editor.player_labels
execute if score grim_editor_dialog_size botc_patch matches 2 run function botc_patch:grim/editor/player_dialog/count_2 with storage botc_patch:grim editor.player_labels
execute if score grim_editor_dialog_size botc_patch matches 3 run function botc_patch:grim/editor/player_dialog/count_3 with storage botc_patch:grim editor.player_labels
execute if score grim_editor_dialog_size botc_patch matches 4 run function botc_patch:grim/editor/player_dialog/count_4 with storage botc_patch:grim editor.player_labels
execute if score grim_editor_dialog_size botc_patch matches 5 run function botc_patch:grim/editor/player_dialog/count_5 with storage botc_patch:grim editor.player_labels
execute if score grim_editor_dialog_size botc_patch matches 6 run function botc_patch:grim/editor/player_dialog/count_6 with storage botc_patch:grim editor.player_labels
execute if score grim_editor_dialog_size botc_patch matches 7 run function botc_patch:grim/editor/player_dialog/count_7 with storage botc_patch:grim editor.player_labels
execute if score grim_editor_dialog_size botc_patch matches 8 run function botc_patch:grim/editor/player_dialog/count_8 with storage botc_patch:grim editor.player_labels
execute if score grim_editor_dialog_size botc_patch matches 9 run function botc_patch:grim/editor/player_dialog/count_9 with storage botc_patch:grim editor.player_labels
execute if score grim_editor_dialog_size botc_patch matches 10 run function botc_patch:grim/editor/player_dialog/count_10 with storage botc_patch:grim editor.player_labels
execute if score grim_editor_dialog_size botc_patch matches 11 run function botc_patch:grim/editor/player_dialog/count_11 with storage botc_patch:grim editor.player_labels
execute if score grim_editor_dialog_size botc_patch matches 12 run function botc_patch:grim/editor/player_dialog/count_12 with storage botc_patch:grim editor.player_labels
execute if score grim_editor_dialog_size botc_patch matches 13 run function botc_patch:grim/editor/player_dialog/count_13 with storage botc_patch:grim editor.player_labels
execute if score grim_editor_dialog_size botc_patch matches 14 run function botc_patch:grim/editor/player_dialog/count_14 with storage botc_patch:grim editor.player_labels
execute if score grim_editor_dialog_size botc_patch matches 15 run function botc_patch:grim/editor/player_dialog/count_15 with storage botc_patch:grim editor.player_labels
execute unless score grim_editor_dialog_size botc_patch matches 0..15 run function botc_patch:grim/editor/player_dialog/count_15 with storage botc_patch:grim editor.player_labels
