# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Replace one completed trusted assignment with Legion while leaving all player-facing pre-start state untouched.
execute if data storage botc_patch:buffet action.convert{category:2} run scoreboard players remove draft_assigned_outsider botc_patch 1
execute if data storage botc_patch:buffet action.convert{category:1} run scoreboard players remove draft_assigned_town botc_patch 1
$data modify storage botc_patch:buffet draft.seats.s$(seat).actual set value 130
$data modify storage botc_patch:buffet draft.seats.s$(seat).perceived set value 130
$data modify storage botc_patch:buffet draft.seats.s$(seat).alignment set value 2
$data modify storage botc_patch:buffet draft.seats.s$(seat).perceived_alignment set value 2
$data modify storage botc_patch:buffet draft.seats.s$(seat).category set value 4
$data modify storage botc_patch:buffet draft.seats.s$(seat).archetype set value "demon_format_and_setup_changing"
$data modify storage botc_patch:buffet draft.seats.s$(seat).hidden_mode set value 0
$data modify storage botc_patch:buffet draft.seats.s$(seat).topology_modifier set value "legion_conversion"
execute store result score draft_legion_convert_dt botc_patch run data get storage botc_patch:buffet action.convert.delta_town
execute store result score draft_legion_convert_do botc_patch run data get storage botc_patch:buffet action.convert.delta_outsider
execute store result score draft_legion_convert_dm botc_patch run data get storage botc_patch:buffet action.convert.delta_minion
execute store result score draft_legion_convert_dd botc_patch run data get storage botc_patch:buffet action.convert.delta_demon
scoreboard players operation draft_target_town botc_patch -= draft_legion_convert_dt botc_patch
scoreboard players operation draft_target_outsider botc_patch -= draft_legion_convert_do botc_patch
scoreboard players operation draft_target_minion botc_patch -= draft_legion_convert_dm botc_patch
scoreboard players operation draft_target_demon botc_patch -= draft_legion_convert_dd botc_patch
$data modify storage botc_patch:buffet draft.seats.s$(seat).modifier_owner set value 0b
$data modify storage botc_patch:buffet draft.seats.s$(seat).delta_town set value 0
$data modify storage botc_patch:buffet draft.seats.s$(seat).delta_outsider set value 0
$data modify storage botc_patch:buffet draft.seats.s$(seat).delta_minion set value 0
$data modify storage botc_patch:buffet draft.seats.s$(seat).delta_demon set value 0
$data remove storage botc_patch:buffet draft.seats.s$(seat).hermit_forced_ability
$data remove storage botc_patch:buffet draft.seats.s$(seat).hermit_abilities
scoreboard players add draft_assigned_demon botc_patch 1
scoreboard players set draft_chosen_130 botc_patch 1
scoreboard players set draft_available_130 botc_patch 0
$scoreboard players set draft_chosen_$(actual) botc_patch 0
$scoreboard players set draft_available_$(actual) botc_patch 1
$data modify storage botc_patch:buffet action.restore.actual set value $(actual)
function botc_patch:buffet/draft/review/recheck_unassigned_role with storage botc_patch:buffet action.restore
$scoreboard players set draft_chosen_$(perceived) botc_patch 0
$scoreboard players set draft_available_$(perceived) botc_patch 1
$data modify storage botc_patch:buffet action.restore.actual set value $(perceived)
function botc_patch:buffet/draft/review/recheck_unassigned_role with storage botc_patch:buffet action.restore
execute if data storage botc_patch:buffet action.convert.hermit_forced_ability run data modify storage botc_patch:buffet action.restore.actual set from storage botc_patch:buffet action.convert.hermit_forced_ability
execute if data storage botc_patch:buffet action.convert.hermit_forced_ability run function botc_patch:buffet/draft/topology/legion/restore_role with storage botc_patch:buffet action.restore
scoreboard players remove draft_legion_conversion_need botc_patch 1
scoreboard players set draft_legion_convert_done botc_patch 1
function botc_patch:buffet/draft/topology/legion/convert_next
