# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Commit Legion's exact majority after every required private conversion succeeds.
scoreboard players operation draft_target_demon botc_patch = draft_legion_count botc_patch
scoreboard players set draft_target_minion botc_patch 0
scoreboard players operation draft_target_outsider botc_patch = draft_assigned_outsider botc_patch
execute if score draft_target_outsider botc_patch < draft_legion_outsider_floor botc_patch run scoreboard players operation draft_target_outsider botc_patch = draft_legion_outsider_floor botc_patch
scoreboard players operation draft_target_town botc_patch = buffet_roster_count botc_patch
scoreboard players operation draft_target_town botc_patch -= draft_target_outsider botc_patch
scoreboard players operation draft_target_town botc_patch -= draft_target_demon botc_patch
scoreboard players operation draft_required_legion botc_patch = draft_legion_count botc_patch
scoreboard players operation draft_required_legion botc_patch -= draft_assigned_demon botc_patch
function botc_patch:buffet/draft/topology/commit
function botc_patch:buffet/draft/rebuild_requirements
function botc_patch:buffet/draft/next_turn
