# Generated by tools/generate-buffet-gamemodes.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Select one trusted reminder-token category and start at its first page.
execute if score @s botc_buffet_action matches 8511 run scoreboard players set @s botc_bg_rcat 1
execute if score @s botc_buffet_action matches 8512 run scoreboard players set @s botc_bg_rcat 2
execute if score @s botc_buffet_action matches 8513 run scoreboard players set @s botc_bg_rcat 3
execute if score @s botc_buffet_action matches 8514 run scoreboard players set @s botc_bg_rcat 4
execute if score @s botc_buffet_action matches 8515 run scoreboard players set @s botc_bg_rcat 5
scoreboard players set @s botc_bg_rpage 1
function botc_patch:buffet/personal_grimoire/reminders/show
