# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Confirm the Atheist already reserved by the private all-good route.
execute unless score draft_route_kind botc_patch matches 3 run scoreboard players set draft_topology_status botc_patch 3
execute unless score draft_route_kind botc_patch matches 3 run function botc_patch:buffet/attention/block_storytellers
execute unless score draft_route_kind botc_patch matches 3 run return run tellraw @a[tag=storyteller] [{"text":"! ","color":"red","bold":true},{"text":"A real Atheist is only legal in the Storyteller-selected Atheist route.","color":"gray","bold":false}]
function botc_patch:buffet/draft/recount_needs
function botc_patch:buffet/draft/next_turn
