# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Translate the trusted target button into a private setup decision.
execute unless data storage botc_patch:buffet modifier{role:119} unless data storage botc_patch:buffet modifier{role:129} unless data storage botc_patch:buffet modifier{role:134} run return 0
scoreboard players operation draft_requested_outsider botc_patch = @s botc_buffet_action
scoreboard players remove draft_requested_outsider botc_patch 7500
execute store result storage botc_patch:buffet modifier.target int 1 run scoreboard players get draft_requested_outsider botc_patch
function botc_patch:buffet/draft/modifier/set_outsider_target with storage botc_patch:buffet modifier
