# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Choose the next online waiting Draft player without revealing the order publicly.
execute if score draft_modifier_pending botc_patch matches 1 run return 0
function botc_patch:buffet/draft/recount_needs
execute if score draft_current_seat botc_patch matches 1.. run return 0
function botc_patch:buffet/draft/forced/prepare
execute as @r[tag=botc_buffet_draft_waiting] run function botc_patch:buffet/draft/begin_turn
execute if score draft_assigned_total botc_patch = buffet_roster_count botc_patch run scoreboard players set draft_ready botc_patch 1
execute if score draft_assigned_total botc_patch = buffet_roster_count botc_patch run tellraw @a[tag=storyteller] [{"text":"Draft complete. ","color":"green","bold":true},{"text":"Review the assignments, then use Start Game when ready.","color":"gray","bold":false}]
execute unless score draft_assigned_total botc_patch = buffet_roster_count botc_patch unless entity @a[tag=botc_buffet_draft_waiting] if score draft_wait_notice botc_patch matches 0 run tellraw @a[tag=storyteller] [{"text":"The current drafter is offline. The draft will continue when they return.","color":"gray"}]
execute unless score draft_assigned_total botc_patch = buffet_roster_count botc_patch unless entity @a[tag=botc_buffet_draft_waiting] run scoreboard players set draft_wait_notice botc_patch 1
