# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Remind the acting player how to reopen an unfinished Draft turn.
tellraw @s [{"text":"You still need to make a choice, reopen the menu when you're ready.","color":"yellow"}]
