# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Open the trusted Draft history for one selected seat.
scoreboard players operation buffet_selected_seat botc_patch = @s botc_buffet_action
scoreboard players remove buffet_selected_seat botc_patch 7200
execute if score buffet_selected_seat botc_patch matches 1..15 run function botc_patch:buffet/draft/review/open_selected
