# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Copy the private Hermit abilities into the owning seat.
$data modify storage botc_patch:buffet draft.seats.s$(seat).hermit_abilities set from storage botc_patch:buffet modifier.hermit
function botc_patch:buffet/draft/modifier/finish
