# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Show the private Hermit ability picker to Storytellers.
function botc_patch:buffet/draft/modifier/hermit/prepare_abilities
function botc_patch:buffet/draft/modifier/hermit/show_abilities with storage botc_patch:buffet ui
