# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Toggle one trusted Hermit Outsider ability.
scoreboard players set draft_hermit_removed botc_patch 0
$execute if data storage botc_patch:buffet modifier.hermit{r$(role):1b} run scoreboard players set draft_hermit_removed botc_patch 1
$execute if data storage botc_patch:buffet modifier.hermit{r$(role):1b} run data remove storage botc_patch:buffet modifier.hermit.r$(role)
$execute unless data storage botc_patch:buffet modifier.hermit{r$(role):1b} if score draft_hermit_removed botc_patch matches 0 if score draft_hermit_ability_count botc_patch matches 3.. run return run function botc_patch:buffet/draft/modifier/hermit/full
$execute unless data storage botc_patch:buffet modifier.hermit{r$(role):1b} if score draft_hermit_removed botc_patch matches 0 run data modify storage botc_patch:buffet modifier.hermit.r$(role) set value 1b
execute if score draft_hermit_removed botc_patch matches 0 run scoreboard players add draft_hermit_ability_count botc_patch 1
execute if score draft_hermit_removed botc_patch matches 1 run scoreboard players remove draft_hermit_ability_count botc_patch 1
function botc_patch:buffet/draft/modifier/hermit/open_abilities
