# Generated by tools/generate-storyteller-player-menu.ps1.
# Do not hand-edit this file; update the generator and regenerate.
# Teleports the Storyteller to the currently online player in seat 9.
tag @s add botc_st_tool_used
dialog clear @s
execute if entity @a[tag=!storyteller,tag=!spectator,scores={id=9},limit=1] run tellraw @s {"text":"Teleporting...","color":"gray"}
execute if entity @a[tag=!storyteller,tag=!spectator,scores={id=9},limit=1] run tp @s @a[tag=!storyteller,tag=!spectator,scores={id=9},limit=1]
execute if entity @a[tag=!storyteller,tag=!spectator,scores={id=9},limit=1] run function botc_patch:storyteller_tools/teleport_sound
execute unless entity @a[tag=!storyteller,tag=!spectator,scores={id=9},limit=1] run tellraw @s {"text":"That player is no longer available.","color":"red"}
