# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Commit Summoner's no-Demon topology while keeping the standard Minion count.
$data modify storage botc_patch:buffet action.topology set value {seat:$(seat),kind:"summoner"}
function botc_patch:buffet/draft/topology/begin with storage botc_patch:buffet action.topology
execute unless score draft_assigned_demon botc_patch matches 0 run function botc_patch:buffet/draft/topology/rollback
execute unless score draft_assigned_demon botc_patch matches 0 run function botc_patch:buffet/draft/topology/block
execute unless score draft_assigned_demon botc_patch matches 0 run return run tellraw @a[tag=storyteller] [{"text":"! ","color":"red","bold":true},{"text":"Summoner cannot remove the starting Demon because a Demon has already been chosen.","color":"gray","bold":false}]
scoreboard players add draft_target_town botc_patch 1
scoreboard players remove draft_target_demon botc_patch 1
scoreboard players set draft_summoner_active botc_patch 1
$scoreboard players set draft_summoner_owner botc_patch $(seat)
$data modify storage botc_patch:buffet draft.seats.s$(seat).delta_town set value 1
$data modify storage botc_patch:buffet draft.seats.s$(seat).delta_demon set value -1
$data modify storage botc_patch:buffet draft.seats.s$(seat).modifier_owner set value 1b
$data modify storage botc_patch:buffet draft.seats.s$(seat).topology_modifier set value "summoner"
function botc_patch:buffet/draft/topology/commit
function botc_patch:buffet/draft/next_turn
