# Generated by tools/generate-storyteller-kill-menu.ps1.
# Do not hand-edit this file; update the generator and regenerate.
# Filtered player dialog with 0 eligible seat(s).
dialog show @s {type:"multi_action",title:"Kill Player",body:{type:"plain_message",contents:{text:"Choose an alive seated player.",color:"gray"},width:360},columns:3,actions:[{label:"Close",action:{type:"run_command",command:"/botc dialog_cancel"}}],exit_action:{label:"Cancel",action:{type:"run_command",command:"/botc dialog_cancel"}}}
