# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Record the first exact final-editor duplicate conflict and its owning player.
$execute if score buffet_duplicate_found botc_patch matches 0 run data modify storage botc_patch:buffet draft.editor.conflict set value {role:$(role),seat:$(seat),kind:$(kind),player:"Seat $(seat)",role_name:"Unknown character"}
$execute if score buffet_duplicate_found botc_patch matches 0 if data storage botc_patch:buffet draft.seats.s$(seat).name run data modify storage botc_patch:buffet draft.editor.conflict.player set from storage botc_patch:buffet draft.seats.s$(seat).name
execute if score buffet_duplicate_found botc_patch matches 0 run scoreboard players set buffet_duplicate_found botc_patch 1
