# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Select one unseen Draft demon role by random ordinal.
function botc_patch:buffet/draft/pick/prepare_eligibility
scoreboard players set draft_pool_size botc_patch 0
$execute if score draft_eligible_22 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r22:1b} run scoreboard players add draft_pool_size botc_patch 1
$execute if score draft_eligible_120 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r120:1b} run scoreboard players add draft_pool_size botc_patch 1
$execute if score draft_eligible_121 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r121:1b} run scoreboard players add draft_pool_size botc_patch 1
$execute if score draft_eligible_122 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r122:1b} run scoreboard players add draft_pool_size botc_patch 1
$execute if score draft_eligible_123 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r123:1b} run scoreboard players add draft_pool_size botc_patch 1
$execute if score draft_eligible_124 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r124:1b} run scoreboard players add draft_pool_size botc_patch 1
$execute if score draft_eligible_125 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r125:1b} run scoreboard players add draft_pool_size botc_patch 1
$execute if score draft_eligible_126 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r126:1b} run scoreboard players add draft_pool_size botc_patch 1
$execute if score draft_eligible_127 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r127:1b} run scoreboard players add draft_pool_size botc_patch 1
$execute if score draft_eligible_128 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r128:1b} run scoreboard players add draft_pool_size botc_patch 1
$execute if score draft_eligible_129 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r129:1b} run scoreboard players add draft_pool_size botc_patch 1
$execute if score draft_eligible_130 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r130:1b} run scoreboard players add draft_pool_size botc_patch 1
$execute if score draft_eligible_131 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r131:1b} run scoreboard players add draft_pool_size botc_patch 1
$execute if score draft_eligible_132 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r132:1b} run scoreboard players add draft_pool_size botc_patch 1
$execute if score draft_eligible_133 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r133:1b} run scoreboard players add draft_pool_size botc_patch 1
$execute if score draft_eligible_134 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r134:1b} run scoreboard players add draft_pool_size botc_patch 1
$execute if score draft_eligible_135 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r135:1b} run scoreboard players add draft_pool_size botc_patch 1
$execute if score draft_eligible_136 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r136:1b} run scoreboard players add draft_pool_size botc_patch 1
$execute if score draft_eligible_137 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r137:1b} run scoreboard players add draft_pool_size botc_patch 1
execute if score draft_pool_size botc_patch matches 0 if score draft_recycling botc_patch matches 1 run function botc_patch:buffet/draft/pick/recycle_demon with storage botc_patch:buffet action
execute if score draft_pool_size botc_patch matches 0 run scoreboard players set draft_offer_failed botc_patch 1
execute if score draft_pool_size botc_patch matches 0 run return 0
execute store result score draft_pick botc_patch run random value 0..2147483647
scoreboard players operation draft_pick botc_patch %= draft_pool_size botc_patch
scoreboard players add draft_pick botc_patch 1
scoreboard players set draft_cursor botc_patch 0
scoreboard players set draft_role_picked botc_patch 0
$execute if score draft_role_picked botc_patch matches 0 if score draft_eligible_22 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r22:1b} run scoreboard players add draft_cursor botc_patch 1
$execute if score draft_role_picked botc_patch matches 0 if score draft_cursor botc_patch = draft_pick botc_patch if score draft_eligible_22 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r22:1b} run function botc_patch:buffet/draft/pick/role/22
$execute if score draft_role_picked botc_patch matches 0 if score draft_eligible_120 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r120:1b} run scoreboard players add draft_cursor botc_patch 1
$execute if score draft_role_picked botc_patch matches 0 if score draft_cursor botc_patch = draft_pick botc_patch if score draft_eligible_120 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r120:1b} run function botc_patch:buffet/draft/pick/role/120
$execute if score draft_role_picked botc_patch matches 0 if score draft_eligible_121 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r121:1b} run scoreboard players add draft_cursor botc_patch 1
$execute if score draft_role_picked botc_patch matches 0 if score draft_cursor botc_patch = draft_pick botc_patch if score draft_eligible_121 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r121:1b} run function botc_patch:buffet/draft/pick/role/121
$execute if score draft_role_picked botc_patch matches 0 if score draft_eligible_122 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r122:1b} run scoreboard players add draft_cursor botc_patch 1
$execute if score draft_role_picked botc_patch matches 0 if score draft_cursor botc_patch = draft_pick botc_patch if score draft_eligible_122 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r122:1b} run function botc_patch:buffet/draft/pick/role/122
$execute if score draft_role_picked botc_patch matches 0 if score draft_eligible_123 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r123:1b} run scoreboard players add draft_cursor botc_patch 1
$execute if score draft_role_picked botc_patch matches 0 if score draft_cursor botc_patch = draft_pick botc_patch if score draft_eligible_123 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r123:1b} run function botc_patch:buffet/draft/pick/role/123
$execute if score draft_role_picked botc_patch matches 0 if score draft_eligible_124 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r124:1b} run scoreboard players add draft_cursor botc_patch 1
$execute if score draft_role_picked botc_patch matches 0 if score draft_cursor botc_patch = draft_pick botc_patch if score draft_eligible_124 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r124:1b} run function botc_patch:buffet/draft/pick/role/124
$execute if score draft_role_picked botc_patch matches 0 if score draft_eligible_125 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r125:1b} run scoreboard players add draft_cursor botc_patch 1
$execute if score draft_role_picked botc_patch matches 0 if score draft_cursor botc_patch = draft_pick botc_patch if score draft_eligible_125 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r125:1b} run function botc_patch:buffet/draft/pick/role/125
$execute if score draft_role_picked botc_patch matches 0 if score draft_eligible_126 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r126:1b} run scoreboard players add draft_cursor botc_patch 1
$execute if score draft_role_picked botc_patch matches 0 if score draft_cursor botc_patch = draft_pick botc_patch if score draft_eligible_126 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r126:1b} run function botc_patch:buffet/draft/pick/role/126
$execute if score draft_role_picked botc_patch matches 0 if score draft_eligible_127 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r127:1b} run scoreboard players add draft_cursor botc_patch 1
$execute if score draft_role_picked botc_patch matches 0 if score draft_cursor botc_patch = draft_pick botc_patch if score draft_eligible_127 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r127:1b} run function botc_patch:buffet/draft/pick/role/127
$execute if score draft_role_picked botc_patch matches 0 if score draft_eligible_128 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r128:1b} run scoreboard players add draft_cursor botc_patch 1
$execute if score draft_role_picked botc_patch matches 0 if score draft_cursor botc_patch = draft_pick botc_patch if score draft_eligible_128 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r128:1b} run function botc_patch:buffet/draft/pick/role/128
$execute if score draft_role_picked botc_patch matches 0 if score draft_eligible_129 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r129:1b} run scoreboard players add draft_cursor botc_patch 1
$execute if score draft_role_picked botc_patch matches 0 if score draft_cursor botc_patch = draft_pick botc_patch if score draft_eligible_129 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r129:1b} run function botc_patch:buffet/draft/pick/role/129
$execute if score draft_role_picked botc_patch matches 0 if score draft_eligible_130 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r130:1b} run scoreboard players add draft_cursor botc_patch 1
$execute if score draft_role_picked botc_patch matches 0 if score draft_cursor botc_patch = draft_pick botc_patch if score draft_eligible_130 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r130:1b} run function botc_patch:buffet/draft/pick/role/130
$execute if score draft_role_picked botc_patch matches 0 if score draft_eligible_131 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r131:1b} run scoreboard players add draft_cursor botc_patch 1
$execute if score draft_role_picked botc_patch matches 0 if score draft_cursor botc_patch = draft_pick botc_patch if score draft_eligible_131 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r131:1b} run function botc_patch:buffet/draft/pick/role/131
$execute if score draft_role_picked botc_patch matches 0 if score draft_eligible_132 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r132:1b} run scoreboard players add draft_cursor botc_patch 1
$execute if score draft_role_picked botc_patch matches 0 if score draft_cursor botc_patch = draft_pick botc_patch if score draft_eligible_132 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r132:1b} run function botc_patch:buffet/draft/pick/role/132
$execute if score draft_role_picked botc_patch matches 0 if score draft_eligible_133 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r133:1b} run scoreboard players add draft_cursor botc_patch 1
$execute if score draft_role_picked botc_patch matches 0 if score draft_cursor botc_patch = draft_pick botc_patch if score draft_eligible_133 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r133:1b} run function botc_patch:buffet/draft/pick/role/133
$execute if score draft_role_picked botc_patch matches 0 if score draft_eligible_134 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r134:1b} run scoreboard players add draft_cursor botc_patch 1
$execute if score draft_role_picked botc_patch matches 0 if score draft_cursor botc_patch = draft_pick botc_patch if score draft_eligible_134 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r134:1b} run function botc_patch:buffet/draft/pick/role/134
$execute if score draft_role_picked botc_patch matches 0 if score draft_eligible_135 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r135:1b} run scoreboard players add draft_cursor botc_patch 1
$execute if score draft_role_picked botc_patch matches 0 if score draft_cursor botc_patch = draft_pick botc_patch if score draft_eligible_135 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r135:1b} run function botc_patch:buffet/draft/pick/role/135
$execute if score draft_role_picked botc_patch matches 0 if score draft_eligible_136 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r136:1b} run scoreboard players add draft_cursor botc_patch 1
$execute if score draft_role_picked botc_patch matches 0 if score draft_cursor botc_patch = draft_pick botc_patch if score draft_eligible_136 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r136:1b} run function botc_patch:buffet/draft/pick/role/136
$execute if score draft_role_picked botc_patch matches 0 if score draft_eligible_137 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r137:1b} run scoreboard players add draft_cursor botc_patch 1
$execute if score draft_role_picked botc_patch matches 0 if score draft_cursor botc_patch = draft_pick botc_patch if score draft_eligible_137 botc_patch matches 1 unless data storage botc_patch:buffet draft.seats.s$(seat).seen{r137:1b} run function botc_patch:buffet/draft/pick/role/137
$data modify storage botc_patch:buffet action.picked.seat set value $(seat)
$data modify storage botc_patch:buffet action.picked.option set value $(option)
function botc_patch:buffet/draft/pick/store_offer with storage botc_patch:buffet action.picked
execute if score draft_role_picked botc_patch matches 1 run scoreboard players set draft_category_picked botc_patch 1
