# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Store the server-owned role reserved for this private player.
execute if score draft_forced_role botc_patch matches 66 run function botc_patch:buffet/draft/pick/role/66
execute if score draft_forced_role botc_patch matches 87 run function botc_patch:buffet/draft/pick/role/87
execute if score draft_forced_role botc_patch matches 130 run function botc_patch:buffet/draft/pick/role/130
execute if score draft_forced_role botc_patch matches 136 run function botc_patch:buffet/draft/pick/role/136
execute if score draft_forced_role botc_patch matches 78 run function botc_patch:buffet/draft/pick/role/78
$data modify storage botc_patch:buffet action.picked.seat set value $(seat)
$data modify storage botc_patch:buffet action.picked.option set value $(option)
function botc_patch:buffet/draft/pick/store_offer with storage botc_patch:buffet action.picked
execute if score draft_forced_role botc_patch matches 66 run scoreboard players set draft_required_king botc_patch 2
execute if score draft_forced_role botc_patch matches 66 run scoreboard players set draft_king_offer_consumed botc_patch 1
execute if score draft_forced_role botc_patch matches 87 run scoreboard players set draft_required_damsel botc_patch 2
execute if score draft_forced_role botc_patch matches 87 run scoreboard players set draft_damsel_offer_consumed botc_patch 1
