# Generated by tools/generate-grim-character-editor.ps1.
# Do not hand-edit this file; update the generator and regenerate.
# Appends one trusted current-script role to the editor list.
$data modify storage botc_patch:grim editor.roles append from storage botc_patch:grim editor.catalog.$(id)
