# Generated by tools/generate-grim-character-editor.ps1.
# Do not hand-edit this file; update the generator and regenerate.
# Trusted nightly Demon-assignment player dialog for 0 occupied seats.
dialog show @s {type:"multi_action",title:{text:"Assign Demon Tonight - Choose Player",color:"red",bold:true},body:{type:"plain_message",contents:{text:"Choose the player who becomes an evil Demon now.",color:"gray"},width:380},columns:3,after_action:"wait_for_response",actions:[{label:{text:"No seated players",color:"gray"},action:{type:"run_command",command:"/botc grimoire change_characters"}}],exit_action:{label:"Back",action:{type:"run_command",command:"/botc grimoire change_characters"}}}
