# Generated by tools/generate-storyteller-rps.ps1.
# Do not hand-edit this file; update the generator and regenerate.
# Opens the first RPS participant picker from players who already made a choice.
dialog clear @s
execute unless entity @s[tag=storyteller] run return 0
execute unless score phase game_data matches 1.. run return run tellraw @s [{text:"RPS can only start during an active game.",color:"red"}]
execute if score cd rps matches 1.. run return run tellraw @s [{text:"An RPS countdown is already running.",color:"red"}]
tag @a remove botc_rps_first
function botc_patch:storyteller_tools/rps/first/dialog
