# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Choose Drunk or Hermit-Drunk equally when both hidden Atheist actuals remain legal.
scoreboard players set draft_fake_atheist_pool botc_patch 0
execute if score draft_available_17 botc_patch matches 1 run scoreboard players add draft_fake_atheist_pool botc_patch 1
execute if score draft_available_17 botc_patch matches 1 if score draft_available_90 botc_patch matches 1 run scoreboard players add draft_fake_atheist_pool botc_patch 1
execute unless score draft_fake_atheist_pool botc_patch matches 1.. run return run function botc_patch:buffet/draft/next_turn
execute store result score draft_fake_atheist_pick botc_patch run random value 0..2147483646
scoreboard players operation draft_fake_atheist_pick botc_patch %= draft_fake_atheist_pool botc_patch
scoreboard players add draft_fake_atheist_pick botc_patch 1
data modify storage botc_patch:buffet action.picked set value {actual:53,perceived:53,alignment:1,perceived_alignment:1,category:1,archetype:"town_public_action_confirmation_and_alternate_victory",archetype_id:6,hidden:0b,hidden_mode:0,hermit_forced_ability:0,name:"Atheist",color:"#55aaff",glyph:""}
execute if score draft_fake_atheist_pick botc_patch matches 1 run data modify storage botc_patch:buffet action.picked.actual set value 17
execute if score draft_fake_atheist_pick botc_patch matches 1 run data modify storage botc_patch:buffet action.picked.hidden_mode set value 6
execute if score draft_fake_atheist_pick botc_patch matches 2 run data modify storage botc_patch:buffet action.picked.actual set value 90
execute if score draft_fake_atheist_pick botc_patch matches 2 run data modify storage botc_patch:buffet action.picked.hidden_mode set value 7
execute if score draft_fake_atheist_pick botc_patch matches 2 run data modify storage botc_patch:buffet action.picked.hermit_forced_ability set value 17
data modify storage botc_patch:buffet action.picked.alignment set value 1
data modify storage botc_patch:buffet action.picked.category set value 2
data modify storage botc_patch:buffet action.picked.archetype set value "outsider_hidden_identity_ability_and_registration"
data modify storage botc_patch:buffet action.picked.archetype_id set value 9
data modify storage botc_patch:buffet action.picked.hidden set value 1b
data modify storage botc_patch:buffet action.picked.seat set from storage botc_patch:buffet action.seat
function botc_patch:buffet/draft/atheist/store with storage botc_patch:buffet action.picked
