# Generated by tools/generate-buffet-gamemodes.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Begin the Buffet perceived-role announcement sequence.
execute if score buffet_mode botc_patch matches 1 run scoreboard players set buffet_greedy_hud_ready botc_patch 0
title @a[tag=botc_buffet_roster] subtitle " "
title @a[tag=botc_buffet_roster] title "You are..."
title @a[tag=storyteller] subtitle " "
title @a[tag=storyteller] title "You are..."
schedule function botc_patch:buffet/roles/announce_perceived 4s replace
