# Generated by tools/generate-storyteller-madness-execution.ps1.
# Do not hand-edit this file; update the generator and regenerate.
# Dispatches a confirmed seat to its bounded execution function.
dialog clear @s
execute unless entity @s[tag=storyteller] run return 0
$function botc_patch:storyteller_tools/madness_execution/to_seat_$(seat)
