# Generated by tools/generate-storyteller-madness-execution.ps1.
# Do not hand-edit this file; update the generator and regenerate.
# Validates a selected seat before showing the irreversible execution confirmation.
dialog clear @s
execute unless entity @s[tag=storyteller] run return 0
execute unless score phase game_data matches 3 run return run tellraw @s [{text:"Madness executions are only available during nominations.",color:"red"}]
execute unless entity @a[tag=!storyteller,tag=!spectator,scores={id=1..15,role=100}] run return run tellraw @s [{text:"No Cerenovus is in play.",color:"red"}]
$execute unless entity @a[tag=!storyteller,tag=!spectator,tag=!dead,scores={id=$(seat)},limit=1] run return run tellraw @s [{text:"That player is no longer available to execute.",color:"red"}]
$data modify storage botc_patch:dialogs madness_execution_confirm.name set from storage botc_patch:grim editor.player_labels.p$(seat)_name
$data modify storage botc_patch:dialogs madness_execution_confirm.role set from storage botc_patch:grim editor.player_labels.p$(seat)_role
$data modify storage botc_patch:dialogs madness_execution_confirm.glyph set from storage botc_patch:grim editor.player_labels.p$(seat)_glyph
$data modify storage botc_patch:dialogs madness_execution_confirm.color set from storage botc_patch:grim editor.player_labels.p$(seat)_color
$data modify storage botc_patch:dialogs madness_execution_confirm.seat set value $(seat)
function botc_patch:storyteller_tools/madness_execution/show_confirm with storage botc_patch:dialogs madness_execution_confirm
