# Generated by tools/generate-storyteller-madness-execution.ps1.
# Do not hand-edit this file; update the generator and regenerate.
# Executes and kills the alive player in seat 15 for broken Cerenovus madness.
execute unless score phase game_data matches 3 run return run tellraw @s [{text:"! ",color:"red",bold:true},{text:"Executions are only available during nominations.",color:"gray",bold:false}]
execute if entity @s[tag=botc_boomdandy_execution_pending] run return run function botc_patch:storyteller_tools/boomdandy/show_execution_choice
execute if entity @a[tag=storyteller,tag=botc_boomdandy_execution_pending,limit=1] run return run tellraw @s [{text:"Another Storyteller is already choosing how to execute the Boomdandy.",color:"yellow"}]
execute unless entity @a[tag=!storyteller,tag=!spectator,scores={id=1..15,role=100}] run return run tellraw @s [{text:"! ",color:"red",bold:true},{text:"No Cerenovus is in play.",color:"gray",bold:false}]
execute unless entity @a[tag=!storyteller,tag=!spectator,tag=!dead,scores={id=15},limit=1] run return run tellraw @s [{text:"! ",color:"red",bold:true},{text:"That player is no longer available to execute.",color:"gray",bold:false}]
function botc_patch:storyteller_tools/nomination_menu/cancel_vote
tag @a remove nominee
tag @a remove botc_st_last_executed
tag @s remove botc_st_post_kill_resolved
execute as @a[tag=!storyteller,tag=!spectator,tag=!dead,scores={id=15},limit=1] run function ct:kill/execute/mark
tag @a[tag=!storyteller,tag=!spectator,tag=!dead,scores={id=15},limit=1] add botc_st_last_executed
execute if score @a[tag=!storyteller,tag=!spectator,tag=!dead,scores={id=15},limit=1] role matches 107 run return run function botc_patch:storyteller_tools/boomdandy/prepare_execution_choice
execute as @a[tag=!storyteller,tag=!spectator,tag=!dead,scores={id=15},limit=1] run function ct:kill/execute/execute
execute as @a[tag=!storyteller,tag=!spectator,tag=!dead,scores={id=15},limit=1] run function ct:kill/die
tag @s add botc_st_post_kill_resolved
function botc_patch:storyteller_tools/post_execution/replace_items
