# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Select Artist as the current private Draft offer.
data modify storage botc_patch:buffet action.picked set value {actual:33,perceived:33,alignment:1,perceived_alignment:1,category:1,hermit_forced_ability:0,name:"Artist",color:"#55aaff",glyph:""}
scoreboard players set draft_role_picked botc_patch 1
