# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Select Preacher as the trusted actual Draft character.
data modify storage botc_patch:buffet action.picked set value {actual:75,perceived:75,alignment:1,perceived_alignment:1,category:1,archetype:"town_suppression_and_interference",archetype_id:7,hidden:0b,hidden_mode:0,hermit_forced_ability:0,name:"Preacher",color:"#55aaff",glyph:""}
scoreboard players set draft_role_picked botc_patch 1
