# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Divert a first-internal-card lunatic actual into the special-looking sequential flow.
scoreboard players set draft_diversion botc_patch 1
scoreboard players set draft_special_active botc_patch 1
scoreboard players set draft_special_real botc_patch 0
scoreboard players set draft_special_discards botc_patch 0
$data modify storage botc_patch:buffet draft.seats.s$(seat).special set value {active:1b,real:0b,progress:0,discards:0,actual:84,hidden_mode:2,forced_ability:0,archetype:"outsider_hidden_identity_ability_and_registration",archetype_id:9,seen:{}}
$data modify storage botc_patch:buffet draft.seats.s$(seat).seen.r84 set value 1b
$data modify storage botc_patch:buffet draft.seats.s$(seat).exclusions.r84 set value 1b
