# Generated by tools/generate-setup-role-clear.ps1 from Jays-Patch/upstream-contract.json.
scoreboard players set setup_import_valid botc_patch 0
tellraw @s [{"text":"! ","color":"red","bold":true},{"text":"Couldn't import that script: Organ Grinder is unavailable. Unsupported by Sybillian 1.5.4.","color":"gray","bold":false}]
