# Generated by tools/generate-setup-role-clear.ps1 from Jays-Patch/upstream-contract.json.
# Reject scripts containing compatibility-disabled roles.
execute if data storage ct:script in_characters{minions:["organ_grinder"]} run function botc_patch:setup/import/fail_disabled_organ_grinder
