# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Reserve one generated card inside the fresh hand without prematurely retiring it globally.
execute store result storage botc_patch:buffet action.picked.hand_id int 1 run scoreboard players get draft_hand_id botc_patch
execute store result storage botc_patch:buffet action.picked.internal_draw int 1 run scoreboard players get draft_internal_position botc_patch
execute store result storage botc_patch:buffet action.picked.route int 1 run scoreboard players get draft_route_kind botc_patch
$data modify storage botc_patch:buffet draft.seats.s$(seat).internal_offers.i$(option) set from storage botc_patch:buffet action.picked
$data modify storage botc_patch:buffet draft.seats.s$(seat).seen.r$(actual) set value 1b
$data modify storage botc_patch:buffet draft.seats.s$(seat).seen.r$(perceived) set value 1b
$data modify storage botc_patch:buffet draft.seats.s$(seat).exclusions.r$(actual) set value 1b
$data modify storage botc_patch:buffet draft.seats.s$(seat).exclusions.r$(perceived) set value 1b
$scoreboard players set draft_reserved_$(actual) botc_patch 1
$scoreboard players set draft_reserved_$(perceived) botc_patch 1
$data modify storage botc_patch:buffet draft.reservations.r$(actual) set value 1b
$data modify storage botc_patch:buffet draft.reservations.r$(perceived) set value 1b
$execute unless data storage botc_patch:buffet action.picked{hermit_forced_ability:0} run data modify storage botc_patch:buffet draft.seats.s$(seat).seen.r$(hermit_forced_ability) set value 1b
$execute unless data storage botc_patch:buffet action.picked{hermit_forced_ability:0} run data modify storage botc_patch:buffet draft.seats.s$(seat).exclusions.r$(hermit_forced_ability) set value 1b
$execute unless data storage botc_patch:buffet action.picked{hermit_forced_ability:0} run scoreboard players set draft_reserved_$(hermit_forced_ability) botc_patch 1
execute if data storage botc_patch:buffet action.picked{archetype_id:1} run scoreboard players add draft_arch_1 botc_patch 1
execute if data storage botc_patch:buffet action.picked{archetype_id:2} run scoreboard players add draft_arch_2 botc_patch 1
execute if data storage botc_patch:buffet action.picked{archetype_id:3} run scoreboard players add draft_arch_3 botc_patch 1
execute if data storage botc_patch:buffet action.picked{archetype_id:4} run scoreboard players add draft_arch_4 botc_patch 1
execute if data storage botc_patch:buffet action.picked{archetype_id:5} run scoreboard players add draft_arch_5 botc_patch 1
execute if data storage botc_patch:buffet action.picked{archetype_id:6} run scoreboard players add draft_arch_6 botc_patch 1
execute if data storage botc_patch:buffet action.picked{archetype_id:7} run scoreboard players add draft_arch_7 botc_patch 1
execute if data storage botc_patch:buffet action.picked{archetype_id:8} run scoreboard players add draft_arch_8 botc_patch 1
execute if data storage botc_patch:buffet action.picked{archetype_id:9} run scoreboard players add draft_arch_9 botc_patch 1
execute if data storage botc_patch:buffet action.picked{archetype_id:10} run scoreboard players add draft_arch_10 botc_patch 1
execute if data storage botc_patch:buffet action.picked{archetype_id:11} run scoreboard players add draft_arch_11 botc_patch 1
execute if data storage botc_patch:buffet action.picked{archetype_id:12} run scoreboard players add draft_arch_12 botc_patch 1
execute if data storage botc_patch:buffet action.picked{archetype_id:13} run scoreboard players add draft_arch_13 botc_patch 1
execute if data storage botc_patch:buffet action.picked{archetype_id:14} run scoreboard players add draft_arch_14 botc_patch 1
execute if data storage botc_patch:buffet action.picked{archetype_id:15} run scoreboard players add draft_arch_15 botc_patch 1
execute if data storage botc_patch:buffet action.picked{archetype_id:16} run scoreboard players add draft_arch_16 botc_patch 1
execute if data storage botc_patch:buffet action.picked{archetype_id:17} run scoreboard players add draft_arch_17 botc_patch 1
execute if data storage botc_patch:buffet action.picked{archetype_id:18} run scoreboard players add draft_arch_18 botc_patch 1
execute if data storage botc_patch:buffet action.picked{archetype_id:19} run scoreboard players add draft_arch_19 botc_patch 1
execute if data storage botc_patch:buffet action.picked{archetype_id:20} run scoreboard players add draft_arch_20 botc_patch 1
execute if data storage botc_patch:buffet action.picked{archetype_id:21} run scoreboard players add draft_arch_21 botc_patch 1
execute if data storage botc_patch:buffet action.picked{archetype_id:22} run scoreboard players add draft_arch_22 botc_patch 1
scoreboard players set draft_category_picked botc_patch 1
