# Generated by tools/generate-buffet-gamemodes.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Prepare the Storyteller grimoire overlay for a hidden drunk player.
data modify storage botc_patch:buffet hidden_grim set value {seat:0,perceived:0,role:"none",reminder:"drunk"}
execute store result storage botc_patch:buffet hidden_grim.seat int 1 run scoreboard players get @s id
execute store result storage botc_patch:buffet hidden_grim.perceived int 1 run scoreboard players get @s botc_buffet_perceived
function botc_patch:buffet/roles/resolve_hidden_grim_role with storage botc_patch:buffet hidden_grim
