# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Show a completed player only the character they were shown.
$dialog show @s {type:"notice",title:{text:"Your Draft Choice",color:"aqua",bold:true},body:[{type:"plain_message",contents:{text:"$(completed_glyph)",font:"botc_patch:role_icons",color:"white",extra:[{text:" $(completed_name)",font:"minecraft:default",color:"$(completed_color)",bold:true}]},width:360},{type:"plain_message",contents:{text:"This is the character you were shown. Only you can see this.",color:"gray"},width:360}],action:{label:{text:"Close",color:"gray"}}}
