# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Select Goblin as a perceived hidden-role mask.
data modify storage botc_patch:buffet action.mask set value {actual:109,perceived:109,alignment:2,perceived_alignment:2,category:3,hermit_forced_ability:0,name:"Goblin",color:"#ffaa00",glyph:""}
scoreboard players set draft_mask_picked botc_patch 1
