# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Select Klutz as a trusted perceived mask.
data modify storage botc_patch:buffet action.mask set value {actual:82,perceived:82,alignment:1,perceived_alignment:1,category:2,archetype:"outsider_death_consequence",archetype_id:11,hidden:0b,hidden_mode:0,hermit_forced_ability:0,name:"Klutz",color:"#55ffff",glyph:""}
scoreboard players set draft_mask_picked botc_patch 1
