# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Select Snitch as a perceived hidden-role mask.
data modify storage botc_patch:buffet action.mask set value {actual:96,perceived:96,alignment:1,perceived_alignment:1,category:2,hermit_forced_ability:0,name:"Snitch",color:"#55ffff",glyph:""}
scoreboard players set draft_mask_picked botc_patch 1
