# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Select Mezepheles as the trusted actual Draft character.
data modify storage botc_patch:buffet action.picked set value {actual:112,perceived:112,alignment:2,perceived_alignment:2,category:3,archetype:"minion_character_and_setup_manipulation",archetype_id:18,hidden:0b,hidden_mode:0,hermit_forced_ability:0,name:"Mezepheles",color:"#ffaa00",glyph:""}
scoreboard players set draft_role_picked botc_patch 1
