# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Select Shabaloth as the trusted actual Draft character.
data modify storage botc_patch:buffet action.picked set value {actual:126,perceived:126,alignment:2,perceived_alignment:2,category:4,archetype:"demon_variable_killing_and_target_control",archetype_id:20,hidden:0b,hidden_mode:0,hermit_forced_ability:0,name:"Shabaloth",color:"#ff5555",glyph:""}
scoreboard players set draft_role_picked botc_patch 1
