# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Select Butler as the trusted actual Draft character.
data modify storage botc_patch:buffet action.picked set value {actual:14,perceived:14,alignment:1,perceived_alignment:1,category:2,archetype:"outsider_voting_and_nomination_constraint",archetype_id:10,hidden:0b,hidden_mode:0,hermit_forced_ability:0,name:"Butler",color:"#55ffff",glyph:""}
scoreboard players set draft_role_picked botc_patch 1
