# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Select Grandmother as the current private Draft offer.
data modify storage botc_patch:buffet action.picked set value {actual:36,perceived:36,alignment:1,perceived_alignment:1,category:1,name:"Grandmother",color:"#55aaff",glyph:""}
scoreboard players set draft_role_picked botc_patch 1
