# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Select Sailor as the trusted actual Draft character.
data modify storage botc_patch:buffet action.picked set value {actual:37,perceived:37,alignment:1,perceived_alignment:1,category:1,archetype:"town_protection_and_survival",archetype_id:4,hidden:0b,hidden_mode:0,hermit_forced_ability:0,name:"Sailor",color:"#55aaff",glyph:""}
scoreboard players set draft_role_picked botc_patch 1
