# Generated by tools/generate-storyteller-boomdandy.ps1.
# Do not hand-edit this file; update the generator and regenerate.
# Stops an active resolution when the confirmed final three are no longer valid.
tellraw @a[tag=storyteller] [{text:"! ",color:"red",bold:true},{text:"Boomdandy paused because all three finalists must remain online and living.",color:"gray",bold:false}]
function botc_patch:storyteller_tools/boomdandy/cleanup
