# Generated by tools/generate-storyteller-boomdandy.ps1.
# Do not hand-edit this file; update the generator and regenerate.
# Removes every chair except the three selected finalists' locked-layout seats.
function botc_patch:seat_layout/clear
tag @e[type=minecraft:item_display,tag=vote_marker] remove botc_boomdandy_finalist_seat
execute if entity @a[tag=botc_boomdandy_finalist,scores={id=1},limit=1] run tag @e[type=minecraft:item_display,tag=vote_marker,scores={id=1},limit=1] add botc_boomdandy_finalist_seat
execute if entity @a[tag=botc_boomdandy_finalist,scores={id=2},limit=1] run tag @e[type=minecraft:item_display,tag=vote_marker,scores={id=2},limit=1] add botc_boomdandy_finalist_seat
execute if entity @a[tag=botc_boomdandy_finalist,scores={id=3},limit=1] run tag @e[type=minecraft:item_display,tag=vote_marker,scores={id=3},limit=1] add botc_boomdandy_finalist_seat
execute if entity @a[tag=botc_boomdandy_finalist,scores={id=4},limit=1] run tag @e[type=minecraft:item_display,tag=vote_marker,scores={id=4},limit=1] add botc_boomdandy_finalist_seat
execute if entity @a[tag=botc_boomdandy_finalist,scores={id=5},limit=1] run tag @e[type=minecraft:item_display,tag=vote_marker,scores={id=5},limit=1] add botc_boomdandy_finalist_seat
execute if entity @a[tag=botc_boomdandy_finalist,scores={id=6},limit=1] run tag @e[type=minecraft:item_display,tag=vote_marker,scores={id=6},limit=1] add botc_boomdandy_finalist_seat
execute if entity @a[tag=botc_boomdandy_finalist,scores={id=7},limit=1] run tag @e[type=minecraft:item_display,tag=vote_marker,scores={id=7},limit=1] add botc_boomdandy_finalist_seat
execute if entity @a[tag=botc_boomdandy_finalist,scores={id=8},limit=1] run tag @e[type=minecraft:item_display,tag=vote_marker,scores={id=8},limit=1] add botc_boomdandy_finalist_seat
execute if entity @a[tag=botc_boomdandy_finalist,scores={id=9},limit=1] run tag @e[type=minecraft:item_display,tag=vote_marker,scores={id=9},limit=1] add botc_boomdandy_finalist_seat
execute if entity @a[tag=botc_boomdandy_finalist,scores={id=10},limit=1] run tag @e[type=minecraft:item_display,tag=vote_marker,scores={id=10},limit=1] add botc_boomdandy_finalist_seat
execute if entity @a[tag=botc_boomdandy_finalist,scores={id=11},limit=1] run tag @e[type=minecraft:item_display,tag=vote_marker,scores={id=11},limit=1] add botc_boomdandy_finalist_seat
execute if entity @a[tag=botc_boomdandy_finalist,scores={id=12},limit=1] run tag @e[type=minecraft:item_display,tag=vote_marker,scores={id=12},limit=1] add botc_boomdandy_finalist_seat
execute if entity @a[tag=botc_boomdandy_finalist,scores={id=13},limit=1] run tag @e[type=minecraft:item_display,tag=vote_marker,scores={id=13},limit=1] add botc_boomdandy_finalist_seat
execute if entity @a[tag=botc_boomdandy_finalist,scores={id=14},limit=1] run tag @e[type=minecraft:item_display,tag=vote_marker,scores={id=14},limit=1] add botc_boomdandy_finalist_seat
execute if entity @a[tag=botc_boomdandy_finalist,scores={id=15},limit=1] run tag @e[type=minecraft:item_display,tag=vote_marker,scores={id=15},limit=1] add botc_boomdandy_finalist_seat
execute as @a[tag=botc_boomdandy_finalist,tag=!dead,scores={id=1..15}] run function botc_patch:storyteller_tools/boomdandy/seats/place_selected
execute as @e[type=minecraft:item_display,tag=vote_marker,scores={id=1..15}] run data modify entity @s transformation.scale set value [0f,0f,0f]
scoreboard players set boomdandy_seats_trimmed botc_patch 1
