# Generated by tools/generate-storyteller-boomdandy.ps1.
# Do not hand-edit this file; update the generator and regenerate.
# Requires all game-start seats online and at least three living players.
scoreboard players set boomdandy_population_ok botc_patch 1
scoreboard players set boomdandy_online botc_patch 0
scoreboard players set boomdandy_alive botc_patch 0
execute as @a[tag=!storyteller,tag=!spectator,scores={id=1..15}] run scoreboard players add boomdandy_online botc_patch 1
execute as @a[tag=!storyteller,tag=!spectator,tag=!dead,scores={id=1..15}] run scoreboard players add boomdandy_alive botc_patch 1
scoreboard players operation boomdandy_expected botc_patch = seat_layout_locked_count botc_patch
execute if score boomdandy_expected botc_patch matches 0 run scoreboard players operation boomdandy_expected botc_patch = player_count game_data
execute unless score boomdandy_online botc_patch = boomdandy_expected botc_patch run tellraw @s [{text:"Every seated player must be online before resolving Boomdandy.",color:"red"}]
execute unless score boomdandy_online botc_patch = boomdandy_expected botc_patch run scoreboard players set boomdandy_population_ok botc_patch 0
execute unless score boomdandy_alive botc_patch matches 3.. run tellraw @s [{text:"Boomdandy needs at least three living players.",color:"red"}]
execute unless score boomdandy_alive botc_patch matches 3.. run scoreboard players set boomdandy_population_ok botc_patch 0
