# Generated by tools/generate-storyteller-boomdandy.ps1.
# Do not hand-edit this file; update the generator and regenerate.
# Rebuilds seat 8 from the locked 15-player layout.
setblock 129 72 73 minecraft:spruce_door[facing=south,half=lower,hinge=left,open=false,powered=false]
setblock 129 73 73 minecraft:spruce_door[facing=south,half=upper,hinge=left,open=false,powered=false]
setblock 129 72 72 minecraft:spruce_slab[type=bottom,waterlogged=false]
setblock 128 72 72 minecraft:spruce_trapdoor[facing=west,half=bottom,open=true,powered=false,waterlogged=false]
setblock 130 72 72 minecraft:spruce_trapdoor[facing=east,half=bottom,open=true,powered=false,waterlogged=false]
setblock 129 72 71 minecraft:spruce_wall_sign[facing=north,waterlogged=false]
data modify block 129 72 71 front_text.messages[1] set value {"selector":"@a[team=08_blue]","color":"#4363d8"}
setblock 129 73 72 minecraft:white_wall_banner[facing=north]
data modify block 129 73 72 patterns set value [{pattern:"ct:blue",color:"white"}]
