# Generated by tools/generate-music.ps1.
# Do not hand-edit this file; update Jays-Patch/music-tracks.json and regenerate.
# Chooses uniformly from every track exposed in the Night Music dialog.
execute store result score @s botc_music_pick run random value 0..26
function botc_patch:music/play_selected
