# Generated by tools/generate-music.ps1.
# Do not hand-edit this file; update Jays-Patch/music-tracks.json and regenerate.
# Routes stable trigger values into music controls or a selected track.
execute unless score phase game_data matches 4 run tellraw @s [{text:"Night music can only be changed during night.",color:"gray"}]
execute unless score phase game_data matches 4 run return 0

execute if score @s botc_music_select matches 1 run function botc_patch:music/off
execute if score @s botc_music_select matches 2 run function botc_patch:music/on
execute if score @s botc_music_select matches 3 run function botc_patch:music/random_self
execute if score @s botc_music_select matches 4 run scoreboard players set @s botc_music_pick 0
execute if score @s botc_music_select matches 5 run scoreboard players set @s botc_music_pick 1
execute if score @s botc_music_select matches 6 run scoreboard players set @s botc_music_pick 2
execute if score @s botc_music_select matches 7 run scoreboard players set @s botc_music_pick 3
execute if score @s botc_music_select matches 8 run scoreboard players set @s botc_music_pick 4
execute if score @s botc_music_select matches 9 run scoreboard players set @s botc_music_pick 5
execute if score @s botc_music_select matches 10 run scoreboard players set @s botc_music_pick 6
execute if score @s botc_music_select matches 11 run scoreboard players set @s botc_music_pick 7
execute if score @s botc_music_select matches 12 run scoreboard players set @s botc_music_pick 8
execute if score @s botc_music_select matches 13 run scoreboard players set @s botc_music_pick 9
execute if score @s botc_music_select matches 14 run scoreboard players set @s botc_music_pick 10
execute if score @s botc_music_select matches 15 run scoreboard players set @s botc_music_pick 11
execute if score @s botc_music_select matches 16 run scoreboard players set @s botc_music_pick 12
execute if score @s botc_music_select matches 17 run scoreboard players set @s botc_music_pick 13
execute if score @s botc_music_select matches 18 run scoreboard players set @s botc_music_pick 14
execute if score @s botc_music_select matches 19 run scoreboard players set @s botc_music_pick 15
execute if score @s botc_music_select matches 20 run scoreboard players set @s botc_music_pick 16
execute if score @s botc_music_select matches 21 run scoreboard players set @s botc_music_pick 17
execute if score @s botc_music_select matches 23 run scoreboard players set @s botc_music_pick 18
execute if score @s botc_music_select matches 24 run scoreboard players set @s botc_music_pick 19
execute if score @s botc_music_select matches 25 run scoreboard players set @s botc_music_pick 20
execute if score @s botc_music_select matches 26 run scoreboard players set @s botc_music_pick 21
execute if score @s botc_music_select matches 27 run scoreboard players set @s botc_music_pick 22
execute if score @s botc_music_select matches 28 run scoreboard players set @s botc_music_pick 23
execute if score @s botc_music_select matches 29 run scoreboard players set @s botc_music_pick 24
execute if score @s botc_music_select matches 30 run scoreboard players set @s botc_music_pick 25
execute if score @s botc_music_select matches 31 run scoreboard players set @s botc_music_pick 26
execute if score @s botc_music_select matches 22 run function botc_patch:music/toggle_pitch
execute if score @s botc_music_select matches 4 run function botc_patch:music/play_selected
execute if score @s botc_music_select matches 5 run function botc_patch:music/play_selected
execute if score @s botc_music_select matches 6 run function botc_patch:music/play_selected
execute if score @s botc_music_select matches 7 run function botc_patch:music/play_selected
execute if score @s botc_music_select matches 8 run function botc_patch:music/play_selected
execute if score @s botc_music_select matches 9 run function botc_patch:music/play_selected
execute if score @s botc_music_select matches 10 run function botc_patch:music/play_selected
execute if score @s botc_music_select matches 11 run function botc_patch:music/play_selected
execute if score @s botc_music_select matches 12 run function botc_patch:music/play_selected
execute if score @s botc_music_select matches 13 run function botc_patch:music/play_selected
execute if score @s botc_music_select matches 14 run function botc_patch:music/play_selected
execute if score @s botc_music_select matches 15 run function botc_patch:music/play_selected
execute if score @s botc_music_select matches 16 run function botc_patch:music/play_selected
execute if score @s botc_music_select matches 17 run function botc_patch:music/play_selected
execute if score @s botc_music_select matches 18 run function botc_patch:music/play_selected
execute if score @s botc_music_select matches 19 run function botc_patch:music/play_selected
execute if score @s botc_music_select matches 20 run function botc_patch:music/play_selected
execute if score @s botc_music_select matches 21 run function botc_patch:music/play_selected
execute if score @s botc_music_select matches 23 run function botc_patch:music/play_selected
execute if score @s botc_music_select matches 24 run function botc_patch:music/play_selected
execute if score @s botc_music_select matches 25 run function botc_patch:music/play_selected
execute if score @s botc_music_select matches 26 run function botc_patch:music/play_selected
execute if score @s botc_music_select matches 27 run function botc_patch:music/play_selected
execute if score @s botc_music_select matches 28 run function botc_patch:music/play_selected
execute if score @s botc_music_select matches 29 run function botc_patch:music/play_selected
execute if score @s botc_music_select matches 30 run function botc_patch:music/play_selected
execute if score @s botc_music_select matches 31 run function botc_patch:music/play_selected
