# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Use the available hidden Drunk fallback while preserving the perceived source role.
$data modify storage botc_patch:buffet draft.seats.s$(seat).actual set value 17
$data modify storage botc_patch:buffet draft.seats.s$(seat).perceived set value $(source)
$data modify storage botc_patch:buffet draft.seats.s$(seat).category set value 2
scoreboard players remove draft_assigned_town botc_patch 1
scoreboard players add draft_assigned_outsider botc_patch 1
scoreboard players remove draft_target_town botc_patch 1
scoreboard players add draft_target_outsider botc_patch 1
scoreboard players set draft_chosen_17 botc_patch 1
scoreboard players set draft_available_17 botc_patch 0
execute if data storage botc_patch:buffet action{source:58} run scoreboard players set draft_required_king botc_patch 0
execute if data storage botc_patch:buffet action{source:65} run scoreboard players set draft_required_damsel botc_patch 0
