# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Use the category-preserving Village Idiot dependency fallback.
function botc_patch:buffet/draft/start/init_fallback_vi
$data modify storage botc_patch:buffet draft.seats.s$(seat).actual set value 78
$data modify storage botc_patch:buffet draft.seats.s$(seat).perceived set value 78
$data modify storage botc_patch:buffet draft.seats.s$(seat).alignment set value 1
$data modify storage botc_patch:buffet draft.seats.s$(seat).perceived_alignment set value 1
scoreboard players set draft_chosen_78 botc_patch 1
scoreboard players set draft_available_78 botc_patch 0
execute if data storage botc_patch:buffet action{source:58} run scoreboard players set draft_required_king botc_patch 0
execute if data storage botc_patch:buffet action{source:65} run scoreboard players set draft_required_damsel botc_patch 0
