# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Restore a resolved Bounty Hunter target when its source or reserved seat disappears before game start.
execute if score draft_bounty_target_seat botc_patch matches 1 if data storage botc_patch:buffet draft.seats.s1{status:2,category:1} run data modify storage botc_patch:buffet draft.seats.s1.alignment set value 1
execute if score draft_bounty_target_seat botc_patch matches 1 if data storage botc_patch:buffet draft.seats.s1{status:2,category:1} run data modify storage botc_patch:buffet draft.seats.s1.perceived_alignment set value 1
execute if score draft_bounty_target_seat botc_patch matches 2 if data storage botc_patch:buffet draft.seats.s2{status:2,category:1} run data modify storage botc_patch:buffet draft.seats.s2.alignment set value 1
execute if score draft_bounty_target_seat botc_patch matches 2 if data storage botc_patch:buffet draft.seats.s2{status:2,category:1} run data modify storage botc_patch:buffet draft.seats.s2.perceived_alignment set value 1
execute if score draft_bounty_target_seat botc_patch matches 3 if data storage botc_patch:buffet draft.seats.s3{status:2,category:1} run data modify storage botc_patch:buffet draft.seats.s3.alignment set value 1
execute if score draft_bounty_target_seat botc_patch matches 3 if data storage botc_patch:buffet draft.seats.s3{status:2,category:1} run data modify storage botc_patch:buffet draft.seats.s3.perceived_alignment set value 1
execute if score draft_bounty_target_seat botc_patch matches 4 if data storage botc_patch:buffet draft.seats.s4{status:2,category:1} run data modify storage botc_patch:buffet draft.seats.s4.alignment set value 1
execute if score draft_bounty_target_seat botc_patch matches 4 if data storage botc_patch:buffet draft.seats.s4{status:2,category:1} run data modify storage botc_patch:buffet draft.seats.s4.perceived_alignment set value 1
execute if score draft_bounty_target_seat botc_patch matches 5 if data storage botc_patch:buffet draft.seats.s5{status:2,category:1} run data modify storage botc_patch:buffet draft.seats.s5.alignment set value 1
execute if score draft_bounty_target_seat botc_patch matches 5 if data storage botc_patch:buffet draft.seats.s5{status:2,category:1} run data modify storage botc_patch:buffet draft.seats.s5.perceived_alignment set value 1
execute if score draft_bounty_target_seat botc_patch matches 6 if data storage botc_patch:buffet draft.seats.s6{status:2,category:1} run data modify storage botc_patch:buffet draft.seats.s6.alignment set value 1
execute if score draft_bounty_target_seat botc_patch matches 6 if data storage botc_patch:buffet draft.seats.s6{status:2,category:1} run data modify storage botc_patch:buffet draft.seats.s6.perceived_alignment set value 1
execute if score draft_bounty_target_seat botc_patch matches 7 if data storage botc_patch:buffet draft.seats.s7{status:2,category:1} run data modify storage botc_patch:buffet draft.seats.s7.alignment set value 1
execute if score draft_bounty_target_seat botc_patch matches 7 if data storage botc_patch:buffet draft.seats.s7{status:2,category:1} run data modify storage botc_patch:buffet draft.seats.s7.perceived_alignment set value 1
execute if score draft_bounty_target_seat botc_patch matches 8 if data storage botc_patch:buffet draft.seats.s8{status:2,category:1} run data modify storage botc_patch:buffet draft.seats.s8.alignment set value 1
execute if score draft_bounty_target_seat botc_patch matches 8 if data storage botc_patch:buffet draft.seats.s8{status:2,category:1} run data modify storage botc_patch:buffet draft.seats.s8.perceived_alignment set value 1
execute if score draft_bounty_target_seat botc_patch matches 9 if data storage botc_patch:buffet draft.seats.s9{status:2,category:1} run data modify storage botc_patch:buffet draft.seats.s9.alignment set value 1
execute if score draft_bounty_target_seat botc_patch matches 9 if data storage botc_patch:buffet draft.seats.s9{status:2,category:1} run data modify storage botc_patch:buffet draft.seats.s9.perceived_alignment set value 1
execute if score draft_bounty_target_seat botc_patch matches 10 if data storage botc_patch:buffet draft.seats.s10{status:2,category:1} run data modify storage botc_patch:buffet draft.seats.s10.alignment set value 1
execute if score draft_bounty_target_seat botc_patch matches 10 if data storage botc_patch:buffet draft.seats.s10{status:2,category:1} run data modify storage botc_patch:buffet draft.seats.s10.perceived_alignment set value 1
execute if score draft_bounty_target_seat botc_patch matches 11 if data storage botc_patch:buffet draft.seats.s11{status:2,category:1} run data modify storage botc_patch:buffet draft.seats.s11.alignment set value 1
execute if score draft_bounty_target_seat botc_patch matches 11 if data storage botc_patch:buffet draft.seats.s11{status:2,category:1} run data modify storage botc_patch:buffet draft.seats.s11.perceived_alignment set value 1
execute if score draft_bounty_target_seat botc_patch matches 12 if data storage botc_patch:buffet draft.seats.s12{status:2,category:1} run data modify storage botc_patch:buffet draft.seats.s12.alignment set value 1
execute if score draft_bounty_target_seat botc_patch matches 12 if data storage botc_patch:buffet draft.seats.s12{status:2,category:1} run data modify storage botc_patch:buffet draft.seats.s12.perceived_alignment set value 1
execute if score draft_bounty_target_seat botc_patch matches 13 if data storage botc_patch:buffet draft.seats.s13{status:2,category:1} run data modify storage botc_patch:buffet draft.seats.s13.alignment set value 1
execute if score draft_bounty_target_seat botc_patch matches 13 if data storage botc_patch:buffet draft.seats.s13{status:2,category:1} run data modify storage botc_patch:buffet draft.seats.s13.perceived_alignment set value 1
execute if score draft_bounty_target_seat botc_patch matches 14 if data storage botc_patch:buffet draft.seats.s14{status:2,category:1} run data modify storage botc_patch:buffet draft.seats.s14.alignment set value 1
execute if score draft_bounty_target_seat botc_patch matches 14 if data storage botc_patch:buffet draft.seats.s14{status:2,category:1} run data modify storage botc_patch:buffet draft.seats.s14.perceived_alignment set value 1
execute if score draft_bounty_target_seat botc_patch matches 15 if data storage botc_patch:buffet draft.seats.s15{status:2,category:1} run data modify storage botc_patch:buffet draft.seats.s15.alignment set value 1
execute if score draft_bounty_target_seat botc_patch matches 15 if data storage botc_patch:buffet draft.seats.s15{status:2,category:1} run data modify storage botc_patch:buffet draft.seats.s15.perceived_alignment set value 1
scoreboard players set draft_bounty_resolved botc_patch 0
scoreboard players set draft_bounty_target_seat botc_patch 0
