# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Choose one random Townsfolk as Bounty Hunter's evil Townsfolk.
execute unless score draft_bounty_pending botc_patch matches 1 run return 0
scoreboard players set draft_bounty_pool botc_patch 0
execute if data storage botc_patch:buffet draft.seats.s1{status:2,category:1} unless data storage botc_patch:buffet draft.seats.s1{actual:56} run scoreboard players add draft_bounty_pool botc_patch 1
execute if data storage botc_patch:buffet draft.seats.s2{status:2,category:1} unless data storage botc_patch:buffet draft.seats.s2{actual:56} run scoreboard players add draft_bounty_pool botc_patch 1
execute if data storage botc_patch:buffet draft.seats.s3{status:2,category:1} unless data storage botc_patch:buffet draft.seats.s3{actual:56} run scoreboard players add draft_bounty_pool botc_patch 1
execute if data storage botc_patch:buffet draft.seats.s4{status:2,category:1} unless data storage botc_patch:buffet draft.seats.s4{actual:56} run scoreboard players add draft_bounty_pool botc_patch 1
execute if data storage botc_patch:buffet draft.seats.s5{status:2,category:1} unless data storage botc_patch:buffet draft.seats.s5{actual:56} run scoreboard players add draft_bounty_pool botc_patch 1
execute if data storage botc_patch:buffet draft.seats.s6{status:2,category:1} unless data storage botc_patch:buffet draft.seats.s6{actual:56} run scoreboard players add draft_bounty_pool botc_patch 1
execute if data storage botc_patch:buffet draft.seats.s7{status:2,category:1} unless data storage botc_patch:buffet draft.seats.s7{actual:56} run scoreboard players add draft_bounty_pool botc_patch 1
execute if data storage botc_patch:buffet draft.seats.s8{status:2,category:1} unless data storage botc_patch:buffet draft.seats.s8{actual:56} run scoreboard players add draft_bounty_pool botc_patch 1
execute if data storage botc_patch:buffet draft.seats.s9{status:2,category:1} unless data storage botc_patch:buffet draft.seats.s9{actual:56} run scoreboard players add draft_bounty_pool botc_patch 1
execute if data storage botc_patch:buffet draft.seats.s10{status:2,category:1} unless data storage botc_patch:buffet draft.seats.s10{actual:56} run scoreboard players add draft_bounty_pool botc_patch 1
execute if data storage botc_patch:buffet draft.seats.s11{status:2,category:1} unless data storage botc_patch:buffet draft.seats.s11{actual:56} run scoreboard players add draft_bounty_pool botc_patch 1
execute if data storage botc_patch:buffet draft.seats.s12{status:2,category:1} unless data storage botc_patch:buffet draft.seats.s12{actual:56} run scoreboard players add draft_bounty_pool botc_patch 1
execute if data storage botc_patch:buffet draft.seats.s13{status:2,category:1} unless data storage botc_patch:buffet draft.seats.s13{actual:56} run scoreboard players add draft_bounty_pool botc_patch 1
execute if data storage botc_patch:buffet draft.seats.s14{status:2,category:1} unless data storage botc_patch:buffet draft.seats.s14{actual:56} run scoreboard players add draft_bounty_pool botc_patch 1
execute if data storage botc_patch:buffet draft.seats.s15{status:2,category:1} unless data storage botc_patch:buffet draft.seats.s15{actual:56} run scoreboard players add draft_bounty_pool botc_patch 1
execute unless score draft_bounty_pool botc_patch matches 1.. run return 0
execute store result score draft_bounty_pick botc_patch run random value 0..2147483646
scoreboard players operation draft_bounty_pick botc_patch %= draft_bounty_pool botc_patch
scoreboard players add draft_bounty_pick botc_patch 1
scoreboard players set draft_bounty_cursor botc_patch 0
scoreboard players set draft_bounty_pending botc_patch 2
execute if score draft_bounty_pending botc_patch matches 2 if data storage botc_patch:buffet draft.seats.s1{status:2,category:1} unless data storage botc_patch:buffet draft.seats.s1{actual:56} run scoreboard players add draft_bounty_cursor botc_patch 1
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run data modify storage botc_patch:buffet draft.seats.s1.alignment set value 2
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run data modify storage botc_patch:buffet draft.seats.s1.perceived_alignment set value 2
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_target_seat botc_patch 1
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_resolved botc_patch 1
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_pending botc_patch 0
execute if score draft_bounty_pending botc_patch matches 2 if data storage botc_patch:buffet draft.seats.s2{status:2,category:1} unless data storage botc_patch:buffet draft.seats.s2{actual:56} run scoreboard players add draft_bounty_cursor botc_patch 1
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run data modify storage botc_patch:buffet draft.seats.s2.alignment set value 2
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run data modify storage botc_patch:buffet draft.seats.s2.perceived_alignment set value 2
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_target_seat botc_patch 2
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_resolved botc_patch 1
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_pending botc_patch 0
execute if score draft_bounty_pending botc_patch matches 2 if data storage botc_patch:buffet draft.seats.s3{status:2,category:1} unless data storage botc_patch:buffet draft.seats.s3{actual:56} run scoreboard players add draft_bounty_cursor botc_patch 1
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run data modify storage botc_patch:buffet draft.seats.s3.alignment set value 2
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run data modify storage botc_patch:buffet draft.seats.s3.perceived_alignment set value 2
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_target_seat botc_patch 3
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_resolved botc_patch 1
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_pending botc_patch 0
execute if score draft_bounty_pending botc_patch matches 2 if data storage botc_patch:buffet draft.seats.s4{status:2,category:1} unless data storage botc_patch:buffet draft.seats.s4{actual:56} run scoreboard players add draft_bounty_cursor botc_patch 1
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run data modify storage botc_patch:buffet draft.seats.s4.alignment set value 2
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run data modify storage botc_patch:buffet draft.seats.s4.perceived_alignment set value 2
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_target_seat botc_patch 4
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_resolved botc_patch 1
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_pending botc_patch 0
execute if score draft_bounty_pending botc_patch matches 2 if data storage botc_patch:buffet draft.seats.s5{status:2,category:1} unless data storage botc_patch:buffet draft.seats.s5{actual:56} run scoreboard players add draft_bounty_cursor botc_patch 1
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run data modify storage botc_patch:buffet draft.seats.s5.alignment set value 2
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run data modify storage botc_patch:buffet draft.seats.s5.perceived_alignment set value 2
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_target_seat botc_patch 5
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_resolved botc_patch 1
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_pending botc_patch 0
execute if score draft_bounty_pending botc_patch matches 2 if data storage botc_patch:buffet draft.seats.s6{status:2,category:1} unless data storage botc_patch:buffet draft.seats.s6{actual:56} run scoreboard players add draft_bounty_cursor botc_patch 1
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run data modify storage botc_patch:buffet draft.seats.s6.alignment set value 2
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run data modify storage botc_patch:buffet draft.seats.s6.perceived_alignment set value 2
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_target_seat botc_patch 6
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_resolved botc_patch 1
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_pending botc_patch 0
execute if score draft_bounty_pending botc_patch matches 2 if data storage botc_patch:buffet draft.seats.s7{status:2,category:1} unless data storage botc_patch:buffet draft.seats.s7{actual:56} run scoreboard players add draft_bounty_cursor botc_patch 1
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run data modify storage botc_patch:buffet draft.seats.s7.alignment set value 2
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run data modify storage botc_patch:buffet draft.seats.s7.perceived_alignment set value 2
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_target_seat botc_patch 7
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_resolved botc_patch 1
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_pending botc_patch 0
execute if score draft_bounty_pending botc_patch matches 2 if data storage botc_patch:buffet draft.seats.s8{status:2,category:1} unless data storage botc_patch:buffet draft.seats.s8{actual:56} run scoreboard players add draft_bounty_cursor botc_patch 1
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run data modify storage botc_patch:buffet draft.seats.s8.alignment set value 2
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run data modify storage botc_patch:buffet draft.seats.s8.perceived_alignment set value 2
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_target_seat botc_patch 8
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_resolved botc_patch 1
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_pending botc_patch 0
execute if score draft_bounty_pending botc_patch matches 2 if data storage botc_patch:buffet draft.seats.s9{status:2,category:1} unless data storage botc_patch:buffet draft.seats.s9{actual:56} run scoreboard players add draft_bounty_cursor botc_patch 1
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run data modify storage botc_patch:buffet draft.seats.s9.alignment set value 2
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run data modify storage botc_patch:buffet draft.seats.s9.perceived_alignment set value 2
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_target_seat botc_patch 9
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_resolved botc_patch 1
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_pending botc_patch 0
execute if score draft_bounty_pending botc_patch matches 2 if data storage botc_patch:buffet draft.seats.s10{status:2,category:1} unless data storage botc_patch:buffet draft.seats.s10{actual:56} run scoreboard players add draft_bounty_cursor botc_patch 1
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run data modify storage botc_patch:buffet draft.seats.s10.alignment set value 2
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run data modify storage botc_patch:buffet draft.seats.s10.perceived_alignment set value 2
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_target_seat botc_patch 10
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_resolved botc_patch 1
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_pending botc_patch 0
execute if score draft_bounty_pending botc_patch matches 2 if data storage botc_patch:buffet draft.seats.s11{status:2,category:1} unless data storage botc_patch:buffet draft.seats.s11{actual:56} run scoreboard players add draft_bounty_cursor botc_patch 1
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run data modify storage botc_patch:buffet draft.seats.s11.alignment set value 2
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run data modify storage botc_patch:buffet draft.seats.s11.perceived_alignment set value 2
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_target_seat botc_patch 11
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_resolved botc_patch 1
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_pending botc_patch 0
execute if score draft_bounty_pending botc_patch matches 2 if data storage botc_patch:buffet draft.seats.s12{status:2,category:1} unless data storage botc_patch:buffet draft.seats.s12{actual:56} run scoreboard players add draft_bounty_cursor botc_patch 1
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run data modify storage botc_patch:buffet draft.seats.s12.alignment set value 2
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run data modify storage botc_patch:buffet draft.seats.s12.perceived_alignment set value 2
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_target_seat botc_patch 12
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_resolved botc_patch 1
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_pending botc_patch 0
execute if score draft_bounty_pending botc_patch matches 2 if data storage botc_patch:buffet draft.seats.s13{status:2,category:1} unless data storage botc_patch:buffet draft.seats.s13{actual:56} run scoreboard players add draft_bounty_cursor botc_patch 1
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run data modify storage botc_patch:buffet draft.seats.s13.alignment set value 2
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run data modify storage botc_patch:buffet draft.seats.s13.perceived_alignment set value 2
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_target_seat botc_patch 13
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_resolved botc_patch 1
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_pending botc_patch 0
execute if score draft_bounty_pending botc_patch matches 2 if data storage botc_patch:buffet draft.seats.s14{status:2,category:1} unless data storage botc_patch:buffet draft.seats.s14{actual:56} run scoreboard players add draft_bounty_cursor botc_patch 1
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run data modify storage botc_patch:buffet draft.seats.s14.alignment set value 2
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run data modify storage botc_patch:buffet draft.seats.s14.perceived_alignment set value 2
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_target_seat botc_patch 14
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_resolved botc_patch 1
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_pending botc_patch 0
execute if score draft_bounty_pending botc_patch matches 2 if data storage botc_patch:buffet draft.seats.s15{status:2,category:1} unless data storage botc_patch:buffet draft.seats.s15{actual:56} run scoreboard players add draft_bounty_cursor botc_patch 1
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run data modify storage botc_patch:buffet draft.seats.s15.alignment set value 2
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run data modify storage botc_patch:buffet draft.seats.s15.perceived_alignment set value 2
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_target_seat botc_patch 15
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_resolved botc_patch 1
execute if score draft_bounty_pending botc_patch matches 2 if score draft_bounty_cursor botc_patch = draft_bounty_pick botc_patch run scoreboard players set draft_bounty_pending botc_patch 0
