# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Empty the selected Draft seat only through the trusted Storyteller review.
execute if score draft_modifier_pending botc_patch matches 1 run return run tellraw @s [{"text":"! ","color":"red","bold":true},{"text":"Finish the current setup decision before emptying a seat.","color":"gray","bold":false}]
execute unless score buffet_selected_seat botc_patch matches 1..15 run return 0
function botc_patch:buffet/draft/review/empty_dispatch
