# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Prompt for Alchemist-Summoner only when the exact no-Demon topology remains achievable.
function botc_patch:buffet/draft/recount_needs
scoreboard players set draft_alchemist_summoner_legal botc_patch 1
execute if score draft_chosen_115 botc_patch matches 1 run scoreboard players set draft_alchemist_summoner_legal botc_patch 0
execute if score draft_route_kind botc_patch matches 2 if score draft_route_real_special botc_patch matches 1 run scoreboard players set draft_alchemist_summoner_legal botc_patch 0
execute if score draft_topology_status botc_patch matches 1.. run scoreboard players set draft_alchemist_summoner_legal botc_patch 0
execute if score draft_assigned_demon botc_patch matches 1.. run scoreboard players set draft_alchemist_summoner_legal botc_patch 0
execute unless score draft_need_demon botc_patch matches 1 run scoreboard players set draft_alchemist_summoner_legal botc_patch 0
execute unless score draft_need_total botc_patch matches 1.. run scoreboard players set draft_alchemist_summoner_legal botc_patch 0
execute unless score draft_alchemist_summoner_legal botc_patch matches 1 run return 0
scoreboard players set draft_modifier_pending botc_patch 1
$data modify storage botc_patch:buffet modifier set value {seat:$(seat),role:50,kind:"alchemist_summoner"}
function botc_patch:buffet/draft/topology/alchemist_summoner/show
