# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Commit the optional Alchemist-Summoner modifier without consuming a Minion slot.
execute unless score draft_modifier_pending botc_patch matches 1 run return 0
execute unless data storage botc_patch:buffet modifier{kind:"alchemist_summoner"} run return 0
dialog clear @a[tag=storyteller]
data modify storage botc_patch:buffet action.topology.seat set from storage botc_patch:buffet modifier.seat
data modify storage botc_patch:buffet action.topology.kind set value "alchemist_summoner"
function botc_patch:buffet/draft/topology/begin with storage botc_patch:buffet action.topology
scoreboard players add draft_target_town botc_patch 1
scoreboard players remove draft_target_demon botc_patch 1
scoreboard players set draft_alchemist_summoner_active botc_patch 1
execute store result score draft_summoner_owner botc_patch run data get storage botc_patch:buffet modifier.seat
scoreboard players set draft_available_115 botc_patch 0
scoreboard players set draft_blocked_115 botc_patch 1
function botc_patch:buffet/draft/topology/alchemist_summoner/store_owner
scoreboard players set draft_modifier_pending botc_patch 0
data remove storage botc_patch:buffet modifier
function botc_patch:buffet/draft/topology/commit
function botc_patch:buffet/draft/next_turn
