# Generated by tools/generate-storyteller-rps.ps1.
# Do not hand-edit this file; update the generator and regenerate.
# Compacts only currently eligible seated players into a bounded Player (Role) dialog.
dialog clear @s
execute unless entity @s[tag=storyteller] run return 0
execute unless score phase game_data matches 1.. run return run tellraw @s [{text:"RPS can only start during an active game.",color:"red"}]
function botc_patch:grim/editor/refresh_live_roles
function botc_patch:grim/editor/player_labels/prepare
data remove storage botc_patch:dialogs rps_second
scoreboard players set @s botc_st_menu_slot 0
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=1,rps=1..3},limit=1] run scoreboard players add @s botc_st_menu_slot 1
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=1,rps=1..3},limit=1] run data modify storage botc_patch:dialogs lookup set value {source:1,target:0}
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=1,rps=1..3},limit=1] store result storage botc_patch:dialogs lookup.target int 1 run scoreboard players get @s botc_st_menu_slot
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=1,rps=1..3},limit=1] run function botc_patch:storyteller_tools/rps/second/dialog/append with storage botc_patch:dialogs lookup
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=2,rps=1..3},limit=1] run scoreboard players add @s botc_st_menu_slot 1
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=2,rps=1..3},limit=1] run data modify storage botc_patch:dialogs lookup set value {source:2,target:0}
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=2,rps=1..3},limit=1] store result storage botc_patch:dialogs lookup.target int 1 run scoreboard players get @s botc_st_menu_slot
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=2,rps=1..3},limit=1] run function botc_patch:storyteller_tools/rps/second/dialog/append with storage botc_patch:dialogs lookup
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=3,rps=1..3},limit=1] run scoreboard players add @s botc_st_menu_slot 1
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=3,rps=1..3},limit=1] run data modify storage botc_patch:dialogs lookup set value {source:3,target:0}
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=3,rps=1..3},limit=1] store result storage botc_patch:dialogs lookup.target int 1 run scoreboard players get @s botc_st_menu_slot
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=3,rps=1..3},limit=1] run function botc_patch:storyteller_tools/rps/second/dialog/append with storage botc_patch:dialogs lookup
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=4,rps=1..3},limit=1] run scoreboard players add @s botc_st_menu_slot 1
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=4,rps=1..3},limit=1] run data modify storage botc_patch:dialogs lookup set value {source:4,target:0}
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=4,rps=1..3},limit=1] store result storage botc_patch:dialogs lookup.target int 1 run scoreboard players get @s botc_st_menu_slot
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=4,rps=1..3},limit=1] run function botc_patch:storyteller_tools/rps/second/dialog/append with storage botc_patch:dialogs lookup
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=5,rps=1..3},limit=1] run scoreboard players add @s botc_st_menu_slot 1
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=5,rps=1..3},limit=1] run data modify storage botc_patch:dialogs lookup set value {source:5,target:0}
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=5,rps=1..3},limit=1] store result storage botc_patch:dialogs lookup.target int 1 run scoreboard players get @s botc_st_menu_slot
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=5,rps=1..3},limit=1] run function botc_patch:storyteller_tools/rps/second/dialog/append with storage botc_patch:dialogs lookup
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=6,rps=1..3},limit=1] run scoreboard players add @s botc_st_menu_slot 1
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=6,rps=1..3},limit=1] run data modify storage botc_patch:dialogs lookup set value {source:6,target:0}
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=6,rps=1..3},limit=1] store result storage botc_patch:dialogs lookup.target int 1 run scoreboard players get @s botc_st_menu_slot
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=6,rps=1..3},limit=1] run function botc_patch:storyteller_tools/rps/second/dialog/append with storage botc_patch:dialogs lookup
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=7,rps=1..3},limit=1] run scoreboard players add @s botc_st_menu_slot 1
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=7,rps=1..3},limit=1] run data modify storage botc_patch:dialogs lookup set value {source:7,target:0}
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=7,rps=1..3},limit=1] store result storage botc_patch:dialogs lookup.target int 1 run scoreboard players get @s botc_st_menu_slot
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=7,rps=1..3},limit=1] run function botc_patch:storyteller_tools/rps/second/dialog/append with storage botc_patch:dialogs lookup
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=8,rps=1..3},limit=1] run scoreboard players add @s botc_st_menu_slot 1
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=8,rps=1..3},limit=1] run data modify storage botc_patch:dialogs lookup set value {source:8,target:0}
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=8,rps=1..3},limit=1] store result storage botc_patch:dialogs lookup.target int 1 run scoreboard players get @s botc_st_menu_slot
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=8,rps=1..3},limit=1] run function botc_patch:storyteller_tools/rps/second/dialog/append with storage botc_patch:dialogs lookup
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=9,rps=1..3},limit=1] run scoreboard players add @s botc_st_menu_slot 1
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=9,rps=1..3},limit=1] run data modify storage botc_patch:dialogs lookup set value {source:9,target:0}
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=9,rps=1..3},limit=1] store result storage botc_patch:dialogs lookup.target int 1 run scoreboard players get @s botc_st_menu_slot
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=9,rps=1..3},limit=1] run function botc_patch:storyteller_tools/rps/second/dialog/append with storage botc_patch:dialogs lookup
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=10,rps=1..3},limit=1] run scoreboard players add @s botc_st_menu_slot 1
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=10,rps=1..3},limit=1] run data modify storage botc_patch:dialogs lookup set value {source:10,target:0}
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=10,rps=1..3},limit=1] store result storage botc_patch:dialogs lookup.target int 1 run scoreboard players get @s botc_st_menu_slot
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=10,rps=1..3},limit=1] run function botc_patch:storyteller_tools/rps/second/dialog/append with storage botc_patch:dialogs lookup
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=11,rps=1..3},limit=1] run scoreboard players add @s botc_st_menu_slot 1
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=11,rps=1..3},limit=1] run data modify storage botc_patch:dialogs lookup set value {source:11,target:0}
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=11,rps=1..3},limit=1] store result storage botc_patch:dialogs lookup.target int 1 run scoreboard players get @s botc_st_menu_slot
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=11,rps=1..3},limit=1] run function botc_patch:storyteller_tools/rps/second/dialog/append with storage botc_patch:dialogs lookup
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=12,rps=1..3},limit=1] run scoreboard players add @s botc_st_menu_slot 1
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=12,rps=1..3},limit=1] run data modify storage botc_patch:dialogs lookup set value {source:12,target:0}
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=12,rps=1..3},limit=1] store result storage botc_patch:dialogs lookup.target int 1 run scoreboard players get @s botc_st_menu_slot
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=12,rps=1..3},limit=1] run function botc_patch:storyteller_tools/rps/second/dialog/append with storage botc_patch:dialogs lookup
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=13,rps=1..3},limit=1] run scoreboard players add @s botc_st_menu_slot 1
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=13,rps=1..3},limit=1] run data modify storage botc_patch:dialogs lookup set value {source:13,target:0}
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=13,rps=1..3},limit=1] store result storage botc_patch:dialogs lookup.target int 1 run scoreboard players get @s botc_st_menu_slot
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=13,rps=1..3},limit=1] run function botc_patch:storyteller_tools/rps/second/dialog/append with storage botc_patch:dialogs lookup
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=14,rps=1..3},limit=1] run scoreboard players add @s botc_st_menu_slot 1
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=14,rps=1..3},limit=1] run data modify storage botc_patch:dialogs lookup set value {source:14,target:0}
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=14,rps=1..3},limit=1] store result storage botc_patch:dialogs lookup.target int 1 run scoreboard players get @s botc_st_menu_slot
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=14,rps=1..3},limit=1] run function botc_patch:storyteller_tools/rps/second/dialog/append with storage botc_patch:dialogs lookup
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=15,rps=1..3},limit=1] run scoreboard players add @s botc_st_menu_slot 1
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=15,rps=1..3},limit=1] run data modify storage botc_patch:dialogs lookup set value {source:15,target:0}
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=15,rps=1..3},limit=1] store result storage botc_patch:dialogs lookup.target int 1 run scoreboard players get @s botc_st_menu_slot
execute if entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_rps_first,scores={id=15,rps=1..3},limit=1] run function botc_patch:storyteller_tools/rps/second/dialog/append with storage botc_patch:dialogs lookup
execute if score @s botc_st_menu_slot matches 0 run tellraw @s [{text:"No other living seated player has made an RPS choice yet.",color:"yellow"}]
execute if score @s botc_st_menu_slot matches 1 run function botc_patch:storyteller_tools/rps/second/dialog/count_1 with storage botc_patch:dialogs rps_second
execute if score @s botc_st_menu_slot matches 2 run function botc_patch:storyteller_tools/rps/second/dialog/count_2 with storage botc_patch:dialogs rps_second
execute if score @s botc_st_menu_slot matches 3 run function botc_patch:storyteller_tools/rps/second/dialog/count_3 with storage botc_patch:dialogs rps_second
execute if score @s botc_st_menu_slot matches 4 run function botc_patch:storyteller_tools/rps/second/dialog/count_4 with storage botc_patch:dialogs rps_second
execute if score @s botc_st_menu_slot matches 5 run function botc_patch:storyteller_tools/rps/second/dialog/count_5 with storage botc_patch:dialogs rps_second
execute if score @s botc_st_menu_slot matches 6 run function botc_patch:storyteller_tools/rps/second/dialog/count_6 with storage botc_patch:dialogs rps_second
execute if score @s botc_st_menu_slot matches 7 run function botc_patch:storyteller_tools/rps/second/dialog/count_7 with storage botc_patch:dialogs rps_second
execute if score @s botc_st_menu_slot matches 8 run function botc_patch:storyteller_tools/rps/second/dialog/count_8 with storage botc_patch:dialogs rps_second
execute if score @s botc_st_menu_slot matches 9 run function botc_patch:storyteller_tools/rps/second/dialog/count_9 with storage botc_patch:dialogs rps_second
execute if score @s botc_st_menu_slot matches 10 run function botc_patch:storyteller_tools/rps/second/dialog/count_10 with storage botc_patch:dialogs rps_second
execute if score @s botc_st_menu_slot matches 11 run function botc_patch:storyteller_tools/rps/second/dialog/count_11 with storage botc_patch:dialogs rps_second
execute if score @s botc_st_menu_slot matches 12 run function botc_patch:storyteller_tools/rps/second/dialog/count_12 with storage botc_patch:dialogs rps_second
execute if score @s botc_st_menu_slot matches 13 run function botc_patch:storyteller_tools/rps/second/dialog/count_13 with storage botc_patch:dialogs rps_second
execute if score @s botc_st_menu_slot matches 14 run function botc_patch:storyteller_tools/rps/second/dialog/count_14 with storage botc_patch:dialogs rps_second
execute if score @s botc_st_menu_slot matches 15 run function botc_patch:storyteller_tools/rps/second/dialog/count_15 with storage botc_patch:dialogs rps_second
scoreboard players reset @s botc_st_menu_slot
