# Generated by tools/generate-buffet-gamemodes.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Introduce one late Greedy participant without interrupting other players.
execute at @s run playsound minecraft:block.note_block.chime master @s ~ ~ ~ 0.9 0.8
execute at @s run playsound minecraft:block.amethyst_block.chime master @s ~ ~ ~ 0.8 1.3
execute at @s run playsound minecraft:entity.experience_orb.pickup master @s ~ ~ ~ 0.7 1.6
title @s times 10 60 20
title @s title {"text":"You joined Greedy Whalebuffet.","color":"gold","bold":true}
tellraw @s [{"text":"✔ ","color":"green","bold":true},{"text":"You joined ","color":"gray","bold":false},{"text":"Greedy Whalebuffet","color":"gold","bold":true},{"text":".","color":"gray","bold":false}]
tellraw @s [{"text":"Choose at least 8 characters total and at least 2 of every type. Choose Dealer's Choice if you don't mind getting anything.","color":"gray"}]
