# Generated by tools/generate-buffet-gamemodes.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Prepare the acting player's Dealer's Choice state.
$execute if data storage botc_patch:buffet greedy.seats.s$(seat){dealer:1b} run data modify storage botc_patch:buffet ui.dealer_mark set value "✓"
$execute if data storage botc_patch:buffet greedy.seats.s$(seat){dealer:1b} run data modify storage botc_patch:buffet ui.dealer_mark_color set value "#55ff55"
