# Generated by tools/generate-storyteller-boomdandy.ps1.
# Do not hand-edit this file; update the generator and regenerate.
# Renders cosmetic Boomdandy TNT impact 9 of 12 with strictly increasing particle density and layers.
particle minecraft:explosion ~ ~ ~ 0 0 0 0 1 force @a
particle minecraft:poof ~ ~0.10 ~ 0.635 0.460 0.635 0.08 20 force @a
particle minecraft:smoke ~ ~0.18 ~ 0.635 0.460 0.635 0.03 31 force @a
particle minecraft:flame ~ ~0.12 ~ 0.635 0.460 0.635 0.06 20 force @a
particle minecraft:electric_spark ~ ~0.20 ~ 0.635 0.460 0.635 0.12 18 force @a
particle minecraft:firework ~ ~0.25 ~ 0.635 0.460 0.635 0.15 9 force @a
particle minecraft:end_rod ~ ~0.30 ~ 0.635 0.460 0.635 0.09 9 force @a
particle minecraft:explosion ~ ~0.35 ~ 0 0 0 0 1 force @a
particle minecraft:totem_of_undying ~ ~0.45 ~ 0 0 0 0 5 force @a
