# Generated by tools/generate-storyteller-boomdandy.ps1.
# Do not hand-edit this file; update the generator and regenerate.
# Renders cosmetic Boomdandy TNT impact 6 of 12 with strictly increasing particle density and layers.
particle minecraft:explosion ~ ~ ~ 0 0 0 0 1 force @a
particle minecraft:poof ~ ~0.10 ~ 0.470 0.340 0.470 0.08 14 force @a
particle minecraft:smoke ~ ~0.18 ~ 0.470 0.340 0.470 0.03 22 force @a
particle minecraft:flame ~ ~0.12 ~ 0.470 0.340 0.470 0.06 14 force @a
particle minecraft:electric_spark ~ ~0.20 ~ 0.470 0.340 0.470 0.12 12 force @a
particle minecraft:firework ~ ~0.25 ~ 0.470 0.340 0.470 0.15 6 force @a
