# Generated by tools/generate-buffet-gamemodes.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Append one exact assigned role from the trusted catalog.
$data modify storage ct:roles roles append from storage botc_patch:buffet catalog.s$(role).ct
