# Generated by tools/generate-storyteller-boomdandy.ps1.
# Do not hand-edit this file; update the generator and regenerate.
# Begins the first readable typewriter warning before the countdown.
scoreboard players set boomdandy_stage botc_patch 3
scoreboard players set boomdandy_announce_step botc_patch 0
title @a times 0t 20t 0t
title @a title {"text":""}
title @a subtitle {"text":""}
schedule function botc_patch:storyteller_tools/boomdandy/announce/part_1/advance 1t replace
