param(
    [int] $SinceMinutes = 15,
    [switch] $SkipSourceSafety,
    [string] $ClientModsPath = (Join-Path $env:APPDATA "ModrinthApp/profiles/Blood on the Clocktower/mods"),
    [switch] $SkipClientUiModCompare
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$RepoRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSScriptRoot))
$ReportRoot = Join-Path $RepoRoot "docs/project-notes/live-test-reports"
$Timestamp = Get-Date -Format "yyyy-MM-dd-HHmmss"
$ReportPath = Join-Path $ReportRoot ("kept-systems-preflight-{0}.md" -f $Timestamp)

function Invoke-Captured {
    param(
        [string] $Name,
        [scriptblock] $Command
    )

    $output = @(& $Command 2>&1)
    $exitCode = if ($null -eq $global:LASTEXITCODE) { 0 } else { $global:LASTEXITCODE }

    [pscustomobject]@{
        Name = $Name
        ExitCode = $exitCode
        Output = @($output | ForEach-Object { [string] $_ })
    }
}

function Add-CommandSection {
    param(
        [System.Collections.Generic.List[string]] $Lines,
        [pscustomobject] $Result
    )

    $status = if ($Result.ExitCode -eq 0) { "PASS" } else { "FAIL" }
    $Lines.Add(("### {0}: {1}" -f $Result.Name, $status))
    $Lines.Add("")
    $Lines.Add('```text')
    if ($Result.Output.Count -eq 0) {
        $Lines.Add("(no output)")
    } else {
        foreach ($line in $Result.Output) {
            $Lines.Add($line)
        }
    }
    $Lines.Add('```')
    $Lines.Add("")
}

New-Item -ItemType Directory -Path $ReportRoot -Force | Out-Null

$results = @()

$result = Invoke-Captured -Name "Docker container status" -Command {
    docker ps --filter "name=botc-minecraft" --format "{{.Names}} {{.Status}}"
}
$results += $result

$result = Invoke-Captured -Name "Online player list" -Command {
    docker exec -i botc-minecraft rcon-cli list
}
$results += $result

$result = Invoke-Captured -Name "Runtime sync" -Command {
    powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $RepoRoot "tools/tests/live/test-runtime-sync.ps1")
}
$results += $result

$result = Invoke-Captured -Name "Runtime FancyMenu button coverage" -Command {
    powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $RepoRoot "tools/tests/live/audit-runtime-fancymenu-buttons.ps1")
}
$results += $result

if (-not $SkipClientUiModCompare) {
    $result = Invoke-Captured -Name "Client/server UI dependency comparison" -Command {
        powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $RepoRoot "tools/tests/live/compare-ui-client-mods.ps1") -ClientModsPath $ClientModsPath
    }
    $results += $result
}

$result = Invoke-Captured -Name "Recent FancyMenu/codec/disconnect log scan" -Command {
    powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $RepoRoot "tools/tests/live/watch-fancymenu-errors.ps1") -SinceMinutes $SinceMinutes
}
$results += $result

if (-not $SkipSourceSafety) {
    $result = Invoke-Captured -Name "Source safety" -Command {
        powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $RepoRoot "tools/tests/test-source-safety.ps1")
    }
    $results += $result
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("# Kept Systems Live-Test Preflight Report")
$lines.Add("")
$lines.Add(("Created: {0}" -f (Get-Date -Format "yyyy-MM-dd HH:mm:ss zzz")))
$lines.Add("")
$lines.Add("## Evidence")
$lines.Add("")
$lines.Add('- This report is generated by `tools/tests/live/new-kept-systems-test-report.ps1`.')
$lines.Add("- It is read-only against the live server: no reload, restart, deploy, RCON mutation, or world edit.")
$lines.Add("- It does not complete the live checklist by itself; a real non-op Storyteller still needs to test the player-facing systems.")
$lines.Add("")
$lines.Add("## Inference")
$lines.Add("")
$lines.Add("If every command below passes, the server is ready for the manual kept-systems checklist.")
$lines.Add("If any command fails, fix that evidence gap before starting live feature testing.")
$lines.Add("")
$lines.Add("## Recommendation")
$lines.Add("")
$lines.Add('Use `docs/project-notes/live-kept-systems-test-checklist.md` for the manual pass.')
$lines.Add("After testing, append pass/fail notes to this report or the TODO.")
$lines.Add("")
$lines.Add("## Command Evidence")
$lines.Add("")

foreach ($result in $results) {
    Add-CommandSection -Lines $lines -Result $result
}

[System.IO.File]::WriteAllText(
    $ReportPath,
    ($lines -join [Environment]::NewLine) + [Environment]::NewLine,
    [System.Text.UTF8Encoding]::new($false)
)

Write-Host ("Created live-test preflight report: {0}" -f $ReportPath) -ForegroundColor Green

$failed = @($results | Where-Object { $_.ExitCode -ne 0 })
if ($failed.Count -gt 0) {
    throw ("Live-test preflight failed: {0}" -f (($failed | ForEach-Object { $_.Name }) -join ", "))
}
