# Generated by tools/generate-grim-character-editor.ps1.
# Do not hand-edit this file; update the generator and regenerate.
# Commits one trusted nightly evil role to live, Grimoire, and private player state.
execute unless score phase game_data matches 4 run return run tellraw @s [{"text":"! ","color":"red","bold":true},{"text":"You can only assign a Demon during the night.","color":"gray","bold":false}]
scoreboard players set grim_editor_summoner_target_online botc_patch 0
execute if score @s botc_grim_edit_seat matches 1 if entity @a[tag=!storyteller,tag=!spectator,scores={id=1},limit=1] run scoreboard players set grim_editor_summoner_target_online botc_patch 1
execute if score @s botc_grim_edit_seat matches 2 if entity @a[tag=!storyteller,tag=!spectator,scores={id=2},limit=1] run scoreboard players set grim_editor_summoner_target_online botc_patch 1
execute if score @s botc_grim_edit_seat matches 3 if entity @a[tag=!storyteller,tag=!spectator,scores={id=3},limit=1] run scoreboard players set grim_editor_summoner_target_online botc_patch 1
execute if score @s botc_grim_edit_seat matches 4 if entity @a[tag=!storyteller,tag=!spectator,scores={id=4},limit=1] run scoreboard players set grim_editor_summoner_target_online botc_patch 1
execute if score @s botc_grim_edit_seat matches 5 if entity @a[tag=!storyteller,tag=!spectator,scores={id=5},limit=1] run scoreboard players set grim_editor_summoner_target_online botc_patch 1
execute if score @s botc_grim_edit_seat matches 6 if entity @a[tag=!storyteller,tag=!spectator,scores={id=6},limit=1] run scoreboard players set grim_editor_summoner_target_online botc_patch 1
execute if score @s botc_grim_edit_seat matches 7 if entity @a[tag=!storyteller,tag=!spectator,scores={id=7},limit=1] run scoreboard players set grim_editor_summoner_target_online botc_patch 1
execute if score @s botc_grim_edit_seat matches 8 if entity @a[tag=!storyteller,tag=!spectator,scores={id=8},limit=1] run scoreboard players set grim_editor_summoner_target_online botc_patch 1
execute if score @s botc_grim_edit_seat matches 9 if entity @a[tag=!storyteller,tag=!spectator,scores={id=9},limit=1] run scoreboard players set grim_editor_summoner_target_online botc_patch 1
execute if score @s botc_grim_edit_seat matches 10 if entity @a[tag=!storyteller,tag=!spectator,scores={id=10},limit=1] run scoreboard players set grim_editor_summoner_target_online botc_patch 1
execute if score @s botc_grim_edit_seat matches 11 if entity @a[tag=!storyteller,tag=!spectator,scores={id=11},limit=1] run scoreboard players set grim_editor_summoner_target_online botc_patch 1
execute if score @s botc_grim_edit_seat matches 12 if entity @a[tag=!storyteller,tag=!spectator,scores={id=12},limit=1] run scoreboard players set grim_editor_summoner_target_online botc_patch 1
execute if score @s botc_grim_edit_seat matches 13 if entity @a[tag=!storyteller,tag=!spectator,scores={id=13},limit=1] run scoreboard players set grim_editor_summoner_target_online botc_patch 1
execute if score @s botc_grim_edit_seat matches 14 if entity @a[tag=!storyteller,tag=!spectator,scores={id=14},limit=1] run scoreboard players set grim_editor_summoner_target_online botc_patch 1
execute if score @s botc_grim_edit_seat matches 15 if entity @a[tag=!storyteller,tag=!spectator,scores={id=15},limit=1] run scoreboard players set grim_editor_summoner_target_online botc_patch 1
execute unless score grim_editor_summoner_target_online botc_patch matches 1 run return run tellraw @s [{"text":"! ","color":"red","bold":true},{"text":"That player must be online before you can change their character.","color":"gray","bold":false}]
$scoreboard players set @s botc_grim_edit_role $(score)
scoreboard players set @s botc_grim_edit_alignment 2
function botc_patch:grim/editor/apply_selected
$execute if score @s botc_grim_edit_seat matches 1 run scoreboard players set @a[tag=!storyteller,tag=!spectator,scores={id=1},limit=1] role $(score)
execute if score @s botc_grim_edit_seat matches 1 run tag @a[tag=!storyteller,tag=!spectator,scores={id=1},limit=1] remove town
execute if score @s botc_grim_edit_seat matches 1 run tag @a[tag=!storyteller,tag=!spectator,scores={id=1},limit=1] remove outsider
execute if score @s botc_grim_edit_seat matches 1 run tag @a[tag=!storyteller,tag=!spectator,scores={id=1},limit=1] remove minion
execute if score @s botc_grim_edit_seat matches 1 run tag @a[tag=!storyteller,tag=!spectator,scores={id=1},limit=1] remove demon
$execute if score @s botc_grim_edit_seat matches 1 run tag @a[tag=!storyteller,tag=!spectator,scores={id=1},limit=1] add $(category)
$execute if score @s botc_grim_edit_seat matches 1 run fmvariable set p1_role false $(role)
execute if score @s botc_grim_edit_seat matches 1 run scoreboard players set grim_editor_seat_1_alignment botc_patch 2
$execute if score @s botc_grim_edit_seat matches 1 run scoreboard players set grim_seat_1_role botc_patch $(score)
execute if score @s botc_grim_edit_seat matches 1 run scoreboard players set grim_seat_1_alignment botc_patch 2
$execute if score @s botc_grim_edit_seat matches 1 run tellraw @a[tag=!storyteller,tag=!spectator,scores={id=1},limit=1] [{"text":"You are now the ","color":"gray"},{"text":"$(name)","color":"$(color)","bold":true},{"text":". You are evil.","color":"red","bold":false}]
$execute if score @s botc_grim_edit_seat matches 2 run scoreboard players set @a[tag=!storyteller,tag=!spectator,scores={id=2},limit=1] role $(score)
execute if score @s botc_grim_edit_seat matches 2 run tag @a[tag=!storyteller,tag=!spectator,scores={id=2},limit=1] remove town
execute if score @s botc_grim_edit_seat matches 2 run tag @a[tag=!storyteller,tag=!spectator,scores={id=2},limit=1] remove outsider
execute if score @s botc_grim_edit_seat matches 2 run tag @a[tag=!storyteller,tag=!spectator,scores={id=2},limit=1] remove minion
execute if score @s botc_grim_edit_seat matches 2 run tag @a[tag=!storyteller,tag=!spectator,scores={id=2},limit=1] remove demon
$execute if score @s botc_grim_edit_seat matches 2 run tag @a[tag=!storyteller,tag=!spectator,scores={id=2},limit=1] add $(category)
$execute if score @s botc_grim_edit_seat matches 2 run fmvariable set p2_role false $(role)
execute if score @s botc_grim_edit_seat matches 2 run scoreboard players set grim_editor_seat_2_alignment botc_patch 2
$execute if score @s botc_grim_edit_seat matches 2 run scoreboard players set grim_seat_2_role botc_patch $(score)
execute if score @s botc_grim_edit_seat matches 2 run scoreboard players set grim_seat_2_alignment botc_patch 2
$execute if score @s botc_grim_edit_seat matches 2 run tellraw @a[tag=!storyteller,tag=!spectator,scores={id=2},limit=1] [{"text":"You are now the ","color":"gray"},{"text":"$(name)","color":"$(color)","bold":true},{"text":". You are evil.","color":"red","bold":false}]
$execute if score @s botc_grim_edit_seat matches 3 run scoreboard players set @a[tag=!storyteller,tag=!spectator,scores={id=3},limit=1] role $(score)
execute if score @s botc_grim_edit_seat matches 3 run tag @a[tag=!storyteller,tag=!spectator,scores={id=3},limit=1] remove town
execute if score @s botc_grim_edit_seat matches 3 run tag @a[tag=!storyteller,tag=!spectator,scores={id=3},limit=1] remove outsider
execute if score @s botc_grim_edit_seat matches 3 run tag @a[tag=!storyteller,tag=!spectator,scores={id=3},limit=1] remove minion
execute if score @s botc_grim_edit_seat matches 3 run tag @a[tag=!storyteller,tag=!spectator,scores={id=3},limit=1] remove demon
$execute if score @s botc_grim_edit_seat matches 3 run tag @a[tag=!storyteller,tag=!spectator,scores={id=3},limit=1] add $(category)
$execute if score @s botc_grim_edit_seat matches 3 run fmvariable set p3_role false $(role)
execute if score @s botc_grim_edit_seat matches 3 run scoreboard players set grim_editor_seat_3_alignment botc_patch 2
$execute if score @s botc_grim_edit_seat matches 3 run scoreboard players set grim_seat_3_role botc_patch $(score)
execute if score @s botc_grim_edit_seat matches 3 run scoreboard players set grim_seat_3_alignment botc_patch 2
$execute if score @s botc_grim_edit_seat matches 3 run tellraw @a[tag=!storyteller,tag=!spectator,scores={id=3},limit=1] [{"text":"You are now the ","color":"gray"},{"text":"$(name)","color":"$(color)","bold":true},{"text":". You are evil.","color":"red","bold":false}]
$execute if score @s botc_grim_edit_seat matches 4 run scoreboard players set @a[tag=!storyteller,tag=!spectator,scores={id=4},limit=1] role $(score)
execute if score @s botc_grim_edit_seat matches 4 run tag @a[tag=!storyteller,tag=!spectator,scores={id=4},limit=1] remove town
execute if score @s botc_grim_edit_seat matches 4 run tag @a[tag=!storyteller,tag=!spectator,scores={id=4},limit=1] remove outsider
execute if score @s botc_grim_edit_seat matches 4 run tag @a[tag=!storyteller,tag=!spectator,scores={id=4},limit=1] remove minion
execute if score @s botc_grim_edit_seat matches 4 run tag @a[tag=!storyteller,tag=!spectator,scores={id=4},limit=1] remove demon
$execute if score @s botc_grim_edit_seat matches 4 run tag @a[tag=!storyteller,tag=!spectator,scores={id=4},limit=1] add $(category)
$execute if score @s botc_grim_edit_seat matches 4 run fmvariable set p4_role false $(role)
execute if score @s botc_grim_edit_seat matches 4 run scoreboard players set grim_editor_seat_4_alignment botc_patch 2
$execute if score @s botc_grim_edit_seat matches 4 run scoreboard players set grim_seat_4_role botc_patch $(score)
execute if score @s botc_grim_edit_seat matches 4 run scoreboard players set grim_seat_4_alignment botc_patch 2
$execute if score @s botc_grim_edit_seat matches 4 run tellraw @a[tag=!storyteller,tag=!spectator,scores={id=4},limit=1] [{"text":"You are now the ","color":"gray"},{"text":"$(name)","color":"$(color)","bold":true},{"text":". You are evil.","color":"red","bold":false}]
$execute if score @s botc_grim_edit_seat matches 5 run scoreboard players set @a[tag=!storyteller,tag=!spectator,scores={id=5},limit=1] role $(score)
execute if score @s botc_grim_edit_seat matches 5 run tag @a[tag=!storyteller,tag=!spectator,scores={id=5},limit=1] remove town
execute if score @s botc_grim_edit_seat matches 5 run tag @a[tag=!storyteller,tag=!spectator,scores={id=5},limit=1] remove outsider
execute if score @s botc_grim_edit_seat matches 5 run tag @a[tag=!storyteller,tag=!spectator,scores={id=5},limit=1] remove minion
execute if score @s botc_grim_edit_seat matches 5 run tag @a[tag=!storyteller,tag=!spectator,scores={id=5},limit=1] remove demon
$execute if score @s botc_grim_edit_seat matches 5 run tag @a[tag=!storyteller,tag=!spectator,scores={id=5},limit=1] add $(category)
$execute if score @s botc_grim_edit_seat matches 5 run fmvariable set p5_role false $(role)
execute if score @s botc_grim_edit_seat matches 5 run scoreboard players set grim_editor_seat_5_alignment botc_patch 2
$execute if score @s botc_grim_edit_seat matches 5 run scoreboard players set grim_seat_5_role botc_patch $(score)
execute if score @s botc_grim_edit_seat matches 5 run scoreboard players set grim_seat_5_alignment botc_patch 2
$execute if score @s botc_grim_edit_seat matches 5 run tellraw @a[tag=!storyteller,tag=!spectator,scores={id=5},limit=1] [{"text":"You are now the ","color":"gray"},{"text":"$(name)","color":"$(color)","bold":true},{"text":". You are evil.","color":"red","bold":false}]
$execute if score @s botc_grim_edit_seat matches 6 run scoreboard players set @a[tag=!storyteller,tag=!spectator,scores={id=6},limit=1] role $(score)
execute if score @s botc_grim_edit_seat matches 6 run tag @a[tag=!storyteller,tag=!spectator,scores={id=6},limit=1] remove town
execute if score @s botc_grim_edit_seat matches 6 run tag @a[tag=!storyteller,tag=!spectator,scores={id=6},limit=1] remove outsider
execute if score @s botc_grim_edit_seat matches 6 run tag @a[tag=!storyteller,tag=!spectator,scores={id=6},limit=1] remove minion
execute if score @s botc_grim_edit_seat matches 6 run tag @a[tag=!storyteller,tag=!spectator,scores={id=6},limit=1] remove demon
$execute if score @s botc_grim_edit_seat matches 6 run tag @a[tag=!storyteller,tag=!spectator,scores={id=6},limit=1] add $(category)
$execute if score @s botc_grim_edit_seat matches 6 run fmvariable set p6_role false $(role)
execute if score @s botc_grim_edit_seat matches 6 run scoreboard players set grim_editor_seat_6_alignment botc_patch 2
$execute if score @s botc_grim_edit_seat matches 6 run scoreboard players set grim_seat_6_role botc_patch $(score)
execute if score @s botc_grim_edit_seat matches 6 run scoreboard players set grim_seat_6_alignment botc_patch 2
$execute if score @s botc_grim_edit_seat matches 6 run tellraw @a[tag=!storyteller,tag=!spectator,scores={id=6},limit=1] [{"text":"You are now the ","color":"gray"},{"text":"$(name)","color":"$(color)","bold":true},{"text":". You are evil.","color":"red","bold":false}]
$execute if score @s botc_grim_edit_seat matches 7 run scoreboard players set @a[tag=!storyteller,tag=!spectator,scores={id=7},limit=1] role $(score)
execute if score @s botc_grim_edit_seat matches 7 run tag @a[tag=!storyteller,tag=!spectator,scores={id=7},limit=1] remove town
execute if score @s botc_grim_edit_seat matches 7 run tag @a[tag=!storyteller,tag=!spectator,scores={id=7},limit=1] remove outsider
execute if score @s botc_grim_edit_seat matches 7 run tag @a[tag=!storyteller,tag=!spectator,scores={id=7},limit=1] remove minion
execute if score @s botc_grim_edit_seat matches 7 run tag @a[tag=!storyteller,tag=!spectator,scores={id=7},limit=1] remove demon
$execute if score @s botc_grim_edit_seat matches 7 run tag @a[tag=!storyteller,tag=!spectator,scores={id=7},limit=1] add $(category)
$execute if score @s botc_grim_edit_seat matches 7 run fmvariable set p7_role false $(role)
execute if score @s botc_grim_edit_seat matches 7 run scoreboard players set grim_editor_seat_7_alignment botc_patch 2
$execute if score @s botc_grim_edit_seat matches 7 run scoreboard players set grim_seat_7_role botc_patch $(score)
execute if score @s botc_grim_edit_seat matches 7 run scoreboard players set grim_seat_7_alignment botc_patch 2
$execute if score @s botc_grim_edit_seat matches 7 run tellraw @a[tag=!storyteller,tag=!spectator,scores={id=7},limit=1] [{"text":"You are now the ","color":"gray"},{"text":"$(name)","color":"$(color)","bold":true},{"text":". You are evil.","color":"red","bold":false}]
$execute if score @s botc_grim_edit_seat matches 8 run scoreboard players set @a[tag=!storyteller,tag=!spectator,scores={id=8},limit=1] role $(score)
execute if score @s botc_grim_edit_seat matches 8 run tag @a[tag=!storyteller,tag=!spectator,scores={id=8},limit=1] remove town
execute if score @s botc_grim_edit_seat matches 8 run tag @a[tag=!storyteller,tag=!spectator,scores={id=8},limit=1] remove outsider
execute if score @s botc_grim_edit_seat matches 8 run tag @a[tag=!storyteller,tag=!spectator,scores={id=8},limit=1] remove minion
execute if score @s botc_grim_edit_seat matches 8 run tag @a[tag=!storyteller,tag=!spectator,scores={id=8},limit=1] remove demon
$execute if score @s botc_grim_edit_seat matches 8 run tag @a[tag=!storyteller,tag=!spectator,scores={id=8},limit=1] add $(category)
$execute if score @s botc_grim_edit_seat matches 8 run fmvariable set p8_role false $(role)
execute if score @s botc_grim_edit_seat matches 8 run scoreboard players set grim_editor_seat_8_alignment botc_patch 2
$execute if score @s botc_grim_edit_seat matches 8 run scoreboard players set grim_seat_8_role botc_patch $(score)
execute if score @s botc_grim_edit_seat matches 8 run scoreboard players set grim_seat_8_alignment botc_patch 2
$execute if score @s botc_grim_edit_seat matches 8 run tellraw @a[tag=!storyteller,tag=!spectator,scores={id=8},limit=1] [{"text":"You are now the ","color":"gray"},{"text":"$(name)","color":"$(color)","bold":true},{"text":". You are evil.","color":"red","bold":false}]
$execute if score @s botc_grim_edit_seat matches 9 run scoreboard players set @a[tag=!storyteller,tag=!spectator,scores={id=9},limit=1] role $(score)
execute if score @s botc_grim_edit_seat matches 9 run tag @a[tag=!storyteller,tag=!spectator,scores={id=9},limit=1] remove town
execute if score @s botc_grim_edit_seat matches 9 run tag @a[tag=!storyteller,tag=!spectator,scores={id=9},limit=1] remove outsider
execute if score @s botc_grim_edit_seat matches 9 run tag @a[tag=!storyteller,tag=!spectator,scores={id=9},limit=1] remove minion
execute if score @s botc_grim_edit_seat matches 9 run tag @a[tag=!storyteller,tag=!spectator,scores={id=9},limit=1] remove demon
$execute if score @s botc_grim_edit_seat matches 9 run tag @a[tag=!storyteller,tag=!spectator,scores={id=9},limit=1] add $(category)
$execute if score @s botc_grim_edit_seat matches 9 run fmvariable set p9_role false $(role)
execute if score @s botc_grim_edit_seat matches 9 run scoreboard players set grim_editor_seat_9_alignment botc_patch 2
$execute if score @s botc_grim_edit_seat matches 9 run scoreboard players set grim_seat_9_role botc_patch $(score)
execute if score @s botc_grim_edit_seat matches 9 run scoreboard players set grim_seat_9_alignment botc_patch 2
$execute if score @s botc_grim_edit_seat matches 9 run tellraw @a[tag=!storyteller,tag=!spectator,scores={id=9},limit=1] [{"text":"You are now the ","color":"gray"},{"text":"$(name)","color":"$(color)","bold":true},{"text":". You are evil.","color":"red","bold":false}]
$execute if score @s botc_grim_edit_seat matches 10 run scoreboard players set @a[tag=!storyteller,tag=!spectator,scores={id=10},limit=1] role $(score)
execute if score @s botc_grim_edit_seat matches 10 run tag @a[tag=!storyteller,tag=!spectator,scores={id=10},limit=1] remove town
execute if score @s botc_grim_edit_seat matches 10 run tag @a[tag=!storyteller,tag=!spectator,scores={id=10},limit=1] remove outsider
execute if score @s botc_grim_edit_seat matches 10 run tag @a[tag=!storyteller,tag=!spectator,scores={id=10},limit=1] remove minion
execute if score @s botc_grim_edit_seat matches 10 run tag @a[tag=!storyteller,tag=!spectator,scores={id=10},limit=1] remove demon
$execute if score @s botc_grim_edit_seat matches 10 run tag @a[tag=!storyteller,tag=!spectator,scores={id=10},limit=1] add $(category)
$execute if score @s botc_grim_edit_seat matches 10 run fmvariable set p10_role false $(role)
execute if score @s botc_grim_edit_seat matches 10 run scoreboard players set grim_editor_seat_10_alignment botc_patch 2
$execute if score @s botc_grim_edit_seat matches 10 run scoreboard players set grim_seat_10_role botc_patch $(score)
execute if score @s botc_grim_edit_seat matches 10 run scoreboard players set grim_seat_10_alignment botc_patch 2
$execute if score @s botc_grim_edit_seat matches 10 run tellraw @a[tag=!storyteller,tag=!spectator,scores={id=10},limit=1] [{"text":"You are now the ","color":"gray"},{"text":"$(name)","color":"$(color)","bold":true},{"text":". You are evil.","color":"red","bold":false}]
$execute if score @s botc_grim_edit_seat matches 11 run scoreboard players set @a[tag=!storyteller,tag=!spectator,scores={id=11},limit=1] role $(score)
execute if score @s botc_grim_edit_seat matches 11 run tag @a[tag=!storyteller,tag=!spectator,scores={id=11},limit=1] remove town
execute if score @s botc_grim_edit_seat matches 11 run tag @a[tag=!storyteller,tag=!spectator,scores={id=11},limit=1] remove outsider
execute if score @s botc_grim_edit_seat matches 11 run tag @a[tag=!storyteller,tag=!spectator,scores={id=11},limit=1] remove minion
execute if score @s botc_grim_edit_seat matches 11 run tag @a[tag=!storyteller,tag=!spectator,scores={id=11},limit=1] remove demon
$execute if score @s botc_grim_edit_seat matches 11 run tag @a[tag=!storyteller,tag=!spectator,scores={id=11},limit=1] add $(category)
$execute if score @s botc_grim_edit_seat matches 11 run fmvariable set p11_role false $(role)
execute if score @s botc_grim_edit_seat matches 11 run scoreboard players set grim_editor_seat_11_alignment botc_patch 2
$execute if score @s botc_grim_edit_seat matches 11 run scoreboard players set grim_seat_11_role botc_patch $(score)
execute if score @s botc_grim_edit_seat matches 11 run scoreboard players set grim_seat_11_alignment botc_patch 2
$execute if score @s botc_grim_edit_seat matches 11 run tellraw @a[tag=!storyteller,tag=!spectator,scores={id=11},limit=1] [{"text":"You are now the ","color":"gray"},{"text":"$(name)","color":"$(color)","bold":true},{"text":". You are evil.","color":"red","bold":false}]
$execute if score @s botc_grim_edit_seat matches 12 run scoreboard players set @a[tag=!storyteller,tag=!spectator,scores={id=12},limit=1] role $(score)
execute if score @s botc_grim_edit_seat matches 12 run tag @a[tag=!storyteller,tag=!spectator,scores={id=12},limit=1] remove town
execute if score @s botc_grim_edit_seat matches 12 run tag @a[tag=!storyteller,tag=!spectator,scores={id=12},limit=1] remove outsider
execute if score @s botc_grim_edit_seat matches 12 run tag @a[tag=!storyteller,tag=!spectator,scores={id=12},limit=1] remove minion
execute if score @s botc_grim_edit_seat matches 12 run tag @a[tag=!storyteller,tag=!spectator,scores={id=12},limit=1] remove demon
$execute if score @s botc_grim_edit_seat matches 12 run tag @a[tag=!storyteller,tag=!spectator,scores={id=12},limit=1] add $(category)
$execute if score @s botc_grim_edit_seat matches 12 run fmvariable set p12_role false $(role)
execute if score @s botc_grim_edit_seat matches 12 run scoreboard players set grim_editor_seat_12_alignment botc_patch 2
$execute if score @s botc_grim_edit_seat matches 12 run scoreboard players set grim_seat_12_role botc_patch $(score)
execute if score @s botc_grim_edit_seat matches 12 run scoreboard players set grim_seat_12_alignment botc_patch 2
$execute if score @s botc_grim_edit_seat matches 12 run tellraw @a[tag=!storyteller,tag=!spectator,scores={id=12},limit=1] [{"text":"You are now the ","color":"gray"},{"text":"$(name)","color":"$(color)","bold":true},{"text":". You are evil.","color":"red","bold":false}]
$execute if score @s botc_grim_edit_seat matches 13 run scoreboard players set @a[tag=!storyteller,tag=!spectator,scores={id=13},limit=1] role $(score)
execute if score @s botc_grim_edit_seat matches 13 run tag @a[tag=!storyteller,tag=!spectator,scores={id=13},limit=1] remove town
execute if score @s botc_grim_edit_seat matches 13 run tag @a[tag=!storyteller,tag=!spectator,scores={id=13},limit=1] remove outsider
execute if score @s botc_grim_edit_seat matches 13 run tag @a[tag=!storyteller,tag=!spectator,scores={id=13},limit=1] remove minion
execute if score @s botc_grim_edit_seat matches 13 run tag @a[tag=!storyteller,tag=!spectator,scores={id=13},limit=1] remove demon
$execute if score @s botc_grim_edit_seat matches 13 run tag @a[tag=!storyteller,tag=!spectator,scores={id=13},limit=1] add $(category)
$execute if score @s botc_grim_edit_seat matches 13 run fmvariable set p13_role false $(role)
execute if score @s botc_grim_edit_seat matches 13 run scoreboard players set grim_editor_seat_13_alignment botc_patch 2
$execute if score @s botc_grim_edit_seat matches 13 run scoreboard players set grim_seat_13_role botc_patch $(score)
execute if score @s botc_grim_edit_seat matches 13 run scoreboard players set grim_seat_13_alignment botc_patch 2
$execute if score @s botc_grim_edit_seat matches 13 run tellraw @a[tag=!storyteller,tag=!spectator,scores={id=13},limit=1] [{"text":"You are now the ","color":"gray"},{"text":"$(name)","color":"$(color)","bold":true},{"text":". You are evil.","color":"red","bold":false}]
$execute if score @s botc_grim_edit_seat matches 14 run scoreboard players set @a[tag=!storyteller,tag=!spectator,scores={id=14},limit=1] role $(score)
execute if score @s botc_grim_edit_seat matches 14 run tag @a[tag=!storyteller,tag=!spectator,scores={id=14},limit=1] remove town
execute if score @s botc_grim_edit_seat matches 14 run tag @a[tag=!storyteller,tag=!spectator,scores={id=14},limit=1] remove outsider
execute if score @s botc_grim_edit_seat matches 14 run tag @a[tag=!storyteller,tag=!spectator,scores={id=14},limit=1] remove minion
execute if score @s botc_grim_edit_seat matches 14 run tag @a[tag=!storyteller,tag=!spectator,scores={id=14},limit=1] remove demon
$execute if score @s botc_grim_edit_seat matches 14 run tag @a[tag=!storyteller,tag=!spectator,scores={id=14},limit=1] add $(category)
$execute if score @s botc_grim_edit_seat matches 14 run fmvariable set p14_role false $(role)
execute if score @s botc_grim_edit_seat matches 14 run scoreboard players set grim_editor_seat_14_alignment botc_patch 2
$execute if score @s botc_grim_edit_seat matches 14 run scoreboard players set grim_seat_14_role botc_patch $(score)
execute if score @s botc_grim_edit_seat matches 14 run scoreboard players set grim_seat_14_alignment botc_patch 2
$execute if score @s botc_grim_edit_seat matches 14 run tellraw @a[tag=!storyteller,tag=!spectator,scores={id=14},limit=1] [{"text":"You are now the ","color":"gray"},{"text":"$(name)","color":"$(color)","bold":true},{"text":". You are evil.","color":"red","bold":false}]
$execute if score @s botc_grim_edit_seat matches 15 run scoreboard players set @a[tag=!storyteller,tag=!spectator,scores={id=15},limit=1] role $(score)
execute if score @s botc_grim_edit_seat matches 15 run tag @a[tag=!storyteller,tag=!spectator,scores={id=15},limit=1] remove town
execute if score @s botc_grim_edit_seat matches 15 run tag @a[tag=!storyteller,tag=!spectator,scores={id=15},limit=1] remove outsider
execute if score @s botc_grim_edit_seat matches 15 run tag @a[tag=!storyteller,tag=!spectator,scores={id=15},limit=1] remove minion
execute if score @s botc_grim_edit_seat matches 15 run tag @a[tag=!storyteller,tag=!spectator,scores={id=15},limit=1] remove demon
$execute if score @s botc_grim_edit_seat matches 15 run tag @a[tag=!storyteller,tag=!spectator,scores={id=15},limit=1] add $(category)
$execute if score @s botc_grim_edit_seat matches 15 run fmvariable set p15_role false $(role)
execute if score @s botc_grim_edit_seat matches 15 run scoreboard players set grim_editor_seat_15_alignment botc_patch 2
$execute if score @s botc_grim_edit_seat matches 15 run scoreboard players set grim_seat_15_role botc_patch $(score)
execute if score @s botc_grim_edit_seat matches 15 run scoreboard players set grim_seat_15_alignment botc_patch 2
$execute if score @s botc_grim_edit_seat matches 15 run tellraw @a[tag=!storyteller,tag=!spectator,scores={id=15},limit=1] [{"text":"You are now the ","color":"gray"},{"text":"$(name)","color":"$(color)","bold":true},{"text":". You are evil.","color":"red","bold":false}]
function botc_patch:wraith/sync_roles
scoreboard players set draft_summoner_resolution_pending botc_patch 0
scoreboard players set @s botc_grim_edit_mode 0
scoreboard players set @s botc_grim_edit_valid 1
dialog clear @s
$tellraw @s [{"text":"Demon assigned: ","color":"green","bold":true},{"text":"$(name)","color":"$(color)","bold":true},{"text":" is now in play and the selected player is evil.","color":"gray","bold":false}]
