# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Validate without mutation, report blockers in chat, then show one complete confirmation.
scoreboard players set buffet_start_confirmed botc_patch 0
function botc_patch:buffet/draft/rebuild_requirements
function botc_patch:buffet/draft/recount_needs
function botc_patch:buffet/draft/start/validate_preflight
execute unless score buffet_hard_valid botc_patch matches 1 run function botc_patch:buffet/draft/start/report_invalid
execute unless score buffet_hard_valid botc_patch matches 1 run return 0
function botc_patch:buffet/draft/start/build_warning
