# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Show one forced Legion card to an unfinished player reserved by the real topology.
scoreboard players add draft_hand_id botc_patch 1
data modify storage botc_patch:buffet action.picked set value {actual:130,perceived:130,alignment:2,perceived_alignment:2,category:4,archetype:"demon_format_and_setup_changing",archetype_id:22,hidden:0b,hidden_mode:0,hermit_forced_ability:0,name:"Legion",color:"#ff5555",glyph:""}
execute store result storage botc_patch:buffet action.picked.hand_id int 1 run scoreboard players get draft_hand_id botc_patch
data modify storage botc_patch:buffet action.picked.internal_draw set value 1
execute store result storage botc_patch:buffet action.picked.route int 1 run scoreboard players get draft_route_kind botc_patch
$data modify storage botc_patch:buffet action.picked.seat set value $(seat)
$data modify storage botc_patch:buffet draft.seats.s$(seat).round set value 2
$data modify storage botc_patch:buffet draft.seats.s$(seat).offers set value {}
$data modify storage botc_patch:buffet draft.seats.s$(seat).offers.o1 set from storage botc_patch:buffet action.picked
function botc_patch:buffet/draft/dialog/prepare with storage botc_patch:buffet action
