# Generated by tools/generate-buffet-gamemodes.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Clear one entry only from the acting player's private Personal Grimoire.
execute if score @s botc_bg_target matches 1 run scoreboard players set @s botc_bg_s1 0
execute if score @s botc_bg_target matches 1 run fmvariable set p1_role false none
execute if score @s botc_bg_target matches 2 run scoreboard players set @s botc_bg_s2 0
execute if score @s botc_bg_target matches 2 run fmvariable set p2_role false none
execute if score @s botc_bg_target matches 3 run scoreboard players set @s botc_bg_s3 0
execute if score @s botc_bg_target matches 3 run fmvariable set p3_role false none
execute if score @s botc_bg_target matches 4 run scoreboard players set @s botc_bg_s4 0
execute if score @s botc_bg_target matches 4 run fmvariable set p4_role false none
execute if score @s botc_bg_target matches 5 run scoreboard players set @s botc_bg_s5 0
execute if score @s botc_bg_target matches 5 run fmvariable set p5_role false none
execute if score @s botc_bg_target matches 6 run scoreboard players set @s botc_bg_s6 0
execute if score @s botc_bg_target matches 6 run fmvariable set p6_role false none
execute if score @s botc_bg_target matches 7 run scoreboard players set @s botc_bg_s7 0
execute if score @s botc_bg_target matches 7 run fmvariable set p7_role false none
execute if score @s botc_bg_target matches 8 run scoreboard players set @s botc_bg_s8 0
execute if score @s botc_bg_target matches 8 run fmvariable set p8_role false none
execute if score @s botc_bg_target matches 9 run scoreboard players set @s botc_bg_s9 0
execute if score @s botc_bg_target matches 9 run fmvariable set p9_role false none
execute if score @s botc_bg_target matches 10 run scoreboard players set @s botc_bg_s10 0
execute if score @s botc_bg_target matches 10 run fmvariable set p10_role false none
execute if score @s botc_bg_target matches 11 run scoreboard players set @s botc_bg_s11 0
execute if score @s botc_bg_target matches 11 run fmvariable set p11_role false none
execute if score @s botc_bg_target matches 12 run scoreboard players set @s botc_bg_s12 0
execute if score @s botc_bg_target matches 12 run fmvariable set p12_role false none
execute if score @s botc_bg_target matches 13 run scoreboard players set @s botc_bg_s13 0
execute if score @s botc_bg_target matches 13 run fmvariable set p13_role false none
execute if score @s botc_bg_target matches 14 run scoreboard players set @s botc_bg_s14 0
execute if score @s botc_bg_target matches 14 run fmvariable set p14_role false none
execute if score @s botc_bg_target matches 15 run scoreboard players set @s botc_bg_s15 0
execute if score @s botc_bg_target matches 15 run fmvariable set p15_role false none
function botc_patch:buffet/personal_grimoire/open
