# Generated by tools/generate-buffet-gamemodes.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Synchronize the acting player's saved private notes, then open Sybillian's player-facing Grimoire view.
data modify storage botc_patch:buffet action.personal_grimoire_name set value {seat:1,name:"Nobody!"}
execute if data storage botc_patch:buffet roster.p1 run data modify storage botc_patch:buffet action.personal_grimoire_name.name set from storage botc_patch:buffet roster.p1
function botc_patch:buffet/personal_grimoire/sync_sybillian_name with storage botc_patch:buffet action.personal_grimoire_name
fmvariable set p1_role false none
data modify storage botc_patch:buffet action.personal_grimoire_sync set value {seat:1,role:0}
execute store result storage botc_patch:buffet action.personal_grimoire_sync.role int 1 run scoreboard players get @s botc_bg_s1
execute if score @s botc_bg_s1 matches 1..325 run function botc_patch:buffet/personal_grimoire/sync_sybillian_role with storage botc_patch:buffet action.personal_grimoire_sync
data modify storage botc_patch:buffet action.personal_grimoire_name set value {seat:2,name:"Nobody!"}
execute if data storage botc_patch:buffet roster.p2 run data modify storage botc_patch:buffet action.personal_grimoire_name.name set from storage botc_patch:buffet roster.p2
function botc_patch:buffet/personal_grimoire/sync_sybillian_name with storage botc_patch:buffet action.personal_grimoire_name
fmvariable set p2_role false none
data modify storage botc_patch:buffet action.personal_grimoire_sync set value {seat:2,role:0}
execute store result storage botc_patch:buffet action.personal_grimoire_sync.role int 1 run scoreboard players get @s botc_bg_s2
execute if score @s botc_bg_s2 matches 1..325 run function botc_patch:buffet/personal_grimoire/sync_sybillian_role with storage botc_patch:buffet action.personal_grimoire_sync
data modify storage botc_patch:buffet action.personal_grimoire_name set value {seat:3,name:"Nobody!"}
execute if data storage botc_patch:buffet roster.p3 run data modify storage botc_patch:buffet action.personal_grimoire_name.name set from storage botc_patch:buffet roster.p3
function botc_patch:buffet/personal_grimoire/sync_sybillian_name with storage botc_patch:buffet action.personal_grimoire_name
fmvariable set p3_role false none
data modify storage botc_patch:buffet action.personal_grimoire_sync set value {seat:3,role:0}
execute store result storage botc_patch:buffet action.personal_grimoire_sync.role int 1 run scoreboard players get @s botc_bg_s3
execute if score @s botc_bg_s3 matches 1..325 run function botc_patch:buffet/personal_grimoire/sync_sybillian_role with storage botc_patch:buffet action.personal_grimoire_sync
data modify storage botc_patch:buffet action.personal_grimoire_name set value {seat:4,name:"Nobody!"}
execute if data storage botc_patch:buffet roster.p4 run data modify storage botc_patch:buffet action.personal_grimoire_name.name set from storage botc_patch:buffet roster.p4
function botc_patch:buffet/personal_grimoire/sync_sybillian_name with storage botc_patch:buffet action.personal_grimoire_name
fmvariable set p4_role false none
data modify storage botc_patch:buffet action.personal_grimoire_sync set value {seat:4,role:0}
execute store result storage botc_patch:buffet action.personal_grimoire_sync.role int 1 run scoreboard players get @s botc_bg_s4
execute if score @s botc_bg_s4 matches 1..325 run function botc_patch:buffet/personal_grimoire/sync_sybillian_role with storage botc_patch:buffet action.personal_grimoire_sync
data modify storage botc_patch:buffet action.personal_grimoire_name set value {seat:5,name:"Nobody!"}
execute if data storage botc_patch:buffet roster.p5 run data modify storage botc_patch:buffet action.personal_grimoire_name.name set from storage botc_patch:buffet roster.p5
function botc_patch:buffet/personal_grimoire/sync_sybillian_name with storage botc_patch:buffet action.personal_grimoire_name
fmvariable set p5_role false none
data modify storage botc_patch:buffet action.personal_grimoire_sync set value {seat:5,role:0}
execute store result storage botc_patch:buffet action.personal_grimoire_sync.role int 1 run scoreboard players get @s botc_bg_s5
execute if score @s botc_bg_s5 matches 1..325 run function botc_patch:buffet/personal_grimoire/sync_sybillian_role with storage botc_patch:buffet action.personal_grimoire_sync
data modify storage botc_patch:buffet action.personal_grimoire_name set value {seat:6,name:"Nobody!"}
execute if data storage botc_patch:buffet roster.p6 run data modify storage botc_patch:buffet action.personal_grimoire_name.name set from storage botc_patch:buffet roster.p6
function botc_patch:buffet/personal_grimoire/sync_sybillian_name with storage botc_patch:buffet action.personal_grimoire_name
fmvariable set p6_role false none
data modify storage botc_patch:buffet action.personal_grimoire_sync set value {seat:6,role:0}
execute store result storage botc_patch:buffet action.personal_grimoire_sync.role int 1 run scoreboard players get @s botc_bg_s6
execute if score @s botc_bg_s6 matches 1..325 run function botc_patch:buffet/personal_grimoire/sync_sybillian_role with storage botc_patch:buffet action.personal_grimoire_sync
data modify storage botc_patch:buffet action.personal_grimoire_name set value {seat:7,name:"Nobody!"}
execute if data storage botc_patch:buffet roster.p7 run data modify storage botc_patch:buffet action.personal_grimoire_name.name set from storage botc_patch:buffet roster.p7
function botc_patch:buffet/personal_grimoire/sync_sybillian_name with storage botc_patch:buffet action.personal_grimoire_name
fmvariable set p7_role false none
data modify storage botc_patch:buffet action.personal_grimoire_sync set value {seat:7,role:0}
execute store result storage botc_patch:buffet action.personal_grimoire_sync.role int 1 run scoreboard players get @s botc_bg_s7
execute if score @s botc_bg_s7 matches 1..325 run function botc_patch:buffet/personal_grimoire/sync_sybillian_role with storage botc_patch:buffet action.personal_grimoire_sync
data modify storage botc_patch:buffet action.personal_grimoire_name set value {seat:8,name:"Nobody!"}
execute if data storage botc_patch:buffet roster.p8 run data modify storage botc_patch:buffet action.personal_grimoire_name.name set from storage botc_patch:buffet roster.p8
function botc_patch:buffet/personal_grimoire/sync_sybillian_name with storage botc_patch:buffet action.personal_grimoire_name
fmvariable set p8_role false none
data modify storage botc_patch:buffet action.personal_grimoire_sync set value {seat:8,role:0}
execute store result storage botc_patch:buffet action.personal_grimoire_sync.role int 1 run scoreboard players get @s botc_bg_s8
execute if score @s botc_bg_s8 matches 1..325 run function botc_patch:buffet/personal_grimoire/sync_sybillian_role with storage botc_patch:buffet action.personal_grimoire_sync
data modify storage botc_patch:buffet action.personal_grimoire_name set value {seat:9,name:"Nobody!"}
execute if data storage botc_patch:buffet roster.p9 run data modify storage botc_patch:buffet action.personal_grimoire_name.name set from storage botc_patch:buffet roster.p9
function botc_patch:buffet/personal_grimoire/sync_sybillian_name with storage botc_patch:buffet action.personal_grimoire_name
fmvariable set p9_role false none
data modify storage botc_patch:buffet action.personal_grimoire_sync set value {seat:9,role:0}
execute store result storage botc_patch:buffet action.personal_grimoire_sync.role int 1 run scoreboard players get @s botc_bg_s9
execute if score @s botc_bg_s9 matches 1..325 run function botc_patch:buffet/personal_grimoire/sync_sybillian_role with storage botc_patch:buffet action.personal_grimoire_sync
data modify storage botc_patch:buffet action.personal_grimoire_name set value {seat:10,name:"Nobody!"}
execute if data storage botc_patch:buffet roster.p10 run data modify storage botc_patch:buffet action.personal_grimoire_name.name set from storage botc_patch:buffet roster.p10
function botc_patch:buffet/personal_grimoire/sync_sybillian_name with storage botc_patch:buffet action.personal_grimoire_name
fmvariable set p10_role false none
data modify storage botc_patch:buffet action.personal_grimoire_sync set value {seat:10,role:0}
execute store result storage botc_patch:buffet action.personal_grimoire_sync.role int 1 run scoreboard players get @s botc_bg_s10
execute if score @s botc_bg_s10 matches 1..325 run function botc_patch:buffet/personal_grimoire/sync_sybillian_role with storage botc_patch:buffet action.personal_grimoire_sync
data modify storage botc_patch:buffet action.personal_grimoire_name set value {seat:11,name:"Nobody!"}
execute if data storage botc_patch:buffet roster.p11 run data modify storage botc_patch:buffet action.personal_grimoire_name.name set from storage botc_patch:buffet roster.p11
function botc_patch:buffet/personal_grimoire/sync_sybillian_name with storage botc_patch:buffet action.personal_grimoire_name
fmvariable set p11_role false none
data modify storage botc_patch:buffet action.personal_grimoire_sync set value {seat:11,role:0}
execute store result storage botc_patch:buffet action.personal_grimoire_sync.role int 1 run scoreboard players get @s botc_bg_s11
execute if score @s botc_bg_s11 matches 1..325 run function botc_patch:buffet/personal_grimoire/sync_sybillian_role with storage botc_patch:buffet action.personal_grimoire_sync
data modify storage botc_patch:buffet action.personal_grimoire_name set value {seat:12,name:"Nobody!"}
execute if data storage botc_patch:buffet roster.p12 run data modify storage botc_patch:buffet action.personal_grimoire_name.name set from storage botc_patch:buffet roster.p12
function botc_patch:buffet/personal_grimoire/sync_sybillian_name with storage botc_patch:buffet action.personal_grimoire_name
fmvariable set p12_role false none
data modify storage botc_patch:buffet action.personal_grimoire_sync set value {seat:12,role:0}
execute store result storage botc_patch:buffet action.personal_grimoire_sync.role int 1 run scoreboard players get @s botc_bg_s12
execute if score @s botc_bg_s12 matches 1..325 run function botc_patch:buffet/personal_grimoire/sync_sybillian_role with storage botc_patch:buffet action.personal_grimoire_sync
data modify storage botc_patch:buffet action.personal_grimoire_name set value {seat:13,name:"Nobody!"}
execute if data storage botc_patch:buffet roster.p13 run data modify storage botc_patch:buffet action.personal_grimoire_name.name set from storage botc_patch:buffet roster.p13
function botc_patch:buffet/personal_grimoire/sync_sybillian_name with storage botc_patch:buffet action.personal_grimoire_name
fmvariable set p13_role false none
data modify storage botc_patch:buffet action.personal_grimoire_sync set value {seat:13,role:0}
execute store result storage botc_patch:buffet action.personal_grimoire_sync.role int 1 run scoreboard players get @s botc_bg_s13
execute if score @s botc_bg_s13 matches 1..325 run function botc_patch:buffet/personal_grimoire/sync_sybillian_role with storage botc_patch:buffet action.personal_grimoire_sync
data modify storage botc_patch:buffet action.personal_grimoire_name set value {seat:14,name:"Nobody!"}
execute if data storage botc_patch:buffet roster.p14 run data modify storage botc_patch:buffet action.personal_grimoire_name.name set from storage botc_patch:buffet roster.p14
function botc_patch:buffet/personal_grimoire/sync_sybillian_name with storage botc_patch:buffet action.personal_grimoire_name
fmvariable set p14_role false none
data modify storage botc_patch:buffet action.personal_grimoire_sync set value {seat:14,role:0}
execute store result storage botc_patch:buffet action.personal_grimoire_sync.role int 1 run scoreboard players get @s botc_bg_s14
execute if score @s botc_bg_s14 matches 1..325 run function botc_patch:buffet/personal_grimoire/sync_sybillian_role with storage botc_patch:buffet action.personal_grimoire_sync
data modify storage botc_patch:buffet action.personal_grimoire_name set value {seat:15,name:"Nobody!"}
execute if data storage botc_patch:buffet roster.p15 run data modify storage botc_patch:buffet action.personal_grimoire_name.name set from storage botc_patch:buffet roster.p15
function botc_patch:buffet/personal_grimoire/sync_sybillian_name with storage botc_patch:buffet action.personal_grimoire_name
fmvariable set p15_role false none
data modify storage botc_patch:buffet action.personal_grimoire_sync set value {seat:15,role:0}
execute store result storage botc_patch:buffet action.personal_grimoire_sync.role int 1 run scoreboard players get @s botc_bg_s15
execute if score @s botc_bg_s15 matches 1..325 run function botc_patch:buffet/personal_grimoire/sync_sybillian_role with storage botc_patch:buffet action.personal_grimoire_sync
dialog clear @s
execute at @s run playsound minecraft:entity.villager.work_librarian voice @s ~ ~ ~ 1 1
openguiscreen ct-player_grim
