# Generated by tools/generate-buffet-gamemodes.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Apply one trusted role slug only to the acting player's Sybillian Grimoire view.
$fmvariable set p$(seat)_role false $(id)
