# Generated by tools/generate-buffet-gamemodes.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Resolve one assigned role into the Storyteller dashboard.
$execute if data storage botc_patch:buffet catalog.s$(role) run data modify storage botc_patch:buffet ui.p$(seat)_role set from storage botc_patch:buffet catalog.s$(role).name
$execute if data storage botc_patch:buffet catalog.s$(role) run data modify storage botc_patch:buffet ui.p$(seat)_glyph set from storage botc_patch:buffet catalog.s$(role).glyph
