param(
    [switch] $Check
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$RepoRoot = Split-Path -Parent $PSScriptRoot
$SybillianRolePath = Join-Path $RepoRoot "data\resources\datapack\required\ct\data\ct\function\admin\setup\set_from_menu.mcfunction"
$SybillianCharactersPath = Join-Path $RepoRoot "data\resources\datapack\required\ct\data\ct\function\admin\setup\characters.mcfunction"
$RoleIconPath = Join-Path $RepoRoot "Jays-Patch/role-icons.json"
$RoleCatalogHelper = Join-Path $RepoRoot "tools/lib/sybillian-role-catalog.ps1"
$RoleExtensionPath = Join-Path $RepoRoot "Jays-Patch/role-extensions.json"
$ContractPath = Join-Path $RepoRoot "Jays-Patch/upstream-contract.json"
$RulesPath = Join-Path $RepoRoot "Jays-Patch/buffet-rules.json"
$RoleGlyphHelper = Join-Path $RepoRoot "tools/lib/role-icon-glyphs.ps1"
$OutputRoot = Join-Path $RepoRoot "Jays-Patch/datapack/data/botc_patch/function/grim/editor"
$PlayerDialogRoot = Join-Path $OutputRoot "player_dialog"
$PlayerLabelsRoot = Join-Path $OutputRoot "player_labels"
$CharacterDialogRoot = Join-Path $OutputRoot "character_dialog"
$SummonerPlayerDialogRoot = Join-Path $OutputRoot "summoner/player_dialog"
$SummonerDemonDialogRoot = Join-Path $OutputRoot "summoner/demon_dialog"
$SummonerMinionDialogRoot = Join-Path $OutputRoot "summoner/minion_dialog"
$DemonRoot = Join-Path $OutputRoot "demon"
$RolesRoot = Join-Path $OutputRoot "roles"
$RevealRoot = Join-Path $RepoRoot "Jays-Patch/datapack/data/botc_patch/function/grim/reveal"

if (-not (Test-Path -LiteralPath $SybillianRolePath -PathType Leaf)) {
    throw "Missing Sybillian role table: $SybillianRolePath"
}

if (-not (Test-Path -LiteralPath $RoleIconPath -PathType Leaf)) {
    throw "Missing role icon table: $RoleIconPath"
}

$roleIconConfig = Get-Content -LiteralPath $RoleIconPath -Raw | ConvertFrom-Json
$roleIconSet = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
foreach ($roleIcon in @($roleIconConfig.roles)) {
    [void] $roleIconSet.Add([string] $roleIcon)
}

. $RoleCatalogHelper
. $RoleGlyphHelper
$roles = @(Get-SybillianRoleCatalog -SetFromMenuPath $SybillianRolePath -CharactersPath $SybillianCharactersPath -ExtensionPath $RoleExtensionPath)
$disabledRoleReasons = Get-BotcDisabledRoleMap -ContractPath $ContractPath -RoleCatalog $roles
$selectableRoles = @($roles | Where-Object { -not $disabledRoleReasons.ContainsKey([string] $_.Role) })
$rules = Get-Content -LiteralPath $RulesPath -Raw | ConvertFrom-Json
if ([string] $rules.draft.topologyRules.trustedDemonEditor.availability -cne "every-night" -or
    [bool] $rules.draft.topologyRules.trustedDemonEditor.automaticThirdNightPrompt) {
    throw "Grimoire editor requires the accepted every-night trusted Demon catalog without an automatic third-night prompt."
}
$demons = @($selectableRoles | Where-Object Category -eq "demon")
$summonerMinions = @($selectableRoles | Where-Object { $_.Category -eq "minion" -and $_.Role -notin @("summoner", "marionette") })
$lilMonsta = $roles | Where-Object Role -eq "lil_monsta" | Select-Object -First 1
if ($null -eq $lilMonsta -or $demons.Count -lt 1 -or $summonerMinions.Count -lt 1) {
    throw "Summoner editor requires Lil' Monsta plus nonempty trusted Demon and direct-Minion catalogs."
}
$noneGlyph = Get-BotcRoleIconGlyph -RoleScore 0

$missingIcons = @($roles | Where-Object { -not $roleIconSet.Contains($_.Role) } | Select-Object -ExpandProperty Role)
if ($missingIcons.Count -gt 0) {
    throw "Missing role icons for editor roles: $($missingIcons -join ', ')"
}

$utf8NoBom = [System.Text.UTF8Encoding]::new($false)

function Write-Lines {
    param(
        [string] $Path,
        [System.Collections.Generic.List[string]] $Lines
    )

    $expected = ($Lines -join "`n") + "`n"
    if ($Check) {
        if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
            throw "Generated output is missing: $Path"
        }
        $actual = [System.IO.File]::ReadAllText($Path)
        if ($actual -cne $expected) {
            throw "Generated output is stale: $Path"
        }
        return
    }

    New-Item -ItemType Directory -Path (Split-Path -Parent $Path) -Force | Out-Null
    [System.IO.File]::WriteAllText($Path, $expected, $utf8NoBom)
}

function New-Header {
    param([string] $Responsibility)

    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add("# Generated by tools/generate-grim-character-editor.ps1.")
    $lines.Add("# Do not hand-edit this file; update the generator and regenerate.")
    $lines.Add("# $Responsibility")
    return ,$lines
}

if (-not $Check) {
    New-Item -ItemType Directory -Path $PlayerDialogRoot -Force | Out-Null
    New-Item -ItemType Directory -Path $PlayerLabelsRoot -Force | Out-Null
    New-Item -ItemType Directory -Path $CharacterDialogRoot -Force | Out-Null
    New-Item -ItemType Directory -Path $SummonerPlayerDialogRoot -Force | Out-Null
    New-Item -ItemType Directory -Path $SummonerDemonDialogRoot -Force | Out-Null
    New-Item -ItemType Directory -Path $SummonerMinionDialogRoot -Force | Out-Null
    New-Item -ItemType Directory -Path $DemonRoot -Force | Out-Null
    New-Item -ItemType Directory -Path $RolesRoot -Force | Out-Null
    New-Item -ItemType Directory -Path $RevealRoot -Force | Out-Null
}

$initLines = New-Header "Builds the trusted role catalog from Sybillian's role-score table."
$initLines.Add("data remove storage botc_patch:grim editor.catalog")
$initLines.Add("data remove storage botc_patch:grim editor.score_catalog")
$initLines.Add("data modify storage botc_patch:grim editor.catalog.none set value {id:`"none`",name:`"None`",score:0,alignment:0,color:`"#aaaaaa`",glyph:`"$noneGlyph`"}")
$initLines.Add('data modify storage botc_patch:grim editor.score_catalog.s0 set from storage botc_patch:grim editor.catalog.none')
foreach ($role in $roles) {
    $glyph = Get-BotcRoleIconGlyph -RoleScore $role.Id
    $entry = '{{id:"{0}",name:"{1}",score:{2},alignment:{3},color:"{4}",glyph:"{5}"}}' -f $role.Role, $role.Name, $role.Id, $role.Alignment, $role.Color, $glyph
    $initLines.Add(('data modify storage botc_patch:grim editor.catalog.{0} set value {1}' -f $role.Role, $entry))
    $initLines.Add(('data modify storage botc_patch:grim editor.score_catalog.s{0} set from storage botc_patch:grim editor.catalog.{1}' -f $role.Id, $role.Role))
}
Write-Lines -Path (Join-Path $RolesRoot "init.mcfunction") -Lines $initLines

$revealSpawnLines = New-Header "Maps every trusted character score to its Grimoire reveal display."
foreach ($role in $roles) {
    $revealSpawnLines.Add(('execute if score grim_reveal_role botc_patch matches {0} run function botc_patch:grim/reveal/spawn {{role:"{1}"}}' -f $role.Id, $role.Role))
}
Write-Lines -Path (Join-Path $RevealRoot "spawn_from_score.mcfunction") -Lines $revealSpawnLines

$appendLines = New-Header "Appends one trusted current-script role to the editor list."
$appendLines.Add('scoreboard players set grim_editor_role_selectable botc_patch 1')
foreach ($roleName in $disabledRoleReasons.Keys | Sort-Object) {
    $appendLines.Add(('execute if data storage botc_patch:grim editor.append{{id:"{0}"}} run scoreboard players set grim_editor_role_selectable botc_patch 0' -f $roleName))
}
$appendLines.Add('$execute if score grim_editor_role_selectable botc_patch matches 1 run data modify storage botc_patch:grim editor.roles append from storage botc_patch:grim editor.catalog.$(id)')
Write-Lines -Path (Join-Path $RolesRoot "append.mcfunction") -Lines $appendLines

$buildLines = New-Header "Builds the normal current-script list or the trusted nightly Demon/direct-Minion catalog."
$buildLines.Add("data modify storage botc_patch:grim editor.roles set value []")
$buildLines.Add("data remove storage botc_patch:grim editor.append")
$scriptSlots = @(
    [pscustomobject]@{ Name = "town"; Count = 15 },
    [pscustomobject]@{ Name = "outsiders"; Count = 5 },
    [pscustomobject]@{ Name = "minions"; Count = 5 },
    [pscustomobject]@{ Name = "demons"; Count = 5 }
)
foreach ($group in $scriptSlots) {
    for ($index = 0; $index -lt $group.Count; $index++) {
        $path = "in_characters.$($group.Name)[$index]"
        $buildLines.Add("execute if score @s botc_grim_edit_mode matches 0 if data storage ct:script $path run data modify storage botc_patch:grim editor.append.id set from storage ct:script $path")
        $buildLines.Add("execute if score @s botc_grim_edit_mode matches 0 if data storage ct:script $path run function botc_patch:grim/editor/roles/append with storage botc_patch:grim editor.append")
    }
}
foreach ($role in $demons) {
    $buildLines.Add(('execute if score @s botc_grim_edit_mode matches 1 run data modify storage botc_patch:grim editor.roles append from storage botc_patch:grim editor.catalog.{0}' -f $role.Role))
}
foreach ($role in $summonerMinions) {
    $unusedChecks = 1..15 | ForEach-Object { 'unless score grim_editor_seat_{0}_role botc_patch matches {1}' -f $_, $role.Id }
    $buildLines.Add(('execute if score @s botc_grim_edit_mode matches 2 {0} run data modify storage botc_patch:grim editor.roles append from storage botc_patch:grim editor.catalog.{1}' -f ($unusedChecks -join ' '), $role.Role))
}
$buildLines.Add("execute store result score grim_editor_role_count botc_patch run data get storage botc_patch:grim editor.roles")
Write-Lines -Path (Join-Path $RolesRoot "build.mcfunction") -Lines $buildLines

$prepareArgsLines = New-Header "Copies the role list into flat macro arguments for generated dialogs."
$prepareArgsLines.Add("data modify storage botc_patch:grim editor.dialog set value {player_name:`"Unknown`",current_role:`"none`",current_role_name:`"None`",current_role_glyph:`"$noneGlyph`",current_alignment_name:`"Unknown`",current_alignment_color:`"#aaaaaa`"}")
for ($index = 0; $index -lt 30; $index++) {
    $number = $index + 1
    foreach ($field in @("id", "name", "color", "glyph")) {
        $prepareArgsLines.Add("execute if data storage botc_patch:grim editor.roles[$index].$field run data modify storage botc_patch:grim editor.dialog.r$($number)_$field set from storage botc_patch:grim editor.roles[$index].$field")
    }
}
Write-Lines -Path (Join-Path $RolesRoot "prepare_args.mcfunction") -Lines $prepareArgsLines

$prepareCurrentLines = New-Header "Resolves the selected snapshot role through the trusted score catalog."
$prepareCurrentLines.Add('$data modify storage botc_patch:grim editor.dialog.current_role set from storage botc_patch:grim editor.score_catalog.s$(score).id')
$prepareCurrentLines.Add('$data modify storage botc_patch:grim editor.dialog.current_role_name set from storage botc_patch:grim editor.score_catalog.s$(score).name')
$prepareCurrentLines.Add('$data modify storage botc_patch:grim editor.dialog.current_role_glyph set from storage botc_patch:grim editor.score_catalog.s$(score).glyph')
Write-Lines -Path (Join-Path $RolesRoot "prepare_current.mcfunction") -Lines $prepareCurrentLines

$validateLines = New-Header "Validates a normal current-script edit or a trusted nightly full-catalog selection."
foreach ($role in $selectableRoles) {
    $validateLines.Add(('execute if score @s botc_grim_edit_mode matches 0 if data storage botc_patch:grim editor.request{{role:"{0}"}} if data storage ct:script in_characters{{{1}:["{0}"]}} run function botc_patch:grim/editor/apply_character {{role:"{0}",score:{2}}}' -f $role.Role, $role.StorageCategory, $role.Id))
}
foreach ($role in $demons) {
    if ($role.Role -eq "lil_monsta") {
        $validateLines.Add(('execute if score @s botc_grim_edit_mode matches 1 if data storage botc_patch:grim editor.request{{role:"{0}"}} run function botc_patch:grim/editor/summoner/begin_lil_monsta' -f $role.Role))
    }
    else {
        $validateLines.Add(('execute if score @s botc_grim_edit_mode matches 1 if data storage botc_patch:grim editor.request{{role:"{0}"}} run function botc_patch:grim/editor/summoner/apply_demon {{role:"{0}",score:{1},name:"{2}",color:"{3}",script_id:"{4}"}}' -f $role.Role, $role.Id, $role.Name.Replace('"', '\"'), $role.Color, $role.ScriptId))
    }
}
foreach ($role in $summonerMinions) {
    $unusedChecks = 1..15 | ForEach-Object { 'unless score grim_editor_seat_{0}_role botc_patch matches {1}' -f $_, $role.Id }
    $validateLines.Add(('execute if score @s botc_grim_edit_mode matches 2 if data storage botc_patch:grim editor.request{{role:"{0}"}} {1} run function botc_patch:grim/editor/summoner/apply_minion {{role:"{0}",score:{2},name:"{3}",color:"{4}",script_id:"{5}"}}' -f $role.Role, ($unusedChecks -join ' '), $role.Id, $role.Name.Replace('"', '\"'), $role.Color, $role.ScriptId))
}
Write-Lines -Path (Join-Path $RolesRoot "validate_requested.mcfunction") -Lines $validateLines

$clearGameLines = New-Header "Clears cached live-game character edits only when the game returns to setup."
$clearGameLines.Add("scoreboard players set grim_editor_game_captured botc_patch 0")
$clearGameLines.Add("scoreboard players set grim_editor_reveal_started botc_patch 0")
$clearGameLines.Add("scoreboard players set grim_editor_dialog_size botc_patch 0")
$clearGameLines.Add("scoreboard players reset @a botc_grim_edit_seat")
$clearGameLines.Add("scoreboard players reset @a botc_grim_edit_role")
$clearGameLines.Add("scoreboard players reset @a botc_grim_edit_alignment")
$clearGameLines.Add("scoreboard players reset @a botc_grim_edit_valid")
$clearGameLines.Add("scoreboard players reset @a botc_grim_edit_mode")
$clearGameLines.Add("data remove storage botc_patch:grim editor.roles")
$clearGameLines.Add("data remove storage botc_patch:grim editor.dialog")
$clearGameLines.Add("data remove storage botc_patch:grim editor.player_labels")
$clearGameLines.Add("data remove storage botc_patch:grim editor.player_label_lookup")
$clearGameLines.Add("data remove storage botc_patch:grim editor.request")
for ($seat = 1; $seat -le 15; $seat++) {
    $clearGameLines.Add("scoreboard players set grim_editor_seat_$($seat)_known botc_patch 0")
    $clearGameLines.Add("scoreboard players set grim_editor_seat_$($seat)_role botc_patch 0")
    $clearGameLines.Add("scoreboard players set grim_editor_seat_$($seat)_alignment botc_patch 0")
    $clearGameLines.Add("scoreboard players set grim_editor_seat_$($seat)_override botc_patch 0")
}
Write-Lines -Path (Join-Path $OutputRoot "clear_game.mcfunction") -Lines $clearGameLines

$refreshLines = New-Header "Refreshes non-overridden cached roles from online seated players."
for ($seat = 1; $seat -le 15; $seat++) {
    $target = "@a[tag=!storyteller,tag=!spectator,scores={id=$seat},limit=1]"
    $prefix = "execute if score grim_editor_seat_$($seat)_override botc_patch matches 0 if entity $target"
    $refreshLines.Add("$prefix run scoreboard players set grim_editor_seat_$($seat)_known botc_patch 1")
    $refreshLines.Add("$prefix run scoreboard players operation grim_editor_seat_$($seat)_role botc_patch = $target role")
    $refreshLines.Add("$prefix run scoreboard players set grim_editor_seat_$($seat)_alignment botc_patch 0")
    $refreshLines.Add("$prefix if score $target role matches 1..17 run scoreboard players set grim_editor_seat_$($seat)_alignment botc_patch 1")
    $refreshLines.Add("$prefix if score $target role matches 23..97 run scoreboard players set grim_editor_seat_$($seat)_alignment botc_patch 1")
    $refreshLines.Add("$prefix if score $target role matches 18..22 run scoreboard players set grim_editor_seat_$($seat)_alignment botc_patch 2")
    $refreshLines.Add("$prefix if score $target role matches 98..137 run scoreboard players set grim_editor_seat_$($seat)_alignment botc_patch 2")
    foreach ($extension in @($roles | Where-Object Id -gt 137)) {
        $refreshLines.Add("$prefix if score $target role matches $($extension.Id) run scoreboard players set grim_editor_seat_$($seat)_alignment botc_patch $($extension.Alignment)")
    }
}
Write-Lines -Path (Join-Path $OutputRoot "refresh_live_roles.mcfunction") -Lines $refreshLines

$playerLabelPrepareLines = New-Header "Prepares reusable Player (Role) labels from the current server-authoritative editor state."
$playerLabelPrepareLines.Add("data remove storage botc_patch:grim editor.player_labels")
for ($seat = 1; $seat -le 15; $seat++) {
    $playerLabelPrepareLines.Add(('data modify storage botc_patch:grim editor.player_labels.p{0}_name set value "Seat {0}"' -f $seat))
    $playerLabelPrepareLines.Add(('data modify storage botc_patch:grim editor.player_labels.p{0}_role set value "Unknown"' -f $seat))
    $playerLabelPrepareLines.Add(('data modify storage botc_patch:grim editor.player_labels.p{0}_glyph set value "{1}"' -f $seat, $noneGlyph))
    $playerLabelPrepareLines.Add(('data modify storage botc_patch:grim editor.player_labels.p{0}_color set value "#aaaaaa"' -f $seat))
    $playerLabelPrepareLines.Add(('execute if score grim_editor_seat_{0}_known botc_patch matches 1 if score grim_editor_seat_{0}_alignment botc_patch matches 1 run data modify storage botc_patch:grim editor.player_labels.p{0}_color set value "#55aaff"' -f $seat))
    $playerLabelPrepareLines.Add(('execute if score grim_editor_seat_{0}_known botc_patch matches 1 if score grim_editor_seat_{0}_alignment botc_patch matches 2 run data modify storage botc_patch:grim editor.player_labels.p{0}_color set value "#ff5555"' -f $seat))
    $playerLabelPrepareLines.Add(('execute if data storage ct:players players.p{0} unless data storage ct:players players{{p{0}:"Nobody!"}} run data modify storage botc_patch:grim editor.player_labels.p{0}_name set from storage ct:players players.p{0}' -f $seat))
    $playerLabelPrepareLines.Add(('data modify storage botc_patch:grim editor.player_label_lookup set value {{seat:{0},score:0}}' -f $seat))
    $playerLabelPrepareLines.Add(('execute if score grim_editor_seat_{0}_known botc_patch matches 1 store result storage botc_patch:grim editor.player_label_lookup.score int 1 run scoreboard players get grim_editor_seat_{0}_role botc_patch' -f $seat))
    $playerLabelPrepareLines.Add(('execute if score grim_editor_seat_{0}_known botc_patch matches 1 run function botc_patch:grim/editor/player_labels/prepare_role with storage botc_patch:grim editor.player_label_lookup' -f $seat))
}
Write-Lines -Path (Join-Path $PlayerLabelsRoot "prepare.mcfunction") -Lines $playerLabelPrepareLines

$playerLabelRoleLines = New-Header "Resolves one current editor role into its trusted display name."
$playerLabelRoleLines.Add('$data modify storage botc_patch:grim editor.player_labels.p$(seat)_role set from storage botc_patch:grim editor.score_catalog.s$(score).name')
$playerLabelRoleLines.Add('$data modify storage botc_patch:grim editor.player_labels.p$(seat)_glyph set from storage botc_patch:grim editor.score_catalog.s$(score).glyph')
Write-Lines -Path (Join-Path $PlayerLabelsRoot "prepare_role.mcfunction") -Lines $playerLabelRoleLines

$captureLines = New-Header "Captures the active game's server-authoritative seats before any reveal edits."
$captureLines.Add("execute unless data storage ct:players players.p1 run return 0")
$captureLines.Add('execute if data storage ct:players players{p1:"Nobody!"} run return 0')
$captureLines.Add("function botc_patch:grim/editor/clear_game")
$captureLines.Add("function botc_patch:grim/editor/refresh_live_roles")
for ($seat = 1; $seat -le 15; $seat++) {
    $captureLines.Add(('execute if data storage ct:players players.p{0} unless data storage ct:players players{{p{0}:"Nobody!"}} run scoreboard players set grim_editor_dialog_size botc_patch {0}' -f $seat))
}
$captureLines.Add("scoreboard players set grim_editor_game_captured botc_patch 1")
Write-Lines -Path (Join-Path $OutputRoot "capture_game.mcfunction") -Lines $captureLines

$prepareSelectedLines = New-Header "Loads a selected game-start seat from the cached live-game character state."
$prepareSelectedLines.Add("scoreboard players set @s botc_grim_edit_valid 0")
for ($seat = 1; $seat -le 15; $seat++) {
    $prefix = ('execute if score @s botc_grim_edit_seat matches {0} if score grim_editor_seat_{0}_known botc_patch matches 1 if data storage ct:players players.p{0} unless data storage ct:players players{{p{0}:"Nobody!"}}' -f $seat)
    $prepareSelectedLines.Add("$prefix run scoreboard players set @s botc_grim_edit_valid 1")
    $prepareSelectedLines.Add("$prefix run data modify storage botc_patch:grim editor.dialog.player_name set from storage ct:players players.p$seat")
    $prepareSelectedLines.Add("$prefix run scoreboard players operation @s botc_grim_edit_role = grim_editor_seat_$($seat)_role botc_patch")
    $prepareSelectedLines.Add("$prefix run scoreboard players operation @s botc_grim_edit_alignment = grim_editor_seat_$($seat)_alignment botc_patch")
}
$prepareSelectedLines.Add("execute unless score @s botc_grim_edit_valid matches 1 run return 0")
$prepareSelectedLines.Add("execute store result storage botc_patch:grim editor.lookup.score int 1 run scoreboard players get @s botc_grim_edit_role")
$prepareSelectedLines.Add("function botc_patch:grim/editor/roles/prepare_current with storage botc_patch:grim editor.lookup")
$prepareSelectedLines.Add('execute if score @s botc_grim_edit_alignment matches 1 run data modify storage botc_patch:grim editor.dialog.current_alignment_name set value "Good"')
$prepareSelectedLines.Add('execute if score @s botc_grim_edit_alignment matches 1 run data modify storage botc_patch:grim editor.dialog.current_alignment_color set value "#55aaff"')
$prepareSelectedLines.Add('execute if score @s botc_grim_edit_alignment matches 2 run data modify storage botc_patch:grim editor.dialog.current_alignment_name set value "Evil"')
$prepareSelectedLines.Add('execute if score @s botc_grim_edit_alignment matches 2 run data modify storage botc_patch:grim editor.dialog.current_alignment_color set value "#ff5555"')
Write-Lines -Path (Join-Path $OutputRoot "prepare_selected.mcfunction") -Lines $prepareSelectedLines

$applySelectedLines = New-Header "Stores the selected Storyteller edit for the later reveal snapshot."
for ($seat = 1; $seat -le 15; $seat++) {
    $applySelectedLines.Add("execute if score @s botc_grim_edit_seat matches $seat run scoreboard players set grim_editor_seat_$($seat)_known botc_patch 1")
    $applySelectedLines.Add("execute if score @s botc_grim_edit_seat matches $seat run scoreboard players set grim_editor_seat_$($seat)_override botc_patch 1")
    $applySelectedLines.Add("execute if score @s botc_grim_edit_seat matches $seat run scoreboard players operation grim_editor_seat_$($seat)_role botc_patch = @s botc_grim_edit_role")
    $applySelectedLines.Add("execute if score @s botc_grim_edit_seat matches $seat run scoreboard players operation grim_editor_seat_$($seat)_alignment botc_patch = @s botc_grim_edit_alignment")
}
Write-Lines -Path (Join-Path $OutputRoot "apply_selected.mcfunction") -Lines $applySelectedLines

$applySnapshotLines = New-Header "Copies cached live-game character state into the confirmed reveal snapshot."
for ($seat = 1; $seat -le 15; $seat++) {
    $prefix = "execute if score grim_editor_seat_$($seat)_known botc_patch matches 1"
    $applySnapshotLines.Add("$prefix run scoreboard players set grim_dialog_size botc_patch $seat")
    $applySnapshotLines.Add("$prefix run scoreboard players set grim_seat_$($seat)_occupied botc_patch 1")
    $applySnapshotLines.Add("$prefix run scoreboard players set grim_seat_$($seat)_revealed botc_patch 0")
    $applySnapshotLines.Add("$prefix run scoreboard players operation grim_seat_$($seat)_role botc_patch = grim_editor_seat_$($seat)_role botc_patch")
    $applySnapshotLines.Add("$prefix run scoreboard players operation grim_seat_$($seat)_alignment botc_patch = grim_editor_seat_$($seat)_alignment botc_patch")
}
Write-Lines -Path (Join-Path $OutputRoot "apply_to_snapshot.mcfunction") -Lines $applySnapshotLines

$syncDisplayLines = New-Header "Updates only the acting Storyteller's Sybillian grimoire display variable."
for ($seat = 1; $seat -le 15; $seat++) {
    $syncDisplayLines.Add(('$execute if score @s botc_grim_edit_seat matches {0} run fmvariable set p{0}_role false $(role)' -f $seat))
}
Write-Lines -Path (Join-Path $OutputRoot "sync_storyteller_display.mcfunction") -Lines $syncDisplayLines

$playerDispatchLines = New-Header "Shows the occupied-seat player picker using Sybillian's game-start name snapshot."
$playerDispatchLines.Add("dialog clear @s")
$playerDispatchLines.Add('execute unless score phase game_data matches 1.. run return run tellraw @s [{"text":"! ","color":"red","bold":true},{"text":"You can only change characters during an active game.","color":"gray","bold":false}]')
$playerDispatchLines.Add("execute if score grim_editor_reveal_started botc_patch matches 1 unless score @s botc_grim_edit_mode matches 1..2 run return run function botc_patch:grim/editor/locked")
$playerDispatchLines.Add("execute unless score grim_editor_game_captured botc_patch matches 1 run function botc_patch:grim/editor/capture_game")
$playerDispatchLines.Add('execute unless score grim_editor_game_captured botc_patch matches 1 run return run tellraw @s [{"text":"! ","color":"red","bold":true},{"text":"The player list from the start of the game is not available yet.","color":"gray","bold":false}]')
$playerDispatchLines.Add("function botc_patch:grim/editor/refresh_live_roles")
$playerDispatchLines.Add("function botc_patch:grim/editor/player_labels/prepare")
for ($seatCount = 0; $seatCount -le 15; $seatCount++) {
    $playerDispatchLines.Add("execute if score @s botc_grim_edit_mode matches 0 if score grim_editor_dialog_size botc_patch matches $seatCount run function botc_patch:grim/editor/player_dialog/count_$seatCount with storage botc_patch:grim editor.player_labels")
    $playerDispatchLines.Add("execute if score @s botc_grim_edit_mode matches 1 if score grim_editor_dialog_size botc_patch matches $seatCount run function botc_patch:grim/editor/summoner/player_dialog/count_$seatCount with storage botc_patch:grim editor.player_labels")
}
$playerDispatchLines.Add("execute if score @s botc_grim_edit_mode matches 0 unless score grim_editor_dialog_size botc_patch matches 0..15 run function botc_patch:grim/editor/player_dialog/count_15 with storage botc_patch:grim editor.player_labels")
$playerDispatchLines.Add("execute if score @s botc_grim_edit_mode matches 1 unless score grim_editor_dialog_size botc_patch matches 0..15 run function botc_patch:grim/editor/summoner/player_dialog/count_15 with storage botc_patch:grim editor.player_labels")
Write-Lines -Path (Join-Path $OutputRoot "player_dialog.mcfunction") -Lines $playerDispatchLines

for ($seatCount = 0; $seatCount -le 15; $seatCount++) {
    $actions = [System.Collections.Generic.List[string]]::new()
    if ($seatCount -gt 0) {
        $actions.Add('{label:{text:"Assign Demon Tonight",color:"#ff5555",bold:true},tooltip:{text:"Choose any supported Demon for a player during the night.",color:"gray"},action:{type:"run_command",command:"/botc grimoire choose_demon"}}')
    }
    for ($seat = 1; $seat -le $seatCount; $seat++) {
        $actions.Add('{label:{text:"$(p' + $seat + '_glyph)",font:"botc_patch:role_icons",color:"white",extra:[{text:" $(p' + $seat + '_name)",font:"minecraft:default",color:"white"},{text:" ($(p' + $seat + '_role))",font:"minecraft:default",color:"$(p' + $seat + '_color)"}]},tooltip:{text:"Seat ' + $seat + '",color:"gray"},action:{type:"run_command",command:"/botc grimoire edit_seat ' + $seat + '"}}')
    }

    if ($actions.Count -eq 0) {
        $actions.Add('{label:{text:"No seated players",color:"gray"},action:{type:"run_command",command:"/botc grimoire confirm"}}')
    }

    $macroPrefix = if ($seatCount -gt 0) { '$' } else { '' }
    $line = $macroPrefix + 'dialog show @s {type:"multi_action",title:"Change Characters",body:{type:"plain_message",contents:{text:"Pick a player to edit before starting Reveal Grimoire.",color:"gray"},width:360},columns:3,after_action:"wait_for_response",actions:[' + ($actions -join ',') + '],exit_action:{label:"Back",action:{type:"run_command",command:"/botc grimoire confirm"}}}'
    $lines = New-Header "Player-name dialog for $seatCount occupied seats."
    $lines.Add($line)
    Write-Lines -Path (Join-Path $PlayerDialogRoot "count_$seatCount.mcfunction") -Lines $lines

    $summonerActions = [System.Collections.Generic.List[string]]::new()
    for ($seat = 1; $seat -le $seatCount; $seat++) {
        $summonerActions.Add('{label:{text:"$(p' + $seat + '_glyph)",font:"botc_patch:role_icons",color:"white",extra:[{text:" $(p' + $seat + '_name)",font:"minecraft:default",color:"white"},{text:" ($(p' + $seat + '_role))",font:"minecraft:default",color:"$(p' + $seat + '_color)"}]},tooltip:{text:"Seat ' + $seat + '",color:"gray"},action:{type:"run_command",command:"/botc grimoire edit_seat ' + $seat + '"}}')
    }
    if ($summonerActions.Count -eq 0) {
        $summonerActions.Add('{label:{text:"No seated players",color:"gray"},action:{type:"run_command",command:"/botc grimoire change_characters"}}')
    }
    $summonerMacroPrefix = if ($seatCount -gt 0) { '$' } else { '' }
    $summonerLine = $summonerMacroPrefix + 'dialog show @s {type:"multi_action",title:{text:"Assign Demon Tonight - Choose Player",color:"red",bold:true},body:{type:"plain_message",contents:{text:"Choose the player who becomes an evil Demon now.",color:"gray"},width:380},columns:3,after_action:"wait_for_response",actions:[' + ($summonerActions -join ',') + '],exit_action:{label:"Back",action:{type:"run_command",command:"/botc grimoire change_characters"}}}'
    $summonerLines = New-Header "Trusted nightly Demon-assignment player dialog for $seatCount occupied seats."
    $summonerLines.Add($summonerLine)
    Write-Lines -Path (Join-Path $SummonerPlayerDialogRoot "count_$seatCount.mcfunction") -Lines $summonerLines
}

$characterDispatchLines = New-Header "Builds and shows the current-script character picker for the selected player."
$characterDispatchLines.Add("dialog clear @s")
$characterDispatchLines.Add('execute unless score phase game_data matches 1.. run return run tellraw @s [{"text":"! ","color":"red","bold":true},{"text":"You can only change characters during an active game.","color":"gray","bold":false}]')
$characterDispatchLines.Add("execute if score grim_editor_reveal_started botc_patch matches 1 unless score @s botc_grim_edit_mode matches 1..2 run return run function botc_patch:grim/editor/locked")
$characterDispatchLines.Add('execute if score @s botc_grim_edit_mode matches 1..2 unless score phase game_data matches 4 run return run tellraw @s [{"text":"! ","color":"red","bold":true},{"text":"You can only assign a Demon during the night.","color":"gray","bold":false}]')
$characterDispatchLines.Add("function botc_patch:grim/editor/refresh_live_roles")
$characterDispatchLines.Add("function botc_patch:grim/editor/roles/build")
$characterDispatchLines.Add("function botc_patch:grim/editor/roles/prepare_args")
$characterDispatchLines.Add("function botc_patch:grim/editor/prepare_selected")
$characterDispatchLines.Add("execute unless score @s botc_grim_edit_valid matches 1 run return run function botc_patch:grim/editor/invalid_seat")
for ($roleCount = 0; $roleCount -le 30; $roleCount++) {
    $characterDispatchLines.Add("execute if score @s botc_grim_edit_mode matches 0 if score grim_editor_role_count botc_patch matches $roleCount run function botc_patch:grim/editor/character_dialog/count_$roleCount with storage botc_patch:grim editor.dialog")
    $characterDispatchLines.Add("execute if score @s botc_grim_edit_mode matches 1 if score grim_editor_role_count botc_patch matches $roleCount run function botc_patch:grim/editor/summoner/demon_dialog/count_$roleCount with storage botc_patch:grim editor.dialog")
    $characterDispatchLines.Add("execute if score @s botc_grim_edit_mode matches 2 if score grim_editor_role_count botc_patch matches $roleCount run function botc_patch:grim/editor/summoner/minion_dialog/count_$roleCount with storage botc_patch:grim editor.dialog")
}
$characterDispatchLines.Add("execute if score @s botc_grim_edit_mode matches 0 unless score grim_editor_role_count botc_patch matches 0..30 run function botc_patch:grim/editor/character_dialog/count_30 with storage botc_patch:grim editor.dialog")
$characterDispatchLines.Add("execute if score @s botc_grim_edit_mode matches 1 unless score grim_editor_role_count botc_patch matches 0..30 run function botc_patch:grim/editor/summoner/demon_dialog/count_30 with storage botc_patch:grim editor.dialog")
$characterDispatchLines.Add("execute if score @s botc_grim_edit_mode matches 2 unless score grim_editor_role_count botc_patch matches 0..30 run function botc_patch:grim/editor/summoner/minion_dialog/count_30 with storage botc_patch:grim editor.dialog")
Write-Lines -Path (Join-Path $OutputRoot "character_dialog.mcfunction") -Lines $characterDispatchLines

for ($roleCount = 0; $roleCount -le 30; $roleCount++) {
    $actions = [System.Collections.Generic.List[string]]::new()
    $actions.Add('{label:{text:"Set Good",color:"#0000aa",bold:true},tooltip:{text:"Show this player as good during the Grimoire reveal.",color:"gray"},action:{type:"run_command",command:"/botc grimoire set_good"}}')
    $actions.Add('{label:{text:"Set Evil",color:"#aa0000",bold:true},tooltip:{text:"Show this player as evil during the Grimoire reveal.",color:"gray"},action:{type:"run_command",command:"/botc grimoire set_evil"}}')
    for ($roleIndex = 1; $roleIndex -le $roleCount; $roleIndex++) {
        $actions.Add('{label:{text:"$(r' + $roleIndex + '_glyph)",font:"botc_patch:role_icons",color:"white",extra:[{text:" $(r' + $roleIndex + '_name)",font:"minecraft:default",color:"$(r' + $roleIndex + '_color)"}]},action:{type:"run_command",command:"/botc grimoire set_character $(r' + $roleIndex + '_id)"}}')
    }

    $body = '[{type:"plain_message",contents:[{text:"CURRENT CHARACTER\n",font:"minecraft:default",color:"dark_gray",bold:true},{text:"$(current_role_glyph)",font:"botc_patch:role_icons",color:"white"},{text:" $(current_role_name)",font:"minecraft:default",color:"$(current_alignment_color)",bold:true,underlined:true},{text:"  |  ",color:"dark_gray"},{text:"$(current_alignment_name)",color:"$(current_alignment_color)",bold:true}],width:360},{type:"plain_message",contents:[{text:"Townsfolk",color:"#55aaff"},{text:" | ",color:"dark_gray"},{text:"Outsiders",color:"#55ffff"},{text:" | ",color:"dark_gray"},{text:"Minions",color:"#ffaa00"},{text:" | ",color:"dark_gray"},{text:"Demons",color:"#ff5555"}],width:360},{type:"plain_message",contents:{text:"Pick a character from the current script, or change only the alignment shown during the reveal.",color:"gray"},width:360}]'
    $title = '[{text:"Edit ",color:"gray"},{text:"$(player_name)",color:"white"},{text:" - ",color:"dark_gray"},{text:"$(current_role_name)",color:"$(current_alignment_color)",bold:true}]'
    $line = '$dialog show @s {type:"multi_action",title:' + $title + ',body:' + $body + ',columns:2,after_action:"wait_for_response",actions:[' + ($actions -join ',') + '],exit_action:{label:"Back",action:{type:"run_command",command:"/botc grimoire change_characters"}}}'
    $lines = New-Header "Character dialog for $roleCount current-script roles."
    $lines.Add($line)
    Write-Lines -Path (Join-Path $CharacterDialogRoot "count_$roleCount.mcfunction") -Lines $lines

    $summonerActions = [System.Collections.Generic.List[string]]::new()
    $summonerActions.Add('{label:{text:"Set Good",color:"#0000aa",bold:true},tooltip:{text:"Show this player as good during the Grimoire reveal.",color:"gray"},action:{type:"run_command",command:"/botc grimoire set_good"}}')
    $summonerActions.Add('{label:{text:"Set Evil",color:"#aa0000",bold:true},tooltip:{text:"Show this player as evil during the Grimoire reveal.",color:"gray"},action:{type:"run_command",command:"/botc grimoire set_evil"}}')
    for ($roleIndex = 1; $roleIndex -le $roleCount; $roleIndex++) {
        $summonerActions.Add('{label:{text:"$(r' + $roleIndex + '_glyph)",font:"botc_patch:role_icons",color:"white",extra:[{text:" $(r' + $roleIndex + '_name)",font:"minecraft:default",color:"$(r' + $roleIndex + '_color)"}]},action:{type:"run_command",command:"/botc grimoire set_character $(r' + $roleIndex + '_id)"}}')
    }
    $summonerTitle = '[{text:"Assign Demon - ",color:"red",bold:true},{text:"$(player_name)",color:"white",bold:true}]'
    $summonerCurrent = '{type:"plain_message",contents:[{text:"CURRENT CHARACTER\n",color:"dark_gray",bold:true},{text:"$(current_role_glyph)",font:"botc_patch:role_icons",color:"white"},{text:" $(current_role_name)",color:"$(current_alignment_color)",bold:true},{text:"  |  ",color:"dark_gray"},{text:"$(current_alignment_name)",color:"$(current_alignment_color)",bold:true}],width:400}'
    $summonerMacro = '$'
    $demonBody = '[' + $summonerCurrent + ',{type:"plain_message",contents:{text:"Choose the Demon this player becomes. They become evil immediately. Choosing Lil'' Monsta lets you choose their Minion character next.",color:"gray"},width:400}]'
    $demonLine = $summonerMacro + 'dialog show @s {type:"multi_action",title:' + $summonerTitle + ',body:' + $demonBody + ',columns:3,after_action:"wait_for_response",actions:[' + ($summonerActions -join ',') + '],exit_action:{label:"Back",action:{type:"run_command",command:"/botc grimoire change_characters"}}}'
    $demonLines = New-Header "Trusted nightly full Demon dialog for $roleCount roles."
    $demonLines.Add($demonLine)
    Write-Lines -Path (Join-Path $SummonerDemonDialogRoot "count_$roleCount.mcfunction") -Lines $demonLines

    $minionBody = '[' + $summonerCurrent + ',{type:"plain_message",contents:{text:"Choose this player''s evil Minion character. Summoner, Marionette, and Minions already in play are unavailable.",color:"gray"},width:400}]'
    $minionLine = $summonerMacro + 'dialog show @s {type:"multi_action",title:' + $summonerTitle + ',body:' + $minionBody + ',columns:3,after_action:"wait_for_response",actions:[' + ($summonerActions -join ',') + '],exit_action:{label:"Back",action:{type:"run_command",command:"/botc grimoire choose_demon"}}}'
    $minionLines = New-Header "Trusted Lil' Monsta direct-Minion dialog for $roleCount legal roles."
    $minionLines.Add($minionLine)
    Write-Lines -Path (Join-Path $SummonerMinionDialogRoot "count_$roleCount.mcfunction") -Lines $minionLines
}

$summonerCheckLines = New-Header "Retains a safe compatibility target after retiring the automatic third-night Summoner prompt."
$summonerCheckLines.Add('return 0')
Write-Lines -Path (Join-Path $OutputRoot "summoner/check.mcfunction") -Lines $summonerCheckLines

$demonBeginLines = New-Header "Lets one Storyteller explicitly open the trusted full Demon catalog during any night."
$demonBeginLines.Add('dialog clear @s')
$demonBeginLines.Add('execute unless entity @s[tag=storyteller] run return 0')
$demonBeginLines.Add('execute unless score phase game_data matches 4 run return run tellraw @s [{"text":"! ","color":"red","bold":true},{"text":"You can only assign a Demon during the night.","color":"gray","bold":false}]')
$demonBeginLines.Add('scoreboard players set @s botc_grim_edit_mode 1')
$demonBeginLines.Add('scoreboard players reset @s botc_grim_edit_seat')
$demonBeginLines.Add('scoreboard players reset @s botc_grim_edit_role')
$demonBeginLines.Add('scoreboard players reset @s botc_grim_edit_alignment')
$demonBeginLines.Add('function botc_patch:grim/editor/player_dialog')
Write-Lines -Path (Join-Path $DemonRoot "begin.mcfunction") -Lines $demonBeginLines

$summonerBeginLilLines = New-Header "Branches a trusted Lil' Monsta choice into the legal direct-Minion catalog without assigning role 132."
$summonerBeginLilLines.Add('execute unless score phase game_data matches 4 run return run tellraw @s [{"text":"! ","color":"red","bold":true},{"text":"You can only assign a Demon during the night.","color":"gray","bold":false}]')
$summonerBeginLilLines.Add('scoreboard players set @s botc_grim_edit_mode 2')
$summonerBeginLilLines.Add('scoreboard players set @s botc_grim_edit_valid 1')
$summonerBeginLilLines.Add('function botc_patch:grim/editor/character_dialog')
Write-Lines -Path (Join-Path $OutputRoot "summoner/begin_lil_monsta.mcfunction") -Lines $summonerBeginLilLines

$summonerValidateTargetLines = New-Header "Validates that the selected trusted Demon target is still online before any state changes."
$summonerValidateTargetLines.Add('scoreboard players set grim_editor_summoner_target_online botc_patch 0')
for ($seat = 1; $seat -le 15; $seat++) {
    $target = "@a[tag=!storyteller,tag=!spectator,scores={id=$seat},limit=1]"
    $summonerValidateTargetLines.Add("execute if score @s botc_grim_edit_seat matches $seat if entity $target run scoreboard players set grim_editor_summoner_target_online botc_patch 1")
}
Write-Lines -Path (Join-Path $OutputRoot "summoner/validate_target.mcfunction") -Lines $summonerValidateTargetLines

$summonerMetadataLines = New-Header "Adds one trusted full-catalog role to private script metadata and rebuilds Storyteller reminders/night order."
$summonerMetadataLines.Add('$execute unless data storage ct:script formatted_characters[{id:"$(script_id)"}] run data modify storage ct:script formatted_characters append value {id:"$(script_id)"}')
$summonerMetadataLines.Add('$execute unless data storage ct:script current_script[{id:"$(script_id)"}] run data modify storage ct:script current_script append value {id:"$(script_id)"}')
$summonerMetadataLines.Add('$execute unless data storage ct:script in_characters{$(storage_category):["$(role)"]} run data modify storage ct:script in_characters.$(storage_category) append value "$(role)"')
$summonerMetadataLines.Add('data remove storage ct:script order_stored')
$summonerMetadataLines.Add('data modify storage ct:script order_stored set from storage ct:script current_script')
$summonerMetadataLines.Add('data remove storage ct:script night_order')
$summonerMetadataLines.Add('function ct:admin/setup/night_order')
$summonerMetadataLines.Add('data remove storage ct:script reminders_stored')
$summonerMetadataLines.Add('data modify storage ct:script reminders_stored set from storage ct:script current_script')
$summonerMetadataLines.Add('data remove storage ct:script in_reminders')
$summonerMetadataLines.Add('data remove storage ct:script reminder_img')
$summonerMetadataLines.Add('function ct:admin/setup/reminder_tokens')
$summonerMetadataLines.Add('execute as @a[tag=storyteller] run function ct:admin/give_script')
Write-Lines -Path (Join-Path $OutputRoot "summoner/add_metadata.mcfunction") -Lines $summonerMetadataLines

$summonerApplyDemonLines = New-Header "Applies one validated full-catalog Demon during the night and resolves any pending no-Demon workflow."
$summonerApplyDemonLines.Add('execute unless score phase game_data matches 4 run return run tellraw @s [{"text":"! ","color":"red","bold":true},{"text":"You can only assign a Demon during the night.","color":"gray","bold":false}]')
$summonerApplyDemonLines.Add('function botc_patch:grim/editor/summoner/validate_target')
$summonerApplyDemonLines.Add('execute unless score grim_editor_summoner_target_online botc_patch matches 1 run return run tellraw @s [{"text":"! ","color":"red","bold":true},{"text":"That player must be online before you can change their character.","color":"gray","bold":false}]')
$summonerApplyDemonLines.Add('$function botc_patch:grim/editor/summoner/add_metadata {role:"$(role)",script_id:"$(script_id)",storage_category:"demons"}')
$summonerApplyDemonLines.Add('$function botc_patch:grim/editor/summoner/apply_live {role:"$(role)",score:$(score),name:"$(name)",color:"$(color)",category:"demon"}')
Write-Lines -Path (Join-Path $OutputRoot "summoner/apply_demon.mcfunction") -Lines $summonerApplyDemonLines

$summonerApplyMinionLines = New-Header "Applies the validated direct Minion selected for a trusted Lil' Monsta assignment."
$summonerApplyMinionLines.Add('execute unless score phase game_data matches 4 run return run tellraw @s [{"text":"! ","color":"red","bold":true},{"text":"You can only assign a Demon during the night.","color":"gray","bold":false}]')
$summonerApplyMinionLines.Add('function botc_patch:grim/editor/summoner/validate_target')
$summonerApplyMinionLines.Add('execute unless score grim_editor_summoner_target_online botc_patch matches 1 run return run tellraw @s [{"text":"! ","color":"red","bold":true},{"text":"That player must be online before you can change their character.","color":"gray","bold":false}]')
$summonerApplyMinionLines.Add('$function botc_patch:grim/editor/summoner/add_metadata {role:"$(role)",script_id:"$(script_id)",storage_category:"minions"}')
$summonerApplyMinionLines.Add(('function botc_patch:grim/editor/summoner/add_metadata {{role:"lil_monsta",script_id:"{0}",storage_category:"demons"}}' -f $lilMonsta.ScriptId))
$summonerApplyMinionLines.Add('scoreboard players set draft_lil_monsta_active botc_patch 1')
$summonerApplyMinionLines.Add('$function botc_patch:grim/editor/summoner/apply_live {role:"$(role)",score:$(score),name:"$(name)",color:"$(color)",category:"minion"}')
Write-Lines -Path (Join-Path $OutputRoot "summoner/apply_minion.mcfunction") -Lines $summonerApplyMinionLines

$summonerApplyLiveLines = New-Header "Commits one trusted nightly evil role to live, Grimoire, and private player state."
$summonerApplyLiveLines.Add('execute unless score phase game_data matches 4 run return run tellraw @s [{"text":"! ","color":"red","bold":true},{"text":"You can only assign a Demon during the night.","color":"gray","bold":false}]')
$summonerApplyLiveLines.Add('scoreboard players set grim_editor_summoner_target_online botc_patch 0')
for ($seat = 1; $seat -le 15; $seat++) {
    $target = "@a[tag=!storyteller,tag=!spectator,scores={id=$seat},limit=1]"
    $summonerApplyLiveLines.Add("execute if score @s botc_grim_edit_seat matches $seat if entity $target run scoreboard players set grim_editor_summoner_target_online botc_patch 1")
}
$summonerApplyLiveLines.Add('execute unless score grim_editor_summoner_target_online botc_patch matches 1 run return run tellraw @s [{"text":"! ","color":"red","bold":true},{"text":"That player must be online before you can change their character.","color":"gray","bold":false}]')
$summonerApplyLiveLines.Add('$scoreboard players set @s botc_grim_edit_role $(score)')
$summonerApplyLiveLines.Add('scoreboard players set @s botc_grim_edit_alignment 2')
$summonerApplyLiveLines.Add('function botc_patch:grim/editor/apply_selected')
for ($seat = 1; $seat -le 15; $seat++) {
    $target = "@a[tag=!storyteller,tag=!spectator,scores={id=$seat},limit=1]"
    $summonerApplyLiveLines.Add(('$execute if score @s botc_grim_edit_seat matches {0} run scoreboard players set {1} role $(score)' -f $seat, $target))
    foreach ($category in @('town', 'outsider', 'minion', 'demon')) {
        $summonerApplyLiveLines.Add(('execute if score @s botc_grim_edit_seat matches {0} run tag {1} remove {2}' -f $seat, $target, $category))
    }
    $summonerApplyLiveLines.Add(('$execute if score @s botc_grim_edit_seat matches {0} run tag {1} add $(category)' -f $seat, $target))
    $summonerApplyLiveLines.Add(('$execute if score @s botc_grim_edit_seat matches {0} run fmvariable set p{0}_role false $(role)' -f $seat))
    $summonerApplyLiveLines.Add(('execute if score @s botc_grim_edit_seat matches {0} run scoreboard players set grim_editor_seat_{0}_alignment botc_patch 2' -f $seat))
    $summonerApplyLiveLines.Add(('$execute if score @s botc_grim_edit_seat matches {0} run scoreboard players set grim_seat_{0}_role botc_patch $(score)' -f $seat))
    $summonerApplyLiveLines.Add(('execute if score @s botc_grim_edit_seat matches {0} run scoreboard players set grim_seat_{0}_alignment botc_patch 2' -f $seat))
    $summonerApplyLiveLines.Add(('$execute if score @s botc_grim_edit_seat matches {0} run tellraw {1} [{{"text":"You are now the ","color":"gray"}},{{"text":"$(name)","color":"$(color)","bold":true}},{{"text":". You are evil.","color":"red","bold":false}}]' -f $seat, $target))
}
$summonerApplyLiveLines.Add('function botc_patch:wraith/sync_roles')
$summonerApplyLiveLines.Add('scoreboard players set draft_summoner_resolution_pending botc_patch 0')
$summonerApplyLiveLines.Add('scoreboard players set @s botc_grim_edit_mode 0')
$summonerApplyLiveLines.Add('scoreboard players set @s botc_grim_edit_valid 1')
$summonerApplyLiveLines.Add('dialog clear @s')
$summonerApplyLiveLines.Add('$tellraw @s [{"text":"\u2714 ","color":"green","bold":true},{"text":"Demon assigned: ","color":"gray","bold":false},{"text":"$(name)","color":"$(color)","bold":true},{"text":" is now in play and the selected player is evil.","color":"gray","bold":false}]')
Write-Lines -Path (Join-Path $OutputRoot "summoner/apply_live.mcfunction") -Lines $summonerApplyLiveLines

if ($Check) {
    Write-Host "Reveal Grimoire character editor outputs are current for $($roles.Count) trusted roles."
} else {
    Write-Host "Generated Reveal Grimoire character editor for $($roles.Count) trusted roles."
}
