Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$RepoRoot = Split-Path -Parent $PSScriptRoot
$SybillianRolePath = Join-Path $RepoRoot "..\data\resources\datapack\required\ct\data\ct\function\admin\setup\set_from_menu.mcfunction"
$SybillianCharactersPath = Join-Path $RepoRoot "..\data\resources\datapack\required\ct\data\ct\function\admin\setup\characters.mcfunction"
$RoleIconPath = Join-Path $RepoRoot "Jays-Patch/role-icons.json"
$RoleCatalogHelper = Join-Path $RepoRoot "tools/lib/sybillian-role-catalog.ps1"
$OutputRoot = Join-Path $RepoRoot "Jays-Patch/datapack/data/botc_patch/function/grim/editor"
$PlayerDialogRoot = Join-Path $OutputRoot "player_dialog"
$PlayerLabelsRoot = Join-Path $OutputRoot "player_labels"
$CharacterDialogRoot = Join-Path $OutputRoot "character_dialog"
$RolesRoot = Join-Path $OutputRoot "roles"

if (-not (Test-Path -LiteralPath $SybillianRolePath -PathType Leaf)) {
    throw "Missing Sybillian role table: $SybillianRolePath"
}

if (-not (Test-Path -LiteralPath $RoleIconPath -PathType Leaf)) {
    throw "Missing role icon table: $RoleIconPath"
}

$roleIconConfig = Get-Content -LiteralPath $RoleIconPath -Raw | ConvertFrom-Json
$roleIconSet = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
foreach ($roleIcon in @($roleIconConfig.roles)) {
    [void] $roleIconSet.Add([string] $roleIcon)
}

. $RoleCatalogHelper
$roles = @(Get-SybillianRoleCatalog -SetFromMenuPath $SybillianRolePath -CharactersPath $SybillianCharactersPath)

$missingIcons = @($roles | Where-Object { -not $roleIconSet.Contains($_.Role) } | Select-Object -ExpandProperty Role)
if ($missingIcons.Count -gt 0) {
    throw "Missing role icons for editor roles: $($missingIcons -join ', ')"
}

$utf8NoBom = [System.Text.UTF8Encoding]::new($false)

function Write-Lines {
    param(
        [string] $Path,
        [System.Collections.Generic.List[string]] $Lines
    )

    New-Item -ItemType Directory -Path (Split-Path -Parent $Path) -Force | Out-Null
    [System.IO.File]::WriteAllText($Path, ($Lines -join [Environment]::NewLine) + [Environment]::NewLine, $utf8NoBom)
}

function New-Header {
    param([string] $Responsibility)

    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add("# Generated by tools/generate-grim-character-editor.ps1.")
    $lines.Add("# Do not hand-edit this file; update the generator and regenerate.")
    $lines.Add("# $Responsibility")
    return ,$lines
}

New-Item -ItemType Directory -Path $PlayerDialogRoot -Force | Out-Null
New-Item -ItemType Directory -Path $PlayerLabelsRoot -Force | Out-Null
New-Item -ItemType Directory -Path $CharacterDialogRoot -Force | Out-Null
New-Item -ItemType Directory -Path $RolesRoot -Force | Out-Null

$initLines = New-Header "Builds the trusted role catalog from Sybillian's role-score table."
$initLines.Add("data remove storage botc_patch:grim editor.catalog")
$initLines.Add("data remove storage botc_patch:grim editor.score_catalog")
$initLines.Add('data modify storage botc_patch:grim editor.catalog.none set value {id:"none",name:"None",score:0,alignment:0,color:"#aaaaaa"}')
$initLines.Add('data modify storage botc_patch:grim editor.score_catalog.s0 set from storage botc_patch:grim editor.catalog.none')
foreach ($role in $roles) {
    $entry = '{{id:"{0}",name:"{1}",score:{2},alignment:{3},color:"{4}"}}' -f $role.Role, $role.Name, $role.Id, $role.Alignment, $role.Color
    $initLines.Add(('data modify storage botc_patch:grim editor.catalog.{0} set value {1}' -f $role.Role, $entry))
    $initLines.Add(('data modify storage botc_patch:grim editor.score_catalog.s{0} set from storage botc_patch:grim editor.catalog.{1}' -f $role.Id, $role.Role))
}
Write-Lines -Path (Join-Path $RolesRoot "init.mcfunction") -Lines $initLines

$appendLines = New-Header "Appends one trusted current-script role to the editor list."
$appendLines.Add('$data modify storage botc_patch:grim editor.roles append from storage botc_patch:grim editor.catalog.$(id)')
Write-Lines -Path (Join-Path $RolesRoot "append.mcfunction") -Lines $appendLines

$buildLines = New-Header "Flattens only the current Sybillian script into one ordered editor list."
$buildLines.Add("data modify storage botc_patch:grim editor.roles set value []")
$buildLines.Add("data remove storage botc_patch:grim editor.append")
$scriptSlots = @(
    [pscustomobject]@{ Name = "town"; Count = 15 },
    [pscustomobject]@{ Name = "outsiders"; Count = 5 },
    [pscustomobject]@{ Name = "minions"; Count = 5 },
    [pscustomobject]@{ Name = "demons"; Count = 5 }
)
foreach ($group in $scriptSlots) {
    for ($index = 0; $index -lt $group.Count; $index++) {
        $path = "in_characters.$($group.Name)[$index]"
        $buildLines.Add("execute if data storage ct:script $path run data modify storage botc_patch:grim editor.append.id set from storage ct:script $path")
        $buildLines.Add("execute if data storage ct:script $path run function botc_patch:grim/editor/roles/append with storage botc_patch:grim editor.append")
    }
}
$buildLines.Add("execute store result score grim_editor_role_count botc_patch run data get storage botc_patch:grim editor.roles")
Write-Lines -Path (Join-Path $RolesRoot "build.mcfunction") -Lines $buildLines

$prepareArgsLines = New-Header "Copies the role list into flat macro arguments for generated dialogs."
$prepareArgsLines.Add('data modify storage botc_patch:grim editor.dialog set value {player_name:"Unknown",current_role:"none",current_role_name:"None",current_alignment_name:"Unknown",current_alignment_color:"#aaaaaa"}')
for ($index = 0; $index -lt 30; $index++) {
    $number = $index + 1
    foreach ($field in @("id", "name", "color")) {
        $prepareArgsLines.Add("execute if data storage botc_patch:grim editor.roles[$index].$field run data modify storage botc_patch:grim editor.dialog.r$($number)_$field set from storage botc_patch:grim editor.roles[$index].$field")
    }
}
Write-Lines -Path (Join-Path $RolesRoot "prepare_args.mcfunction") -Lines $prepareArgsLines

$prepareCurrentLines = New-Header "Resolves the selected snapshot role through the trusted score catalog."
$prepareCurrentLines.Add('$data modify storage botc_patch:grim editor.dialog.current_role set from storage botc_patch:grim editor.score_catalog.s$(score).id')
$prepareCurrentLines.Add('$data modify storage botc_patch:grim editor.dialog.current_role_name set from storage botc_patch:grim editor.score_catalog.s$(score).name')
Write-Lines -Path (Join-Path $RolesRoot "prepare_current.mcfunction") -Lines $prepareCurrentLines

$validateLines = New-Header "Validates a requested character against both the trusted catalog and current script."
foreach ($role in $roles) {
    $validateLines.Add(('execute if data storage botc_patch:grim editor.request{{role:"{0}"}} if data storage ct:script in_characters{{{1}:["{0}"]}} run function botc_patch:grim/editor/apply_character {{role:"{0}",score:{2},alignment:{3}}}' -f $role.Role, $role.StorageCategory, $role.Id, $role.Alignment))
}
Write-Lines -Path (Join-Path $RolesRoot "validate_requested.mcfunction") -Lines $validateLines

$clearGameLines = New-Header "Clears cached live-game character edits only when the game returns to setup."
$clearGameLines.Add("scoreboard players set grim_editor_game_captured botc_patch 0")
$clearGameLines.Add("scoreboard players set grim_editor_reveal_started botc_patch 0")
$clearGameLines.Add("scoreboard players set grim_editor_dialog_size botc_patch 0")
$clearGameLines.Add("scoreboard players reset @a botc_grim_edit_seat")
$clearGameLines.Add("scoreboard players reset @a botc_grim_edit_role")
$clearGameLines.Add("scoreboard players reset @a botc_grim_edit_alignment")
$clearGameLines.Add("scoreboard players reset @a botc_grim_edit_valid")
$clearGameLines.Add("data remove storage botc_patch:grim editor.roles")
$clearGameLines.Add("data remove storage botc_patch:grim editor.dialog")
$clearGameLines.Add("data remove storage botc_patch:grim editor.player_labels")
$clearGameLines.Add("data remove storage botc_patch:grim editor.player_label_lookup")
$clearGameLines.Add("data remove storage botc_patch:grim editor.request")
for ($seat = 1; $seat -le 15; $seat++) {
    $clearGameLines.Add("scoreboard players set grim_editor_seat_$($seat)_known botc_patch 0")
    $clearGameLines.Add("scoreboard players set grim_editor_seat_$($seat)_role botc_patch 0")
    $clearGameLines.Add("scoreboard players set grim_editor_seat_$($seat)_alignment botc_patch 0")
    $clearGameLines.Add("scoreboard players set grim_editor_seat_$($seat)_override botc_patch 0")
}
Write-Lines -Path (Join-Path $OutputRoot "clear_game.mcfunction") -Lines $clearGameLines

$refreshLines = New-Header "Refreshes non-overridden cached roles from online seated players."
for ($seat = 1; $seat -le 15; $seat++) {
    $target = "@a[tag=!storyteller,tag=!spectator,scores={id=$seat},limit=1]"
    $prefix = "execute if score grim_editor_seat_$($seat)_override botc_patch matches 0 if entity $target"
    $refreshLines.Add("$prefix run scoreboard players set grim_editor_seat_$($seat)_known botc_patch 1")
    $refreshLines.Add("$prefix run scoreboard players operation grim_editor_seat_$($seat)_role botc_patch = $target role")
    $refreshLines.Add("$prefix run scoreboard players set grim_editor_seat_$($seat)_alignment botc_patch 0")
    $refreshLines.Add("$prefix if score $target role matches 1..17 run scoreboard players set grim_editor_seat_$($seat)_alignment botc_patch 1")
    $refreshLines.Add("$prefix if score $target role matches 23..97 run scoreboard players set grim_editor_seat_$($seat)_alignment botc_patch 1")
    $refreshLines.Add("$prefix if score $target role matches 18..22 run scoreboard players set grim_editor_seat_$($seat)_alignment botc_patch 2")
    $refreshLines.Add("$prefix if score $target role matches 98..137 run scoreboard players set grim_editor_seat_$($seat)_alignment botc_patch 2")
}
Write-Lines -Path (Join-Path $OutputRoot "refresh_live_roles.mcfunction") -Lines $refreshLines

$playerLabelPrepareLines = New-Header "Prepares reusable Player (Role) labels from the current server-authoritative editor state."
$playerLabelPrepareLines.Add("data remove storage botc_patch:grim editor.player_labels")
for ($seat = 1; $seat -le 15; $seat++) {
    $playerLabelPrepareLines.Add(('data modify storage botc_patch:grim editor.player_labels.p{0}_name set value "Seat {0}"' -f $seat))
    $playerLabelPrepareLines.Add(('data modify storage botc_patch:grim editor.player_labels.p{0}_role set value "Unknown"' -f $seat))
    $playerLabelPrepareLines.Add(('data modify storage botc_patch:grim editor.player_labels.p{0}_color set value "#aaaaaa"' -f $seat))
    $playerLabelPrepareLines.Add(('execute if data storage ct:players players.p{0} unless data storage ct:players players{{p{0}:"Nobody!"}} run data modify storage botc_patch:grim editor.player_labels.p{0}_name set from storage ct:players players.p{0}' -f $seat))
    $playerLabelPrepareLines.Add(('data modify storage botc_patch:grim editor.player_label_lookup set value {{seat:{0},score:0}}' -f $seat))
    $playerLabelPrepareLines.Add(('execute if score grim_editor_seat_{0}_known botc_patch matches 1 store result storage botc_patch:grim editor.player_label_lookup.score int 1 run scoreboard players get grim_editor_seat_{0}_role botc_patch' -f $seat))
    $playerLabelPrepareLines.Add(('execute if score grim_editor_seat_{0}_known botc_patch matches 1 run function botc_patch:grim/editor/player_labels/prepare_role with storage botc_patch:grim editor.player_label_lookup' -f $seat))
}
Write-Lines -Path (Join-Path $PlayerLabelsRoot "prepare.mcfunction") -Lines $playerLabelPrepareLines

$playerLabelRoleLines = New-Header "Resolves one current editor role into its trusted display name and category color."
$playerLabelRoleLines.Add('$data modify storage botc_patch:grim editor.player_labels.p$(seat)_role set from storage botc_patch:grim editor.score_catalog.s$(score).name')
$playerLabelRoleLines.Add('$data modify storage botc_patch:grim editor.player_labels.p$(seat)_color set from storage botc_patch:grim editor.score_catalog.s$(score).color')
Write-Lines -Path (Join-Path $PlayerLabelsRoot "prepare_role.mcfunction") -Lines $playerLabelRoleLines

$captureLines = New-Header "Captures the active game's server-authoritative seats before any reveal edits."
$captureLines.Add("execute unless data storage ct:players players.p1 run return 0")
$captureLines.Add('execute if data storage ct:players players{p1:"Nobody!"} run return 0')
$captureLines.Add("function botc_patch:grim/editor/clear_game")
$captureLines.Add("function botc_patch:grim/editor/refresh_live_roles")
for ($seat = 1; $seat -le 15; $seat++) {
    $captureLines.Add(('execute if data storage ct:players players.p{0} unless data storage ct:players players{{p{0}:"Nobody!"}} run scoreboard players set grim_editor_dialog_size botc_patch {0}' -f $seat))
}
$captureLines.Add("scoreboard players set grim_editor_game_captured botc_patch 1")
Write-Lines -Path (Join-Path $OutputRoot "capture_game.mcfunction") -Lines $captureLines

$prepareSelectedLines = New-Header "Loads a selected game-start seat from the cached live-game character state."
$prepareSelectedLines.Add("scoreboard players set @s botc_grim_edit_valid 0")
for ($seat = 1; $seat -le 15; $seat++) {
    $prefix = ('execute if score @s botc_grim_edit_seat matches {0} if score grim_editor_seat_{0}_known botc_patch matches 1 if data storage ct:players players.p{0} unless data storage ct:players players{{p{0}:"Nobody!"}}' -f $seat)
    $prepareSelectedLines.Add("$prefix run scoreboard players set @s botc_grim_edit_valid 1")
    $prepareSelectedLines.Add("$prefix run data modify storage botc_patch:grim editor.dialog.player_name set from storage ct:players players.p$seat")
    $prepareSelectedLines.Add("$prefix run scoreboard players operation @s botc_grim_edit_role = grim_editor_seat_$($seat)_role botc_patch")
    $prepareSelectedLines.Add("$prefix run scoreboard players operation @s botc_grim_edit_alignment = grim_editor_seat_$($seat)_alignment botc_patch")
}
$prepareSelectedLines.Add("execute unless score @s botc_grim_edit_valid matches 1 run return 0")
$prepareSelectedLines.Add("execute store result storage botc_patch:grim editor.lookup.score int 1 run scoreboard players get @s botc_grim_edit_role")
$prepareSelectedLines.Add("function botc_patch:grim/editor/roles/prepare_current with storage botc_patch:grim editor.lookup")
$prepareSelectedLines.Add('execute if score @s botc_grim_edit_alignment matches 1 run data modify storage botc_patch:grim editor.dialog.current_alignment_name set value "Good"')
$prepareSelectedLines.Add('execute if score @s botc_grim_edit_alignment matches 1 run data modify storage botc_patch:grim editor.dialog.current_alignment_color set value "#55aaff"')
$prepareSelectedLines.Add('execute if score @s botc_grim_edit_alignment matches 2 run data modify storage botc_patch:grim editor.dialog.current_alignment_name set value "Evil"')
$prepareSelectedLines.Add('execute if score @s botc_grim_edit_alignment matches 2 run data modify storage botc_patch:grim editor.dialog.current_alignment_color set value "#ff5555"')
Write-Lines -Path (Join-Path $OutputRoot "prepare_selected.mcfunction") -Lines $prepareSelectedLines

$applySelectedLines = New-Header "Stores the selected Storyteller edit for the later reveal snapshot."
for ($seat = 1; $seat -le 15; $seat++) {
    $applySelectedLines.Add("execute if score @s botc_grim_edit_seat matches $seat run scoreboard players set grim_editor_seat_$($seat)_known botc_patch 1")
    $applySelectedLines.Add("execute if score @s botc_grim_edit_seat matches $seat run scoreboard players set grim_editor_seat_$($seat)_override botc_patch 1")
    $applySelectedLines.Add("execute if score @s botc_grim_edit_seat matches $seat run scoreboard players operation grim_editor_seat_$($seat)_role botc_patch = @s botc_grim_edit_role")
    $applySelectedLines.Add("execute if score @s botc_grim_edit_seat matches $seat run scoreboard players operation grim_editor_seat_$($seat)_alignment botc_patch = @s botc_grim_edit_alignment")
}
Write-Lines -Path (Join-Path $OutputRoot "apply_selected.mcfunction") -Lines $applySelectedLines

$applySnapshotLines = New-Header "Copies cached live-game character state into the confirmed reveal snapshot."
for ($seat = 1; $seat -le 15; $seat++) {
    $prefix = "execute if score grim_editor_seat_$($seat)_known botc_patch matches 1"
    $applySnapshotLines.Add("$prefix run scoreboard players set grim_dialog_size botc_patch $seat")
    $applySnapshotLines.Add("$prefix run scoreboard players set grim_seat_$($seat)_occupied botc_patch 1")
    $applySnapshotLines.Add("$prefix run scoreboard players set grim_seat_$($seat)_revealed botc_patch 0")
    $applySnapshotLines.Add("$prefix run scoreboard players operation grim_seat_$($seat)_role botc_patch = grim_editor_seat_$($seat)_role botc_patch")
    $applySnapshotLines.Add("$prefix run scoreboard players operation grim_seat_$($seat)_alignment botc_patch = grim_editor_seat_$($seat)_alignment botc_patch")
}
Write-Lines -Path (Join-Path $OutputRoot "apply_to_snapshot.mcfunction") -Lines $applySnapshotLines

$syncDisplayLines = New-Header "Updates only the acting Storyteller's Sybillian grimoire display variable."
for ($seat = 1; $seat -le 15; $seat++) {
    $syncDisplayLines.Add(('$execute if score @s botc_grim_edit_seat matches {0} run fmvariable set p{0}_role false $(role)' -f $seat))
}
Write-Lines -Path (Join-Path $OutputRoot "sync_storyteller_display.mcfunction") -Lines $syncDisplayLines

$playerDispatchLines = New-Header "Shows the occupied-seat player picker using Sybillian's game-start name snapshot."
$playerDispatchLines.Add("dialog clear @s")
$playerDispatchLines.Add('execute unless score phase game_data matches 1.. run return run tellraw @s {"text":"Characters can only be changed during an active game.","color":"red"}')
$playerDispatchLines.Add("execute if score grim_editor_reveal_started botc_patch matches 1 run return run function botc_patch:grim/editor/locked")
$playerDispatchLines.Add("execute unless score grim_editor_game_captured botc_patch matches 1 run function botc_patch:grim/editor/capture_game")
$playerDispatchLines.Add('execute unless score grim_editor_game_captured botc_patch matches 1 run return run tellraw @s {"text":"Game-start player data is not available yet.","color":"red"}')
$playerDispatchLines.Add("function botc_patch:grim/editor/refresh_live_roles")
$playerDispatchLines.Add("function botc_patch:grim/editor/player_labels/prepare")
for ($seatCount = 0; $seatCount -le 15; $seatCount++) {
    $playerDispatchLines.Add("execute if score grim_editor_dialog_size botc_patch matches $seatCount run function botc_patch:grim/editor/player_dialog/count_$seatCount with storage botc_patch:grim editor.player_labels")
}
$playerDispatchLines.Add("execute unless score grim_editor_dialog_size botc_patch matches 0..15 run function botc_patch:grim/editor/player_dialog/count_15 with storage botc_patch:grim editor.player_labels")
Write-Lines -Path (Join-Path $OutputRoot "player_dialog.mcfunction") -Lines $playerDispatchLines

for ($seatCount = 0; $seatCount -le 15; $seatCount++) {
    $actions = [System.Collections.Generic.List[string]]::new()
    for ($seat = 1; $seat -le $seatCount; $seat++) {
        $actions.Add('{label:{text:"$(p' + $seat + '_name) ($(p' + $seat + '_role))",color:"$(p' + $seat + '_color)"},tooltip:{text:"Seat ' + $seat + '",color:"gray"},action:{type:"run_command",command:"/botc grimoire edit_seat ' + $seat + '"}}')
    }

    if ($actions.Count -eq 0) {
        $actions.Add('{label:{text:"No seated players",color:"gray"},action:{type:"run_command",command:"/botc grimoire confirm"}}')
    }

    $macroPrefix = if ($seatCount -gt 0) { '$' } else { '' }
    $line = $macroPrefix + 'dialog show @s {type:"multi_action",title:"Change Characters",body:{type:"plain_message",contents:{text:"Choose a player before starting Reveal Grimoire.",color:"gray"},width:360},columns:3,after_action:"wait_for_response",actions:[' + ($actions -join ',') + '],exit_action:{label:"Back",action:{type:"run_command",command:"/botc grimoire confirm"}}}'
    $lines = New-Header "Player-name dialog for $seatCount occupied seats."
    $lines.Add($line)
    Write-Lines -Path (Join-Path $PlayerDialogRoot "count_$seatCount.mcfunction") -Lines $lines
}

$characterDispatchLines = New-Header "Builds and shows the current-script character picker for the selected player."
$characterDispatchLines.Add("dialog clear @s")
$characterDispatchLines.Add('execute unless score phase game_data matches 1.. run return run tellraw @s {"text":"Characters can only be changed during an active game.","color":"red"}')
$characterDispatchLines.Add("execute if score grim_editor_reveal_started botc_patch matches 1 run return run function botc_patch:grim/editor/locked")
$characterDispatchLines.Add("function botc_patch:grim/editor/refresh_live_roles")
$characterDispatchLines.Add("function botc_patch:grim/editor/roles/build")
$characterDispatchLines.Add("function botc_patch:grim/editor/roles/prepare_args")
$characterDispatchLines.Add("function botc_patch:grim/editor/prepare_selected")
$characterDispatchLines.Add("execute unless score @s botc_grim_edit_valid matches 1 run return run function botc_patch:grim/editor/invalid_seat")
for ($roleCount = 0; $roleCount -le 30; $roleCount++) {
    $characterDispatchLines.Add("execute if score grim_editor_role_count botc_patch matches $roleCount run function botc_patch:grim/editor/character_dialog/count_$roleCount with storage botc_patch:grim editor.dialog")
}
$characterDispatchLines.Add("execute unless score grim_editor_role_count botc_patch matches 0..30 run function botc_patch:grim/editor/character_dialog/count_30 with storage botc_patch:grim editor.dialog")
Write-Lines -Path (Join-Path $OutputRoot "character_dialog.mcfunction") -Lines $characterDispatchLines

for ($roleCount = 0; $roleCount -le 30; $roleCount++) {
    $actions = [System.Collections.Generic.List[string]]::new()
    $actions.Add('{label:{text:"Set Good",color:"#0000aa",bold:true},tooltip:{text:"Reveal alignment only",color:"gray"},action:{type:"run_command",command:"/botc grimoire set_good"}}')
    $actions.Add('{label:{text:"Set Evil",color:"#aa0000",bold:true},tooltip:{text:"Reveal alignment only",color:"gray"},action:{type:"run_command",command:"/botc grimoire set_evil"}}')
    for ($roleIndex = 1; $roleIndex -le $roleCount; $roleIndex++) {
        $actions.Add('{label:{text:"$(r' + $roleIndex + '_name)",color:"$(r' + $roleIndex + '_color)"},action:{type:"run_command",command:"/botc grimoire set_character $(r' + $roleIndex + '_id)"}}')
    }

    $body = '[{type:"plain_message",contents:[{text:"Current: ",color:"gray"},{text:"$(current_role_name)",color:"$(current_alignment_color)"},{text:" ($(current_alignment_name))",color:"$(current_alignment_color)"}],width:360},{type:"plain_message",contents:[{text:"Townsfolk",color:"#55aaff"},{text:" | ",color:"dark_gray"},{text:"Outsiders",color:"#55ffff"},{text:" | ",color:"dark_gray"},{text:"Minions",color:"#ffaa00"},{text:" | ",color:"dark_gray"},{text:"Demons",color:"#ff5555"}],width:360},{type:"plain_message",contents:{text:"Choose a character from the current script, or override only its reveal alignment.",color:"gray"},width:360}]'
    $line = '$dialog show @s {type:"multi_action",title:{text:"Edit $(player_name)"},body:' + $body + ',columns:2,after_action:"wait_for_response",actions:[' + ($actions -join ',') + '],exit_action:{label:"Back",action:{type:"run_command",command:"/botc grimoire change_characters"}}}'
    $lines = New-Header "Character dialog for $roleCount current-script roles."
    $lines.Add($line)
    Write-Lines -Path (Join-Path $CharacterDialogRoot "count_$roleCount.mcfunction") -Lines $lines
}

Write-Host "Generated Reveal Grimoire character editor for $($roles.Count) Sybillian roles."
