Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$RepoRoot = Split-Path -Parent $PSScriptRoot
$OutputPath = Join-Path $RepoRoot "Jays-Patch/datapack/data/botc_patch/function/grim/confirm.mcfunction"
$VariantRoot = Join-Path $RepoRoot "Jays-Patch/datapack/data/botc_patch/function/grim/confirm"
$DialogIconPath = Join-Path $RepoRoot "Jays-Patch/dialog-icons.json"
$MusicTrackPath = Join-Path $RepoRoot "Jays-Patch/music-tracks.json"
$DialogIconHelper = Join-Path $RepoRoot "tools/lib/dialog-icons.ps1"
$RoleGlyphHelper = Join-Path $RepoRoot "tools/lib/role-icon-glyphs.ps1"
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)

. $DialogIconHelper
. $RoleGlyphHelper
$icons = Get-BotcDialogIconCatalog -DialogIconPath $DialogIconPath -MusicTrackPath $MusicTrackPath
$revealLabel = New-BotcDialogGlyphLabel -Glyph (Get-BotcDialogIconGlyph -Catalog $icons -Id "reveal_grimoire") -Font "botc_patch:ui_icons" -Text "Reveal Grimoire" -Color "gold" -Bold $true
$changeLabel = New-BotcDialogGlyphLabel -Glyph (Get-BotcDialogIconGlyph -Catalog $icons -Id "change_characters") -Font "botc_patch:ui_icons" -Text "Change Characters" -Color "aqua" -Bold $true
$backLabel = New-BotcDialogGlyphLabel -Glyph (Get-BotcDialogIconGlyph -Catalog $icons -Id "back") -Font "botc_patch:ui_icons" -Text "Back" -Color "gray"
$titleLabel = New-BotcDialogGlyphLabel -Glyph (Get-BotcDialogIconGlyph -Catalog $icons -Id "reveal_grimoire") -Font "botc_patch:ui_icons" -Text "Reveal Grimoire?" -Color "white"

function Write-Lines {
    param(
        [string] $Path,
        [System.Collections.Generic.List[string]] $Lines
    )

    New-Item -ItemType Directory -Path (Split-Path -Parent $Path) -Force | Out-Null
    [System.IO.File]::WriteAllText($Path, ($Lines -join "`n") + "`n", $utf8NoBom)
}

function New-Header {
    param([string] $Responsibility)

    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add("# Generated by tools/generate-grim-confirm.ps1.")
    $lines.Add("# Do not hand-edit this file; update the generator and regenerate.")
    $lines.Add("# $Responsibility")
    return ,$lines
}

$options = @(
    [pscustomobject]@{
        Bit = 1
        Condition = 'if entity @a[tag=!storyteller,tag=!spectator,scores={id=1..15,role=108}]'
        Action = '{label:' + (New-BotcDialogGlyphLabel -Glyph (Get-BotcRoleIconGlyph -RoleScore 108) -Font "botc_patch:role_icons" -Text "Announce Fearmonger" -Color "red" -Bold $true) + ',action:{type:"run_command",command:"/botc grimoire announce_fearmonger"}}'
    }
    [pscustomobject]@{
        Bit = 2
        Condition = 'if entity @a[tag=!storyteller,tag=!spectator,tag=dead,tag=!active_banshee,scores={id=1..15,role=55}]'
        Action = '{label:' + (New-BotcDialogGlyphLabel -Glyph (Get-BotcRoleIconGlyph -RoleScore 55) -Font "botc_patch:role_icons" -Text "Awaken Banshee" -Color "aqua" -Bold $true) + ',action:{type:"run_command",command:"/botc grimoire awaken_banshee"}}'
    }
    [pscustomobject]@{
        Bit = 4
        Condition = 'if entity @a[tag=!storyteller,tag=!spectator,scores={id=1..15,role=128}]'
        Action = '{label:' + (New-BotcDialogGlyphLabel -Glyph (Get-BotcRoleIconGlyph -RoleScore 128) -Font "botc_patch:role_icons" -Text "Announce Al-Hadikhia Target" -Color "dark_red" -Bold $true) + ',action:{type:"run_command",command:"/botc grimoire announce_alhadikhia"}}'
    }
)

$confirmLines = New-Header "Routes the pre-reveal controls through one contextual option mask."
$confirmLines.Add('execute unless score phase game_data matches 1.. run return run tellraw @s {"text":"You can only start Reveal Grimoire during an active game.","color":"red"}')
$confirmLines.Add('scoreboard players set grim_confirm_options botc_patch 0')
foreach ($option in $options) {
    $confirmLines.Add("execute $($option.Condition) run scoreboard players add grim_confirm_options botc_patch $($option.Bit)")
}
for ($mask = 0; $mask -le 7; $mask++) {
    $confirmLines.Add("execute if score grim_confirm_options botc_patch matches $mask run function botc_patch:grim/confirm/options_$mask")
}
Write-Lines -Path $OutputPath -Lines $confirmLines

for ($mask = 0; $mask -le 7; $mask++) {
    $actions = [System.Collections.Generic.List[string]]::new()
    $actions.Add('{label:' + $revealLabel + ',action:{type:"run_command",command:"/botc grimoire start"}}')
    $actions.Add('{label:' + $changeLabel + ',action:{type:"run_command",command:"/botc grimoire change_characters"}}')
    foreach ($option in $options) {
        if (($mask -band $option.Bit) -ne 0) {
            $actions.Add($option.Action)
        }
    }
    $actions.Add('{label:' + $backLabel + ',action:{type:"run_command",command:"/botc grimoire cancel"}}')

    $lines = New-Header "Pre-reveal confirmation for contextual option mask $mask."
    $lines.Add('dialog show @s {type:"multi_action",title:' + $titleLabel + ',actions:[' + ($actions -join ',') + ']}')
    Write-Lines -Path (Join-Path $VariantRoot "options_$mask.mcfunction") -Lines $lines
}

Write-Host "Generated contextual Reveal Grimoire confirmation dialogs." -ForegroundColor Green
