Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$RepoRoot = Split-Path -Parent $PSScriptRoot
$RoleIconPath = Join-Path $RepoRoot "Jays-Patch\role-icons.json"
$OutputRoot = Join-Path $RepoRoot "Jays-Patch\datapack\data\botc_patch\function\storyteller_tools\player_menu"
$DialogRoot = Join-Path $OutputRoot "dialog"

if (-not (Test-Path -LiteralPath $RoleIconPath)) {
    throw "Missing role icon source table: $RoleIconPath"
}

$seatColorNames = @(
    "red", "orange", "yellow", "lime", "green",
    "mint", "cyan", "blue", "navy", "purple",
    "magenta", "lavender", "white", "gray", "black"
)

$roleIconConfig = Get-Content -LiteralPath $RoleIconPath -Raw | ConvertFrom-Json
$roleIcons = @($roleIconConfig.roles | ForEach-Object { [string] $_ } | Where-Object { -not [string]::IsNullOrWhiteSpace($_) } | Sort-Object -Unique)
if ($roleIcons.Count -eq 0) {
    throw "Role icon table has no roles."
}

$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
New-Item -ItemType Directory -Path $OutputRoot -Force | Out-Null
New-Item -ItemType Directory -Path $DialogRoot -Force | Out-Null

function New-GeneratedHeader {
    param([string] $Responsibility)

    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add("# Generated by tools/generate-storyteller-player-menu.ps1.")
    $lines.Add("# Do not hand-edit this file; update the generator and regenerate.")
    if (-not [string]::IsNullOrWhiteSpace($Responsibility)) {
        $lines.Add("# $Responsibility")
    }
    return ,$lines
}

function Write-Lines {
    param(
        [string] $Path,
        [System.Collections.Generic.List[string]] $Lines
    )

    $content = ($Lines -join [Environment]::NewLine) + [Environment]::NewLine
    [System.IO.File]::WriteAllText($Path, $content, $utf8NoBom)
}

$openLines = New-GeneratedHeader "Opens the active-game player dialog without replacing the Storyteller hotbar."
$openLines.Add("tag @s add botc_st_tool_used")
$openLines.Add("execute unless entity @s[tag=storyteller] run return 0")
$openLines.Add('execute unless score phase game_data matches 1.. run return run tellraw @s {"text":"Teleport to Player is only available during an active game.","color":"red"}')
$openLines.Add('execute if score phase game_data matches 4 run tellraw @s {"text":"Teleporting...","color":"gray"}')
$openLines.Add("execute if score phase game_data matches 4 run function botc_patch:storyteller_tools/teleport_den")
$openLines.Add("execute if score phase game_data matches 4 run function botc_patch:storyteller_tools/teleport_sound")
$openLines.Add("function botc_patch:storyteller_tools/player_menu/dialog")
Write-Lines -Path (Join-Path $OutputRoot "open.mcfunction") -Lines $openLines

$dialogLines = New-GeneratedHeader "Builds player-and-role labels from Sybillian's game-start seats and current Storyteller role state."
$dialogLines.Add("dialog clear @s")
$dialogLines.Add("execute unless entity @s[tag=storyteller] run return 0")
$dialogLines.Add('execute unless score phase game_data matches 1.. run return run tellraw @s {"text":"Teleport to Player is only available during an active game.","color":"red"}')
$dialogLines.Add("function botc_patch:grim/editor/refresh_live_roles")
$dialogLines.Add("function botc_patch:grim/editor/player_labels/prepare")
$dialogLines.Add("scoreboard players set botc_tp_dialog_size botc_patch 0")
for ($seat = 1; $seat -le 15; $seat++) {
    $dialogLines.Add(('execute if data storage ct:players players.p{0} unless data storage ct:players players{{p{0}:"Nobody!"}} run scoreboard players set botc_tp_dialog_size botc_patch {0}' -f $seat))
}
for ($seatCount = 0; $seatCount -le 15; $seatCount++) {
    $dialogLines.Add("execute if score botc_tp_dialog_size botc_patch matches $seatCount run function botc_patch:storyteller_tools/player_menu/dialog/count_$seatCount with storage botc_patch:grim editor.player_labels")
}
$dialogLines.Add("execute unless score botc_tp_dialog_size botc_patch matches 0..15 run function botc_patch:storyteller_tools/player_menu/dialog/count_15 with storage botc_patch:grim editor.player_labels")
Write-Lines -Path (Join-Path $OutputRoot "dialog.mcfunction") -Lines $dialogLines

for ($seatCount = 0; $seatCount -le 15; $seatCount++) {
    $actions = [System.Collections.Generic.List[string]]::new()
    for ($seat = 1; $seat -le $seatCount; $seat++) {
        $actions.Add('{label:{text:"$(p' + $seat + '_name) ($(p' + $seat + '_role))",color:"$(p' + $seat + '_color)"},tooltip:{text:"Seat ' + $seat + '",color:"gray"},action:{type:"run_command",command:"/botc teleport_player ' + $seat + '"}}')
    }

    if ($actions.Count -eq 0) {
        $actions.Add('{label:{text:"No seated players",color:"gray"},action:{type:"run_command",command:"/botc teleport_cancel"}}')
    }

    $macroPrefix = if ($seatCount -gt 0) { '$' } else { '' }
    $line = $macroPrefix + 'dialog show @s {type:"multi_action",title:"Teleport to Player",body:{type:"plain_message",contents:{text:"Choose a seated player.",color:"gray"},width:360},columns:3,actions:[' + ($actions -join ',') + '],exit_action:{label:"Cancel",action:{type:"run_command",command:"/botc teleport_cancel"}}}'
    $lines = New-GeneratedHeader "Teleport player dialog for $seatCount occupied seats."
    $lines.Add($line)
    Write-Lines -Path (Join-Path $DialogRoot "count_$seatCount.mcfunction") -Lines $lines
}

$cancelLines = New-GeneratedHeader "Closes the teleport player dialog without changing the hotbar."
$cancelLines.Add("dialog clear @s")
Write-Lines -Path (Join-Path $OutputRoot "cancel.mcfunction") -Lines $cancelLines

$teleportSelectedLines = New-GeneratedHeader "Validates a dialog seat selection before dispatching to its fixed target function."
$teleportSelectedLines.Add("dialog clear @s")
$teleportSelectedLines.Add("execute unless entity @s[tag=storyteller] run return 0")
$teleportSelectedLines.Add('execute unless score phase game_data matches 1.. run return run tellraw @s {"text":"Teleport to Player is only available during an active game.","color":"red"}')
$teleportSelectedLines.Add('$function botc_patch:storyteller_tools/player_menu/to_seat_$(seat)')
Write-Lines -Path (Join-Path $OutputRoot "teleport_selected.mcfunction") -Lines $teleportSelectedLines

for ($seat = 1; $seat -le 15; $seat++) {
    $targetSelector = "@a[tag=!storyteller,tag=!spectator,scores={id=$seat},limit=1]"
    $lines = New-GeneratedHeader "Teleports the Storyteller to the currently online player in seat $seat."
    $lines.Add("tag @s add botc_st_tool_used")
    $lines.Add("dialog clear @s")
    $lines.Add(('execute if entity {0} run tellraw @s {{"text":"Teleporting...","color":"gray"}}' -f $targetSelector))
    $lines.Add(('execute if entity {0} run tp @s {0}' -f $targetSelector))
    $lines.Add(('execute if entity {0} run function botc_patch:storyteller_tools/teleport_sound' -f $targetSelector))
    $lines.Add(('execute unless entity {0} run tellraw @s {{"text":"That player is no longer available.","color":"red"}}' -f $targetSelector))
    Write-Lines -Path (Join-Path $OutputRoot "to_seat_$seat.mcfunction") -Lines $lines
}

$clearRoleItems = New-GeneratedHeader "Clears shared role-icon carrot items used by legacy and player-action menus."
foreach ($icon in $roleIcons) {
    $clearRoleItems.Add(('clear @s minecraft:carrot_on_a_stick[minecraft:custom_model_data={{strings:["botc_role_{0}"]}}]' -f $icon))
}
Write-Lines -Path (Join-Path $OutputRoot "clear_role_items.mcfunction") -Lines $clearRoleItems

$clearItems = New-GeneratedHeader "Clears retired teleport picker tokens while preserving shared cleanup callers."
for ($seat = 0; $seat -lt $seatColorNames.Count; $seat++) {
    $clearItems.Add(('clear @s minecraft:carrot_on_a_stick[minecraft:custom_model_data={{strings:["storyteller_tp_{0}"]}}]' -f $seatColorNames[$seat]))
    $clearItems.Add(('clear @s minecraft:carrot_on_a_stick[minecraft:custom_model_data={{strings:["storyteller_nom_{0}"]}}]' -f $seatColorNames[$seat]))
}
$clearItems.Add("function botc_patch:storyteller_tools/player_menu/clear_role_items")
Write-Lines -Path (Join-Path $OutputRoot "clear_items.mcfunction") -Lines $clearItems

$cleanupItems = New-GeneratedHeader "Removes any retired teleport picker tokens left from an older deployment."
foreach ($seatColorName in $seatColorNames) {
    $cleanupItems.Add(('clear @a minecraft:carrot_on_a_stick[minecraft:custom_model_data={{strings:["storyteller_tp_{0}"]}}]' -f $seatColorName))
}
Write-Lines -Path (Join-Path $OutputRoot "cleanup_items.mcfunction") -Lines $cleanupItems

foreach ($staleName in @("back.mcfunction", "close.mcfunction", "page_1.mcfunction", "page_1_day.mcfunction", "page_1_night.mcfunction", "page_2.mcfunction", "page_2_day.mcfunction", "page_2_night.mcfunction")) {
    Remove-Item -LiteralPath (Join-Path $OutputRoot $staleName) -Force -ErrorAction SilentlyContinue
}

Write-Host "Generated Storyteller teleport player dialog with 15 player-and-role labels."
