param(
    [switch] $Check
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$RepoRoot = Split-Path -Parent $PSScriptRoot
$PatchRoot = Join-Path $RepoRoot "Jays-Patch"
$ConfigPath = Join-Path $PatchRoot "night-chat.json"
$OutputPath = Join-Path $PatchRoot "datapack/data/ct/function/loop/player/join_vc.mcfunction"
$Utf8NoBom = [System.Text.UTF8Encoding]::new($false)

if (-not (Test-Path -LiteralPath $ConfigPath -PathType Leaf)) {
    throw "Missing Night Chat contract: $ConfigPath"
}

try {
    $config = Get-Content -LiteralPath $ConfigPath -Raw | ConvertFrom-Json
}
catch {
    throw "Invalid Night Chat contract JSON: $($_.Exception.Message)"
}

if ([string] $config.status -ne "active") {
    throw "Night Chat generation requires status 'active', got '$($config.status)'."
}

$routerPath = Join-Path $RepoRoot ([string] $config.upstreamRouter.path)
if (-not (Test-Path -LiteralPath $routerPath -PathType Leaf)) {
    throw "Missing pinned Sybillian voice router: $routerPath"
}

$actualHash = (Get-FileHash -LiteralPath $routerPath -Algorithm SHA256).Hash.ToLowerInvariant()
$expectedHash = ([string] $config.upstreamRouter.sha256).ToLowerInvariant()
if ($actualHash -cne $expectedHash) {
    throw "Sybillian voice router changed. Expected SHA-256 $expectedHash, got $actualHash. Review the upstream file before regenerating."
}

$sourceLines = @([System.IO.File]::ReadAllLines($routerPath, [System.Text.Encoding]::UTF8))
$expectedLineCount = [int] $config.upstreamRouter.lineCount
if ($sourceLines.Count -ne $expectedLineCount) {
    throw "Sybillian voice router line count changed. Expected $expectedLineCount, got $($sourceLines.Count)."
}

$voiceCommandPattern = '\brun voicechat (join|leave)\b'
$voiceCommandCount = @($sourceLines | Where-Object { $_ -match $voiceCommandPattern }).Count
$expectedVoiceCommandCount = [int] $config.upstreamRouter.voiceGroupCommandCount
if ($voiceCommandCount -ne $expectedVoiceCommandCount) {
    throw "Sybillian voice router command count changed. Expected $expectedVoiceCommandCount voice-group commands, got $voiceCommandCount."
}

$nightChatTag = [string] $config.nightChatTag
if ($nightChatTag -notmatch '^[a-z0-9_.-]+$') {
    throw "Night Chat tag contains unsupported characters: $nightChatTag"
}

$generatedLines = [System.Collections.Generic.List[string]]::new()
$generatedLines.Add("# Generated by tools/generate-night-chat.ps1 from Jays-Patch/night-chat.json.")
$generatedLines.Add("# Do not hand-edit. The source contract pins Sybillian's 1.5.4 voice router by SHA-256.")
$generatedLines.Add("# Only voice-group commands are suppressed while a player has tag=$nightChatTag.")

foreach ($line in $sourceLines) {
    if ($line -notmatch $voiceCommandPattern) {
        $generatedLines.Add($line)
        continue
    }

    if ($line -notmatch '^execute\s+') {
        throw "Cannot safely guard unexpected voice-router command: $line"
    }

    $generatedLines.Add(($line -replace '^execute\s+', "execute unless entity @s[tag=$nightChatTag] "))
}

$content = ($generatedLines -join "`n") + "`n"
if ($Check) {
    if (-not (Test-Path -LiteralPath $OutputPath -PathType Leaf)) {
        throw "Generated Night Chat router is missing: $OutputPath"
    }

    $actualContent = [System.IO.File]::ReadAllText($OutputPath)
    if ($actualContent -cne $content) {
        throw "Generated Night Chat router is stale. Run tools/generate-night-chat.ps1."
    }

    Write-Host "Night Chat router is current and matches the pinned Sybillian 1.5.4 source." -ForegroundColor Green
    exit 0
}

$outputDirectory = Split-Path -Parent $OutputPath
if (-not (Test-Path -LiteralPath $outputDirectory -PathType Container)) {
    New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null
}

[System.IO.File]::WriteAllText($OutputPath, $content, $Utf8NoBom)
Write-Host "Generated $OutputPath"
