Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$RepoRoot = Split-Path -Parent $PSScriptRoot
$SybillianRolePath = Join-Path $RepoRoot "..\data\resources\datapack\required\ct\data\ct\function\admin\setup\set_from_menu.mcfunction"
$SybillianCharactersPath = Join-Path $RepoRoot "..\data\resources\datapack\required\ct\data\ct\function\admin\setup\characters.mcfunction"
$OutputPath = Join-Path $RepoRoot "Jays-Patch\datapack\data\botc_patch\function\cmd\character\sync_role.mcfunction"
$RoleCatalogHelper = Join-Path $RepoRoot "tools\lib\sybillian-role-catalog.ps1"

. $RoleCatalogHelper
$roles = @(Get-SybillianRoleCatalog -SetFromMenuPath $SybillianRolePath -CharactersPath $SybillianCharactersPath)
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
New-Item -ItemType Directory -Path (Split-Path -Parent $OutputPath) -Force | Out-Null

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("# Generated by tools/generate-character-sync.ps1.")
$lines.Add("# Do not hand-edit this file; update the generator and regenerate.")
$lines.Add("# Source of truth: Sybillian ct:admin/setup/set_from_menu role IDs.")
$lines.Add("")
$lines.Add('$execute if data storage botc_patch:character request{character:"none"} run scoreboard players set @a[scores={id=$(id)},limit=1] role 0')
$lines.Add('$execute if data storage botc_patch:character request{character:"none"} run scoreboard players set grim_seat_$(id)_role botc_patch 0')
$lines.Add('$execute if data storage botc_patch:character request{character:"none"} run scoreboard players set grim_seat_$(id)_alignment botc_patch 0')
$lines.Add('$execute if data storage botc_patch:character request{character:"none"} as @a[scores={id=$(id)},limit=1] run function botc_patch:cmd/character/update_alignment')
$lines.Add('execute if data storage botc_patch:character request{character:"none"} run scoreboard players set character_matched botc_patch 1')

foreach ($role in $roles) {
    $lines.Add("")
    $lines.Add(('$execute if data storage botc_patch:character request{{character:"{0}"}} run scoreboard players set @a[scores={{id=$(id)}},limit=1] role {1}' -f $role.Role, $role.Id))
    $lines.Add(('$execute if data storage botc_patch:character request{{character:"{0}"}} run scoreboard players set grim_seat_$(id)_role botc_patch {1}' -f $role.Role, $role.Id))
    $lines.Add(('$execute if data storage botc_patch:character request{{character:"{0}"}} run scoreboard players set grim_seat_$(id)_alignment botc_patch {1}' -f $role.Role, $role.Alignment))
    $lines.Add(('$execute if data storage botc_patch:character request{{character:"{0}"}} as @a[scores={{id=$(id)}},limit=1] run function botc_patch:cmd/character/update_alignment' -f $role.Role))
    $lines.Add(('execute if data storage botc_patch:character request{{character:"{0}"}} run scoreboard players set character_matched botc_patch 1' -f $role.Role))
}

$content = ($lines -join [Environment]::NewLine) + [Environment]::NewLine
[System.IO.File]::WriteAllText($OutputPath, $content, $utf8NoBom)

Write-Host ("Generated character sync for {0} Sybillian roles." -f $roles.Count)
