Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$RepoRoot = Split-Path -Parent $PSScriptRoot
$OutputRoot = Join-Path $RepoRoot "Jays-Patch/datapack/data/botc_patch/function/storyteller_tools/boomdandy"
$PyreOutputRoot = Join-Path $RepoRoot "Jays-Patch/datapack/data/botc_patch/function/storyteller_tools/boomdandy_pyre"
$SeatLayoutRoot = Join-Path $RepoRoot "Jays-Patch/datapack/data/botc_patch/function/seat_layout/apply"
$UpstreamExecutePath = Join-Path $RepoRoot "data/resources/datapack/required/ct/data/ct/function/kill/execute/execute.mcfunction"
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
$invariantCulture = [System.Globalization.CultureInfo]::InvariantCulture
New-Item -ItemType Directory -Path $OutputRoot -Force | Out-Null
New-Item -ItemType Directory -Path (Join-Path $OutputRoot "dialog") -Force | Out-Null

$pyreOutputFull = [System.IO.Path]::GetFullPath($PyreOutputRoot)
$storytellerToolsFull = [System.IO.Path]::GetFullPath((Join-Path $RepoRoot "Jays-Patch/datapack/data/botc_patch/function/storyteller_tools"))
if (-not $pyreOutputFull.StartsWith($storytellerToolsFull, [System.StringComparison]::OrdinalIgnoreCase)) {
    throw "Refusing to clean generated Boomdandy pyre files outside the Storyteller tools root."
}
if (Test-Path -LiteralPath $pyreOutputFull) {
    Remove-Item -LiteralPath $pyreOutputFull -Recurse -Force
}
New-Item -ItemType Directory -Path $PyreOutputRoot -Force | Out-Null

foreach ($generatedFolder in @("announce", "seats")) {
    $path = Join-Path $OutputRoot $generatedFolder
    $outputFull = [System.IO.Path]::GetFullPath($OutputRoot)
    $pathFull = [System.IO.Path]::GetFullPath($path)
    if (-not $pathFull.StartsWith($outputFull, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Refusing to clean generated Boomdandy files outside $OutputRoot"
    }
    if (Test-Path -LiteralPath $pathFull) {
        Remove-Item -LiteralPath $pathFull -Recurse -Force
    }
}

function New-GeneratedHeader {
    param([string] $Responsibility)

    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add("# Generated by tools/generate-storyteller-boomdandy.ps1.")
    $lines.Add("# Do not hand-edit this file; update the generator and regenerate.")
    $lines.Add("# $Responsibility")
    return ,$lines
}

function Write-Lines {
    param(
        [string] $Path,
        [System.Collections.Generic.List[string]] $Lines
    )

    New-Item -ItemType Directory -Path (Split-Path -Parent $Path) -Force | Out-Null
    [System.IO.File]::WriteAllText($Path, (($Lines -join "`n") + "`n"), $utf8NoBom)
}

function Get-SeatCommands {
    param(
        [int] $LayoutCount,
        [int] $Seat
    )

    $layoutPath = Join-Path $SeatLayoutRoot "$LayoutCount.mcfunction"
    if (-not (Test-Path -LiteralPath $layoutPath -PathType Leaf)) {
        throw "Missing generated seat layout: $layoutPath"
    }

    $lines = @(Get-Content -LiteralPath $layoutPath)
    $start = -1
    for ($index = 0; $index -lt $lines.Count; $index++) {
        if ($lines[$index] -match "^# Seat $Seat \(") {
            $start = $index + 1
            break
        }
    }
    if ($start -lt 0) {
        throw "Seat $Seat was not found in layout $LayoutCount."
    }

    $commands = [System.Collections.Generic.List[string]]::new()
    for ($index = $start; $index -lt $lines.Count; $index++) {
        if ($lines[$index] -match '^# (Seat|Move all)') {
            break
        }
        if ($lines[$index].Trim().Length -gt 0) {
            $commands.Add($lines[$index])
        }
    }
    return $commands
}

function Get-TypewriterPrefixes {
    param(
        [string] $Text,
        [int] $CharactersPerFrame = 3
    )

    $prefixes = [System.Collections.Generic.List[string]]::new()
    for ($length = $CharactersPerFrame; $length -lt $Text.Length; $length += $CharactersPerFrame) {
        $prefixes.Add($Text.Substring(0, $length))
    }
    $prefixes.Add($Text)
    return $prefixes
}

$aliveSelector = '@a[tag=!storyteller,tag=!spectator,tag=!dead,scores={id=1..15}]'
$seatedSelector = '@a[tag=!storyteller,tag=!spectator,scores={id=1..15}]'
$executedBoomdandySelector = '@a[tag=botc_st_last_executed,scores={id=1..15,role=107},limit=1]'
$pendingExecutionTargetSelector = '@a[tag=botc_st_last_executed,tag=marked_for_execution,tag=!dead,scores={id=1..15,role=107},limit=1]'
$pendingExecutionOwnerSelector = '@a[tag=storyteller,tag=botc_boomdandy_execution_pending,limit=1]'

$placeSelected = New-GeneratedHeader "Rebuilds one selected finalist's chair at its locked-layout position."
for ($count = 5; $count -le 15; $count++) {
    for ($seat = 1; $seat -le $count; $seat++) {
        $seatFunction = "botc_patch:storyteller_tools/boomdandy/seats/layout_$count/seat_$seat"
        $placeSelected.Add("execute if score seat_layout_locked_count botc_patch matches $count if entity @s[scores={id=$seat}] run function $seatFunction")

        $seatLines = New-GeneratedHeader "Rebuilds seat $seat from the locked $count-player layout."
        foreach ($command in Get-SeatCommands -LayoutCount $count -Seat $seat) {
            $seatLines.Add($command)
        }
        Write-Lines -Path (Join-Path $OutputRoot "seats/layout_$count/seat_$seat.mcfunction") -Lines $seatLines
    }
}
Write-Lines -Path (Join-Path $OutputRoot "seats/place_selected.mcfunction") -Lines $placeSelected

$prepareFinalSeats = New-GeneratedHeader "Removes every chair except the three selected finalists' locked-layout seats."
$prepareFinalSeats.Add("function botc_patch:seat_layout/clear")
$prepareFinalSeats.Add("tag @e[type=minecraft:item_display,tag=vote_marker] remove botc_boomdandy_finalist_seat")
for ($seat = 1; $seat -le 15; $seat++) {
    $prepareFinalSeats.Add("execute if entity @a[tag=botc_boomdandy_finalist,scores={id=$seat},limit=1] run tag @e[type=minecraft:item_display,tag=vote_marker,scores={id=$seat},limit=1] add botc_boomdandy_finalist_seat")
}
$prepareFinalSeats.Add("execute as @a[tag=botc_boomdandy_finalist,tag=!dead,scores={id=1..15}] run function botc_patch:storyteller_tools/boomdandy/seats/place_selected")
$prepareFinalSeats.Add("execute as @e[type=minecraft:item_display,tag=vote_marker,scores={id=1..15}] run data modify entity @s transformation.scale set value [0f,0f,0f]")
$prepareFinalSeats.Add("scoreboard players set boomdandy_seats_trimmed botc_patch 1")
Write-Lines -Path (Join-Path $OutputRoot "prepare_final_seats.mcfunction") -Lines $prepareFinalSeats

$restoreSeats = New-GeneratedHeader "Restores the full locked game layout after a Boomdandy flow is abandoned or ends."
$restoreSeats.Add("execute unless score boomdandy_seats_trimmed botc_patch matches 1 run return 0")
$restoreSeats.Add("scoreboard players operation seat_layout_target_count botc_patch = seat_layout_locked_count botc_patch")
$restoreSeats.Add("function botc_patch:seat_layout/apply_target")
$restoreSeats.Add("execute as @e[type=minecraft:item_display,tag=vote_marker,scores={id=1..15}] run data modify entity @s transformation.scale set value [1.5f,1.5f,1.5f]")
$restoreSeats.Add("scoreboard players set boomdandy_seats_trimmed botc_patch 0")
Write-Lines -Path (Join-Path $OutputRoot "restore_seats.mcfunction") -Lines $restoreSeats

$cleanup = New-GeneratedHeader "Clears every transient final-three selection without touching normal death state."
$cleanup.Add("execute if score boomdandy_stage botc_patch matches 4 run scoreboard players set bd_cd game_data -22")
$cleanup.Add("schedule clear botc_patch:storyteller_tools/boomdandy/announce/part_1/advance")
$cleanup.Add("schedule clear botc_patch:storyteller_tools/boomdandy/announce/part_2/start")
$cleanup.Add("schedule clear botc_patch:storyteller_tools/boomdandy/announce/part_2/advance")
$cleanup.Add("schedule clear botc_patch:storyteller_tools/boomdandy/announce/finish")
$cleanup.Add("function botc_patch:storyteller_tools/boomdandy/effects/cleanup")
$cleanup.Add("function botc_patch:storyteller_tools/boomdandy/restore_seats")
$cleanup.Add("scoreboard players set boomdandy_stage botc_patch 0")
$cleanup.Add("scoreboard players set boomdandy_selected botc_patch 0")
$cleanup.Add("scoreboard players set boomdandy_actual_selected botc_patch 0")
$cleanup.Add("scoreboard players set boomdandy_population_ok botc_patch 0")
$cleanup.Add("scoreboard players set boomdandy_elimination_remaining botc_patch 0")
$cleanup.Add("scoreboard players set boomdandy_elimination_timer botc_patch 0")
$cleanup.Add("scoreboard players set boomdandy_waiting_announced botc_patch 0")
$cleanup.Add("scoreboard players set boomdandy_announce_step botc_patch 0")
$cleanup.Add("scoreboard players set boomdandy_majority_target botc_patch 0")
$cleanup.Add("tag @a remove botc_boomdandy_finalist")
$cleanup.Add("tag @a remove botc_boomdandy_eliminate")
$cleanup.Add("tag @a remove botc_boomdandy_current_voter")
$cleanup.Add("tag @a remove botc_boomdandy_majority_target")
$cleanup.Add("tag @a remove botc_boomdandy_execution_pending")
$cleanup.Add("tag @e[type=minecraft:item_display,tag=vote_marker] remove botc_boomdandy_finalist_seat")
$cleanup.Add("data remove storage botc_patch:dialogs boomdandy")
$cleanup.Add("data remove storage botc_patch:dialogs boomdandy_selection")
Write-Lines -Path (Join-Path $OutputRoot "cleanup.mcfunction") -Lines $cleanup

$resetSelection = New-GeneratedHeader "Restarts only the current final-three selection."
$resetSelection.Add("scoreboard players set boomdandy_selected botc_patch 0")
$resetSelection.Add("scoreboard players set boomdandy_actual_selected botc_patch 0")
$resetSelection.Add("tag @a remove botc_boomdandy_finalist")
$resetSelection.Add("tag @a remove botc_boomdandy_eliminate")
$resetSelection.Add("data remove storage botc_patch:dialogs boomdandy")
$resetSelection.Add("data remove storage botc_patch:dialogs boomdandy_selection")
Write-Lines -Path (Join-Path $OutputRoot "reset_selection.mcfunction") -Lines $resetSelection

$validatePopulation = New-GeneratedHeader "Requires all game-start seats online and at least three living players."
$validatePopulation.Add("scoreboard players set boomdandy_population_ok botc_patch 1")
$validatePopulation.Add("scoreboard players set boomdandy_online botc_patch 0")
$validatePopulation.Add("scoreboard players set boomdandy_alive botc_patch 0")
$validatePopulation.Add("execute as $seatedSelector run scoreboard players add boomdandy_online botc_patch 1")
$validatePopulation.Add("execute as $aliveSelector run scoreboard players add boomdandy_alive botc_patch 1")
$validatePopulation.Add("scoreboard players operation boomdandy_expected botc_patch = seat_layout_locked_count botc_patch")
$validatePopulation.Add("execute if score boomdandy_expected botc_patch matches 0 run scoreboard players operation boomdandy_expected botc_patch = player_count game_data")
$validatePopulation.Add('execute unless score boomdandy_online botc_patch = boomdandy_expected botc_patch run tellraw @s [{text:"! ",color:"red",bold:true},{text:"Every seated player must be online before resolving Boomdandy.",color:"gray",bold:false}]')
$validatePopulation.Add("execute unless score boomdandy_online botc_patch = boomdandy_expected botc_patch run scoreboard players set boomdandy_population_ok botc_patch 0")
$validatePopulation.Add('execute unless score boomdandy_alive botc_patch matches 3.. run tellraw @s [{text:"! ",color:"red",bold:true},{text:"Boomdandy needs at least three living players.",color:"gray",bold:false}]')
$validatePopulation.Add("execute unless score boomdandy_alive botc_patch matches 3.. run scoreboard players set boomdandy_population_ok botc_patch 0")
Write-Lines -Path (Join-Path $OutputRoot "validate_population.mcfunction") -Lines $validatePopulation

$validateSelection = New-GeneratedHeader "Rejects stale finalist state caused by a death or disconnected selection."
$validateSelection.Add("scoreboard players set boomdandy_actual_selected botc_patch 0")
$validateSelection.Add("scoreboard players set boomdandy_selection_stale botc_patch 0")
$validateSelection.Add("execute as @a[tag=botc_boomdandy_finalist,tag=!dead,scores={id=1..15}] run scoreboard players add boomdandy_actual_selected botc_patch 1")
$validateSelection.Add("execute unless score boomdandy_actual_selected botc_patch = boomdandy_selected botc_patch run scoreboard players set boomdandy_selection_stale botc_patch 1")
$validateSelection.Add("execute if score boomdandy_selection_stale botc_patch matches 1 run function botc_patch:storyteller_tools/boomdandy/reset_selection")
$validateSelection.Add('execute if score boomdandy_selection_stale botc_patch matches 1 run tellraw @s [{text:"The selected finalists changed, so the selection was reset.",color:"yellow"}]')
Write-Lines -Path (Join-Path $OutputRoot "validate_selection.mcfunction") -Lines $validateSelection

$abort = New-GeneratedHeader "Stops an active resolution when the confirmed final three are no longer valid."
$abort.Add('tellraw @a[tag=storyteller] [{text:"! ",color:"red",bold:true},{text:"Boomdandy paused because all three finalists must remain online and living.",color:"gray",bold:false}]')
$abort.Add("function botc_patch:storyteller_tools/boomdandy/cleanup")
Write-Lines -Path (Join-Path $OutputRoot "abort.mcfunction") -Lines $abort

$monitorFinalists = New-GeneratedHeader "Verifies the locked final three throughout elimination, announcement, and countdown."
$monitorFinalists.Add("scoreboard players set boomdandy_actual_selected botc_patch 0")
$monitorFinalists.Add("execute as @a[tag=botc_boomdandy_finalist,tag=!dead,scores={id=1..15}] run scoreboard players add boomdandy_actual_selected botc_patch 1")
$monitorFinalists.Add("execute unless score boomdandy_actual_selected botc_patch matches 3 run function botc_patch:storyteller_tools/boomdandy/abort")
Write-Lines -Path (Join-Path $OutputRoot "monitor_finalists.mcfunction") -Lines $monitorFinalists

$skipElimination = New-GeneratedHeader "Removes one already-dead player from the pending elimination queue."
$skipElimination.Add("tag @s remove botc_boomdandy_eliminate")
$skipElimination.Add("scoreboard players remove boomdandy_elimination_remaining botc_patch 1")
Write-Lines -Path (Join-Path $OutputRoot "skip_elimination.mcfunction") -Lines $skipElimination

$eliminateOne = New-GeneratedHeader "Kills exactly one pending non-finalist through Sybillian's ordinary death flow."
$eliminateOne.Add("tag @s remove botc_boomdandy_eliminate")
$eliminateOne.Add("scoreboard players remove boomdandy_elimination_remaining botc_patch 1")
$eliminateOne.Add("scoreboard players set boomdandy_eliminated_this_step botc_patch 1")
$eliminateOne.Add("function ct:kill/die")
Write-Lines -Path (Join-Path $OutputRoot "eliminate_one.mcfunction") -Lines $eliminateOne

$eliminateNext = New-GeneratedHeader "Kills at most one non-finalist when the persistent elimination timer expires."
$eliminateNext.Add("execute unless score phase game_data matches 3 run return 0")
$eliminateNext.Add("execute unless score boomdandy_stage botc_patch matches 2 run return 0")
$eliminateNext.Add("function botc_patch:storyteller_tools/boomdandy/monitor_finalists")
$eliminateNext.Add("execute unless score boomdandy_stage botc_patch matches 2 run return 0")
$eliminateNext.Add("execute as @a[tag=botc_boomdandy_eliminate,tag=dead] run function botc_patch:storyteller_tools/boomdandy/skip_elimination")
$eliminateNext.Add("execute if score boomdandy_elimination_remaining botc_patch matches 0 run return run function botc_patch:storyteller_tools/boomdandy/announce/start")
$eliminateNext.Add("scoreboard players set boomdandy_eliminated_this_step botc_patch 0")
for ($seat = 1; $seat -le 15; $seat++) {
    $eliminateNext.Add("execute if score boomdandy_eliminated_this_step botc_patch matches 0 as @a[tag=botc_boomdandy_eliminate,tag=!dead,scores={id=$seat},limit=1] run function botc_patch:storyteller_tools/boomdandy/eliminate_one")
}
$eliminateNext.Add("execute if score boomdandy_eliminated_this_step botc_patch matches 1 run scoreboard players set boomdandy_waiting_announced botc_patch 0")
$eliminateNext.Add('execute if score boomdandy_eliminated_this_step botc_patch matches 0 if score boomdandy_waiting_announced botc_patch matches 0 run tellraw @a[tag=storyteller] [{text:"Boomdandy is paused until the missing player returns.",color:"yellow"}]')
$eliminateNext.Add("execute if score boomdandy_eliminated_this_step botc_patch matches 0 run scoreboard players set boomdandy_waiting_announced botc_patch 1")
$eliminateNext.Add("execute if score boomdandy_elimination_remaining botc_patch matches 1.. if score boomdandy_eliminated_this_step botc_patch matches 1 run scoreboard players set boomdandy_elimination_timer botc_patch 30")
$eliminateNext.Add("execute if score boomdandy_elimination_remaining botc_patch matches 1.. if score boomdandy_eliminated_this_step botc_patch matches 0 run scoreboard players set boomdandy_elimination_timer botc_patch 20")
$eliminateNext.Add("execute if score boomdandy_elimination_remaining botc_patch matches 0 run function botc_patch:storyteller_tools/boomdandy/announce/start")
Write-Lines -Path (Join-Path $OutputRoot "eliminate_next.mcfunction") -Lines $eliminateNext

$announcementPartOne = "Get ready..."
$announcementPartTwo = "Something's about to explode!"
$announcementSubtitle = "Stand near a player's seat to vote for their death."

$announceStart = New-GeneratedHeader "Begins the first readable typewriter warning before the countdown."
$announceStart.Add("scoreboard players set boomdandy_stage botc_patch 3")
$announceStart.Add("scoreboard players set boomdandy_announce_step botc_patch 0")
$announceStart.Add("title @a times 0t 20t 0t")
$announceStart.Add('title @a title {"text":""}')
$announceStart.Add('title @a subtitle {"text":""}')
$announceStart.Add("schedule function botc_patch:storyteller_tools/boomdandy/announce/part_1/advance 1t replace")
Write-Lines -Path (Join-Path $OutputRoot "announce/start.mcfunction") -Lines $announceStart

$partOneFrames = @(Get-TypewriterPrefixes -Text $announcementPartOne)
for ($index = 0; $index -lt $partOneFrames.Count; $index++) {
    $frameNumber = $index + 1
    $titleJson = [string] ($partOneFrames[$index] | ConvertTo-Json -Compress)
    $frameLines = New-GeneratedHeader "First warning frame $frameNumber of $($partOneFrames.Count)."
    $frameLines.Add("title @a title {text:$titleJson,color:`"#ffae00`",bold:true}")
    $frameLines.Add("execute as @a at @s run playsound minecraft:block.note_block.hat master @s ~ ~ ~ 0.24 1.8")
    if ($frameNumber -eq $partOneFrames.Count) {
        $frameLines.Add("title @a times 0t 24t 0t")
        $frameLines.Add("title @a title {text:$titleJson,color:`"#ffae00`",bold:true}")
    }
    Write-Lines -Path (Join-Path $OutputRoot "announce/part_1/frame_$frameNumber.mcfunction") -Lines $frameLines
}

$partOneAdvance = New-GeneratedHeader "Advances the short first warning, then pauses before the second."
$partOneAdvance.Add("execute unless score phase game_data matches 3 run return 0")
$partOneAdvance.Add("execute unless score boomdandy_stage botc_patch matches 3 run return 0")
$partOneAdvance.Add("scoreboard players add boomdandy_announce_step botc_patch 1")
for ($frameNumber = 1; $frameNumber -le $partOneFrames.Count; $frameNumber++) {
    $partOneAdvance.Add("execute if score boomdandy_announce_step botc_patch matches $frameNumber run function botc_patch:storyteller_tools/boomdandy/announce/part_1/frame_$frameNumber")
}
$partOneLastFrame = $partOneFrames.Count
$partOneAdvance.Add("execute if score boomdandy_announce_step botc_patch matches ..$($partOneLastFrame - 1) run schedule function botc_patch:storyteller_tools/boomdandy/announce/part_1/advance 3t replace")
$partOneAdvance.Add("execute if score boomdandy_announce_step botc_patch matches $partOneLastFrame run schedule function botc_patch:storyteller_tools/boomdandy/announce/part_2/start 24t replace")
Write-Lines -Path (Join-Path $OutputRoot "announce/part_1/advance.mcfunction") -Lines $partOneAdvance

$partTwoStart = New-GeneratedHeader "Clears the first warning and begins the main warning."
$partTwoStart.Add("execute unless score phase game_data matches 3 run return 0")
$partTwoStart.Add("execute unless score boomdandy_stage botc_patch matches 3 run return 0")
$partTwoStart.Add("scoreboard players set boomdandy_announce_step botc_patch 0")
$partTwoStart.Add('title @a title {"text":""}')
$partTwoStart.Add('title @a subtitle {"text":""}')
$partTwoStart.Add("schedule function botc_patch:storyteller_tools/boomdandy/announce/part_2/advance 1t replace")
Write-Lines -Path (Join-Path $OutputRoot "announce/part_2/start.mcfunction") -Lines $partTwoStart

$partTwoFrames = [System.Collections.Generic.List[object]]::new()
foreach ($prefix in Get-TypewriterPrefixes -Text $announcementPartTwo) {
    $partTwoFrames.Add([pscustomobject] @{ Title = $prefix; Subtitle = "" })
}
foreach ($prefix in Get-TypewriterPrefixes -Text $announcementSubtitle) {
    $partTwoFrames.Add([pscustomobject] @{ Title = $announcementPartTwo; Subtitle = $prefix })
}

for ($index = 0; $index -lt $partTwoFrames.Count; $index++) {
    $frameNumber = $index + 1
    $frame = $partTwoFrames[$index]
    $titleJson = [string] ($frame.Title | ConvertTo-Json -Compress)
    $subtitleJson = [string] ($frame.Subtitle | ConvertTo-Json -Compress)
    $frameLines = New-GeneratedHeader "Second warning frame $frameNumber of $($partTwoFrames.Count)."
    $frameLines.Add("title @a title {text:$titleJson,color:`"#ff4b1f`",bold:true}")
    $frameLines.Add("title @a subtitle {text:$subtitleJson,color:`"#ffffff`"}")
    $frameLines.Add("execute as @a at @s run playsound minecraft:block.note_block.hat master @s ~ ~ ~ 0.24 1.9")
    if ($frameNumber -eq $partTwoFrames.Count) {
        $frameLines.Add("title @a times 0t 60t 0t")
        $frameLines.Add("title @a title {text:$titleJson,color:`"#ff4b1f`",bold:true}")
        $frameLines.Add("title @a subtitle {text:$subtitleJson,color:`"#ffffff`"}")
    }
    Write-Lines -Path (Join-Path $OutputRoot "announce/part_2/frame_$frameNumber.mcfunction") -Lines $frameLines
}

$partTwoAdvance = New-GeneratedHeader "Types the main warning and its subtitle before a three-second reading pause."
$partTwoAdvance.Add("execute unless score phase game_data matches 3 run return 0")
$partTwoAdvance.Add("execute unless score boomdandy_stage botc_patch matches 3 run return 0")
$partTwoAdvance.Add("scoreboard players add boomdandy_announce_step botc_patch 1")
for ($frameNumber = 1; $frameNumber -le $partTwoFrames.Count; $frameNumber++) {
    $partTwoAdvance.Add("execute if score boomdandy_announce_step botc_patch matches $frameNumber run function botc_patch:storyteller_tools/boomdandy/announce/part_2/frame_$frameNumber")
}
$partTwoLastFrame = $partTwoFrames.Count
$partTwoAdvance.Add("execute if score boomdandy_announce_step botc_patch matches ..$($partTwoLastFrame - 1) run schedule function botc_patch:storyteller_tools/boomdandy/announce/part_2/advance 2t replace")
$partTwoAdvance.Add("execute if score boomdandy_announce_step botc_patch matches $partTwoLastFrame run schedule function botc_patch:storyteller_tools/boomdandy/announce/finish 60t replace")
Write-Lines -Path (Join-Path $OutputRoot "announce/part_2/advance.mcfunction") -Lines $partTwoAdvance

$announceFinish = New-GeneratedHeader "Starts Sybillian's countdown after the final warning frame."
$announceFinish.Add("execute unless score phase game_data matches 3 run return 0")
$announceFinish.Add("execute unless score boomdandy_stage botc_patch matches 3 run return 0")
$announceFinish.Add("execute store result score boomdandy_previous_time botc_patch run time query daytime")
$announceFinish.Add("scoreboard players set boomdandy_time_saved botc_patch 1")
$announceFinish.Add("time set midnight")
$announceFinish.Add("scoreboard players set boomdandy_stage botc_patch 4")
$announceFinish.Add("scoreboard players reset @a pointing_at")
$announceFinish.Add("function ct:loop/boomdandy/start")
Write-Lines -Path (Join-Path $OutputRoot "announce/finish.mcfunction") -Lines $announceFinish

$recordVote = New-GeneratedHeader "Copies the nearest selected seat ID onto the current finalist voter."
$recordVote.Add("scoreboard players operation @a[tag=botc_boomdandy_current_voter,limit=1] pointing_at = @s id")
Write-Lines -Path (Join-Path $OutputRoot "record_vote.mcfunction") -Lines $recordVote

$collectVote = New-GeneratedHeader "Records a finalist's nearest selected seat when they stand within voting range."
$collectVote.Add("tag @s add botc_boomdandy_current_voter")
$collectVote.Add("execute as @e[type=minecraft:item_display,tag=vote_marker,tag=botc_boomdandy_finalist_seat,sort=nearest,limit=1] at @s positioned ~ ~-3.5 ~ if entity @a[tag=botc_boomdandy_current_voter,distance=..2.75,limit=1] run function botc_patch:storyteller_tools/boomdandy/record_vote")
$collectVote.Add("tag @s remove botc_boomdandy_current_voter")
Write-Lines -Path (Join-Path $OutputRoot "collect_vote.mcfunction") -Lines $collectVote

$resolveWinner = New-GeneratedHeader "Starts the cinematic death of the unique finalist who received a strict majority."
$resolveWinner.Add("function botc_patch:storyteller_tools/boomdandy/effects/winner/start")
Write-Lines -Path (Join-Path $OutputRoot "resolve_winner.mcfunction") -Lines $resolveWinner

$resolveNoMajority = New-GeneratedHeader "Starts the harmless fizzle shown when no finalist receives a strict majority."
$resolveNoMajority.Add("function botc_patch:storyteller_tools/boomdandy/effects/tie/start")
Write-Lines -Path (Join-Path $OutputRoot "resolve_no_majority.mcfunction") -Lines $resolveNoMajority

$resolveVote = New-GeneratedHeader "Counts finalist proximity votes and resolves only a strict two-of-three majority."
$resolveVote.Add("execute unless score boomdandy_stage botc_patch matches 4 run return 0")
$resolveVote.Add("scoreboard players reset @a[tag=botc_boomdandy_finalist] pointing_at")
$resolveVote.Add("tag @a remove botc_boomdandy_current_voter")
$resolveVote.Add("tag @a remove botc_boomdandy_majority_target")
for ($seat = 1; $seat -le 15; $seat++) {
    $resolveVote.Add("scoreboard players set boomdandy_votes_$seat botc_patch 0")
}
$resolveVote.Add("execute as @a[tag=botc_boomdandy_finalist,tag=!dead,scores={id=1..15}] at @s run function botc_patch:storyteller_tools/boomdandy/collect_vote")
for ($seat = 1; $seat -le 15; $seat++) {
    $resolveVote.Add("execute as @a[tag=botc_boomdandy_finalist,scores={pointing_at=$seat}] run scoreboard players add boomdandy_votes_$seat botc_patch 1")
}
$resolveVote.Add("scoreboard players set boomdandy_majority_target botc_patch 0")
for ($seat = 1; $seat -le 15; $seat++) {
    $resolveVote.Add("execute if entity @a[tag=botc_boomdandy_finalist,scores={id=$seat},limit=1] if score boomdandy_votes_$seat botc_patch matches 2.. run scoreboard players set boomdandy_majority_target botc_patch $seat")
    $resolveVote.Add("execute if score boomdandy_majority_target botc_patch matches $seat run tag @a[tag=botc_boomdandy_finalist,scores={id=$seat},limit=1] add botc_boomdandy_majority_target")
}
$resolveVote.Add("execute if score boomdandy_majority_target botc_patch matches 0 run function botc_patch:storyteller_tools/boomdandy/resolve_no_majority")
$resolveVote.Add("execute if score boomdandy_majority_target botc_patch matches 1..15 run function botc_patch:storyteller_tools/boomdandy/resolve_winner")
$resolveVote.Add("scoreboard players reset @a[tag=botc_boomdandy_finalist] pointing_at")
$resolveVote.Add("tag @a remove botc_boomdandy_majority_target")
$resolveVote.Add("scoreboard players set boomdandy_stage botc_patch 5")
Write-Lines -Path (Join-Path $OutputRoot "resolve_vote.mcfunction") -Lines $resolveVote

$storeSelection = New-GeneratedHeader "Copies one selected player label into its stable confirmation slot."
$storeSelection.Add('$data modify storage botc_patch:dialogs boomdandy_selection.s$(target)_name set from storage botc_patch:grim editor.player_labels.p$(source)_name')
$storeSelection.Add('$data modify storage botc_patch:dialogs boomdandy_selection.s$(target)_role set from storage botc_patch:grim editor.player_labels.p$(source)_role')
$storeSelection.Add('$data modify storage botc_patch:dialogs boomdandy_selection.s$(target)_glyph set from storage botc_patch:grim editor.player_labels.p$(source)_glyph')
$storeSelection.Add('$data modify storage botc_patch:dialogs boomdandy_selection.s$(target)_color set from storage botc_patch:grim editor.player_labels.p$(source)_color')
$storeSelection.Add('$data modify storage botc_patch:dialogs boomdandy_selection.s$(target)_seat set value $(source)')
Write-Lines -Path (Join-Path $OutputRoot "store_selection.mcfunction") -Lines $storeSelection

$append = New-GeneratedHeader "Copies one eligible survivor into the next compact dialog entry."
$append.Add('$data modify storage botc_patch:dialogs boomdandy.e$(target)_name set from storage botc_patch:grim editor.player_labels.p$(source)_name')
$append.Add('$data modify storage botc_patch:dialogs boomdandy.e$(target)_role set from storage botc_patch:grim editor.player_labels.p$(source)_role')
$append.Add('$data modify storage botc_patch:dialogs boomdandy.e$(target)_glyph set from storage botc_patch:grim editor.player_labels.p$(source)_glyph')
$append.Add('$data modify storage botc_patch:dialogs boomdandy.e$(target)_color set from storage botc_patch:grim editor.player_labels.p$(source)_color')
$append.Add('$data modify storage botc_patch:dialogs boomdandy.e$(target)_seat set value $(source)')
Write-Lines -Path (Join-Path $OutputRoot "dialog/append.mcfunction") -Lines $append

$dialog = New-GeneratedHeader "Shows only living players not already chosen for the final three."
$dialog.Add("dialog clear @s")
$dialog.Add("execute unless entity @s[tag=storyteller] run return 0")
$dialog.Add('execute unless score phase game_data matches 3 run return run tellraw @s [{text:"! ",color:"red",bold:true},{text:"Boomdandy can only be resolved during nominations.",color:"gray",bold:false}]')
$dialog.Add('execute unless score boomdandy_stage botc_patch matches 1 run return run tellraw @s [{text:"! ",color:"red",bold:true},{text:"No Boomdandy Final Three selection is active.",color:"gray",bold:false}]')
$dialog.Add("function botc_patch:storyteller_tools/boomdandy/validate_population")
$dialog.Add("execute unless score boomdandy_population_ok botc_patch matches 1 run return 0")
$dialog.Add("function botc_patch:storyteller_tools/boomdandy/validate_selection")
$dialog.Add("execute if score boomdandy_selected botc_patch matches 3 run return run function botc_patch:storyteller_tools/boomdandy/show_confirm with storage botc_patch:dialogs boomdandy_selection")
$dialog.Add("function botc_patch:grim/editor/refresh_live_roles")
$dialog.Add("function botc_patch:grim/editor/player_labels/prepare")
$dialog.Add("data remove storage botc_patch:dialogs boomdandy")
$dialog.Add("scoreboard players set @s botc_st_menu_slot 0")
for ($seat = 1; $seat -le 15; $seat++) {
    $selector = "@a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_boomdandy_finalist,scores={id=$seat},limit=1]"
    $dialog.Add("execute if entity $selector run scoreboard players add @s botc_st_menu_slot 1")
    $dialog.Add(('execute if entity {0} run data modify storage botc_patch:dialogs lookup set value {{source:{1},target:0}}' -f $selector, $seat))
    $dialog.Add("execute if entity $selector store result storage botc_patch:dialogs lookup.target int 1 run scoreboard players get @s botc_st_menu_slot")
    $dialog.Add("execute if entity $selector run function botc_patch:storyteller_tools/boomdandy/dialog/append with storage botc_patch:dialogs lookup")
}
$dialog.Add("execute store result storage botc_patch:dialogs boomdandy.selected int 1 run scoreboard players get boomdandy_selected botc_patch")
for ($count = 1; $count -le 15; $count++) {
    $dialog.Add("execute if score @s botc_st_menu_slot matches $count run function botc_patch:storyteller_tools/boomdandy/dialog/count_$count with storage botc_patch:dialogs boomdandy")
}
$dialog.Add("scoreboard players reset @s botc_st_menu_slot")
Write-Lines -Path (Join-Path $OutputRoot "dialog.mcfunction") -Lines $dialog

for ($count = 1; $count -le 15; $count++) {
    $actions = [System.Collections.Generic.List[string]]::new()
    for ($index = 1; $index -le $count; $index++) {
        $actions.Add('{label:{text:"$(e' + $index + '_glyph)",font:"botc_patch:role_icons",color:"white",extra:[{text:" $(e' + $index + '_name)",font:"minecraft:default",color:"white"},{text:" ($(e' + $index + '_role))",font:"minecraft:default",color:"$(e' + $index + '_color)"}]},tooltip:{text:"Choose seat $(e' + $index + '_seat)",color:"gray"},action:{type:"run_command",command:"/botc boomdandy select $(e' + $index + '_seat)"}}')
    }

    $variant = New-GeneratedHeader "Final-three picker with $count eligible survivor(s)."
    $variant.Add('$dialog show @s {type:"multi_action",title:{text:"Boomdandy: Final Three",color:"dark_red",bold:true},body:{type:"plain_message",contents:{text:"Choose exactly three living players. Selected: $(selected) / 3",color:"gray"},width:380},columns:3,actions:[' + ($actions -join ',') + '],exit_action:{label:"Back",action:{type:"run_command",command:"/botc dialog_cancel"}}}')
    Write-Lines -Path (Join-Path $OutputRoot "dialog/count_$count.mcfunction") -Lines $variant
}

$prepareExecutionChoice = New-GeneratedHeader "Pauses before an executed Boomdandy commits to either supported execution path."
$prepareExecutionChoice.Add("execute unless entity @s[tag=storyteller] run return 0")
$prepareExecutionChoice.Add('execute unless score phase game_data matches 3 run return run tellraw @s [{text:"! ",color:"red",bold:true},{text:"Boomdandy can only be executed during nominations.",color:"gray",bold:false}]')
$prepareExecutionChoice.Add(('execute if entity @s[tag=botc_boomdandy_execution_pending] run return run function botc_patch:storyteller_tools/boomdandy/show_execution_choice' -f $pendingExecutionOwnerSelector))
$prepareExecutionChoice.Add(('execute if entity {0} run return run tellraw @s [{{text:"Another Storyteller is already choosing how to execute this Boomdandy.",color:"yellow"}}]' -f $pendingExecutionOwnerSelector))
$prepareExecutionChoice.Add(('execute unless entity {0} run tag @a remove botc_st_last_executed' -f $pendingExecutionTargetSelector))
$prepareExecutionChoice.Add(('execute unless entity {0} run return run tellraw @s [{{text:"! ",color:"red",bold:true}},{{text:"The marked execution target is no longer a living Boomdandy.",color:"gray",bold:false}}]' -f $pendingExecutionTargetSelector))
$prepareExecutionChoice.Add("tag @s remove botc_st_nom_execute_done")
$prepareExecutionChoice.Add("tag @s add botc_boomdandy_execution_pending")
$prepareExecutionChoice.Add("scoreboard players set grim_notice_boomdandy_done botc_patch 1")
$prepareExecutionChoice.Add("function botc_patch:storyteller_tools/boomdandy/show_execution_choice")
Write-Lines -Path (Join-Path $OutputRoot "prepare_execution_choice.mcfunction") -Lines $prepareExecutionChoice

$showExecutionChoice = New-GeneratedHeader "Shows the initiating Storyteller both Boomdandy execution paths before either path commits."
$showExecutionChoice.Add("dialog clear @s")
$showExecutionChoice.Add("execute unless entity @s[tag=storyteller,tag=botc_boomdandy_execution_pending] run return 0")
$showExecutionChoice.Add('execute unless score phase game_data matches 3 run tag @s remove botc_boomdandy_execution_pending')
$showExecutionChoice.Add('execute unless score phase game_data matches 3 run tag @a remove botc_st_last_executed')
$showExecutionChoice.Add('execute unless score phase game_data matches 3 run return run tellraw @s [{text:"! ",color:"red",bold:true},{text:"The Boomdandy execution choice expired because nominations ended.",color:"gray",bold:false}]')
$showExecutionChoice.Add(('execute unless entity {0} run tag @s remove botc_boomdandy_execution_pending' -f $pendingExecutionTargetSelector))
$showExecutionChoice.Add(('execute unless entity {0} run tag @a remove botc_st_last_executed' -f $pendingExecutionTargetSelector))
$showExecutionChoice.Add(('execute unless entity {0} run return run tellraw @s [{{text:"! ",color:"red",bold:true}},{{text:"The Boomdandy execution choice expired because the marked target changed.",color:"gray",bold:false}}]' -f $pendingExecutionTargetSelector))
$showExecutionChoice.Add('dialog show @s {type:"multi_action",title:{text:"Execute Boomdandy",color:"dark_red",bold:true},body:{type:"plain_message",contents:{text:"Choose how this Boomdandy is executed.\n\nUnique Execution: The TNT pyre plays, the Boomdandy dies, then Final Three begins.\nNormal Execution: Sybillian executes and kills the Boomdandy, then the game continues.",color:"gray"},width:430},columns:1,actions:[{label:{text:"Unique Execution",color:"dark_red",bold:true},action:{type:"run_command",command:"/botc boomdandy execute_unique"}},{label:{text:"Normal Execution",color:"yellow",bold:true},action:{type:"run_command",command:"/botc boomdandy execute_normal"}}],exit_action:{label:"Decide Later"}}')
Write-Lines -Path (Join-Path $OutputRoot "show_execution_choice.mcfunction") -Lines $showExecutionChoice

$executeUnique = New-GeneratedHeader "Commits the trusted unique Boomdandy pyre and Final Three path."
$executeUnique.Add("dialog clear @s")
$executeUnique.Add("execute unless entity @s[tag=storyteller,tag=botc_boomdandy_execution_pending] run return 0")
$executeUnique.Add('execute unless score phase game_data matches 3 run tag @s remove botc_boomdandy_execution_pending')
$executeUnique.Add('execute unless score phase game_data matches 3 run tag @a remove botc_st_last_executed')
$executeUnique.Add('execute unless score phase game_data matches 3 run return run tellraw @s [{text:"! ",color:"red",bold:true},{text:"Boomdandy can only be executed during nominations.",color:"gray",bold:false}]')
$executeUnique.Add(('execute unless entity {0} run tag @s remove botc_boomdandy_execution_pending' -f $pendingExecutionTargetSelector))
$executeUnique.Add(('execute unless entity {0} run tag @a remove botc_st_last_executed' -f $pendingExecutionTargetSelector))
$executeUnique.Add(('execute unless entity {0} run return run tellraw @s [{{text:"! ",color:"red",bold:true}},{{text:"The marked execution target is no longer a living Boomdandy.",color:"gray",bold:false}}]' -f $pendingExecutionTargetSelector))
$executeUnique.Add("tag @s remove botc_boomdandy_execution_pending")
$executeUnique.Add("tag @s add botc_boomdandy_pyre_owner")
$executeUnique.Add(('execute as {0} run function botc_patch:storyteller_tools/boomdandy_pyre/execute' -f $pendingExecutionTargetSelector))
$executeUnique.Add("function botc_patch:storyteller_tools/post_execution/replace_items")
Write-Lines -Path (Join-Path $OutputRoot "execute_unique.mcfunction") -Lines $executeUnique

$executeNormal = New-GeneratedHeader "Commits Sybillian's normal execution and death flow without starting Final Three."
$executeNormal.Add("dialog clear @s")
$executeNormal.Add("execute unless entity @s[tag=storyteller,tag=botc_boomdandy_execution_pending] run return 0")
$executeNormal.Add('execute unless score phase game_data matches 3 run tag @s remove botc_boomdandy_execution_pending')
$executeNormal.Add('execute unless score phase game_data matches 3 run tag @a remove botc_st_last_executed')
$executeNormal.Add('execute unless score phase game_data matches 3 run return run tellraw @s [{text:"! ",color:"red",bold:true},{text:"Boomdandy can only be executed during nominations.",color:"gray",bold:false}]')
$executeNormal.Add(('execute unless entity {0} run tag @s remove botc_boomdandy_execution_pending' -f $pendingExecutionTargetSelector))
$executeNormal.Add(('execute unless entity {0} run tag @a remove botc_st_last_executed' -f $pendingExecutionTargetSelector))
$executeNormal.Add(('execute unless entity {0} run return run tellraw @s [{{text:"! ",color:"red",bold:true}},{{text:"The marked execution target is no longer a living Boomdandy.",color:"gray",bold:false}}]' -f $pendingExecutionTargetSelector))
$executeNormal.Add("tag @s remove botc_boomdandy_execution_pending")
$executeNormal.Add(('execute as {0} run function ct:kill/execute/execute' -f $pendingExecutionTargetSelector))
$executeNormal.Add('execute as @a[tag=botc_st_last_executed,tag=!dead,scores={id=1..15,role=107},limit=1] run function ct:kill/die')
$executeNormal.Add("tag @s add botc_st_post_kill_resolved")
$executeNormal.Add("scoreboard players set grim_notice_boomdandy_done botc_patch 1")
$executeNormal.Add("tag @a remove botc_st_last_executed")
$executeNormal.Add("function botc_patch:storyteller_tools/post_execution/replace_items")
Write-Lines -Path (Join-Path $OutputRoot "execute_normal.mcfunction") -Lines $executeNormal

$start = New-GeneratedHeader "Starts or reopens the Boomdandy final-three selection before Sybillian's countdown."
$start.Add("tag @s add botc_st_tool_used")
$start.Add("execute unless entity @s[tag=storyteller] run return 0")
$start.Add('execute unless score phase game_data matches 3 run return run tellraw @s [{text:"! ",color:"red",bold:true},{text:"Boomdandy can only be resolved during nominations.",color:"gray",bold:false}]')
$start.Add('execute if entity @s[tag=botc_boomdandy_execution_pending] run return run function botc_patch:storyteller_tools/boomdandy/show_execution_choice')
$start.Add(('execute if entity {0} run return run tellraw @s [{{text:"Another Storyteller is choosing the Boomdandy execution path.",color:"yellow"}}]' -f $pendingExecutionOwnerSelector))
$start.Add('execute if score boomdandy_pyre_state botc_patch matches 1..2 run return run tellraw @s [{text:"Boomdandy\u0027s pyre execution is still resolving.",color:"yellow"}]')
$start.Add(('execute unless entity {0} run return run tellraw @s [{{text:"! ",color:"red",bold:true}},{{text:"The last executed player is not the Boomdandy.",color:"gray",bold:false}}]' -f $executedBoomdandySelector))
$start.Add("execute if score boomdandy_stage botc_patch matches 1 run return run function botc_patch:storyteller_tools/boomdandy/dialog")
$start.Add('execute if score boomdandy_stage botc_patch matches 2..4 run return run tellraw @s [{text:"Boomdandy is already resolving.",color:"yellow"}]')
$start.Add('execute if score boomdandy_stage botc_patch matches 5 run return run tellraw @s [{text:"Boomdandy has already been resolved this game.",color:"yellow"}]')
$start.Add("function botc_patch:storyteller_tools/boomdandy/validate_population")
$start.Add("execute unless score boomdandy_population_ok botc_patch matches 1 run return 0")
$start.Add("function botc_patch:storyteller_tools/boomdandy/reset_selection")
$start.Add("scoreboard players set boomdandy_stage botc_patch 1")
$start.Add("scoreboard players set grim_notice_boomdandy_done botc_patch 1")
$start.Add("scoreboard players set botc_item_maintenance_pending botc_patch 1")
$start.Add("function botc_patch:storyteller_tools/boomdandy/dialog")
Write-Lines -Path (Join-Path $OutputRoot "start.mcfunction") -Lines $start

$select = New-GeneratedHeader "Adds one still-living seat to the final three."
$select.Add("dialog clear @s")
$select.Add("execute unless entity @s[tag=storyteller] run return 0")
$select.Add('execute unless score phase game_data matches 3 run return run tellraw @s [{text:"! ",color:"red",bold:true},{text:"Boomdandy can only be resolved during nominations.",color:"gray",bold:false}]')
$select.Add('execute unless score boomdandy_stage botc_patch matches 1 run return run tellraw @s [{text:"! ",color:"red",bold:true},{text:"No Boomdandy Final Three selection is active.",color:"gray",bold:false}]')
$select.Add("execute if score boomdandy_selected botc_patch matches 3.. run return run function botc_patch:storyteller_tools/boomdandy/show_confirm with storage botc_patch:dialogs boomdandy_selection")
$select.Add('$execute unless entity @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_boomdandy_finalist,scores={id=$(seat)},limit=1] run return run tellraw @s [{text:"! ",color:"red",bold:true},{text:"That player is no longer available.",color:"gray",bold:false}]')
$select.Add("function botc_patch:grim/editor/refresh_live_roles")
$select.Add("function botc_patch:grim/editor/player_labels/prepare")
$select.Add("scoreboard players add boomdandy_selected botc_patch 1")
$select.Add('$tag @a[tag=!storyteller,tag=!spectator,tag=!dead,scores={id=$(seat)},limit=1] add botc_boomdandy_finalist')
$select.Add('$data modify storage botc_patch:dialogs lookup set value {source:$(seat),target:0}')
$select.Add("execute store result storage botc_patch:dialogs lookup.target int 1 run scoreboard players get boomdandy_selected botc_patch")
$select.Add("function botc_patch:storyteller_tools/boomdandy/store_selection with storage botc_patch:dialogs lookup")
$select.Add("execute if score boomdandy_selected botc_patch matches 3 run return run function botc_patch:storyteller_tools/boomdandy/show_confirm with storage botc_patch:dialogs boomdandy_selection")
$select.Add("function botc_patch:storyteller_tools/boomdandy/dialog")
Write-Lines -Path (Join-Path $OutputRoot "select_player.mcfunction") -Lines $select

$showConfirm = New-GeneratedHeader "Shows the three chosen survivors before any player is killed."
$showConfirm.Add('$dialog show @s {type:"multi_action",title:{text:"Confirm Final Three",color:"dark_red",bold:true},body:{type:"plain_message",contents:{text:"$(s1_glyph)",font:"botc_patch:role_icons",color:"white",extra:[{text:" $(s1_name)",font:"minecraft:default",color:"white"},{text:" ($(s1_role))\n",font:"minecraft:default",color:"$(s1_color)"},{text:"$(s2_glyph)",font:"botc_patch:role_icons",color:"white"},{text:" $(s2_name)",font:"minecraft:default",color:"white"},{text:" ($(s2_role))\n",font:"minecraft:default",color:"$(s2_color)"},{text:"$(s3_glyph)",font:"botc_patch:role_icons",color:"white"},{text:" $(s3_name)",font:"minecraft:default",color:"white"},{text:" ($(s3_role))",font:"minecraft:default",color:"$(s3_color)"},{text:"\n\nEvery other living player will die.",font:"minecraft:default",color:"gray"}]},width:380},columns:1,actions:[{label:{text:"Confirm Final Three",color:"dark_red",bold:true},action:{type:"run_command",command:"/botc boomdandy confirm"}},{label:{text:"Start Over",color:"yellow"},action:{type:"run_command",command:"/botc boomdandy restart"}}],exit_action:{label:"Back",action:{type:"run_command",command:"/botc dialog_cancel"}}}')
Write-Lines -Path (Join-Path $OutputRoot "show_confirm.mcfunction") -Lines $showConfirm

$restart = New-GeneratedHeader "Lets the Storyteller correct the final three before confirmation."
$restart.Add("dialog clear @s")
$restart.Add("execute unless entity @s[tag=storyteller] run return 0")
$restart.Add('execute unless score boomdandy_stage botc_patch matches 1 run return run tellraw @s [{text:"! ",color:"red",bold:true},{text:"No Boomdandy Final Three selection is active.",color:"gray",bold:false}]')
$restart.Add("function botc_patch:storyteller_tools/boomdandy/reset_selection")
$restart.Add("function botc_patch:storyteller_tools/boomdandy/dialog")
Write-Lines -Path (Join-Path $OutputRoot "restart.mcfunction") -Lines $restart

$confirm = New-GeneratedHeader "Locks the final three, trims the seats, and starts delayed one-by-one eliminations."
$confirm.Add("dialog clear @s")
$confirm.Add("execute unless entity @s[tag=storyteller] run return 0")
$confirm.Add('execute unless score phase game_data matches 3 run return run tellraw @s [{text:"! ",color:"red",bold:true},{text:"Boomdandy can only be resolved during nominations.",color:"gray",bold:false}]')
$confirm.Add('execute unless score boomdandy_stage botc_patch matches 1 run return run tellraw @s [{text:"! ",color:"red",bold:true},{text:"No Boomdandy Final Three selection is active.",color:"gray",bold:false}]')
$confirm.Add(('execute unless entity {0} run return run tellraw @s [{{text:"! ",color:"red",bold:true}},{{text:"The last executed player is not the Boomdandy.",color:"gray",bold:false}}]' -f $executedBoomdandySelector))
$confirm.Add("function botc_patch:storyteller_tools/boomdandy/validate_population")
$confirm.Add("execute unless score boomdandy_population_ok botc_patch matches 1 run return 0")
$confirm.Add("function botc_patch:storyteller_tools/boomdandy/validate_selection")
$confirm.Add('execute unless score boomdandy_selected botc_patch matches 3 run return run tellraw @s [{text:"! ",color:"red",bold:true},{text:"Choose exactly three living players before confirming.",color:"gray",bold:false}]')
$confirm.Add("scoreboard players set boomdandy_stage botc_patch 2")
$confirm.Add("scoreboard players set grim_notice_boomdandy_done botc_patch 1")
$confirm.Add("scoreboard players set boomdandy_elimination_remaining botc_patch 0")
$confirm.Add("scoreboard players set boomdandy_elimination_timer botc_patch 30")
$confirm.Add("scoreboard players set boomdandy_waiting_announced botc_patch 0")
$confirm.Add("tag @a remove botc_boomdandy_eliminate")
$confirm.Add("tag @a[tag=!storyteller,tag=!spectator,tag=!dead,tag=!botc_boomdandy_finalist,scores={id=1..15}] add botc_boomdandy_eliminate")
$confirm.Add("execute as @a[tag=botc_boomdandy_eliminate] run scoreboard players add boomdandy_elimination_remaining botc_patch 1")
$confirm.Add("function botc_patch:storyteller_tools/boomdandy/prepare_final_seats")
$confirm.Add("data remove storage botc_patch:dialogs boomdandy")
$confirm.Add("data remove storage botc_patch:dialogs boomdandy_selection")
$confirm.Add('tellraw @s [{text:"Final Three locked. Everyone else will die one by one.",color:"gold"}]')
$confirm.Add("execute if score boomdandy_elimination_remaining botc_patch matches 0 run function botc_patch:storyteller_tools/boomdandy/announce/start")
Write-Lines -Path (Join-Path $OutputRoot "confirm.mcfunction") -Lines $confirm

$tick = New-GeneratedHeader "Maintains the staged Boomdandy resolution and abandons invalid state safely."
$tick.Add("execute unless score phase game_data matches 3 if score boomdandy_stage botc_patch matches 1.. run function botc_patch:storyteller_tools/boomdandy/cleanup")
$tick.Add("execute if score boomdandy_stage botc_patch matches 2..4 run function botc_patch:storyteller_tools/boomdandy/monitor_finalists")
$tick.Add("execute if score boomdandy_stage botc_patch matches 2 if score boomdandy_elimination_timer botc_patch matches 1.. run scoreboard players remove boomdandy_elimination_timer botc_patch 1")
$tick.Add("execute if score boomdandy_stage botc_patch matches 2 if score boomdandy_elimination_timer botc_patch matches 0 run function botc_patch:storyteller_tools/boomdandy/eliminate_next")
$tick.Add("execute if score boomdandy_stage botc_patch matches 4 run function botc_patch:storyteller_tools/boomdandy/effects/tick")
$tick.Add("execute if score boomdandy_stage botc_patch matches 4 if score bd_cd game_data matches ..-21 run function botc_patch:storyteller_tools/boomdandy/resolve_vote")
$tick.Add("execute if score boomdandy_stage botc_patch matches 0 run tag @a remove botc_boomdandy_finalist")
Write-Lines -Path (Join-Path $OutputRoot "tick.mcfunction") -Lines $tick

$upstreamExecuteLines = @(Get-Content -LiteralPath $UpstreamExecutePath)
$lightningCommand = "execute at @s run summon minecraft:lightning_bolt"
$pyreCloseCommands = @(
    "fill 125 72 65 128 72 62 minecraft:campfire[facing=north,lit=false] replace minecraft:campfire",
    "fill 129 73 61 124 73 66 minecraft:light[level=0] replace minecraft:barrier"
)
$lightningCount = @($upstreamExecuteLines | Where-Object { $_ -eq $lightningCommand }).Count
if ($lightningCount -ne 4) {
    throw "Expected exactly four upstream pyre lightning commands, found $lightningCount. Review the Boomdandy non-lightning adapter."
}
foreach ($pyreCloseCommand in $pyreCloseCommands) {
    $pyreCloseCount = @($upstreamExecuteLines | Where-Object { $_ -eq $pyreCloseCommand }).Count
    if ($pyreCloseCount -ne 1) {
        throw "Expected exactly one upstream pyre-close command '$pyreCloseCommand', found $pyreCloseCount. Review the Boomdandy delayed pyre close."
    }
}

$pyreExecute = New-GeneratedHeader "Executes the Boomdandy through Sybillian's non-lightning announcement/tag contract while leaving the pyre lit for the TNT rain."
foreach ($line in $upstreamExecuteLines) {
    if ($line -ne $lightningCommand -and $line -notin $pyreCloseCommands) {
        $pyreExecute.Add($line)
    }
}
$pyreExecute.Add("function botc_patch:storyteller_tools/boomdandy_pyre/start")
Write-Lines -Path (Join-Path $PyreOutputRoot "execute.mcfunction") -Lines $pyreExecute

$pyreCleanup = New-GeneratedHeader "Removes only the transient Boomdandy pyre spectacle without applying death."
$pyreCleanup.Add("kill @e[type=minecraft:block_display,tag=botc_boomdandy_pyre_tnt]")
foreach ($pyreCloseCommand in $pyreCloseCommands) {
    $pyreCleanup.Add($pyreCloseCommand)
}
$pyreCleanup.Add("scoreboard players set boomdandy_pyre_state botc_patch 0")
$pyreCleanup.Add("scoreboard players set boomdandy_pyre_timer botc_patch 0")
$pyreCleanup.Add("scoreboard players set boomdandy_pyre_spawned botc_patch 0")
$pyreCleanup.Add("scoreboard players set boomdandy_pyre_impacted botc_patch 0")
$pyreCleanup.Add("scoreboard players set boomdandy_pyre_waiting botc_patch 0")
$pyreCleanup.Add("tag @a remove botc_boomdandy_pyre_owner")
Write-Lines -Path (Join-Path $PyreOutputRoot "cleanup.mcfunction") -Lines $pyreCleanup

$pyreStart = New-GeneratedHeader "Starts a bounded five-second cosmetic TNT rain while the executed Boomdandy remains alive."
$pyreStart.Add("execute unless entity @s[tag=botc_st_last_executed,scores={id=1..15,role=107}] run return 0")
$pyreStart.Add("kill @e[type=minecraft:block_display,tag=botc_boomdandy_pyre_tnt]")
$pyreStart.Add("scoreboard players set boomdandy_pyre_state botc_patch 1")
$pyreStart.Add("scoreboard players set boomdandy_pyre_timer botc_patch 0")
$pyreStart.Add("scoreboard players set boomdandy_pyre_spawned botc_patch 0")
$pyreStart.Add("scoreboard players set boomdandy_pyre_impacted botc_patch 0")
$pyreStart.Add("scoreboard players set boomdandy_pyre_waiting botc_patch 0")
$pyreStart.Add("playsound minecraft:entity.tnt.primed master @a 127 88 64 0.70 0.85")
Write-Lines -Path (Join-Path $PyreOutputRoot "start.mcfunction") -Lines $pyreStart

$pyreSpawn = New-GeneratedHeader "Spawns one cosmetic TNT display at a bounded random position, except for the centered twelfth impact."
$pyreSpawn.Add("tag @e[type=minecraft:block_display,tag=botc_boomdandy_pyre_tnt] remove botc_boomdandy_pyre_new")
$pyreSpawn.Add("execute unless score boomdandy_pyre_spawned botc_patch matches 11 store result score boomdandy_pyre_pick botc_patch run random value 1..49")
$positionIndex = 0
foreach ($x in @(121, 123, 125, 127, 129, 131, 133)) {
    foreach ($z in @(58, 60, 62, 64, 66, 68, 70)) {
        $positionIndex++
        $pyreSpawn.Add(('execute unless score boomdandy_pyre_spawned botc_patch matches 11 if score boomdandy_pyre_pick botc_patch matches {0} positioned {1}.5 88 {2}.5 run summon minecraft:block_display ~ ~ ~ {{Tags:["botc_boomdandy_pyre_tnt","botc_boomdandy_pyre_new"],block_state:{{Name:"minecraft:tnt"}},teleport_duration:1,view_range:80f,shadow_radius:0.5f,transformation:{{translation:[-0.5f,-0.5f,-0.5f],left_rotation:[0f,0f,0f,1f],scale:[1f,1f,1f],right_rotation:[0f,0f,0f,1f]}}}}' -f $positionIndex, $x, $z))
    }
}
$pyreSpawn.Add('execute if score boomdandy_pyre_spawned botc_patch matches 11 positioned 127.0 88 64.0 run summon minecraft:block_display ~ ~ ~ {Tags:["botc_boomdandy_pyre_tnt","botc_boomdandy_pyre_new"],block_state:{Name:"minecraft:tnt"},teleport_duration:1,view_range:80f,shadow_radius:0.5f,transformation:{translation:[-0.5f,-0.5f,-0.5f],left_rotation:[0f,0f,0f,1f],scale:[1f,1f,1f],right_rotation:[0f,0f,0f,1f]}}')
$pyreSpawn.Add("scoreboard players set @e[type=minecraft:block_display,tag=botc_boomdandy_pyre_new] botc_patch 30")
$pyreSpawn.Add("tag @e[type=minecraft:block_display,tag=botc_boomdandy_pyre_new] remove botc_boomdandy_pyre_new")
$pyreSpawn.Add("scoreboard players add boomdandy_pyre_spawned botc_patch 1")
Write-Lines -Path (Join-Path $PyreOutputRoot "spawn.mcfunction") -Lines $pyreSpawn

$pyreFallStages = @(
    @{ ScoreRange = "28..30"; Distance = "0.05" },
    @{ ScoreRange = "25..27"; Distance = "0.15" },
    @{ ScoreRange = "22..24"; Distance = "0.25" },
    @{ ScoreRange = "19..21"; Distance = "0.35" },
    @{ ScoreRange = "16..18"; Distance = "0.45" },
    @{ ScoreRange = "13..15"; Distance = "0.55" },
    @{ ScoreRange = "10..12"; Distance = "0.65" },
    @{ ScoreRange = "7..9"; Distance = "0.75" },
    @{ ScoreRange = "4..6"; Distance = "0.85" },
    @{ ScoreRange = "1..3"; Distance = "0.95" }
)

$pyreImpact = New-GeneratedHeader "Dispatches the next progressively larger cosmetic impact and lets the twelfth advance to death."
$pyreImpact.Add("scoreboard players add boomdandy_pyre_impacted botc_patch 1")
for ($impactNumber = 1; $impactNumber -le 12; $impactNumber++) {
    $pyreImpact.Add("execute if score boomdandy_pyre_impacted botc_patch matches $impactNumber run function botc_patch:storyteller_tools/boomdandy_pyre/impact/effect_$impactNumber")
}
$pyreImpact.Add("playsound minecraft:entity.generic.explode master @a ~ ~ ~ 1.00 0.82")
$pyreImpact.Add("execute if score boomdandy_pyre_impacted botc_patch matches 12 run function botc_patch:storyteller_tools/boomdandy_pyre/final_impact")
$pyreImpact.Add("kill @s")
Write-Lines -Path (Join-Path $PyreOutputRoot "impact.mcfunction") -Lines $pyreImpact

for ($impactNumber = 1; $impactNumber -le 12; $impactNumber++) {
    $spreadHorizontal = (0.14 + (0.055 * $impactNumber)).ToString("0.000", $invariantCulture)
    $spreadVertical = (0.10 + (0.040 * $impactNumber)).ToString("0.000", $invariantCulture)
    $smokeCount = 4 + (3 * $impactNumber)
    $flameCount = 2 + (2 * $impactNumber)
    $poofCount = 2 + (2 * $impactNumber)
    $sparkCount = 2 * $impactNumber
    $fireworkCount = $impactNumber
    $endRodCount = $impactNumber

    $impactEffect = New-GeneratedHeader "Renders cosmetic Boomdandy TNT impact $impactNumber of 12 with strictly increasing particle density and layers."
    $impactEffect.Add("particle minecraft:explosion ~ ~ ~ 0 0 0 0 1 force @a")
    $impactEffect.Add("particle minecraft:poof ~ ~0.10 ~ $spreadHorizontal $spreadVertical $spreadHorizontal 0.08 $poofCount force @a")
    $impactEffect.Add("particle minecraft:smoke ~ ~0.18 ~ $spreadHorizontal $spreadVertical $spreadHorizontal 0.03 $smokeCount force @a")
    $impactEffect.Add("particle minecraft:flame ~ ~0.12 ~ $spreadHorizontal $spreadVertical $spreadHorizontal 0.06 $flameCount force @a")
    if ($impactNumber -ge 3) {
        $impactEffect.Add("particle minecraft:electric_spark ~ ~0.20 ~ $spreadHorizontal $spreadVertical $spreadHorizontal 0.12 $sparkCount force @a")
    }
    if ($impactNumber -ge 5) {
        $impactEffect.Add("particle minecraft:firework ~ ~0.25 ~ $spreadHorizontal $spreadVertical $spreadHorizontal 0.15 $fireworkCount force @a")
    }
    if ($impactNumber -ge 7) {
        $impactEffect.Add("particle minecraft:end_rod ~ ~0.30 ~ $spreadHorizontal $spreadVertical $spreadHorizontal 0.09 $endRodCount force @a")
    }
    if ($impactNumber -ge 8) {
        $impactEffect.Add("particle minecraft:explosion ~ ~0.35 ~ 0 0 0 0 1 force @a")
    }
    if ($impactNumber -ge 9) {
        $impactEffect.Add("particle minecraft:totem_of_undying ~ ~0.45 ~ 0 0 0 0 5 force @a")
    }
    if ($impactNumber -ge 10) {
        $impactEffect.Add("particle minecraft:explosion_emitter ~ ~0.10 ~ 0 0 0 0 1 force @a")
    }
    if ($impactNumber -ge 11) {
        $impactEffect.Add("particle minecraft:explosion_emitter ~0.35 ~0.20 ~-0.35 0 0 0 0 1 force @a")
    }
    if ($impactNumber -eq 12) {
        $impactEffect.Add("particle minecraft:explosion_emitter ~-0.45 ~0.25 ~0.45 0 0 0 0 1 force @a")
        $impactEffect.Add("particle minecraft:explosion_emitter ~0.50 ~0.35 ~0.50 0 0 0 0 1 force @a")
        $impactEffect.Add("particle minecraft:totem_of_undying ~ ~0.90 ~ 0.25 0.25 0.25 0.08 24 force @a")
        $impactEffect.Add("particle minecraft:sonic_boom ~ ~0.55 ~ 0 0 0 0 1 force @a")
    }
    Write-Lines -Path (Join-Path $PyreOutputRoot "impact/effect_$impactNumber.mcfunction") -Lines $impactEffect
}

$pyreFinalImpact = New-GeneratedHeader "Extinguishes the still-lit pyre after the last visible TNT impact, then moves to the exact-once Boomdandy death boundary."
foreach ($pyreCloseCommand in $pyreCloseCommands) {
    $pyreFinalImpact.Add($pyreCloseCommand)
}
$pyreFinalImpact.Add("scoreboard players set boomdandy_pyre_state botc_patch 2")
$pyreFinalImpact.Add("function botc_patch:storyteller_tools/boomdandy_pyre/try_finish")
Write-Lines -Path (Join-Path $PyreOutputRoot "final_impact.mcfunction") -Lines $pyreFinalImpact

$pyreTryFinish = New-GeneratedHeader "Kills the returned last-executed Boomdandy after the final impact, or waits safely while they are offline."
$pyreTryFinish.Add("execute unless score phase game_data matches 3 run return run function botc_patch:storyteller_tools/boomdandy_pyre/cleanup")
$pyreTryFinish.Add(('execute unless entity {0} if score boomdandy_pyre_waiting botc_patch matches 0 run tellraw @a[tag=storyteller] [{{text:"Boomdandy death is waiting for the executed player to return.",color:"yellow"}}]' -f $executedBoomdandySelector))
$pyreTryFinish.Add(('execute unless entity {0} run scoreboard players set boomdandy_pyre_waiting botc_patch 1' -f $executedBoomdandySelector))
$pyreTryFinish.Add(('execute unless entity {0} run return 0' -f $executedBoomdandySelector))
$pyreTryFinish.Add('execute as @a[tag=botc_st_last_executed,tag=!dead,scores={id=1..15,role=107},limit=1] run function ct:kill/die')
$pyreTryFinish.Add('execute if entity @a[tag=botc_st_last_executed,tag=dead,scores={id=1..15,role=107},limit=1] run function botc_patch:storyteller_tools/boomdandy_pyre/complete')
Write-Lines -Path (Join-Path $PyreOutputRoot "try_finish.mcfunction") -Lines $pyreTryFinish

$pyreComplete = New-GeneratedHeader "Unlocks post-execution tools and opens the unchanged Final Three flow only after death succeeds."
$pyreComplete.Add("scoreboard players set boomdandy_pyre_state botc_patch 0")
$pyreComplete.Add("scoreboard players set boomdandy_pyre_waiting botc_patch 0")
$pyreComplete.Add("tag @a[tag=storyteller,tag=botc_st_post_execution] add botc_st_post_kill_resolved")
$pyreComplete.Add("scoreboard players set botc_item_maintenance_pending botc_patch 1")
$pyreComplete.Add("execute as @a[tag=storyteller,tag=botc_st_post_execution] run function botc_patch:storyteller_tools/post_execution/replace_items")
$pyreComplete.Add("execute as @a[tag=storyteller,tag=botc_boomdandy_pyre_owner,limit=1] run function botc_patch:storyteller_tools/boomdandy/start")
$pyreComplete.Add("tag @a remove botc_boomdandy_pyre_owner")
Write-Lines -Path (Join-Path $PyreOutputRoot "complete.mcfunction") -Lines $pyreComplete

$pyreTick = New-GeneratedHeader "Ticks the independent TNT rain and preserves the final-impact death boundary across disconnects and reloads."
$pyreTick.Add("execute unless score phase game_data matches 3 if score boomdandy_pyre_state botc_patch matches 1..2 run function botc_patch:storyteller_tools/boomdandy_pyre/cleanup")
$pyreTick.Add("execute if score boomdandy_pyre_state botc_patch matches 1 run scoreboard players add boomdandy_pyre_timer botc_patch 1")
for ($spawnTick = 1; $spawnTick -le 67; $spawnTick += 6) {
    $pyreTick.Add("execute if score boomdandy_pyre_state botc_patch matches 1 if score boomdandy_pyre_timer botc_patch matches $spawnTick run function botc_patch:storyteller_tools/boomdandy_pyre/spawn")
}
foreach ($fallStage in $pyreFallStages) {
    $pyreTick.Add(('execute if score boomdandy_pyre_state botc_patch matches 1 as @e[type=minecraft:block_display,tag=botc_boomdandy_pyre_tnt,scores={{botc_patch={0}}}] at @s run tp @s ~ ~-{1} ~' -f $fallStage.ScoreRange, $fallStage.Distance))
}
$pyreTick.Add("execute if score boomdandy_pyre_state botc_patch matches 1 run scoreboard players remove @e[type=minecraft:block_display,tag=botc_boomdandy_pyre_tnt,scores={botc_patch=1..}] botc_patch 1")
$pyreTick.Add("execute if score boomdandy_pyre_state botc_patch matches 1 as @e[type=minecraft:block_display,tag=botc_boomdandy_pyre_tnt,scores={botc_patch=0}] at @s run function botc_patch:storyteller_tools/boomdandy_pyre/impact")
$pyreTick.Add("execute if score boomdandy_pyre_state botc_patch matches 2 run function botc_patch:storyteller_tools/boomdandy_pyre/try_finish")
$pyreTick.Add("execute if score boomdandy_pyre_state botc_patch matches 0 if entity @e[type=minecraft:block_display,tag=botc_boomdandy_pyre_tnt] run kill @e[type=minecraft:block_display,tag=botc_boomdandy_pyre_tnt]")
$pyreTick.Add("execute if score boomdandy_pyre_state botc_patch matches 0 run tag @a remove botc_boomdandy_pyre_owner")
Write-Lines -Path (Join-Path $PyreOutputRoot "tick.mcfunction") -Lines $pyreTick

Write-Host "Generated guarded Boomdandy final-three flow and separate pyre TNT rain." -ForegroundColor Green
