Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$RepoRoot = Split-Path -Parent $PSScriptRoot
$OutputPath = Join-Path $RepoRoot "Jays-Patch/datapack/data/botc_patch/function/grim/dialog.mcfunction"
$VariantDir = Join-Path $RepoRoot "Jays-Patch/datapack/data/botc_patch/function/grim/dialog"
$RoleGlyphHelper = Join-Path $RepoRoot "tools/lib/role-icon-glyphs.ps1"
$DialogIconPath = Join-Path $RepoRoot "Jays-Patch/dialog-icons.json"
$MusicTrackPath = Join-Path $RepoRoot "Jays-Patch/music-tracks.json"
$GreedyAbilityOverridePath = Join-Path $RepoRoot "Jays-Patch/greedy-ability-overrides.json"
$DialogIconHelper = Join-Path $RepoRoot "tools/lib/dialog-icons.ps1"
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)

. $RoleGlyphHelper
. $DialogIconHelper
$noneGlyph = Get-BotcRoleIconGlyph -RoleScore 0
$icons = Get-BotcDialogIconCatalog -DialogIconPath $DialogIconPath -MusicTrackPath $MusicTrackPath
$goodWinLabel = New-BotcDialogGlyphLabel -Glyph (Get-BotcDialogIconGlyph -Catalog $icons -Id "good_win") -Font "botc_patch:ui_icons" -Text "Good Wins" -Color "#0000aa" -Bold $true
$evilWinLabel = New-BotcDialogGlyphLabel -Glyph (Get-BotcDialogIconGlyph -Catalog $icons -Id "evil_win") -Font "botc_patch:ui_icons" -Text "Evil Wins" -Color "#aa0000" -Bold $true
$rescindLabel = New-BotcDialogGlyphLabel -Glyph (Get-BotcDialogIconGlyph -Catalog $icons -Id "reset") -Font "botc_patch:ui_icons" -Text "Cancel Reveal" -Color "dark_red" -Bold $true
$closeLabel = New-BotcDialogGlyphLabel -Glyph (Get-BotcDialogIconGlyph -Catalog $icons -Id "back") -Font "botc_patch:ui_icons" -Text "Close" -Color "gray"
$titleLabel = New-BotcDialogGlyphLabel -Glyph (Get-BotcDialogIconGlyph -Catalog $icons -Id "reveal_grimoire") -Font "botc_patch:ui_icons" -Text "Grimoire Reveal" -Color "white"
$greedyAbilityDocument = Get-Content -LiteralPath $GreedyAbilityOverridePath -Raw -Encoding UTF8 | ConvertFrom-Json
if ([int] $greedyAbilityDocument.schemaVersion -ne 1) {
    throw "Unsupported Greedy ability override schema version '$($greedyAbilityDocument.schemaVersion)'."
}
$greedyAbilityOverrides = @($greedyAbilityDocument.overrides)
if ($greedyAbilityOverrides.Count -ne [int] $greedyAbilityDocument.expectedOverrideCount) {
    throw "Greedy ability override count is $($greedyAbilityOverrides.Count), expected $($greedyAbilityDocument.expectedOverrideCount)."
}
$greedyAbilityRoles = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
foreach ($override in $greedyAbilityOverrides) {
    $roleName = [string] $override.role
    if ($roleName -notmatch '^[a-z0-9_]+$' -or -not $greedyAbilityRoles.Add($roleName)) {
        throw "Greedy ability override contains an invalid or duplicate role '$roleName'."
    }
}

function New-Header {
    param([string] $Responsibility)

    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add("# Generated by tools/generate-grim-dialog.ps1.")
    $lines.Add("# Do not hand-edit this file; update the generator and regenerate.")
    if (-not [string]::IsNullOrWhiteSpace($Responsibility)) {
        $lines.Add("# $Responsibility")
    }
    return ,$lines
}

function Write-Lines {
    param(
        [string] $Path,
        [System.Collections.Generic.List[string]] $Lines
    )

    [System.IO.File]::WriteAllText($Path, ($Lines -join "`n") + "`n", $utf8NoBom)
}

function New-DialogLine {
    param([int] $SeatCount)

    $dialogActions = [System.Collections.Generic.List[string]]::new()
    $dialogActions.Add('{label:' + $goodWinLabel + ',action:{type:"run_command",command:"/botc winner good"}}')
    $dialogActions.Add('{label:' + $evilWinLabel + ',action:{type:"run_command",command:"/botc winner evil"}}')
    for ($index = 1; $index -le $SeatCount; $index++) {
        $dialogActions.Add('{label:{text:"$(e' + $index + '_glyph)",font:"botc_patch:role_icons",color:"white",extra:[{text:" $(e' + $index + '_name)",font:"minecraft:default",color:"white"},{text:" ($(e' + $index + '_role))",font:"minecraft:default",color:"$(e' + $index + '_color)"}]},tooltip:{translate:"clocktower.role.$(e' + $index + '_ability_role).desc",fallback:"Character unknown",color:"gray"},action:{type:"run_command",command:"/botc grimoire reveal_seat_$(e' + $index + '_seat)"}}')
    }
    $dialogActions.Add('{label:' + $rescindLabel + ',action:{type:"run_command",command:"/botc grimoire rescind_confirm"}}')

    $macroPrefix = if ($SeatCount -gt 0) { '$' } else { '' }
    return $macroPrefix + 'dialog show @s {type:"multi_action",title:' + $titleLabel + ',columns:2,actions:[' + ($dialogActions -join ',') + '],exit_action:{label:' + $closeLabel + ',action:{type:"run_command",command:"/botc grimoire close_dialog"}}}'
}

New-Item -ItemType Directory -Path (Split-Path -Parent $OutputPath) -Force | Out-Null
New-Item -ItemType Directory -Path $VariantDir -Force | Out-Null

$prepareLines = New-Header "Prepares immutable reveal-snapshot names, role labels, and alignment colors."
$prepareLines.Add("data remove storage botc_patch:grim reveal_dialog")
for ($seat = 1; $seat -le 15; $seat++) {
    $prepareLines.Add(('data modify storage botc_patch:grim reveal_dialog.p{0}_name set value "Seat {0}"' -f $seat))
    $prepareLines.Add(('data modify storage botc_patch:grim reveal_dialog.p{0}_role set value "Unknown"' -f $seat))
    $prepareLines.Add(('data modify storage botc_patch:grim reveal_dialog.p{0}_ability_role set value "none"' -f $seat))
    $prepareLines.Add(('data modify storage botc_patch:grim reveal_dialog.p{0}_glyph set value "{1}"' -f $seat, $noneGlyph))
    $prepareLines.Add(('data modify storage botc_patch:grim reveal_dialog.p{0}_color set value "#aaaaaa"' -f $seat))
    $prepareLines.Add(('execute if score grim_seat_{0}_occupied botc_patch matches 1 if score grim_seat_{0}_alignment botc_patch matches 1 run data modify storage botc_patch:grim reveal_dialog.p{0}_color set value "#55aaff"' -f $seat))
    $prepareLines.Add(('execute if score grim_seat_{0}_occupied botc_patch matches 1 if score grim_seat_{0}_alignment botc_patch matches 2 run data modify storage botc_patch:grim reveal_dialog.p{0}_color set value "#ff5555"' -f $seat))
    $prepareLines.Add(('execute if score grim_seat_{0}_occupied botc_patch matches 1 if data storage ct:players players.p{0} unless data storage ct:players players{{p{0}:"Nobody!"}} run data modify storage botc_patch:grim reveal_dialog.p{0}_name set from storage ct:players players.p{0}' -f $seat))
    $prepareLines.Add(('data modify storage botc_patch:grim reveal_lookup set value {{seat:{0},score:0}}' -f $seat))
    $prepareLines.Add(('execute if score grim_seat_{0}_occupied botc_patch matches 1 store result storage botc_patch:grim reveal_lookup.score int 1 run scoreboard players get grim_seat_{0}_role botc_patch' -f $seat))
    $prepareLines.Add(('execute if score grim_seat_{0}_occupied botc_patch matches 1 run function botc_patch:grim/dialog/prepare_role with storage botc_patch:grim reveal_lookup' -f $seat))
}
Write-Lines -Path (Join-Path $VariantDir "prepare.mcfunction") -Lines $prepareLines

$prepareRoleLines = New-Header "Resolves one snapshot role through the trusted Storyteller editor catalog."
$prepareRoleLines.Add('$data modify storage botc_patch:grim reveal_dialog.p$(seat)_role set from storage botc_patch:grim editor.score_catalog.s$(score).name')
$prepareRoleLines.Add('$data modify storage botc_patch:grim reveal_dialog.p$(seat)_ability_role set from storage botc_patch:grim editor.score_catalog.s$(score).id')
$prepareRoleLines.Add('$data modify storage botc_patch:grim reveal_dialog.p$(seat)_glyph set from storage botc_patch:grim editor.score_catalog.s$(score).glyph')
foreach ($override in $greedyAbilityOverrides) {
    $roleName = [string] $override.role
    $prepareRoleLines.Add(('$execute if score buffet_mode botc_patch matches 1 if data storage botc_patch:grim editor.score_catalog.s$(score){{id:"{0}"}} run data modify storage botc_patch:grim reveal_dialog.p$(seat)_ability_role set value "greedy_{0}"' -f $roleName))
}
Write-Lines -Path (Join-Path $VariantDir "prepare_role.mcfunction") -Lines $prepareRoleLines

$appendLines = New-Header "Copies one occupied unrevealed seat into the next compact reveal-dialog entry."
$appendLines.Add('$data modify storage botc_patch:grim reveal_dialog_visible.e$(target)_name set from storage botc_patch:grim reveal_dialog.p$(source)_name')
$appendLines.Add('$data modify storage botc_patch:grim reveal_dialog_visible.e$(target)_role set from storage botc_patch:grim reveal_dialog.p$(source)_role')
$appendLines.Add('$data modify storage botc_patch:grim reveal_dialog_visible.e$(target)_ability_role set from storage botc_patch:grim reveal_dialog.p$(source)_ability_role')
$appendLines.Add('$data modify storage botc_patch:grim reveal_dialog_visible.e$(target)_glyph set from storage botc_patch:grim reveal_dialog.p$(source)_glyph')
$appendLines.Add('$data modify storage botc_patch:grim reveal_dialog_visible.e$(target)_color set from storage botc_patch:grim reveal_dialog.p$(source)_color')
$appendLines.Add('$data modify storage botc_patch:grim reveal_dialog_visible.e$(target)_seat set value $(source)')
Write-Lines -Path (Join-Path $VariantDir "append.mcfunction") -Lines $appendLines

$lines = New-Header "Compacts unrevealed seats and dispatches the stable one-page reveal dialog."
$lines.Add('execute unless score grim_active botc_patch matches 1 run tellraw @s [{"text":"! ","color":"red","bold":true},{"text":"Start ","color":"gray","bold":false},{"text":"Reveal Grimoire","color":"gold","bold":true},{"text":" first.","color":"gray","bold":false}]')
$lines.Add("execute if score grim_active botc_patch matches 1 run function botc_patch:grim/dialog/prepare")
$lines.Add("execute if score grim_active botc_patch matches 1 run data remove storage botc_patch:grim reveal_dialog_visible")
$lines.Add("execute if score grim_active botc_patch matches 1 run scoreboard players set grim_dialog_visible_size botc_patch 0")
for ($seat = 1; $seat -le 15; $seat++) {
    $condition = "execute if score grim_active botc_patch matches 1 if score grim_seat_$($seat)_occupied botc_patch matches 1 unless score grim_seat_$($seat)_revealed botc_patch matches 1"
    $lines.Add("$condition run scoreboard players add grim_dialog_visible_size botc_patch 1")
    $lines.Add("$condition run data modify storage botc_patch:grim reveal_dialog_lookup set value {source:$seat,target:0}")
    $lines.Add("$condition store result storage botc_patch:grim reveal_dialog_lookup.target int 1 run scoreboard players get grim_dialog_visible_size botc_patch")
    $lines.Add("$condition run function botc_patch:grim/dialog/append with storage botc_patch:grim reveal_dialog_lookup")
}
for ($seatCount = 0; $seatCount -le 15; $seatCount++) {
    $suffix = if ($seatCount -gt 0) { " with storage botc_patch:grim reveal_dialog" } else { "" }
    if ($seatCount -gt 0) {
        $suffix = " with storage botc_patch:grim reveal_dialog_visible"
    }
    $lines.Add("execute if score grim_active botc_patch matches 1 if score grim_dialog_visible_size botc_patch matches $seatCount run function botc_patch:grim/dialog/count_$seatCount$suffix")
}
$lines.Add("execute if score grim_active botc_patch matches 1 unless score grim_dialog_visible_size botc_patch matches 0..15 run function botc_patch:grim/dialog/count_15 with storage botc_patch:grim reveal_dialog_visible")
Write-Lines -Path $OutputPath -Lines $lines

for ($seatCount = 0; $seatCount -le 15; $seatCount++) {
    $variantLines = New-Header "Reveal dialog for $seatCount captured seats."
    $variantLines.Add((New-DialogLine -SeatCount $seatCount))
    Write-Lines -Path (Join-Path $VariantDir "count_$seatCount.mcfunction") -Lines $variantLines
}

Remove-Item -LiteralPath (Join-Path $VariantDir "editable") -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath (Join-Path $VariantDir "build.mcfunction") -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath (Join-Path $VariantDir "show.mcfunction") -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath (Join-Path $VariantDir "reveal_slot.mcfunction") -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath (Join-Path $VariantDir "build_mask.mcfunction") -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath (Join-Path $VariantDir "show_mask.mcfunction") -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath (Join-Path $VariantDir "build_group_masks.mcfunction") -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath (Join-Path $VariantDir "main") -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath (Join-Path $VariantDir "mask") -Recurse -Force -ErrorAction SilentlyContinue
foreach ($group in 1..3) {
    Remove-Item -LiteralPath (Join-Path $VariantDir "group_$group.mcfunction") -Force -ErrorAction SilentlyContinue
    Remove-Item -LiteralPath (Join-Path $VariantDir "group_$group") -Recurse -Force -ErrorAction SilentlyContinue
}

Write-Host "Generated stable grimoire reveal dialog with white player names and unrevealed seats only."
