Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$RepoRoot = Split-Path -Parent $PSScriptRoot
$OutputPath = Join-Path $RepoRoot "Jays-Patch/datapack/data/botc_patch/function/grim/dialog.mcfunction"
$VariantDir = Join-Path $RepoRoot "Jays-Patch/datapack/data/botc_patch/function/grim/dialog"
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)

function New-Header {
    param([string] $Responsibility)

    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add("# Generated by tools/generate-grim-dialog.ps1.")
    $lines.Add("# Do not hand-edit this file; update the generator and regenerate.")
    if (-not [string]::IsNullOrWhiteSpace($Responsibility)) {
        $lines.Add("# $Responsibility")
    }
    return ,$lines
}

function Write-Lines {
    param(
        [string] $Path,
        [System.Collections.Generic.List[string]] $Lines
    )

    [System.IO.File]::WriteAllText($Path, ($Lines -join [Environment]::NewLine) + [Environment]::NewLine, $utf8NoBom)
}

function New-DialogLine {
    param([int] $SeatCount)

    $dialogActions = [System.Collections.Generic.List[string]]::new()
    $dialogActions.Add('{label:{text:"Good Wins",color:"#0000aa",bold:true},action:{type:"run_command",command:"/botc winner good"}}')
    $dialogActions.Add('{label:{text:"Evil Wins",color:"#aa0000",bold:true},action:{type:"run_command",command:"/botc winner evil"}}')
    for ($seat = 1; $seat -le $SeatCount; $seat++) {
        $dialogActions.Add('{label:{text:"$(p' + $seat + '_name) ($(p' + $seat + '_role))",color:"$(p' + $seat + '_color)"},tooltip:{text:"Seat ' + $seat + '",color:"gray"},action:{type:"run_command",command:"/botc grimoire reveal_seat_' + $seat + '"}}')
    }

    $macroPrefix = if ($SeatCount -gt 0) { '$' } else { '' }
    return $macroPrefix + 'dialog show @s {type:"multi_action",title:"Grimoire Reveal",columns:2,actions:[' + ($dialogActions -join ',') + ']}'
}

New-Item -ItemType Directory -Path (Split-Path -Parent $OutputPath) -Force | Out-Null
New-Item -ItemType Directory -Path $VariantDir -Force | Out-Null

$prepareLines = New-Header "Prepares immutable reveal-snapshot names, role labels, and category colors."
$prepareLines.Add("data remove storage botc_patch:grim reveal_dialog")
for ($seat = 1; $seat -le 15; $seat++) {
    $prepareLines.Add(('data modify storage botc_patch:grim reveal_dialog.p{0}_name set value "Seat {0}"' -f $seat))
    $prepareLines.Add(('data modify storage botc_patch:grim reveal_dialog.p{0}_role set value "Unknown"' -f $seat))
    $prepareLines.Add(('data modify storage botc_patch:grim reveal_dialog.p{0}_color set value "#aaaaaa"' -f $seat))
    $prepareLines.Add(('execute if score grim_seat_{0}_occupied botc_patch matches 1 if data storage ct:players players.p{0} unless data storage ct:players players{{p{0}:"Nobody!"}} run data modify storage botc_patch:grim reveal_dialog.p{0}_name set from storage ct:players players.p{0}' -f $seat))
    $prepareLines.Add(('data modify storage botc_patch:grim reveal_lookup set value {{seat:{0},score:0}}' -f $seat))
    $prepareLines.Add(('execute if score grim_seat_{0}_occupied botc_patch matches 1 store result storage botc_patch:grim reveal_lookup.score int 1 run scoreboard players get grim_seat_{0}_role botc_patch' -f $seat))
    $prepareLines.Add(('execute if score grim_seat_{0}_occupied botc_patch matches 1 run function botc_patch:grim/dialog/prepare_role with storage botc_patch:grim reveal_lookup' -f $seat))
}
Write-Lines -Path (Join-Path $VariantDir "prepare.mcfunction") -Lines $prepareLines

$prepareRoleLines = New-Header "Resolves one snapshot role through the trusted Storyteller editor catalog."
$prepareRoleLines.Add('$data modify storage botc_patch:grim reveal_dialog.p$(seat)_role set from storage botc_patch:grim editor.score_catalog.s$(score).name')
$prepareRoleLines.Add('$data modify storage botc_patch:grim reveal_dialog.p$(seat)_color set from storage botc_patch:grim editor.score_catalog.s$(score).color')
Write-Lines -Path (Join-Path $VariantDir "prepare_role.mcfunction") -Lines $prepareRoleLines

$lines = New-Header "Dispatches the stable one-page reveal dialog for the captured player count."
$lines.Add('execute unless score grim_active botc_patch matches 1 run tellraw @s {"text":"Start reveal mode with /botc grimoire start first.","color":"red"}')
$lines.Add("execute if score grim_active botc_patch matches 1 run function botc_patch:grim/dialog/prepare")
for ($seatCount = 0; $seatCount -le 15; $seatCount++) {
    $suffix = if ($seatCount -gt 0) { " with storage botc_patch:grim reveal_dialog" } else { "" }
    $lines.Add("execute if score grim_active botc_patch matches 1 if score grim_dialog_size botc_patch matches $seatCount run function botc_patch:grim/dialog/count_$seatCount$suffix")
}
$lines.Add("execute if score grim_active botc_patch matches 1 unless score grim_dialog_size botc_patch matches 0..15 run function botc_patch:grim/dialog/count_15 with storage botc_patch:grim reveal_dialog")
Write-Lines -Path $OutputPath -Lines $lines

for ($seatCount = 0; $seatCount -le 15; $seatCount++) {
    $variantLines = New-Header "Reveal dialog for $seatCount captured seats."
    $variantLines.Add((New-DialogLine -SeatCount $seatCount))
    Write-Lines -Path (Join-Path $VariantDir "count_$seatCount.mcfunction") -Lines $variantLines
}

Remove-Item -LiteralPath (Join-Path $VariantDir "editable") -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath (Join-Path $VariantDir "build.mcfunction") -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath (Join-Path $VariantDir "show.mcfunction") -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath (Join-Path $VariantDir "reveal_slot.mcfunction") -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath (Join-Path $VariantDir "build_mask.mcfunction") -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath (Join-Path $VariantDir "show_mask.mcfunction") -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath (Join-Path $VariantDir "build_group_masks.mcfunction") -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath (Join-Path $VariantDir "main") -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath (Join-Path $VariantDir "mask") -Recurse -Force -ErrorAction SilentlyContinue
foreach ($group in 1..3) {
    Remove-Item -LiteralPath (Join-Path $VariantDir "group_$group.mcfunction") -Force -ErrorAction SilentlyContinue
    Remove-Item -LiteralPath (Join-Path $VariantDir "group_$group") -Recurse -Force -ErrorAction SilentlyContinue
}

Write-Host "Generated stable grimoire reveal dialog with player names and snapshot roles."
