# Generated by tools/generate-buffet-gamemodes.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Replace Sybillian's temporary randomized player-name snapshot with Buffet seat order.
data modify storage ct:players players.p1 set value "Nobody!"
execute if data storage botc_patch:buffet roster.p1 run data modify storage ct:players players.p1 set from storage botc_patch:buffet roster.p1
data modify storage ct:players players.p2 set value "Nobody!"
execute if data storage botc_patch:buffet roster.p2 run data modify storage ct:players players.p2 set from storage botc_patch:buffet roster.p2
data modify storage ct:players players.p3 set value "Nobody!"
execute if data storage botc_patch:buffet roster.p3 run data modify storage ct:players players.p3 set from storage botc_patch:buffet roster.p3
data modify storage ct:players players.p4 set value "Nobody!"
execute if data storage botc_patch:buffet roster.p4 run data modify storage ct:players players.p4 set from storage botc_patch:buffet roster.p4
data modify storage ct:players players.p5 set value "Nobody!"
execute if data storage botc_patch:buffet roster.p5 run data modify storage ct:players players.p5 set from storage botc_patch:buffet roster.p5
data modify storage ct:players players.p6 set value "Nobody!"
execute if data storage botc_patch:buffet roster.p6 run data modify storage ct:players players.p6 set from storage botc_patch:buffet roster.p6
data modify storage ct:players players.p7 set value "Nobody!"
execute if data storage botc_patch:buffet roster.p7 run data modify storage ct:players players.p7 set from storage botc_patch:buffet roster.p7
data modify storage ct:players players.p8 set value "Nobody!"
execute if data storage botc_patch:buffet roster.p8 run data modify storage ct:players players.p8 set from storage botc_patch:buffet roster.p8
data modify storage ct:players players.p9 set value "Nobody!"
execute if data storage botc_patch:buffet roster.p9 run data modify storage ct:players players.p9 set from storage botc_patch:buffet roster.p9
data modify storage ct:players players.p10 set value "Nobody!"
execute if data storage botc_patch:buffet roster.p10 run data modify storage ct:players players.p10 set from storage botc_patch:buffet roster.p10
data modify storage ct:players players.p11 set value "Nobody!"
execute if data storage botc_patch:buffet roster.p11 run data modify storage ct:players players.p11 set from storage botc_patch:buffet roster.p11
data modify storage ct:players players.p12 set value "Nobody!"
execute if data storage botc_patch:buffet roster.p12 run data modify storage ct:players players.p12 set from storage botc_patch:buffet roster.p12
data modify storage ct:players players.p13 set value "Nobody!"
execute if data storage botc_patch:buffet roster.p13 run data modify storage ct:players players.p13 set from storage botc_patch:buffet roster.p13
data modify storage ct:players players.p14 set value "Nobody!"
execute if data storage botc_patch:buffet roster.p14 run data modify storage ct:players players.p14 set from storage botc_patch:buffet roster.p14
data modify storage ct:players players.p15 set value "Nobody!"
execute if data storage botc_patch:buffet roster.p15 run data modify storage ct:players players.p15 set from storage botc_patch:buffet roster.p15
execute as @a run function ct:start_game/roles/set_grim_variables with storage ct:players players
