# Generated by tools/generate-storyteller-player-menu.ps1.
# Do not hand-edit this file; update the generator and regenerate.
# Validates a dialog seat selection before dispatching to its fixed target function.
dialog clear @s
execute unless entity @s[tag=storyteller] run return 0
execute unless score phase game_data matches 1.. run return run tellraw @s {"text":"Teleport to Player is only available during an active game.","color":"red"}
$function botc_patch:storyteller_tools/player_menu/to_seat_$(seat)
