# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Show the pending balloonist setup decision.
dialog show @a[tag=storyteller] {type:"multi_action",title:{text:"Balloonist Setup",color:"gold",bold:true},body:[{type:"plain_message",contents:{text:"Choose whether Balloonist adds one Outsider.",color:"gray"},width:360}],columns:2,actions:[{label:{text:"No change",color:"gray"},action:{type:"run_command",command:"/trigger botc_buffet_action set 7420"}},{label:{text:"+1 Outsider",color:"aqua"},action:{type:"run_command",command:"/trigger botc_buffet_action set 7421"}}],exit_action:{label:"Close"}}
