# Generated by tools/generate-storyteller-boomdandy.ps1.
# Do not hand-edit this file; update the generator and regenerate.
# Second warning frame 1 of 23.
title @a title {text:"Som",color:"#ff4b1f",bold:true}
title @a subtitle {text:"",color:"#ffffff"}
execute as @a at @s run playsound minecraft:block.note_block.hat master @s ~ ~ ~ 0.24 1.9
