# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Show the pending godfather setup decision.
dialog show @a[tag=storyteller] {type:"multi_action",title:{text:"Godfather Setup",color:"gold",bold:true},body:[{type:"plain_message",contents:{text:"Choose the Godfather Outsider adjustment.",color:"gray"},width:360}],columns:2,actions:[{label:{text:"-1 Outsider",color:"yellow"},action:{type:"run_command",command:"/trigger botc_buffet_action set 7430"}},{label:{text:"+1 Outsider",color:"aqua"},action:{type:"run_command",command:"/trigger botc_buffet_action set 7431"}}],exit_action:{label:"Close"}}
