# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Dispatch validated Draft player and Storyteller actions.
execute if entity @s[tag=botc_buffet_draft_current,tag=!storyteller] if score @s botc_buffet_action matches 7001 run function botc_patch:buffet/draft/select_option_1
execute if entity @s[tag=botc_buffet_draft_current,tag=!storyteller] if score @s botc_buffet_action matches 7002 run function botc_patch:buffet/draft/select_option_2
execute if entity @s[tag=botc_buffet_draft_current,tag=!storyteller] if score @s botc_buffet_action matches 7003 run function botc_patch:buffet/draft/select_option_3
execute if entity @s[tag=botc_buffet_draft_current,tag=!storyteller] if score @s botc_buffet_action matches 7010 run function botc_patch:buffet/draft/discard
execute if entity @s[tag=botc_buffet_draft_current,tag=!storyteller] if score @s botc_buffet_action matches 7011 run function botc_patch:buffet/draft/remind_reopen
execute if entity @s[tag=storyteller] if score @s botc_buffet_action matches 7100 run function botc_patch:buffet/draft/review/open
execute if entity @s[tag=storyteller] if score @s botc_buffet_action matches 7101 run function botc_patch:buffet/draft/review/toggle_recycling
execute if entity @s[tag=storyteller] if score @s botc_buffet_action matches 7102 run function botc_patch:buffet/draft/start/try
execute if entity @s[tag=storyteller] if score @s botc_buffet_action matches 7103 run function botc_patch:buffet/draft/start/execute
execute if entity @s[tag=storyteller] if score @s botc_buffet_action matches 7104 run function botc_patch:buffet/draft/jinx/report
execute if entity @s[tag=storyteller] if score @s botc_buffet_action matches 7201..7215 run function botc_patch:buffet/draft/review/select_seat
execute if entity @s[tag=storyteller] if score @s botc_buffet_action matches 7300 run function botc_patch:buffet/draft/review/empty_seat
execute if entity @s[tag=storyteller] if data storage botc_patch:buffet modifier{role:54} if score @s botc_buffet_action matches 7420 run function botc_patch:buffet/draft/modifier/choose_delta_0
execute if entity @s[tag=storyteller] if data storage botc_patch:buffet modifier{role:54} if score @s botc_buffet_action matches 7421 run function botc_patch:buffet/draft/modifier/choose_delta_plus_1
execute if entity @s[tag=storyteller] if data storage botc_patch:buffet modifier{role:102} if score @s botc_buffet_action matches 7430 run function botc_patch:buffet/draft/modifier/choose_delta_minus_1
execute if entity @s[tag=storyteller] if data storage botc_patch:buffet modifier{role:102} if score @s botc_buffet_action matches 7431 run function botc_patch:buffet/draft/modifier/choose_delta_plus_1
execute if entity @s[tag=storyteller] if data storage botc_patch:buffet modifier{role:90} if score @s botc_buffet_action matches 7440 run function botc_patch:buffet/draft/modifier/hermit/choose_delta_0
execute if entity @s[tag=storyteller] if data storage botc_patch:buffet modifier{role:90} if score @s botc_buffet_action matches 7441 run function botc_patch:buffet/draft/modifier/hermit/choose_delta_minus_1
execute if entity @s[tag=storyteller] if score @s botc_buffet_action matches 7500..7504 run function botc_patch:buffet/draft/modifier/choose_outsider_target
execute if entity @s[tag=storyteller] if score @s botc_buffet_action matches 7602..7614 run function botc_patch:buffet/draft/modifier/choose_legion_count
execute if entity @s[tag=storyteller] if data storage botc_patch:buffet modifier{role:90} if score @s botc_buffet_action matches 7998 run function botc_patch:buffet/draft/modifier/hermit/clear
execute if entity @s[tag=storyteller] if data storage botc_patch:buffet modifier{role:90} if score @s botc_buffet_action matches 7999 run function botc_patch:buffet/draft/modifier/hermit/confirm
execute if entity @s[tag=storyteller] if data storage botc_patch:buffet modifier{role:90} if score @s botc_buffet_action matches 8001..8138 run function botc_patch:buffet/draft/modifier/hermit/toggle_dispatch
scoreboard players set @s botc_buffet_action 0
scoreboard players enable @s botc_buffet_action
