# Generated by tools/generate-draft-buffet.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Reopen the acting player's current private Draft choices.
execute unless entity @s[tag=botc_buffet_draft_current] run return 0
function botc_patch:buffet/draft/dialog/prepare
