# Generated by tools/generate-buffet-gamemodes.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Resolve one saved Personal Grimoire role slug for Sybillian's local player view.
$data modify storage botc_patch:buffet action.personal_grimoire_sync.id set from storage botc_patch:buffet catalog.s$(role).id
function botc_patch:buffet/personal_grimoire/sync_sybillian_apply with storage botc_patch:buffet action.personal_grimoire_sync
