# Generated by tools/generate-buffet-gamemodes.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Return to the acting player's current Greedy category page.
execute if score @s botc_buffet_page matches 1 run function botc_patch:buffet/greedy/dialog/town_prepare
execute if score @s botc_buffet_page matches 2 run function botc_patch:buffet/greedy/dialog/outsider_prepare
execute if score @s botc_buffet_page matches 3 run function botc_patch:buffet/greedy/dialog/minion_prepare
execute if score @s botc_buffet_page matches 4 run function botc_patch:buffet/greedy/dialog/demon_prepare
