# Generated by tools/generate-buffet-gamemodes.ps1.
# Do not hand-edit this file; update the generator or Jays-Patch/buffet-rules.json.
# Toggle Dealer's Choice and require the acting player to resubmit.
execute store result storage botc_patch:buffet action.seat int 1 run scoreboard players get @s id
data remove storage botc_patch:buffet action.was_set
$execute if data storage botc_patch:buffet greedy.seats.s$(seat){dealer:1b} run data modify storage botc_patch:buffet action.was_set set value 1b
$data modify storage botc_patch:buffet greedy.seats.s$(seat).dealer set value 0b
$execute unless data storage botc_patch:buffet action{was_set:1b} run data modify storage botc_patch:buffet greedy.seats.s$(seat).dealer set value 1b
$data modify storage botc_patch:buffet greedy.seats.s$(seat).submitted set value 0b
function botc_patch:buffet/greedy/recount
function botc_patch:buffet/greedy/open
