# Generated by tools/generate-storyteller-boomdandy.ps1.
# Do not hand-edit this file; update the generator and regenerate.
# Executes the Boomdandy through Sybillian's non-lightning announcement/tag contract while leaving the pyre lit for the TNT rain.
function ct:util/color_names
tellraw @a [{"selector":"@s"},{"text":" has been executed.","color":"red"}]
function ct:util/color_prefixes


tag @s remove being_executed
tag @s remove marked_for_execution
function botc_patch:storyteller_tools/boomdandy_pyre/start
