# Generated by tools/generate-storyteller-boomdandy.ps1.
# Do not hand-edit this file; update the generator and regenerate.
# Rebuilds seat 7 from the locked 8-player layout.
setblock 118 72 64 minecraft:spruce_door[facing=west,half=lower,hinge=left,open=false,powered=false]
setblock 118 73 64 minecraft:spruce_door[facing=west,half=upper,hinge=left,open=false,powered=false]
setblock 119 72 64 minecraft:spruce_slab[type=bottom,waterlogged=false]
setblock 119 72 63 minecraft:spruce_trapdoor[facing=north,half=bottom,open=true,powered=false,waterlogged=false]
setblock 119 72 65 minecraft:spruce_trapdoor[facing=south,half=bottom,open=true,powered=false,waterlogged=false]
setblock 120 72 64 minecraft:spruce_wall_sign[facing=east,waterlogged=false]
data modify block 120 72 64 front_text.messages[1] set value {"selector":"@a[team=07_cyan]","color":"#42d4f4"}
setblock 119 73 64 minecraft:white_wall_banner[facing=east]
data modify block 119 73 64 patterns set value [{pattern:"ct:cyan",color:"white"}]
